// Persistent presentation preferences; never match state or account statistics.
(function(){
const key='chainSiege.audioOptions.v1',groups=['master','music','sfx','narrator'],listeners=new Set(),buses=new Map(),narrators=new Map();let narratorContext=null;
let state=Object.fromEntries(groups.map(k=>[k,{on:true,volume:100}]));
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved)for(const k of groups){if(typeof saved[k]?.on==='boolean')state[k].on=saved[k].on;if(Number.isFinite(saved[k]?.volume))state[k].volume=Math.max(0,Math.min(100,saved[k].volume));}else state.narrator.on=localStorage.getItem('stoneThrow.storyNarration.enabled.v1')!=='0';}catch{}
const scale=k=>state.master.on&&state[k].on?state.master.volume/100*state[k].volume/100:0;
function notify(){for(const [ctx,bus]of buses){if(ctx.state==='closed'){buses.delete(ctx);continue;}bus.gain.setValueAtTime(scale('sfx'),ctx.currentTime);}for(const [audio,route]of narrators){if(route.gain)route.gain.gain.setValueAtTime(scale('narrator'),narratorContext.currentTime);else audio.volume=scale('narrator');}for(const fn of listeners)fn();}
const api=Object.freeze({get:()=>structuredClone(state),scale,narrator(audio){let route={};try{narratorContext??=new (window.AudioContext||window.webkitAudioContext)();narratorContext.resume()?.catch(()=>{});route.source=narratorContext.createMediaElementSource(audio);route.gain=narratorContext.createGain();route.gain.gain.value=scale('narrator');route.source.connect(route.gain);route.gain.connect(narratorContext.destination);audio.volume=1;}catch{audio.volume=scale('narrator');}narrators.set(audio,route);},releaseNarrator(audio){const route=narrators.get(audio);route?.source?.disconnect();route?.gain?.disconnect();narrators.delete(audio);},set(k,patch){if(!groups.includes(k))return;const old=state[k];if(typeof patch.on==='boolean')old.on=patch.on;if(Number.isFinite(patch.volume))old.volume=Math.max(0,Math.min(100,patch.volume));try{localStorage.setItem(key,JSON.stringify(state));localStorage.setItem('stoneThrow.storyNarration.enabled.v1',state.narrator.on?'1':'0');}catch{}notify();},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},sfxBus(ctx){if(!buses.has(ctx)){const bus=ctx.createGain();bus.gain.value=scale('sfx');bus.connect(ctx.destination);buses.set(ctx,bus);}return buses.get(ctx);}});window.chainSiegeAudio=api;
const settings=document.getElementById('stSettings');if(settings){const panel=document.createElement('section');panel.id='csAudioOptions';const h=document.createElement('h3');h.textContent='AUDIO';panel.append(h);for(const k of groups){const row=document.createElement('div');row.className='cs-audio-row';const label=document.createElement('label');label.textContent=k.toUpperCase();const toggle=document.createElement('button');toggle.type='button';toggle.id='csAudio-'+k+'-toggle';toggle.className='st-toggle';toggle.setAttribute('aria-label',k+' audio');toggle.onclick=()=>api.set(k,{on:!state[k].on});const slider=document.createElement('input');slider.id='csAudio-'+k+'-volume';slider.type='range';slider.min='0';slider.max='100';slider.step='1';slider.setAttribute('aria-label',k+' volume');slider.oninput=()=>api.set(k,{volume:Number(slider.value)});label.htmlFor=slider.id;const value=document.createElement('output');row.append(label,toggle,slider,value);panel.append(row);listeners.add(()=>{toggle.textContent=state[k].on?'ON':'OFF';toggle.setAttribute('aria-pressed',String(state[k].on));slider.value=state[k].volume;value.textContent=state[k].volume;});}settings.querySelector('.st-settings-title').after(panel);}
window.addEventListener('storage',e=>{if(e.key!==key)return;try{const saved=JSON.parse(e.newValue);for(const k of groups)if(typeof saved?.[k]?.on==='boolean'&&Number.isFinite(saved[k].volume))state[k]={on:saved[k].on,volume:Math.max(0,Math.min(100,saved[k].volume))};notify();}catch{}});notify();
})();
