import type {HostState,PolicyMemory} from '../host/contracts.js';import type {PlayerId,Unit} from '../model.js';import {seat,unitAt,cellKey,parseKey,boardSize} from '../combat/access.js';import {neighbors4,neighbors8} from '../rules/coordinates.js';import {random} from '../combat/rng.js';
/** Compatibility-only policy: intentionally consults private unit identities and
 * geometry as the legacy Auto Match does. Never use as an observer API. */
export const brain=(h:HostState,id:PlayerId)=>h.brains.find(b=>b.playerId===id)!;
export const draw=(h:HostState,purpose:string)=>random(h.pendingRoot?.rng||h.rng,'policy:'+purpose);
export function pick<T>(h:HostState,list:readonly T[],purpose:string):T|null{return list.length?list[Math.floor(draw(h,purpose)*list.length)]!:null;}
export function protectedCells(h:HostState,targetId:PlayerId):Set<string>{const result=new Set<string>(),outbreaks=h.state.plagues.filter(p=>p.targetPlayerId===targetId).flatMap(p=>p.outbreaks);for(const o of outbreaks){const remaining=Math.max(0,5-o.round);if(remaining<=0)continue;const seeds=o.infected.length?o.infected:o.origin?[cellKey(o.origin)]:[];for(const seed of seeds){const q=parseKey(seed);for(let y=0;y<h.config.size;y++)for(let x=0;x<h.config.size;x++)if(Math.max(Math.abs(x-q.x),Math.abs(y-q.y))<=remaining)result.add(x+','+y);}}return result;}
function unfinished(h:HostState,u:Unit|null):boolean{if(!u)return false;const shots=seat(h.state,u.ownerId).shots;return (u.type==='cav'||u.type==='castle')&&u.cells.some(c=>!shots.includes(cellKey(c)));}
function multiTarget(h:HostState,actor:PlayerId,target:PlayerId):string|null {const b=brain(h,actor),p=seat(h.state,target),ctx={size:h.config.size};for(const origin of b.knownHits){if(!unfinished(h,unitAt(h.state,p.boardId,origin)))continue;const cluster=new Set([origin]),queue=[origin];while(queue.length){const q=parseKey(queue.shift()!);for(const n of neighbors4(ctx,q.x,q.y)){if(cluster.has(n)||!b.knownHits.includes(n))continue;cluster.add(n);queue.push(n);}}const scored=new Map<string,number>();for(const k of cluster){const q=parseKey(k);for(const n of neighbors4(ctx,q.x,q.y)){if(p.shots.includes(n))continue;const known=b.scoutKnowledge.find(v=>v.cell===n)?.classification;if(known==='empty'||known==='special')continue;scored.set(n,(scored.get(n)||0)+1);}}if(scored.size){const best=Math.max(...scored.values());return pick(h,[...scored].filter(([,s])=>s===best).map(([k])=>k),'unfinished-multi');}}return null;}
function nearForbidden(h:HostState,target:PlayerId,k:string,b:PolicyMemory):boolean {const ctx={size:h.config.size},board=seat(h.state,target).boardId;for(const s of b.scoutKnowledge){if(s.classification!=='special')continue;const q=parseKey(s.cell);if(neighbors8(ctx,q.x,q.y).includes(k))return true;}for(const hit of b.knownHits){const u=unitAt(h.state,board,hit);if(u?.type==='castle'&&unfinished(h,u))continue;const q=parseKey(hit);if(neighbors8(ctx,q.x,q.y).includes(k))return true;}return false;}
function endgame(h:HostState,actor:PlayerId,target:PlayerId):string|null {const p=seat(h.state,target),units=h.state.match.units.filter(u=>u.ownerId===target),hero=units.find(u=>u.type==='hero');if(hero?.hero?.activated&&hero.hero.currentCell)return null;if(units.filter(u=>['inf','archer','monk'].includes(u.type||'')).some(u=>u.cells.some(c=>!p.shots.includes(cellKey(c)))))return null;if(!units.some(u=>unfinished(h,u)))return null;const b=brain(h,actor),legal:string[]=[];for(let y=0;y<h.config.size;y++)for(let x=0;x<h.config.size;x++){const k=x+','+y,known=b.scoutKnowledge.find(c=>c.cell===k)?.classification;if(p.shots.includes(k)||known==='empty'||known==='special'||nearForbidden(h,target,k,b))continue;legal.push(k);}const all=new Set(legal),multi=legal.filter(k=>{const q=parseKey(k);return neighbors4({size:h.config.size},q.x,q.y).some(n=>all.has(n));});if(!multi.length)return null;const parity:[string[],string[]]=[[],[]];for(const k of multi){const q=parseKey(k);parity[(q.x+q.y)&1]!.push(k);}return pick(h,parity[0].length>=parity[1].length?parity[0]:parity[1],'endgame');}
export function autoMatchTarget(h:HostState,actor:PlayerId,plagueAware=false):string|null {const target=seat(h.state,actor).reactionTarget.playerId,p=seat(h.state,target),b=brain(h,actor),res=p.resurrection;if(res.searchActive&&res.suspects.length){const uid=pick(h,res.suspects,'resurrection-unit')!,u=h.state.match.units.find(u=>u.id===uid)!;if(u.cells.length)return pick(h,u.cells.map(cellKey),'resurrection-cell');}const protectedSet=plagueAware?protectedCells(h,target):new Set<string>(),hero=h.state.match.units.find(u=>u.ownerId===target&&u.type==='hero')?.hero,heroKey=hero?.currentCell?cellKey(hero.currentCell):null;if(heroKey&&!p.shots.includes(heroKey)&&b.scoutKnowledge.find(c=>c.cell===heroKey)?.classification==='core'&&!protectedSet.has(heroKey))return heroKey;if(hero?.hitsTaken===2&&hero.activated&&heroKey){const hunt=b.heroHunt.filter(k=>!p.shots.includes(k)&&!protectedSet.has(k));if(hunt.length)return pick(h,hunt,'hero-hunt');}const multi=multiTarget(h,actor,target);if(multi)return multi;const monks=seat(h.state,actor).monkCandidates.filter(k=>!p.shots.includes(k)&&!protectedSet.has(k));if(monks.length)return pick(h,monks,'monk-clue');for(const c of b.scoutKnowledge)if(c.classification==='core'&&!p.shots.includes(c.cell)&&!protectedSet.has(c.cell))return c.cell;const ending=endgame(h,actor,target);if(ending&&!protectedSet.has(ending))return ending;const raw:string[]=[],heat:{green:string[];blue:string[];red:string[]}={green:[],blue:[],red:[]};for(let y=0;y<h.config.size;y++)for(let x=0;x<h.config.size;x++){const k=x+','+y;if(p.shots.includes(k)||protectedSet.has(k))continue;raw.push(k);if(hero?.activated&&heroKey)continue;const known=b.scoutKnowledge.find(c=>c.cell===k)?.classification;if(known==='empty'||known==='special'||nearForbidden(h,target,k,b))continue;const edge=Math.min(x,y,h.config.size-1-x,h.config.size-1-y);heat[edge===0?'green':edge<=2?'blue':'red'].push(k);}if(hero?.activated&&heroKey)return pick(h,raw,'active-hero-pool');const fallback=[...heat.green,...heat.blue,...heat.red];if(!fallback.length)return pick(h,raw,'raw-fallback');const r=draw(h,'heat-colour'),pref=r<.30?'green':r<.69?'blue':'red';return pick(h,heat[pref].length?heat[pref]:fallback,'heat-cell');}
export function scoutChoices(h:HostState,actor:PlayerId,count:number):string[]{const p=seat(h.state,actor),target=seat(h.state,p.reactionTarget.playerId),pool:string[]=[],selected:string[]=[];for(let y=0;y<h.config.size;y++)for(let x=0;x<h.config.size;x++){const k=x+','+y;if(!target.shots.includes(k)&&!p.scouted.includes(k))pool.push(k);}while(selected.length<count&&pool.length){let choice:string|null=null;const hunt=brain(h,actor).heroHunt.filter(k=>pool.includes(k));if(hunt.length&&draw(h,'scout-hunt-preference')<.75)choice=pick(h,hunt,'scout-hunt');if(choice===null)choice=pick(h,pool,'scout-cell');selected.push(choice!);pool.splice(pool.indexOf(choice!),1);}return selected;}
