import {shortMatchId,flagReason} from './labels.js';
import {spectate} from '/client-v13/spectator.js?v=a2b676805607d7226fe0565965247a53c4292aaa729e29b2285533a9471bc5ec';
const content=document.querySelector('#content'),message=document.querySelector('#message'),heading=document.querySelector('#heading');
let section='Overview',generation=0,feedbackType='ALL',feedbackStatus='NEW',offset=0,reviewFilter='needs',reviewQuery='',reviewPage=0,viewerId=null,playerQuery='',playersNewOnly=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
async function api(path,data={}){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const b=await r.json();if(!r.ok){if(r.status===403){generation++;content.replaceChildren();for(const dialog of document.querySelectorAll('dialog.review-confirm')){dialog.close();dialog.remove();}}throw Error(b.error||'Request failed.');}return b;}
const registry=(action,data)=>api('registry/'+action,data);
function button(text,fn){const b=el('button',text);b.onclick=async()=>{b.disabled=true;message.textContent='';try{await fn();}catch(e){message.textContent=e.message;}finally{b.disabled=false;}};return b;}
function select(label,values,current,change){const l=el('label',label),s=el('select');s.setAttribute('aria-label',label);for(const [value,text]of values){const o=el('option',text);o.value=value;s.append(o);}s.value=current;s.onchange=()=>change(s.value);l.append(s);return l;}
function facts(data){const p=el('pre',JSON.stringify(data,null,2));return p;}
function table(headers,rows){const t=el('table'),head=el('tr');headers.forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);t.append(thead);const body=el('tbody');for(const row of rows){const tr=el('tr');for(const value of row){const td=el('td');td.append(value instanceof Node?value:document.createTextNode(String(value??'—')));tr.append(td);}body.append(tr);}t.append(body);return t;}
let gameQuery='',gameOffset=0;
let usageRange='24h',healthRange='24h';
const duration=seconds=>{const days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return (days?days+'d ':'')+(hours?hours+'h ':'')+minutes+'m';};
function rangeButtons(label,current,change){const group=el('div',undefined,'filter-group');group.setAttribute('role','group');group.setAttribute('aria-label',label);for(const [value,text]of [['24h','24 HOURS'],['7d','7 DAYS'],['30d','30 DAYS']]){const b=button(text,()=>change(value));b.setAttribute('aria-pressed',String(value===current));group.append(b);}return group;}
function chart(label,key,points,{value,unit='',description='',bars=false}={}){
 const card=el('section',undefined,'dashboard-chart');card.dataset.metric=key;card.append(el('h3',label),el('div',value==null?'Not recorded':displayNumber(value)+unit,'value'),el('p',description,'muted'));
 const values=points.map(p=>p[key]),finite=values.filter(Number.isFinite),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 300 90');svg.setAttribute('role','img');svg.setAttribute('aria-label',label+' history');
 const shape=(tag,attrs)=>{const n=document.createElementNS(svg.namespaceURI,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;},max=unit==='%'?100:Math.max(1,...finite),x=i=>8+i*284/Math.max(1,points.length-1),y=v=>80-v/max*70;
 shape('path',{d:'M8 80H292',stroke:'#56616b',fill:'none'});
 if(!finite.length)card.append(el('p','No recorded samples in this period.','empty-history'));
 else if(bars){values.forEach((v,i)=>{if(!Number.isFinite(v))return;const bar=shape('rect',{x:x(i)-3,y:y(v),width:6,height:Math.max(1,80-y(v)),fill:'#d3ad58'});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=stamp(points[i].at)+': '+v;bar.append(title);});}
 else{let line=[];const flush=()=>{if(line.length)shape('polyline',{points:line.join(' '),stroke:'#d3ad58','stroke-width':2,fill:'none'});line=[];};values.forEach((v,i)=>{if(!Number.isFinite(v)){flush();return;}line.push(x(i)+','+y(v));const dot=shape('circle',{cx:x(i),cy:y(v),r:2.5,fill:'#e9c870'}),title=document.createElementNS(svg.namespaceURI,'title');title.textContent=stamp(points[i].at)+': '+displayNumber(v)+unit;dot.append(title);});flush();}
 card.append(svg);const axis=el('div',undefined,'chart-axis');axis.append(el('small',stamp(points[0]?.at)),el('small',stamp(points.at(-1)?.at)));card.append(axis);
 const valuesDetail=el('details');valuesDetail.append(el('summary','View values'),table(['Time (UTC)',label],points.map(p=>[new Date(p.at).toISOString().slice(0,16).replace('T',' '),p[key]==null?'Not recorded':displayNumber(p[key])+unit])));card.append(valuesDetail);return card;
}
async function overview(root){
 const d=await api('dev-room/overview',{range:usageRange}),history=healthRange===usageRange?d:await api('dev-room/overview',{range:healthRange});viewerId=d.developer.playerId;
 root.append(el('p','Signed in as '+d.developer.displayName,'muted'));const cards=el('div',undefined,'cards summary-cards');for(const [label,value]of [['Online Now',d.dashboard.onlineNow],['Active Games',d.activeGames],['Games Today',d.dashboard.today.games],['Registered Visitors Today',d.dashboard.today.registered],['Returning Today',d.dashboard.today.returning],['New Accounts Today',d.newAccountsToday]]){const c=el('section',undefined,'card');c.append(el('h3',label),el('div',value,'value'));cards.append(c);}root.append(cards);
 root.append(el('p','Version '+d.version+' · App uptime '+duration(d.uptimeSeconds),'muted'));const build=el('details');build.append(el('summary','Build'),el('p',d.build,'hash'));root.append(build);
 if(d.dashboardIssue)root.append(el('p','Some usage or health readings could not be saved. Recorded totals may be incomplete.','status-badge flagged'));
 const usage=el('section',undefined,'dashboard-section');usage.append(el('h2','Players / Usage'),rangeButtons('Usage range',usageRange,v=>{usageRange=v;return render();}),el('p','Visits and Story recording began '+stamp(d.dashboard.recordingSince)+'. Earlier history is not available. Online Now counts visible game visitors seen in the last two minutes.','muted'));
 const grid=el('div',undefined,'dashboard-grid');for(const [label,key,description]of [['Visitors','visitors','Unique accounts, or browsers for guests. Signing in merges the guest browser into the account.'],['Registered Visits','registered','Unique signed-in accounts seen using the game.'],['Returning Visits','returning','Accounts registered or seen before this selected period who came back.'],['Games Played','games','Finished non-Story matches, including closed or surrendered matches.'],['Story Mode Battles','story','Story battles started, including retries; not chapter views.']])grid.append(chart(label,key,d.dashboard.points,{value:d.dashboard.totals[key],description,bars:true}));usage.append(grid,el('p','UTC hourly buckets for 24 hours; UTC daily buckets for 7 / 30 days, including the current partial bucket. Visit totals count each person once per selected period, not the sum of the bars. Guest browsers cannot identify people across devices or cleared cookies.','muted'));root.append(usage);
 const gb=bytes=>(bytes/1073741824).toFixed(1)+' GB',health=el('section',undefined,'dashboard-section'),h=history.health,percent=x=>x&&x.total>0?100*(1-x.available/x.total):null;
 health.append(el('h2','Server Health'),rangeButtons('Health range',healthRange,v=>{healthRange=v;return render();}),descriptionList([['Server uptime',duration(h.hostUptimeSeconds)],['App uptime',duration(d.uptimeSeconds)],['Last resource reading',stamp(history.healthAt)],['RAM',gb(h.ram.available)+' available of '+gb(h.ram.total)],['Disk',h.disk?gb(h.disk.available)+' available of '+gb(h.disk.total):'Unavailable']]));
 const healthGrid=el('div',undefined,'dashboard-grid health-grid');for(const [label,key,value,unit,description]of [['CPU','cpu',h.cpuPercent,'%','Whole-server CPU use between readings.'],['RAM','ram',percent(h.ram),'%','Whole-server memory use.'],['Disk usage','disk',percent(h.disk),'%','Drive holding the game accounts.']])healthGrid.append(chart(label,key,history.dashboard.points,{value,unit,description}));for(const [label,key,unit,description]of [['Median response time','responseMedian',' ms','Typical request completion time (approximate median).'],['p95 response time','responseP95',' ms','95% of requests completed within this time (approximate).'],['Worst response time','responseWorst',' ms','Slowest completed request.'],['Request count','requestCount','','Completed eligible requests in the sampling window.'],['p95 queue wait','queueP95',' ms','95% of queued requests started within this wait (approximate). Only the main server mutation queue is measured.'],['Max event-loop delay','loopMax',' ms','Longest event-loop scheduling interval; sampled at 20 ms resolution.']])healthGrid.append(chart(label,key,history.dashboard.points,{value:h[key],unit,description}));health.append(healthGrid,el('p','Resource readings are saved every five minutes for 31 days. CPU/RAM/disk show bucket averages. Response percentiles combine request histograms (within 5% bucket precision); worst response and loop delay show maxima, request count is summed. Current values cover the last completed five-minute window. Includes full command completion and request upload; excludes long-poll waiting, usage pings and developer requests. Network/browser rendering are not measured. A long command can stream progress before completing, so high response time does not necessarily mean a freeze. Historical percentiles before this update are unavailable; gaps are not zero.','muted'));root.append(health);
 const announcement=el('section',undefined,'card');announcement.append(el('h3','Global Message'),el('p',d.announcement.text||'No welcome message.','description'),button('Edit',()=>editMessage(d.announcement.text)),button('Clear',async()=>{await api('dev-room/message',{text:''});await render();}));root.append(announcement);
}
function editMessage(current){const dialog=el('dialog',undefined,'review-confirm'),title=el('h2','Welcome message'),input=el('textarea'),actions=el('div',undefined,'actions');title.id='message-title';dialog.setAttribute('aria-labelledby',title.id);input.value=current;input.maxLength=500;input.rows=5;input.setAttribute('aria-label','Welcome message');const close=()=>{dialog.close();dialog.remove();};actions.append(button('Cancel',close),button('Save',async()=>{await api('dev-room/message',{text:input.value});close();await render();}));dialog.append(title,el('p','Shown on the welcome screen. Up to 500 characters.'),input,actions);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(dialog);dialog.showModal();input.focus();}
async function live(root){const {games}=await api('dev-room/games');root.append(el('p','Battles with connected human players, excluding AFK pauses and waiting lobbies. Local battles appear for two minutes after play or resume. Saved games are preserved. Refresh to update.','muted'));if(!games.length){root.append(el('p','No active games.'));return;}root.append(table(['Room / mode','Players','Status','Round',''],games.map(g=>[`${g.code||'Local'} · ${g.mode}`,g.players.map(p=>p.name+(p.ai?' (AI)':'')).join(', '),g.status,g.round,g.spectate?button('Spectate',()=>spectate({request:(_route,data)=>api('dev-room/spectate',data)},g.spectateCode||g.code,g.spectateCode?g.mode:g.code)):'Unavailable'])));}
function recentPlayers(root,players){const list=el('div');for(const p of players){const row=el('div');row.append(p.playerId?button(p.name,()=>playerDetail(root,p.playerId)):el('span',p.name));if(p.ai||p.outcome)row.append(el('span',p.ai?' (AI)':' — '+p.outcome));list.append(row);}return list;}
async function recent(root){
 const search=el('input');search.type='search';search.placeholder='Player name, Match ID or mode';search.setAttribute('aria-label','Find game');search.value=gameQuery;
 const form=el('form'),submit=el('button','SEARCH');submit.type='submit';form.append(search,submit);form.onsubmit=e=>{e.preventDefault();gameQuery=search.value.trim();gameOffset=0;render();};root.append(form,el('p','Retained completed games, newest first. Search by player name, Match ID or mode.','muted'));
 const d=await registry('dev-review-games',{query:gameQuery,offset:gameOffset});root.append(el('p',d.total+' games found'),table(['Match','Mode','Players / outcome','Date',''],d.items.map(row=>[shortId(row.matchId),row.mode,recentPlayers(root,row.players),stamp(row.startedAt),matchActions(root,row,{recent:true})])));
 if(!d.items.length)root.append(el('p','No matching retained games.'));const prev=button('Previous',()=>{gameOffset=Math.max(0,gameOffset-50);return render();}),next=button('Next',()=>{gameOffset+=50;return render();});prev.disabled=gameOffset===0;next.disabled=gameOffset+50>=d.total;root.append(prev,next);
}
const feedbackLabels={NEW:'New',TODO:'To Do List',IGNORED:'Ignored',FINISHED:'Finished'};
const shortId=shortMatchId;
async function feedbackDetail(root,id,back=render){
 const d=await registry('dev-feedback-get',{id});root.replaceChildren(button(back===render?'Back to feedback':'Back to player',back),el('h3',d.type==='BUG'?'Bug':'Idea'));
 const pairs=[['Status',feedbackLabels[d.inboxStatus]],['From',d.displayName||'Guest'],['Submitted',stamp(d.timestamp)]];if(d.matchId)pairs.push(['Match',shortId(d.matchId)]);if(d.mode)pairs.push(['Mode',d.mode]);root.append(descriptionList(pairs),el('h3','Message'),el('p',d.description,'description'));
 const actions=el('div',undefined,'actions');for(const [label,status]of [['LOOK INTO','TODO'],['IGNORE','IGNORED'],['DONE','FINISHED']])actions.append(button(label,async()=>{await registry('dev-feedback-status',{id,status});await updateActivityBadges();await back();}));root.append(actions);
 if(d.screenshot){const img=el('img');img.className='attachment';img.alt='Feedback screenshot';img.src='data:'+d.screenshot.mime+';base64,'+d.screenshot.data;root.append(img);}
 if(d.gameLog)root.append(button('SAVE GAME LOG',()=>downloadText(d.gameLog,'ChainSiege-feedback-'+d.id+'.txt')));else root.append(el('p','No game log attached.'));
 const {screenshot,gameLog,...metadata}=d;root.append(technical(metadata));
}
function filterGroup(label,values,current,change){const group=el('div',undefined,'filter-group');group.setAttribute('role','group');group.setAttribute('aria-label',label);for(const [value,text,count]of values){const b=button(text+' ('+count+')',()=>change(value));b.setAttribute('aria-pressed',String(value===current));group.append(b);}return group;}
async function feedback(root){
 const {items,counts,inboxCounts}=await registry('dev-feedback-list',{type:feedbackType,status:feedbackStatus,offset});
 root.append(filterGroup('Feedback type',[['ALL','All',counts.types.ALL],['BUG','Bugs',counts.types.BUG],['IDEA','Ideas',counts.types.IDEA]],feedbackType,v=>{feedbackType=v;offset=0;return render();}),filterGroup('Feedback status',Object.entries(feedbackLabels).map(([key,label])=>[key,label,inboxCounts[key]]),feedbackStatus,v=>{feedbackStatus=v;offset=0;return render();}),el('p','Counts are global totals across all feedback. Filters change the displayed rows only.','muted'));
 root.append(table(['Type','Status','Submitted','Description',''],items.map(d=>[d.type==='BUG'?'Bug':'Idea',feedbackLabels[d.inboxStatus],new Date(d.timestamp).toLocaleString(),d.preview,button('Open',()=>feedbackDetail(root,d.id))])));
 if(!items.length)root.append(el('p','No feedback matches these filters.'));const prev=button('Previous',()=>{offset=Math.max(0,offset-50);return render();}),next=button('Next',()=>{offset+=50;return render();});prev.disabled=offset===0;next.disabled=items.length<50;root.append(prev,next);
}
const stamp=t=>t==null?'—':new Date(t).toLocaleString();
function technical(data){const d=el('details');d.append(el('summary','Technical details'),facts(data));return d;}
function descriptionList(pairs){const dl=el('dl',undefined,'facts');for(const [key,value]of pairs)dl.append(el('dt',key),el('dd',value??'Unavailable'));return dl;}
async function updateBadge(){const data=await registry('dev-review-search',{scope:'cases'});const badge=document.querySelector('#review-count');if(badge){badge.textContent=data.counts.needs;badge.title='Cases needing review';}return data;}
function caseActions(row,refresh){const actions=el('div',undefined,'case-actions');for(const action of ['OK','NOT OK'])actions.append(button(action,async()=>{if(action==='NOT OK')return restrictionDialog({player:{playerId:row.playerId,displayName:row.displayName},caseId:row.id},action,action,async()=>{await updateBadge();await refresh();});await registry('dev-review-decide',{caseId:row.id,action});await updateBadge();await refresh();}));return actions;}
function downloadText(text,filename){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),link=el('a');link.href=url;link.download=filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function saveGameLog(matchId){const data=await registry('dev-review-game-log',{matchId});downloadText(data.text,data.filename);}
function matchActions(root,row,parent){const actions=el('div',undefined,'match-actions');actions.append(button('VIEW RESULT',()=>viewResult(root,row.matchId,parent)));if(row.replayAvailable)actions.append(button('WATCH REPLAY',()=>watchReplay(root,row.matchId,parent)));else actions.append(el('small','Replay unavailable'));actions.append(button('SAVE GAME LOG',()=>saveGameLog(row.matchId)));return actions;}
function caseTable(rows,root,parent,refresh){return table(['Player','Match','Result / Replay','Reason','Mode','Date / time','Status',''],rows.map(row=>[button(row.displayName,()=>playerCases(root,row.playerId,row.displayName)),shortId(row.matchId),matchActions(root,row,parent),flagReason(row)+(row.ownerReason?' — Owner: '+row.ownerReason:''),row.mode,stamp(row.timestamp),row.status,caseActions(row,refresh)]));}
function backToPlayer(root,parent){return parent.recent?render():parent.admin?playerDetail(root,parent.playerId):playerCases(root,parent.playerId,parent.name);}
async function playerCases(root,playerId,name){
 const data=await updateBadge(),rows=data.items.filter(r=>r.playerId===playerId),parent={playerId,name};root.replaceChildren(button('Back to Flags / Review',showFlags),el('h3',name,'player-title'),el('p','NOT OK flags this account and hides public scores. OK does not remove an account flag; use Players to remove it.','muted'),caseTable(rows,root,parent,()=>playerCases(root,playerId,name)));
 if(!rows.length)root.append(el('p','No flagged cases.'));
 const details=el('details');details.append(el('summary','Technical details'));details.addEventListener('toggle',async()=>{if(!details.open||details.dataset.loaded)return;try{const account=await registry('dev-review-account',{playerId});details.append(facts(account));details.dataset.loaded='1';}catch(e){message.textContent=e.message;}});root.append(details);
}
async function watchReplay(root,matchId,parent){
 const back=el('div',undefined,'actions');if(parent&&!parent.recent)back.append(button(parent.recent?'Back to Recent / Find Game':'Back to '+parent.name,()=>backToPlayer(root,parent)));back.append(button(parent?.recent?'Back to Recent / Find Game':'Back to Flags / Review',parent?.recent?render:showFlags),button('VIEW RESULT',()=>viewResult(root,matchId,parent)));root.replaceChildren(back,el('h3','Match '+shortId(matchId)));
 try{const replay=await registry('dev-review-replay',{matchId});const host=el('div');root.append(host);const {mountReplayViewer}=await import('/client-v13/replay-viewer.js?v=491af6f21a5b6c5518d6f811ff224c8e5210f38266c0e3a92521a4f3ebd6488c');mountReplayViewer(host,replay);}catch(error){if(error.message==='Replay unavailable')root.append(el('p','Replay unavailable'));else throw error;}
 root.append(technical({matchId}));
}
async function viewResult(root,matchId,parent){
 const back=el('div',undefined,'actions');if(parent&&!parent.recent)back.append(button(parent.recent?'Back to Recent / Find Game':'Back to '+parent.name,()=>backToPlayer(root,parent)));back.append(button(parent?.recent?'Back to Recent / Find Game':'Back to Flags / Review',parent?.recent?render:showFlags));root.replaceChildren(back);
 try{const d=await registry('dev-review-result',{matchId}),{buildResultScreen}=await import('/client-v13/result-screen.js');if(!document.querySelector('link[data-dev-result]')){const css=el('link');css.rel='stylesheet';css.href='/styles-result-screen.css';css.dataset.devResult='1';document.head.append(css);}const panel=buildResultScreen(d,{historical:true,back:()=>parent?backToPlayer(root,parent):render()});panel.querySelector('.cs-result-actions button').textContent=parent?.recent?'BACK TO RECENT / FIND GAME':parent?'BACK TO '+parent.name.toUpperCase():'BACK TO FLAGS / REVIEW';root.append(panel);
 }catch(e){if(e.message==='Result unavailable')root.append(el('p','Result unavailable'));else throw e;}
}
function showFlags(){section='Flags / Review';document.querySelectorAll('nav button').forEach(b=>{if(b.getAttribute('aria-label')==='Flags / Review')b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});return render();}
async function review(root){
 const data=await updateBadge();root.append(el('p','NOT OK requires a reason and flags the player’s account. Scores remain private until you remove the flag in Players. OK does not remove an existing account flag.','muted'));
 const search=el('input');search.type='search';search.placeholder='Find a player, match or reason';search.setAttribute('aria-label','Search flags');search.value=reviewQuery;
 const filters=el('div'),results=el('div'),pager=el('div',undefined,'actions');root.append(filters,search,results,pager);
 function draw(){
  filters.replaceChildren(filterGroup('Flag status',[['needs','Needs Review',data.counts.needs],['ok','OK',data.counts.ok],['notOk','NOT OK',data.counts.notOk]],reviewFilter,v=>{reviewFilter=v;reviewPage=0;draw();}));
  const words=reviewQuery.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean),status={needs:'Needs Review',ok:'OK',notOk:'NOT OK'}[reviewFilter],rows=data.items.filter(r=>r.status===status&&words.every(w=>[r.displayName,r.matchId,shortId(r.matchId),flagReason(r),r.mode,r.status].join(' ').toLocaleLowerCase().includes(w)));
  reviewPage=Math.min(reviewPage,Math.max(0,Math.ceil(rows.length/50)-1));results.replaceChildren(caseTable(rows.slice(reviewPage*50,reviewPage*50+50),root,null,render));
  if(!rows.length)results.append(el('p','No cases match this view.'));const previous=button('Previous',()=>{reviewPage--;draw();}),next=button('Next',()=>{reviewPage++;draw();});previous.disabled=reviewPage===0;next.disabled=(reviewPage+1)*50>=rows.length;pager.replaceChildren(previous,el('span','Page '+(reviewPage+1)+' of '+Math.max(1,Math.ceil(rows.length/50))),next);
 }
 search.oninput=()=>{reviewQuery=search.value;reviewPage=0;draw();};draw();
}
const displayNumber=n=>n==null?'Unavailable':new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(n);
let refreshPlayerList=null;
function playerCounts(counts){const online=document.querySelector("#player-online");if(online){online.textContent=String(counts.online);online.style.display="";online.title=counts.online+" registered players online (seen in the last 2 minutes)";online.setAttribute("aria-label",online.title);}const total=document.querySelector('#player-total'),badge=document.querySelector('#player-new');if(total)total.textContent=' ('+counts.total+')';if(badge){badge.textContent='+'+counts.new;badge.title=counts.new+' new registrations in the last 7 days';}}
async function players(root){
 const input=el('input');input.type='search';input.setAttribute('aria-label','Find player');input.placeholder='Display name or username';input.value=playerQuery;const results=el('div'),filters=el('div',undefined,'filter-group'),newButton=button('New registry',()=>{playersNewOnly=!playersNewOnly;newButton.setAttribute('aria-pressed',String(playersNewOnly));return search();});newButton.setAttribute('aria-pressed',String(playersNewOnly));newButton.title='Show only registrations from the last 7 days';filters.append(newButton);root.append(input,filters,results);let request=0;
 async function search(){const ticket=++request;try{const d=await registry('dev-player-search',{query:input.value,newOnly:playersNewOnly});if(ticket!==request)return;playerCounts(d.counts);results.replaceChildren(table(['Player','Username','Country','Status','Actions'],d.items.map(p=>{const name=el('span');const link=button(p.displayName,()=>playerDetail(root,p.playerId));if(p.online){link.classList.add("online-player");name.append(link,el("strong"," ONLINE","online-player"));}else name.append(link);if(p.isNew)name.append(el('strong',' NEW','new-player'));return [name,p.username,p.country,restrictionLabel(p.status)+(p.warningAction==='Player warned'?' · WARNING':''),restrictionControls(p,async()=>{const d=await registry("dev-player-get",{playerId:p.playerId});return d;},search)];})));if(!d.items.length)results.append(el('p','No players found.'));if(d.more)results.append(el('p','Showing the first 50 matches. Type more of the name to narrow the list.'));}catch(e){message.textContent=e.message;}}
 refreshPlayerList=()=>results.isConnected?search():registry("dev-player-search",{}).then(d=>playerCounts(d.counts));input.oninput=()=>{playerQuery=input.value;search();};await search();
}
async function playerDetail(root,playerId){
 const d=await registry('dev-player-get',{playerId}),p=d.player,parent={playerId,name:p.displayName,admin:true};root.replaceChildren(button(section==='Recent / Find Game'?'Back to Recent / Find Game':'Back to Players',render));const identity=el('div',undefined,'player-heading'),avatar=el('img');avatar.src='/'+p.avatar.replace(/^\//,'');avatar.alt=p.displayName;identity.append(avatar,el('h3',p.displayName,'player-title'));root.append(identity,descriptionList([['Username',p.username],['Country',p.country],['Joined',stamp(p.createdAt)]]));
 root.append(el("strong",restrictionLabel(p.status)+(p.notice?.kind==='WARNING'?' · WARNING':'')),el("p",p.notice?.reason||''),restrictionControls(p,async()=>d,()=>playerDetail(root,playerId)),moderationControls(root,d));
 const labels={games:'Games played',wins:'Wins',losses:'Losses',draws:'Draws',lifetimeScore:'Lifetime Score',averageScore:'Average Match Score',highestScore:'Highest Match Score',bestChain:'Best chain',shots:'Shots',hits:'Hits',winRate:'Win rate (%)'};
 root.append(el('h3','Game record'),descriptionList(Object.entries(labels).map(([key,label])=>[label,displayNumber(d.stats[key])])),el('p','Game totals come from completed match results and cannot be edited here without changing those results.','muted'));
 root.append(el('h3','Reliability and streaks'),descriptionList([['Reliability',d.reliability.percent==null?'Unrated':displayNumber(d.reliability.percent)+'%'],['AFK penalties',d.reliability.outstandingAFK],['Disconnect penalties',d.reliability.Disconnect],['AFK penalties forgiven',d.reliability.forgivenAFK],['Clean games in a row',d.reliability.cleanStreak],['Current login streak',d.editable.streak],['Best login streak',d.editable.bestStreak]]),button('EDIT',()=>editPlayer(root,d)));
 root.append(el('h3','Recent matches'),table(['Match','Mode','Date','Outcome','Score',''],d.recent.map(r=>[shortId(r.matchId),r.mode,stamp(r.date),r.outcome,displayNumber(r.score),matchActions(root,r,parent)])));
 root.append(el('h3','Flagged cases'),table(['Match','Reason','Status',''],d.flags.map(r=>[shortId(r.matchId),flagReason(r),r.status,button('OPEN FLAGS',()=>{section='Flags / Review';heading.textContent=section;document.querySelectorAll('nav button').forEach(b=>{if(b.getAttribute('aria-label')===section)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});return playerCases(root,p.playerId,p.displayName);})])));if(!d.flags.length)root.append(el('p','No flagged cases.'));
 root.append(el('h3','Feedback'),table(['Type','Submitted','Message',''],d.feedback.map(f=>[f.type==='BUG'?'Bug':'Idea',stamp(f.timestamp),f.preview,button('OPEN FEEDBACK',()=>feedbackDetail(root,f.id,()=>playerDetail(root,playerId)))])));if(!d.feedback.length)root.append(el('p','No feedback from this player.'));
 root.append(el('h3','Corrections'),table(['What changed','Before','After / Reason','Date','Changed by'],d.audit.map(a=>[a.field+(a.matchId?' · '+shortId(a.matchId):''),a.oldValue,a.newValue,stamp(a.date),a.developer])));if(!d.audit.length)root.append(el('p','No manual corrections.'));
}
function restrictionLabel(status){return {active:'ACTIVE',flagged:'FLAGGED — scores hidden',banned:'BANNED — login blocked, scores hidden'}[status]||'Unavailable';}
function restrictionControls(player,getDetail,refresh){
 const actions=el('div',undefined,'actions');if(player.role!=='player')return actions;
 const choices=player.status==='banned'?[['UNBAN','UNBAN']]:player.status==='flagged'?[['BAN','BAN'],['UNFLAG','REMOVE FLAG']]:player.status==='active'?[['BAN','BAN'],['FLAG','FLAG']]:[];
 if(['active','flagged'].includes(player.status))choices.unshift(['WARN','WARNING']);if(player.warningAction==='Player warned'||player.notice?.kind==='WARNING')choices.push(['UNWARN','REMOVE WARNING']);
 for(const [action,label]of choices)actions.append(button(label,async()=>restrictionDialog(await getDetail(),action,label,refresh)));
 return actions;
}
function restrictionDialog(d,action,label,refresh){
 const dialog=el('dialog',undefined,'review-confirm'),title=el('h2',label+' — '+d.player.displayName),form=el('form'),reason=el('textarea'),error=el('p'),actions=el('div',undefined,'actions');title.id='restriction-title';dialog.setAttribute('aria-labelledby',title.id);reason.setAttribute('aria-label','Reason');reason.required=true;reason.maxLength=500;reason.rows=3;error.setAttribute('role','status');
 const explanations={'NOT OK':'Flags this account and hides public scores. The player will see your reason in their own profile. OK later does not remove the account flag.',WARN:'Shows WARNING beside the player’s name to that player only, with this reason in their profile. Login and public scores stay unchanged.',UNWARN:'Removes the private warning. Other restrictions stay unchanged.',BAN:'Blocks account login, signs out existing account sessions, and hides public rankings and profile scores. Match evidence is kept.',FLAG:'Hides public rankings and profile scores. The player can still log in and play.',UNBAN:'Allows login again and restores public score visibility. Old sessions stay signed out.',UNFLAG:'Restores public score visibility.'};
 const close=()=>{dialog.close();dialog.remove();},cancel=button('Cancel',close),save=el('button',label);save.type='submit';actions.append(cancel,save);form.append(el('label',['WARN','FLAG','NOT OK'].includes(action)?'Reason (visible to this player and Dev Room)':'Reason (private to Dev Room)'),reason,error,actions);
 form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{if(action==='NOT OK')await registry('dev-review-decide',{caseId:d.caseId,action,reason:reason.value});else await registry('dev-player-restrict',{playerId:d.player.playerId,revision:d.revision,action,reason:reason.value});close();await refresh();await updateActivityBadges();}catch(e){error.textContent=e.message;}finally{save.disabled=false;}};
 dialog.append(title,el('p',explanations[action]),form);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(dialog);dialog.showModal();reason.focus();
}
function moderationControls(root,d){
 const group=el('section',undefined,'card');group.append(el('h3','Account details'),el('p','Owner changes do not use the player’s display-name allowance. Email is private.','muted'));
 for(const [field,label]of [['username','Username'],['displayName','Display Name'],['email','Email'],['bio','Bio']]){
  const row=el('section',undefined,'moderation-field');row.setAttribute('aria-label',label);row.append(el('h4',label),el('p',d.player[field]||'Not set','description'));
  const actions=el('div',undefined,'actions'),edit=button('EDIT',()=>editModeration(root,d,field,label));edit.setAttribute('aria-label','Edit '+label.toLowerCase());actions.append(edit);
  const update=async(operation,value)=>{await registry('dev-player-moderate',{playerId:d.player.playerId,revision:d.revision,field,operation,value});await playerDetail(root,d.player.playerId);};
  if(field==='email'||field==='bio'){const clear=button(field==='email'?'REMOVE':'CLEAR',()=>update('edit',''));clear.setAttribute('aria-label',(field==='email'?'Remove ':'Clear ')+label.toLowerCase());clear.disabled=!d.player[field];actions.append(clear);}
  if(field!=='email'){const locked=d.player.locks[field],toggle=button(locked?'UNLOCK':'LOCK',()=>update('lock',!locked));toggle.setAttribute('aria-label',(locked?'Unlock ':'Lock ')+label.toLowerCase());row.append(el('strong',locked?'LOCKED':'UNLOCKED','lock-state'));actions.append(toggle);}
  row.append(actions);group.append(row);
 }
 return group;
}
function editModeration(root,d,field,label){
 const dialog=el('dialog',undefined,'review-confirm'),form=el('form'),title=el('h2','Edit '+label),input=el(field==='bio'?'textarea':'input'),error=el('p'),actions=el('div',undefined,'actions');title.id='moderation-title';dialog.setAttribute('aria-labelledby',title.id);input.setAttribute('aria-label',label);input.value=d.player[field]||'';input.maxLength=field==='bio'?280:field==='email'?254:14;if(field==='email')input.type='email';if(field==='bio')input.rows=5;input.required=['username','displayName'].includes(field);error.setAttribute('role','status');
 const close=()=>{dialog.close();dialog.remove();},cancel=button('Cancel',close);cancel.type='button';const save=el('button','SAVE');save.type='submit';actions.append(cancel,save);form.append(input,error,actions);form.onsubmit=async event=>{event.preventDefault();save.disabled=true;error.textContent='';try{await registry('dev-player-moderate',{playerId:d.player.playerId,revision:d.revision,field,operation:'edit',value:input.value});close();await playerDetail(root,d.player.playerId);}catch(e){error.textContent=e.message;}finally{save.disabled=false;}};
 dialog.append(title,el('p',field==='email'?'Private account email. No email is sent.':field==='bio'?'Plain text, up to 280 characters.':'3–14 letters or numbers. This changes the name, not the account identity.'),form);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});document.body.append(dialog);dialog.showModal();input.focus();
}
function editPlayer(root,d){
 root.replaceChildren(el('h3','Edit '+d.player.displayName),el('p','Remove a mistaken penalty, or restore a penalty previously removed here. The existing Reliability and AFK forgiveness rules are recalculated; no extra clean game is granted.'));
 const inputs={};for(const [key,label]of [['streak','Current login streak'],['bestStreak','Best login streak']]){const wrap=el('label',label),input=el('input');input.type='number';input.required=true;input.min=0;input.max=100000;input.step=1;input.value=d.editable[key];input.setAttribute('aria-label',label);inputs[key]=input;wrap.append(input);root.append(wrap);}
 const changes=new Map();root.append(el('h3','Recorded penalties'),el('p','Checked penalties count toward Reliability. Uncheck only a penalty that was recorded incorrectly. Previously forgiven AFK penalties may no longer affect the current count.','muted'),table(['Type','Match','Date','Count penalty'],d.penalties.map(p=>{const input=el('input');input.type='checkbox';input.checked=!p.excluded;input.disabled=!p.editable;input.setAttribute('aria-label','Count '+p.kind+' penalty '+shortId(p.matchId));input.onchange=()=>changes.set(p.matchId,{matchId:p.matchId,excluded:!input.checked});return [p.kind,shortId(p.matchId),stamp(p.date),p.editable?input:el('small','Protected exemption')];})));
 if(!d.penalties.length)root.append(el('p','No recorded AFK or Disconnect penalties.'));const actions=el('div',undefined,'actions');actions.append(button('Cancel',()=>playerDetail(root,d.player.playerId)),button('SAVE CHANGES',async()=>{for(const input of Object.values(inputs))if(!input.reportValidity())return;await registry('dev-player-correct',{playerId:d.player.playerId,revision:d.revision,streak:Number(inputs.streak.value),bestStreak:Number(inputs.bestStreak.value),penalties:[...changes.values()]});await playerDetail(root,d.player.playerId);}));root.append(actions);
}
function activityBadge(id,count,label){const badge=document.getElementById(id);if(!badge)return;badge.textContent=String(count);badge.style.display=count>0?'':'none';badge.title=count+' '+label;badge.setAttribute('aria-label',badge.title);}
let activityRequest=null;
function updateActivityBadges(){
 if(activityRequest)return activityRequest;
 activityRequest=Promise.allSettled([
  registry('dev-feedback-list',{type:'ALL',status:'NEW',offset:0}).then(d=>activityBadge('feedback-count',d.inboxCounts.NEW,'new feedback reports')),
  api('dev-room/games').then(d=>activityBadge('live-count',d.games.length,'active games')),
  refreshPlayerList?refreshPlayerList():registry('dev-player-search',{}).then(d=>playerCounts(d.counts))
 ]).then(results=>{for(const [i,r]of results.entries())if(r.status==='rejected'){const b=document.getElementById(['feedback-count','live-count','player-online'][i]);if(b){b.style.display='none';b.title='Count unavailable';}}}).finally(()=>{activityRequest=null;});
 return activityRequest;
}
const sections={'Overview':overview,'Live Games':live,'Recent / Find Game':recent,'Players':players,'Feedback':feedback,'Flags / Review':review};
async function render(){refreshPlayerList=null;const turn=++generation;heading.textContent=section;content.replaceChildren();message.textContent='Loading…';const root=el('div');try{await sections[section](root);await updateActivityBadges();if(section!=='Flags / Review')await updateBadge();if(turn!==generation)return;content.replaceChildren(root);message.textContent='';}catch(e){if(turn===generation||e.message.includes('Developer access'))message.textContent=e.message;}}
for(const name of ['Overview','Live Games','Recent / Find Game','Players','Feedback','Flags / Review']){const b=button(name+(sections[name]?'':' · Coming later'),()=>{section=name;document.querySelectorAll('nav button').forEach(n=>n.removeAttribute('aria-current'));b.setAttribute('aria-current','page');return render();});b.disabled=!sections[name];if(name==='Players'){b.setAttribute('aria-label','Players');const total=el('span',' (…)');total.id='player-total';const badge=el('span','…','count-badge');badge.id='player-new';const online=el('span','…','count-badge online-count');online.id='player-online';b.append(total,badge,online);}if(name==='Feedback'||name==='Live Games'){b.setAttribute('aria-label',name);const badge=el('span','','count-badge');badge.id=name==='Feedback'?'feedback-count':'live-count';badge.style.display='none';b.append(badge);}if(name==='Flags / Review'){b.setAttribute('aria-label',name);const badge=el('span','…','count-badge');badge.id='review-count';b.append(badge);}if(name===section)b.setAttribute('aria-current','page');document.querySelector('nav').append(b);}
document.querySelector('#refresh').onclick=render;render();

// Refresh sidebar activity without replacing an open detail or edit form.
setInterval(()=>{if(document.visibilityState==='visible')void updateActivityBadges();},30000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void updateActivityBadges();});
