import {processedChainCells} from '../combat/chain-statistics.js';
import {cloneHost} from '../archives.js';
import {normalTarget,commitEliminations,syncRing} from './ring.js';
import type {HostState,HostCommand} from './contracts.js';import type {Operation,ResolutionContext} from '../combat/contracts.js';import type {PlayerId} from '../model.js';import {startResolution,stepResolution,checkTerminal} from '../combat/resolver.js';import {answerDecision} from '../combat/decisions.js';import {random,shuffle} from '../combat/rng.js';import {seat,cellKey} from '../combat/access.js';import {place} from './initialization.js';import {observeResurrectionFeedback,observeRuleEvent,refreshHost} from './refresh.js';
export interface HostExecution {settleRootBeforeTerminal?:boolean;observePresentationStep?:(host:HostState)=>void;normalTerminalMessage?:(host:HostState)=>void;reserveNormalDemonRunes?:(ctx:ResolutionContext)=>void}
function root(h:HostState,ops:Operation[],purpose:HostState['rootPurpose']){if(!h.activePlayerId||h.pendingRoot)throw Error('Root boundary violation');h.pendingRoot=startResolution(h.state,'match-root-'+(++h.rootSerial),'host-root-'+h.rootSerial,h.activePlayerId,ops,h.rng);h.rootEventCursor=0;h.rootPurpose=purpose;h.status='running';}
function collect(h:HostState){const r=h.pendingRoot;if(!r)return;h.state=r.state;h.rng=r.rng;for(let i=0;i<r.frames.length;i++){const f=r.frames[i]!;if((f.kind!=='wave'&&f.kind!=='interrupt')||h.statisticsFrames.some(s=>s.frameId===f.id))continue;const parent=r.frames[i-1];h.statisticsFrames.push({frameId:f.id,actorId:f.compatibilityTurnId,count:0,startCells:h.counters.reduce((n,c)=>n+c.cellsAffected,0),biggest:f.kind==='wave'&&h.rootPurpose==='shot'&&parent?.kind==='root'});}while(h.rootEventCursor<r.events.length)observeRuleEvent(h,r.events[h.rootEventCursor++]!);h.statisticsFrames=h.statisticsFrames.filter(f=>r.frames.some(frame=>frame.id===f.frameId));
 // One settled causal root includes all nested waves/interrupts, regardless of
 // reaction owner. Count processed cells once, never attack announcements.
 if(r.status==='complete'){const cells=r.events.reduce((n,e)=>n+processedChainCells(e),0),actor=r.events.find(e=>e.statistics?.rootActorId)?.statistics?.rootActorId??r.activePlayerId,counter=h.counters.find(c=>c.playerId===actor);if(counter){counter.biggestAttack=Math.max(counter.biggestAttack,cells);counter.longestChain=Math.max(counter.longestChain,cells);}}
}
function terminal(h:HostState,execution?:HostExecution){h.status='complete';h.turnStep='finish';h.pendingPolicyCells=[];execution?.normalTerminalMessage?.(h);refreshHost(h);}
function nextTurn(h:HostState){const order=h.state.ring?.order||h.config.players.map(p=>p.id),next=order[(order.indexOf(h.activePlayerId!)+1)%order.length]!;if(next===h.starterId)h.round++;h.activePlayerId=next;h.turnIndex++;h.turnStep='enter';h.guards.turnActions=0;h.status='awaiting-turn';h.lastProbeSkippedPlague=false;}
function budget(h:HostState){const p=seat(h.state,h.activePlayerId!),hero=h.state.match.units.find(u=>u.ownerId===p.playerId&&u.type==='hero');p.ordinaryShots=p.nextShots+(hero?.hero?.activated&&hero.hero.currentCell?1:0);p.nextShots=2;}
export function pumpHost(h:HostState,maxSteps=100000,execution?:HostExecution):void {let steps=0;while(h.status==='running'){if(++steps>maxSteps)throw Error('Host step bound exceeded');if(h.pendingRoot){const r=h.pendingRoot;execution?.reserveNormalDemonRunes?.(r);stepResolution(r,{deferLocalHeroPolicy:true,deferTerminal:!!execution?.settleRootBeforeTerminal});collect(h);execution?.observePresentationStep?.(h);if(r.status==='awaiting-decision'){h.status='awaiting-decision';refreshHost(h);return;}if(r.status==='complete'){const purpose=h.rootPurpose;h.pendingRoot=null;h.rootPurpose=null;const displaced=commitEliminations(h);if(h.state.match.outcome.kind!=='ongoing'){terminal(h,execution);return;}if(displaced){refreshHost(h);return;}const p=seat(h.state,h.activePlayerId!);if(purpose==='shot'){if(p.sameTurnBonusTarget==='chain'){p.ordinaryShots+=p.currentChainBonus;p.currentChainBonus=0;}h.turnStep=p.ordinaryShots>0?'actions':'plague';}else if(purpose==='exit')h.turnStep='finish';}continue;}
 const p=seat(h.state,h.activePlayerId!),primary=p.playerId===h.config.players[0]!.id;
 if(h.turnStep==='enter'){h.plagueAwareAtTurnStart=h.state.plagues.some(q=>q.targetPlayerId===p.reactionTarget.playerId);if(primary){budget(h);h.turnStep='catapult';}else h.turnStep='resurrection';}
 else if(h.turnStep==='resurrection'){h.turnStep=primary?'scout':'scout';if(p.clericLater)root(h,[{kind:'turn-resurrection',ownerId:p.playerId}],'entry');}
 else if(h.turnStep==='scout'){h.turnStep=primary?'actions':'catapult';if(p.spyLater)root(h,[{kind:'turn-scout',ownerId:p.playerId,count:p.spyLater}],'entry');}
 else if(h.turnStep==='catapult'){h.turnStep=primary?'resurrection':'budget';if(p.catapultLater){const count=p.catapultLater;p.catapultLater=0;root(h,[{kind:'catapult-series',ownerId:p.playerId,remaining:count}],'entry');}}
 else if(h.turnStep==='budget'){budget(h);h.turnStep='actions';}
 else if(h.turnStep==='actions'){if(p.ordinaryShots<=0){h.turnStep='plague';continue;}if(!primary){const probe=startResolution(h.state,'match-root-'+(h.rootSerial+1),'host-root-'+(h.rootSerial+1),p.playerId,[],h.rng);if(checkTerminal(probe,'enemy-pre-shot')){h.rootSerial++;h.pendingRoot=probe;h.rootEventCursor=0;collect(h);h.pendingRoot=null;terminal(h,execution);return;}}h.status='awaiting-command';}
 else if(h.turnStep==='plague'){if(h.lastProbeSkippedPlague){h.turnStep='finish';continue;}root(h,[...(h.state.ring?h.state.plagues.filter(q=>q.moveOnPlayerId===p.playerId).map(q=>({kind:'plague-step' as const,targetBoardId:q.targetBoardId})):[{kind:'plague-step' as const,targetBoardId:p.reactionTarget.boardId}]),{kind:'terminal-check',reason:'direct-end'}],'exit');}
 else if(h.turnStep==='finish')nextTurn(h);
 else throw Error('Unsupported host continuation '+h.turnStep);
 }refreshHost(h);}
export function acceptCommand(host:HostState,command:HostCommand,execution?:HostExecution):HostState {if(!['place','start','advance-turn','shoot','answer'].includes(command.kind))throw Error('Unknown host command');if(host.status==='complete')throw Error('Match already complete');if(host.history.some(r=>r.command.id===command.id))throw Error('Duplicate command');if(!/^[A-Za-z0-9_-]{1,96}$/.test(command.id))throw Error('Invalid command ID');const h=cloneHost(host),rngBefore=h.rng.cursor,eventStart=h.events.length;
 if(command.kind==='place')place(h,command.placement);
 else if(command.kind==='start'){if(h.status!=='placement')throw Error('Match already started');for(const p of h.config.players)for(const [type,count]of Object.entries(p.roster))if(h.state.match.units.filter(u=>u.ownerId===p.id&&u.type===type).length!==count)throw Error('Incomplete roster');h.initial=structuredClone(h.state);h.initialRng=structuredClone(h.rng);for(const u of h.state.match.units)if(u.hero)u.hero.originalCell=u.hero.currentCell?{...u.hero.currentCell}:null;if(h.state.ring){shuffle(h.state.ring.order,h.rng,'initial-active-ring');syncRing(h.state);h.starterId=h.state.ring.order[0]!;}else h.starterId=h.config.players[Math.floor(random(h.rng,'round-starter')*h.config.players.length)]!.id;h.activePlayerId=h.starterId;h.round=1;h.turnIndex=1;h.status='running';h.turnStep='enter';pumpHost(h,100000,execution);}
 else if(command.kind==='advance-turn'){if(h.status!=='awaiting-turn')throw Error('No turn boundary');h.status='running';pumpHost(h,100000,execution);}
 else if(command.kind==='answer'){if(h.status!=='awaiting-decision'||!h.pendingRoot)throw Error('No decision');answerDecision(h.pendingRoot,command.answer);collect(h);h.status=h.pendingRoot.status==='awaiting-decision'?'awaiting-decision':'running';pumpHost(h,100000,execution);}
 else {if(h.status!=='awaiting-command'||command.actorId!==h.activePlayerId)throw Error('Wrong actor or phase');const p=seat(h.state,command.actorId),target=normalTarget(h.state,p.playerId);if(command.boardId!==target.boardId||command.cell.x<0||command.cell.y<0||command.cell.x>=h.config.size||command.cell.y>=h.config.size||!Number.isInteger(command.cell.x)||!Number.isInteger(command.cell.y))throw Error('Illegal target');const k=cellKey(command.cell),repeated=target.shots.includes(k),probe=target.resurrection.searchActive&&target.resurrection.suspects.some(id=>h.state.match.units.find(u=>u.id===id)?.cells.some(c=>cellKey(c)===k));if(repeated&&!probe)throw Error('Already shot');const stats=h.counters.find(s=>s.playerId===p.playerId)!;stats.shots++;stats.directHits+=!repeated&&target.occupied.includes(k)?1:0;stats.cellsAffected++;stats.biggestAttack=Math.max(1,stats.biggestAttack);h.guards.turnActions++;if(repeated){const suspect=target.resurrection.suspects.find(id=>h.state.match.units.find(u=>u.id===id)?.cells.some(c=>cellKey(c)===k));target.resurrection.suspects=target.resurrection.suspects.filter(id=>id!==suspect);observeResurrectionFeedback(h,target.boardId,command.cell,false);p.ordinaryShots--;h.lastProbeSkippedPlague=p.sameTurnBonusTarget==='ordinary';h.turnStep=p.ordinaryShots>0?'actions':'plague';h.status='running';pumpHost(h,100000,execution);}
 else {h.lastProbeSkippedPlague=false;root(h,[{kind:'host-direct-shot',meta:{actorId:p.playerId,ownerId:p.playerId,targetPlayerId:target.playerId,targetBoardId:target.boardId,sourceUnitId:null,source:p.sameTurnBonusTarget==='ordinary'?'direct-human':'direct-ai',origin:{...command.cell}},cell:{...command.cell}},{kind:'terminal-check',reason:'direct-end'}],'shot');pumpHost(h,100000,execution);}}
 h.history.push({sequence:h.history.length+1,command:structuredClone(command),rngBefore,rngAfter:h.rng.cursor,eventStart,eventEnd:h.events.length});refreshHost(h);return h;}
