import {cloneCombat,cloneRng} from '../archives.js';
import {normalTarget,survives} from '../host/ring.js';
import {catapultImpact,catapultSeries} from './catapult.js';import {plagueProgress} from './plague-scheduler.js';
import type {PlayerId,Unit,Cell} from '../model.js';import {id} from '../model.js';import type {ResolutionContext,CombatState,Operation,ReactionEntry,SourceMetadata,ExplicitRng} from './contracts.js';
import {targetKnowledge,ruleTurn,seat,unit,unitAt,boardSize,cellKey,parseKey,available,destroyed,emit} from './access.js';import {createRuleRng,random} from './rng.js';import {pushFrame,work,waveOperations,complete,terminalTruncate} from './scheduling.js';import {requireDecision} from './decisions.js';import {resolveImpact,unitReaction} from './impact.js';import {archerShotCount,archerTargets} from './units/archer.js';import {goblinTargets} from './units/goblin.js';import {monkProximity} from './units/monk.js';import {heroDestinations,killHero,moveHero} from './units/hero.js';import {resurrectionCandidates,resurrect} from './units/cleric.js';import {releaseHeldPlague} from './units/necromancer.js';import {demonPatternFrom,dragonFlightPathsFrom,wizardBlastLayersFrom} from '../rules/attacks.js';
export function startResolution(state:CombatState,rootId:string,acceptedActionId:string,activePlayerId:PlayerId,operations:Operation[],rng:ExplicitRng=createRuleRng(),scope:ResolutionContext['scope']='accepted-action'):ResolutionContext {if(scope==='accepted-action'&&operations.some(o=>['impact','attack','flush-reactions','monk-continuation','scheduled-benefit','direct-after','direct-finish','catapult-resume','plague-progress'].includes(o.kind)))throw Error('Internal operations require comparison scope or a parent action');if(!/^[A-Za-z][A-Za-z0-9_-]{0,47}$/.test(rootId))throw Error('Invalid resolution ID');if(!state.ring&&(state.match.players.length!==2||state.match.config.format!=='legacy-1v1'))throw Error('N-player resolution requires an explicit active ring');if(state.seats.some(p=>boardSize(state,p.boardId)!==boardSize(state,state.seats[0]!.boardId)))throw Error('Legacy geometry requires equal square boards');if(state.match.outcome.kind!=='ongoing')throw Error('Cannot accept action after outcome');const ctx:ResolutionContext={contract:'stone-throw-resolution-v1',scope,id:id<'resolution'>(rootId),acceptedActionId,activePlayerId,compatibility:'golden-v1.427',status:'running',externalEntropy:[],state:cloneCombat(state),rng:cloneRng(rng),frames:[],future:[],decisions:[],events:[],generated:[],nextWork:1,nextDecision:1,completedAtEvent:null};seat(ctx.state,activePlayerId);pushFrame(ctx,'root',operations);return ctx;}
export function living(ctx:ResolutionContext,ownerId:PlayerId){const p=seat(ctx.state,ownerId);if(p.resurrection.searchActive&&p.resurrection.actualUnitId)return true;return ctx.state.match.units.some(u=>u.ownerId===ownerId&&(u.type==='hero'?!!u.hero?.activated&&!!u.hero.currentCell:['inf','cav','archer','monk','castle'].includes(u.type||'')&&!destroyed(ctx.state,u)&&u.cells.length>0));}
export function checkTerminal(ctx:ResolutionContext,reason:string):boolean {if(ctx.state.ring)return false;const dead=ctx.state.seats.filter(p=>!living(ctx,p.playerId)).map(p=>p.playerId);if(!dead.length)return false;ctx.state.match.outcome=dead.length===ctx.state.seats.length?{kind:'draw'}:{kind:'win',winnerIds:ctx.state.seats.filter(p=>!dead.includes(p.playerId)).map(p=>p.playerId),eliminatedIds:dead};emit(ctx,'outcome',null,null,[],null,ctx.state.match.outcome.kind);terminalTruncate(ctx,reason);return true;}
function attack(ctx:ResolutionContext,entry:ReactionEntry){const announcement=emit(ctx,'attack-started',entry.meta,entry.meta.sourceUnitId,[],null,entry.kind);const {meta}=entry,size=boardSize(ctx.state,meta.targetBoardId);if(!meta.origin)throw Error('Attack requires origin');let layers:Cell[][]=[],defer=false;
 if(entry.kind==='archer'){const u=meta.sourceUnitId?unit(ctx.state,meta.sourceUnitId):null;if(u?.abilities.some(a=>a.kind==='archer'&&a.spent))return;if(u){const a=u.abilities.find(a=>a.kind==='archer');if(a)a.spent=true;else u.abilities.push({kind:'archer',spent:true});}emit(ctx,'ability-spent',meta,u?.id||null);const count=archerShotCount(ctx.rng);layers=[archerTargets(size,meta.origin,new Set(seat(ctx.state,meta.targetPlayerId).shots),count,ctx.rng)];defer=true;}
 else if(entry.kind==='goblin')layers=[goblinTargets(available(ctx.state,meta.targetBoardId,meta.targetPlayerId),ctx.rng).map(parseKey)];
 else if(entry.kind==='dragon')layers=dragonFlightPathsFrom({size},cellKey(meta.origin)).map(a=>a.map(parseKey));
 else if(entry.kind==='demon')layers=[demonPatternFrom({size},cellKey(meta.origin)).map(parseKey)];
 else if(entry.kind==='wizard'){layers=wizardBlastLayersFrom({size},cellKey(meta.origin)).map(a=>a.map(parseKey));defer=true;}
 else {let cells=available(ctx.state,meta.targetBoardId,meta.targetPlayerId);if(ctx.state.monkDuelActive){const known=targetKnowledge(ctx.state,meta.ownerId,meta.targetPlayerId).monkCandidates.filter(k=>cells.includes(k));if(known.length)cells=known;}if(cells.length)layers=[[parseKey(cells[Math.floor(random(ctx.rng,'monk-target')*cells.length)]!)]];}
 if(announcement.statistics)announcement.statistics.plannedCells=layers.flat().map(c=>({...c}));
 const ops:Operation[]=[];for(const layer of layers){for(const cell of layer)ops.push({kind:'impact',meta,cell,deferReactions:defer});if(entry.kind==='wizard')ops.push({kind:'flush-reactions'});}if(entry.kind==='monk-deflect')ops.push({kind:'monk-continuation',meta});if(entry.kind==='archer')ops.push({kind:'hero-queue'},{kind:'flush-reactions'});pushFrame(ctx,'attack',ops);
}
function heroes(ctx:ResolutionContext,deferLocalPolicy=false){while(ctx.state.heroQueue.length){const ev=ctx.state.heroQueue.shift()!,u=unit(ctx.state,ev.unitId);if(ev.kind==='third'){killHero(ctx,u,'third-hit-queue-return');return;}if(ev.kind==='first'){const owner=seat(ctx.state,u.ownerId);owner.occupied=owner.occupied.filter(k=>!u.cells.some(c=>cellKey(c)===k));}const legal=heroDestinations(ctx,u,ev.kind==='second'),p=seat(ctx.state,u.ownerId);if(ev.kind==='second'&&!legal.length){killHero(ctx,u,'trapped-queue-return');return;}if(p.decisionMode==='policy'&&ev.kind==='second'&&!deferLocalPolicy){moveHero(ctx,u,legal[Math.floor(random(ctx.rng,'hero-local-escape')*legal.length)]!);continue;}requireDecision(ctx,'hero-relocation',u.ownerId,u.boardId,u.id,legal);ctx.frames.at(-1)!.current.splice(ctx.frames.at(-1)!.cursor,0,work(ctx,{kind:'hero-queue'},'after-attack'));return;}}
function effects(ctx:ResolutionContext,deferTerminal=false){for(const p of [...ctx.state.seats].sort((a,b)=>a.releasePriority-b.releasePriority)){if(!p.releaseNow)continue;p.releaseNow=false;if(p.releaseRevivesPendingFirst&&p.clericLater){const choices=resurrectionCandidates(ctx,p.playerId);p.clericLater=false;if(choices.length)resurrect(ctx,p.playerId,choices[Math.floor(random(ctx.rng,'resurrection')*choices.length)]!);}releaseHeldPlague(ctx,p.playerId);}
 const p=seat(ctx.state,ruleTurn(ctx));if(p.sameTurnBonusTarget==='ordinary')p.ordinaryShots+=p.dwarfNow;else p.currentChainBonus+=p.dwarfNow;p.dwarfNow=0;
 if(p.catapultNow>0){const count=p.catapultNow;p.catapultNow=0;pushFrame(ctx,'catapult',[{kind:'catapult-series',ownerId:p.playerId,remaining:count},{kind:'same-turn-effects'}]);return;}
 if(p.clericNow){p.clericNow=false;if(!ctx.state.ring&&p.decisionMode==='interactive'&&p.ordinaryShots<=0){p.clericLater=true;}else {const choices=resurrectionCandidates(ctx,p.playerId);p.clericLater=false;if(choices.length){if(p.decisionMode==='policy')resurrect(ctx,p.playerId,choices[Math.floor(random(ctx.rng,'resurrection')*choices.length)]!);else{requireDecision(ctx,'resurrection',p.playerId,p.boardId,null,[],choices);const frame=ctx.frames.at(-1)!;frame.current.splice(frame.cursor,0,work(ctx,{kind:'same-turn-effects'},'same-turn'));if(!deferTerminal&&checkTerminal(ctx,'pending-resurrection-race'))return;return;}}}}
 if(p.elfNow){p.elfNow=false;const target=normalTarget(ctx.state,p.playerId);if(ctx.state.ring&&!survives(ctx.state,target.playerId)){p.spyLater=Math.max(p.spyLater,5);return;}const choices=available(ctx.state,target.boardId,target.playerId).filter(k=>!targetKnowledge(ctx.state,p.playerId,target.playerId).scouted.includes(k));requireDecision(ctx,'scout',p.playerId,target.boardId,null,choices.map(parseKey),[],p.decisionMode==='policy'?Math.min(5,choices.length):5);}
}
export function stepResolution(ctx:ResolutionContext,options:{deferLocalHeroPolicy?:boolean;deferTerminal?:boolean}={}):void {if(ctx.status!=='running')return;const frame=ctx.frames.at(-1);if(!frame){if(ctx.state.ring){const p=ctx.state.seats.find(p=>p.clericNow);if(p){p.clericNow=false;pushFrame(ctx,'root',[{kind:'turn-resurrection',ownerId:p.playerId}]);return;}}if(options.deferTerminal&&checkTerminal(ctx,'settled-root'))return;complete(ctx);return;}if(frame.cursor>=frame.current.length){if(frame.kind==='root'&&ctx.scope==='accepted-action'&&frame.next.length){const entries=frame.next;frame.next=[];pushFrame(ctx,'wave',waveOperations(entries),true);return;}if((frame.kind==='wave'||frame.kind==='interrupt')&&frame.next.length){frame.current=waveOperations(frame.next).map(op=>work(ctx,op,'next-wave',frame.id));frame.next=[];frame.cursor=0;return;}if(frame.kind==='wave'&&frame.stage==='body'){frame.stage='finish';ctx.state.monkDuelActive=false;frame.current=[{kind:'hero-queue'},{kind:'same-turn-effects'},...(frame.terminalCheck?[{kind:'terminal-check',reason:'chain-end'}]:[])].map(op=>work(ctx,op as Operation,'same-turn',frame.id));frame.cursor=0;return;}ctx.frames.pop();const parent=ctx.frames.at(-1);if(parent)parent.next.push(...frame.next);else ctx.generated.push(...frame.next);emit(ctx,'work-finished');return;}
 const current=frame.current[frame.cursor++]!;emit(ctx,'work-started',null,null,[],null,current.operation.kind);const op=current.operation;
 if(op.kind==='impact'){const result=resolveImpact(ctx,op.meta,op.cell,op.deferReactions);if(result.deferred)frame.deferred.push(result.deferred);if(result.reaction){if(op.meta.source==='plague')pushFrame(ctx,'wave',waveOperations([result.reaction]),true);else frame.next.push(result.reaction);}if(!result.repeat&&result.type!=='monk'&&['archer','goblin','monk-deflect'].includes(op.meta.source)){const interrupt=monkProximity(ctx,op.meta,cellKey(op.cell));if(interrupt){if(op.meta.source==='monk-deflect'&&!ctx.state.monkDuelActive){ctx.state.monkDuelActive=true;ctx.state.monkDuelHasHappened=true;emit(ctx,'monk-duel',op.meta);}pushFrame(ctx,'interrupt',waveOperations([interrupt]));}}}
 else if(op.kind==='flush-reactions'){for(const d of frame.deferred){const reaction=unitReaction(ctx,unit(ctx.state,d.unitId),d.meta,d.cell);if(reaction)frame.next.push(reaction);}frame.deferred=[];}
 else if(op.kind==='direct-shot'||op.kind==='host-direct-shot'){
 const attacker=seat(ctx.state,op.meta.ownerId),result=resolveImpact(ctx,op.meta,op.cell);if(result.repeat&&op.meta.source==='direct-human')return;if(!result.type)attacker.ordinaryShots--;const after:Operation[]=[{kind:'hero-queue'},{kind:'direct-after',meta:op.meta,cell:op.cell},...(op.kind==='direct-shot'?[{kind:'direct-finish',meta:op.meta} as Operation]:[])];if(result.reaction)after.unshift({kind:'wave',entries:[result.reaction],terminalCheck:true});pushFrame(ctx,'root',after);
 }else if(op.kind==='direct-after'){const target=unitAt(ctx.state,op.meta.targetBoardId,cellKey(op.cell));if(target?.type!=='monk'){const reaction=monkProximity(ctx,op.meta,cellKey(op.cell));if(reaction)pushFrame(ctx,'wave',waveOperations([reaction]),true);}}
 else if(op.kind==='direct-finish'){if(!options.deferTerminal&&checkTerminal(ctx,'direct-end'))return;const p=seat(ctx.state,op.meta.ownerId);if(p.ordinaryShots<=0)pushFrame(ctx,'root',[{kind:'plague-step',targetBoardId:op.meta.targetBoardId},{kind:'terminal-check',reason:'direct-end'}]);}
 else if(op.kind==='catapult')catapultImpact(ctx,op.meta,op.cell,op.impact,op.generated);
 else if(op.kind==='catapult-series')catapultSeries(ctx,op.ownerId,op.remaining);
 else if(op.kind==='catapult-resume'){const d=ctx.decisions.find(d=>d.id===op.decisionId);if(d?.status!=='answered'||!d.answer?.cell)throw Error('Catapult continuation requires answer');catapultImpact(ctx,op.meta,d.answer.cell,op.impact,op.generated);}
 else if(op.kind==='plague-step'){const due=ctx.state.plagues.filter(p=>p.targetBoardId===op.targetBoardId&&p.moveOnPlayerId===ctx.activePlayerId&&(!op.plagueId||p.outbreaks.some(o=>o.statisticsId===op.plagueId)));for(const plague of [...due].reverse()){const plagueId=plague.outbreaks[0]?.statisticsId;const frame=pushFrame(ctx,'plague',[{kind:'plague-progress',targetBoardId:op.targetBoardId,...(plagueId?{plagueId}:{}),outbreakIndex:0,parentIndex:0,childIndex:0,wanted:0,oldFrontier:[],nextFrontier:[],reserved:[],stage:'start'}]);frame.compatibilityTurnId=plague.triggerPlayerId;}}
 else if(op.kind==='plague-progress')plagueProgress(ctx,op);
 else if(op.kind==='turn-resurrection'){const p=seat(ctx.state,op.ownerId),choices=resurrectionCandidates(ctx,p.playerId);p.clericLater=false;if(choices.length){if(p.decisionMode==='policy')resurrect(ctx,p.playerId,choices[Math.floor(random(ctx.rng,'resurrection')*choices.length)]!);else requireDecision(ctx,'resurrection',p.playerId,p.boardId,null,[],choices);}}
 else if(op.kind==='turn-scout'){const p=seat(ctx.state,op.ownerId),target=normalTarget(ctx.state,p.playerId);if(ctx.state.ring&&!survives(ctx.state,target.playerId)){p.spyLater=Math.max(p.spyLater,op.count);return;}const cells=available(ctx.state,target.boardId,target.playerId).filter(k=>!targetKnowledge(ctx.state,p.playerId,target.playerId).scouted.includes(k));p.spyLater=0;if(cells.length&&op.count>0)requireDecision(ctx,'scout',p.playerId,target.boardId,null,cells.map(parseKey),[],p.decisionMode==='policy'?Math.min(op.count,cells.length):op.count);}
 else if(op.kind==='scheduled-benefit')throw Error('Future-turn work must be accepted by a new turn action');
 else if(op.kind==='monk-continuation'){if(ctx.state.monkDuelActive){const monks=ctx.state.match.units.filter(u=>u.type==='monk'&&!u.abilities.some(a=>a.kind==='monk'&&a.spent)&&u.cells.some(c=>!seat(ctx.state,u.ownerId).shots.includes(cellKey(c))));const target=monks.find(u=>u.ownerId===op.meta.targetPlayerId);if((ctx.state.ring?monks.length>=2:monks.length===2)&&target){const p=seat(ctx.state,target.ownerId);frame.next.push({kind:'monk-deflect',meta:{actorId:target.ownerId,ownerId:target.ownerId,targetPlayerId:p.reactionTarget.playerId,targetBoardId:p.reactionTarget.boardId,sourceUnitId:target.id,source:'monk-deflect',origin:target.cells[0]!}});}}}
 else if(op.kind==='attack')attack(ctx,op.entry);
 else if(op.kind==='wave')pushFrame(ctx,'wave',waveOperations(op.entries),op.terminalCheck);
 else if(op.kind==='hero-queue')heroes(ctx,options.deferLocalHeroPolicy);
 else if(op.kind==='same-turn-effects')effects(ctx,options.deferTerminal);
 else if(op.kind==='terminal-check'){const suppressed=op.reason==='chain-end'&&ctx.state.plagues.some(p=>p.targetPlayerId===ruleTurn(ctx));if(!suppressed&&!options.deferTerminal)checkTerminal(ctx,op.reason);}
 else throw Error('Unknown operation');
}
export function runResolution(ctx:ResolutionContext,maxSteps=100000):ResolutionContext {let steps=0;while(ctx.status==='running'){if(steps++>=maxSteps)throw Error('Resolution safety bound exceeded');stepResolution(ctx);}return ctx;}
