import {assertMatchState} from '../invariants.js';import {stableJson} from '../serialization.js';import type {ResolutionContext,SourceMetadata,Operation,CombatState} from './contracts.js';
function ensure(ok:unknown,message:string):asserts ok {if(!ok)throw Error(message);}
function plain(v:unknown,seen=new Set<object>()):void {if(v===null||typeof v==='boolean')return;if(typeof v==='string'){ensure(!/<\/?[a-z][^>]*>/i.test(v),'HTML is not rule state');return;}if(typeof v==='number'){ensure(Number.isFinite(v),'Nonfinite rule state');return;}ensure(v&&typeof v==='object','Non-JSON rule state');ensure(!seen.has(v),'Cyclic rule state');seen.add(v);ensure(Object.getOwnPropertySymbols(v).length===0,'Symbol rule state');const descriptors=Object.getOwnPropertyDescriptors(v);for(const [k,d]of Object.entries(descriptors)){ensure(!d.get&&!d.set,'Accessor rule state');if(k!=='length'||!Array.isArray(v))ensure(d.enumerable,'Hidden rule state');}if(Array.isArray(v)){for(let i=0;i<v.length;i++){ensure(i in v,'Sparse rule array');plain(v[i],seen);}}else{ensure(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null,'Nonplain rule state');for(const value of Object.values(v))plain(value,seen);}seen.delete(v);}
function exact(v:object,keys:string[]){ensure(Object.keys(v).sort().join('|')===[...keys].sort().join('|'),'Unknown or missing fields');}
const integer=(n:number)=>Number.isSafeInteger(n)&&n>=0;
export function assertResolution(value:unknown):asserts value is ResolutionContext {
 plain(value);ensure(value&&typeof value==='object','Expected resolution');const ctx=value as ResolutionContext;
 exact(ctx,['contract','scope','id','acceptedActionId','activePlayerId','compatibility','status','state','rng','frames','future','decisions','events','generated','nextWork','nextDecision','completedAtEvent','externalEntropy']);
 ensure(['accepted-action','boundary-comparison'].includes(ctx.scope),'Unknown resolution scope');ensure(ctx.contract==='stone-throw-resolution-v1'&&ctx.compatibility==='golden-v1.427','Unknown rules contract');ensure(['running','awaiting-decision','complete'].includes(ctx.status),'Invalid resolution status');ensure(/^[A-Za-z][A-Za-z0-9_-]{0,47}$/.test(ctx.id),'Invalid root ID');ensure(typeof ctx.acceptedActionId==='string'&&ctx.acceptedActionId.length>0,'Missing action ID');
 exact(ctx.state,['match','seats','heroQueue','plagues','monkDuelActive','monkDuelHasHappened','storyMode','storyPlagueTargets',...(ctx.state.ring?['ring']:[])]);if(ctx.state.ring){exact(ctx.state.ring,['order','eliminated','knowledge']);for(const [key,value]of Object.entries(ctx.state.ring.knowledge)){ensure(typeof key==='string','Invalid ring knowledge key');exact(value,['scouted','monkCandidates']);for(const list of [value.scouted,value.monkCandidates])ensure(Array.isArray(list)&&list.every(k=>typeof k==='string'&&/^\d+,\d+$/.test(k)),'Invalid ring knowledge cells');};const all=ctx.state.match.players.map(p=>p.id),ids=[...ctx.state.ring.order,...ctx.state.ring.eliminated];ensure(ids.length===all.length&&new Set(ids).size===all.length&&ids.every(p=>all.includes(p)),'Invalid ring membership');}assertMatchState(ctx.state.match);const state=ctx.state;
 const players=new Set(state.match.players.map(p=>p.id)),boards=new Map(state.match.boards.map(b=>[b.id,b])),units=new Set(state.match.units.map(u=>u.id));ensure(players.has(ctx.activePlayerId),'Unknown active player');ensure(state.seats.length===players.size&&new Set(state.seats.map(p=>p.playerId)).size===players.size,'Seat identity mismatch');
 for(const p of state.seats){exact(p,['playerId','boardId','reactionTarget','decisionMode','sameTurnBonusTarget','releasePriority','releaseRevivesPendingFirst','occupied','shots','scouted','monkCandidates','nextShots','ordinaryShots','currentChainBonus','dwarfNow','catapultNow','catapultLater','elfNow','spyLater','clericNow','clericLater','releaseNow','resurrection','plagueExcluded']);ensure(players.has(p.playerId)&&boards.get(p.boardId)?.ownerId===p.playerId,'Seat ownership mismatch');ensure(players.has(p.reactionTarget.playerId)&&boards.get(p.reactionTarget.boardId)?.ownerId===p.reactionTarget.playerId,'Reaction target mismatch');ensure(['interactive','policy'].includes(p.decisionMode)&&['ordinary','chain'].includes(p.sameTurnBonusTarget),'Unknown compatibility profile');for(const list of [p.occupied,p.shots,p.scouted,p.monkCandidates,p.plagueExcluded]){ensure(Array.isArray(list)&&new Set(list).size===list.length,'Duplicate compatibility cells');for(const k of list){ensure(typeof k==='string'&&/^\d+,\d+$/.test(k),'Invalid cell key');const [x,y]=k.split(',').map(Number),b=boards.get(p.boardId)!;ensure(x!<b.width&&y!<b.height,'Cell outside board');}}}
 const meta=(m:SourceMetadata)=>{exact(m,['actorId','ownerId','targetPlayerId','targetBoardId','sourceUnitId','source','origin']);ensure(players.has(m.actorId)&&players.has(m.ownerId)&&players.has(m.targetPlayerId),'Unknown rule actor');ensure(boards.get(m.targetBoardId)?.ownerId===m.targetPlayerId,'Target board mismatch');ensure(m.sourceUnitId===null||units.has(m.sourceUnitId),'Unknown rule source unit');ensure(['direct-human','direct-ai','chain','archer','monk-deflect','catapult-shot','goblin','dragon','demon-blast','wizard','plague'].includes(m.source),'Unknown rule source');};
 const op=(o:Operation)=>{ensure(o&&typeof o==='object','Invalid operation');const fields:Record<Operation['kind'],string[]>={impact:['meta','cell','deferReactions'],attack:['entry'],'flush-reactions':[],'monk-continuation':['meta'],'scheduled-benefit':['ownerId','benefit','amount','meta','accounting'],'direct-shot':['meta','cell'],'host-direct-shot':['meta','cell'],'turn-resurrection':['ownerId'],'turn-scout':['ownerId','count'],'direct-after':['meta','cell'],'direct-finish':['meta'],wave:['entries','terminalCheck'],'hero-queue':[],'same-turn-effects':[],catapult:['meta','cell','impact','generated'],'catapult-resume':['meta','impact','generated','decisionId'],'catapult-series':['ownerId','remaining'],'plague-step':['targetBoardId','plagueId'],'plague-progress':['targetBoardId','plagueId','outbreakIndex','parentIndex','childIndex','wanted','oldFrontier','nextFrontier','reserved','stage'],'terminal-check':['reason']};ensure(Object.hasOwn(fields,o.kind),'Unknown operation kind');exact(o,['kind',...fields[o.kind].filter(k=>k!=='plagueId'||'plagueId'in o)]);if('plagueId'in o)ensure(typeof o.plagueId==='string'&&o.plagueId.length>0,'Invalid outbreak identity');if('meta'in o)meta(o.meta);if(o.kind==='attack')meta(o.entry.meta);if('entries'in o)for(const e of o.entries)meta(e.meta);};
 const ids=new Set<string>();for(const frame of ctx.frames){ensure(players.has(frame.compatibilityTurnId),'Invalid compatibility turn');if(frame.detachedPlague){ensure(frame.kind==='plague'&&players.has(frame.detachedPlague.triggerPlayerId)&&boards.has(frame.detachedPlague.targetBoardId),'Invalid detached Plague');exact(frame.detachedPlague,['triggerPlayerId','ownerId','targetPlayerId','targetBoardId','moveOnPlayerId','origin','outbreaks','announced']);}exact(frame,['detachedPlague','compatibilityTurnId','id','kind','current','next','deferred','cursor','terminalCheck','stage']);ensure(!ids.has(frame.id),'Duplicate frame ID');ids.add(frame.id);ensure(integer(frame.cursor)&&frame.cursor<=frame.current.length,'Invalid continuation cursor');for(const w of frame.current){exact(w,['id','rootId','parentId','timing','operation']);ensure(w.rootId===ctx.id&&!ids.has(w.id),'Invalid work identity');ids.add(w.id);ensure(['immediate-interrupt','attack-remainder','after-attack','next-wave','same-turn','turn-boundary','future-turn'].includes(w.timing),'Unknown timing');op(w.operation);}for(const d of frame.deferred){ensure(units.has(d.unitId),'Unknown deferred unit');meta(d.meta);}}
 for(const w of ctx.future){exact(w,['id','rootId','parentId','timing','operation']);ensure(w.rootId===ctx.id&&!ids.has(w.id)&&w.timing==='future-turn','Invalid future work');ids.add(w.id);op(w.operation);ensure(w.operation.kind==='scheduled-benefit'&&w.operation.accounting==='already-applied-to-compatibility-counters','Invalid future accounting');}
 for(const e of ctx.generated)meta(e.meta);
 ensure(integer(ctx.nextWork)&&integer(ctx.nextDecision),'Invalid identity counters');ensure(ctx.rng.algorithm==='lcg32-with-tape'&&integer(ctx.rng.cursor)&&ctx.rng.cursor===ctx.rng.draws.length,'Invalid RNG state');ensure(integer(ctx.rng.state)&&ctx.rng.state<=0xffffffff,'Invalid RNG word');for(const n of ctx.rng.tape)ensure(n>=0&&n<1,'Invalid RNG tape');ctx.rng.draws.forEach((d,i)=>ensure(d.ordinal===i&&d.value>=0&&d.value<1,'Invalid RNG journal'));
 let rngWord=ctx.rng.seed;ensure(integer(rngWord)&&rngWord<=0xffffffff,'Invalid RNG seed');for(let i=0;i<ctx.rng.cursor;i++){rngWord=(Math.imul(1664525,rngWord)+1013904223)>>>0;const expected=i<ctx.rng.tape.length?ctx.rng.tape[i]:rngWord/4294967296;ensure(ctx.rng.draws[i]!.value===expected,'RNG replay mismatch');}ensure(rngWord===ctx.rng.state,'RNG state mismatch');
 const decisionIds=new Set<string>();for(const d of ctx.decisions){exact(d,['id','rootId','workId','actorId','boardId','unitId','kind','legalCells','legalUnitIds','remaining','status','answer']);ensure(['hero-relocation','resurrection','catapult-target','catapult-roll','scout','policy-target'].includes(d.kind),'Unknown decision kind');for(const c of d.legalCells){exact(c,['x','y']);const b=boards.get(d.boardId);ensure(b&&integer(c.x)&&integer(c.y)&&c.x<b.width&&c.y<b.height,'Illegal decision geometry');}ensure(d.rootId===ctx.id&&players.has(d.actorId)&&boards.has(d.boardId),'Invalid decision scope');ensure(!decisionIds.has(d.id),'Duplicate decision');decisionIds.add(d.id);ensure(d.status==='pending'||d.status==='answered'||d.status==='cancelled','Invalid decision status');ensure(d.unitId===null||units.has(d.unitId),'Unknown decision unit');for(const u of d.legalUnitIds)ensure(units.has(u),'Unknown legal unit');}
 ensure(ctx.decisions.filter(d=>d.status==='pending').length===(ctx.status==='awaiting-decision'?1:0),'Pending decision/status mismatch');ctx.events.forEach((e,i)=>{exact(e,['sequence','rootId','workId','kind','meta','unitId','cells','amount','reason',...(e.statistics?['statistics']:[])]);ensure(e.sequence===i+1&&e.rootId===ctx.id,'Invalid event sequence');if(e.meta)meta(e.meta);});const completed=ctx.events.filter(e=>e.kind==='resolution-completed');ensure(completed.length===(ctx.status==='complete'?1:0),'Invalid completion boundary');ensure(ctx.status==='complete'?ctx.completedAtEvent===completed[0]?.sequence&&ctx.frames.length===0:ctx.completedAtEvent===null,'Invalid completion marker');
}
export function serializeResolution(ctx:ResolutionContext):string {assertResolution(ctx);return stableJson(ctx);}
export function deserializeResolution(text:string):ResolutionContext {ensure(text.length<=32*1024*1024,'Resolution too large');const value:unknown=JSON.parse(text);assertResolution(value);return value;}
