export function installLan(session,browserClient,opened){
 let meta=opened?.update?.lan,revision=opened?.update?.snapshot.revision,battle=opened?.update?.snapshot.battle,busy=false;
 const bar=document.createElement('aside');bar.id='stLanStatus';bar.style.cssText='position:fixed;top:0;left:0;right:0;z-index:100000;background:#171717;color:white;padding:6px;font:13px sans-serif';document.body.append(bar);
 const panel=document.createElement('div');panel.id='stLanLobby';panel.style.cssText='display:none;position:fixed;inset:15% 20%;z-index:100002;background:#171717;color:white;padding:24px;border:1px solid #ab9';panel.innerHTML='<h2>LAN 1v1</h2><label>Display name <input id="stLanName" maxlength="24"></label><label> Game code <input id="stLanCode" maxlength="6"></label><p><button id="stLanMake">Make Game</button> <button id="stLanJoin">Join Game</button> <button id="stLanClose">Close</button></p><p id="stLanMessage" role="status"></p>';document.body.append(panel);
 const action=async(kind)=>{try{await session.request('pvp/'+kind,{name:document.getElementById('stLanName').value,code:document.getElementById('stLanCode').value});location.reload();}catch(e){document.getElementById('stLanMessage').textContent=e.code||e.message;}};
 document.getElementById('stLanMake').onclick=()=>action('make');document.getElementById('stLanJoin').onclick=()=>action('join');document.getElementById('stLanClose').onclick=()=>panel.style.display='none';
 document.addEventListener('click',e=>{if(meta&&e.target.closest('#playAgainBtn')){e.preventDefault();e.stopImmediatePropagation();document.getElementById('stLanRematch')?.click();return;}if(e.target.closest('#stMenuOnline')){e.preventDefault();e.stopImmediatePropagation();panel.style.display='block';}},true);
 function observe(update){if(!update.lan)return;document.documentElement.dataset.lanRevision=String(update.snapshot.revision);meta=update.lan;revision=update.snapshot.revision;battle=update.snapshot.battle;const s=update.snapshot,other=1-meta.self;bar.replaceChildren();const label=document.createElement('span');label.textContent=`Game ${meta.code} · ${meta.names[meta.self]} vs ${meta.names[other]||'waiting for player'} · `+(meta.closed?'Game closed':s.phase==='placement'?(meta.ready[meta.self]?'Ready — waiting':'Place your army, then Ready'):s.phase==='finished'?s.outcome:s.choice?'Your decision':meta.waiting?'Waiting for opponent decision':s.active==='self'?'Your turn':'Opponent’s turn')+(!meta.connected[other]?' · opponent disconnected/waiting':'');if(update.error==='stale')label.textContent+=' · State updated; please retry your action.';bar.append(label);
  const leave=document.createElement('button');leave.textContent='Leave';leave.id='stLanLeave';leave.onclick=async()=>{await session.request('pvp/leave');location.reload();};bar.append(leave);if(s.phase==='finished'){const rematch=document.createElement('button');rematch.id='stLanRematch';rematch.textContent=meta.rematch[meta.self]?'Rematch requested':'Rematch';rematch.disabled=meta.rematch[meta.self]||meta.closed;rematch.onclick=async()=>browserClient.apply(await session.request('pvp/rematch'));bar.append(rematch);const play=document.getElementById('playAgainBtn');play.textContent='REMATCH';play.onclick=e=>{e.stopImmediatePropagation();rematch.click();};}
  if(s.phase==='placement'){const start=document.getElementById('startBtn');start.disabled=meta.ready[meta.self]||start.disabled;const visible=document.getElementById('stStart');if(visible)visible.textContent=meta.ready[meta.self]?'WAITING':'READY';}
 }
 if(meta)observe(opened.update);else{bar.style.display='none';}
 // Poll only public state; no private checkpoint ever enters this adapter.
 const timer=setInterval(async()=>{if(!meta||busy||window.__stoneThrowViewState?.().inputLocked)return;busy=true;try{const update=await session.client.read();if(update.snapshot.revision!==revision||update.snapshot.battle!==battle)await browserClient.apply(update);else observe(update);}catch(e){bar.textContent='LAN connection: '+(e.code||'unavailable')+' — reload to reconnect';}finally{busy=false;}},700);
 window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
 return {observe,blocked:()=>!!meta&&(meta.closed||meta.waiting||meta.ready[meta.self]&&window.__stoneThrowViewState?.().phase==='ready')};
}
