import {AVATARS,DEFAULT_AVATAR,avatarById} from '../assets/avatars/catalog.mjs';
const css=document.createElement('link');css.rel='stylesheet';css.href='/styles-avatars.css';document.head.append(css);
const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
export function avatarControl({value=DEFAULT_AVATAR,unlocked=false,onSelect}){
 const trigger=el('button');trigger.type='button';trigger.className='cs-avatar-current';trigger.setAttribute('aria-label','Choose avatar');
 function paint(){const a=avatarById(value)||avatarById(DEFAULT_AVATAR),image=el('img');image.src='/'+a.assetPath;image.alt=a.group+' '+a.id.split('-').at(-1);trigger.replaceChildren(image,el('span','Choose avatar'));trigger.dataset.avatarId=a.id;}paint();
 trigger.onclick=()=>{const dialog=el('dialog');dialog.className='cs-avatar-dialog';dialog.setAttribute('aria-label','Avatar Picker');const status=el('p');status.setAttribute('role','status');let busy=false,closed=false;const close=()=>{closed=true;dialog.close();dialog.remove();trigger.focus();};const done=el('button','CLOSE');done.type='button';done.onclick=close;dialog.append(el('h2','Avatar Picker'),done,status);
 let category,race,group,grid;for(const a of AVATARS.filter(a=>['peasant','hero'].includes(a.access))){if(a.access!==category){category=a.access;if(category==='hero'&&!unlocked)dialog.append(el('p','Only available after finishing Story Mode or winning 5 games.'));dialog.append(el('h2',category==='peasant'?'PEASANTS':'HEROS'));race=null;}if(category==='hero'&&race!==a.race){race=a.race;dialog.append(el('h3',{human:'Human',dwarf:'Dwarf',elf:'Elf'}[race]));}if(group!==a.group){group=a.group;dialog.append(el('h4',group));grid=el('div');grid.className='cs-avatar-grid';dialog.append(grid);}const b=el('button');b.type='button';b.className='cs-avatar-tile';b.dataset.avatarId=a.id;b.setAttribute('aria-label',a.group+' '+a.id.split('-').at(-1));b.setAttribute('aria-pressed',String(a.id===value));b.disabled=a.access==='hero'&&!unlocked;const img=el('img');img.src='/'+a.assetPath;img.alt='';img.loading='lazy';b.append(img);grid.append(b);b.onclick=async()=>{if(busy||closed)return;busy=true;done.disabled=true;status.textContent='Saving…';try{await onSelect(a.id);value=a.id;paint();close();}catch(e){status.textContent=e.message;}finally{busy=false;done.disabled=false;}};}
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(!busy)close();});document.body.append(dialog);dialog.showModal();};return trigger;
}
