// Observer-only adapter of v1.427 Event Log wording/grouping. No gameplay state.
const names={inf:'Infantry',cav:'Cavalry',archer:'Archer',castle:'Castle',monk:'Monk',hero:'Hero',dwarf:'Dwarf',catapult:'Catapult',elf:'Elves',goblin:'Goblins',cleric:'Cleric',necro:'Necromancer',wizard:'Wizard',demon:'Demon',dragon:'Dragon'};
const same=(a,b)=>a.x===b.x&&a.y===b.y;
export function damageSummary(hits){if(!hits?.length)return '';const order=[],counts=new Map();for(const h of hits){if(!counts.has(h))order.push(h);counts.set(h,(counts.get(h)||0)+1);}const plural=(h,n)=>{if(n===1)return h;if(h==='Infantry')return `${n} Infantry units`;if(h==='Cavalry')return `${n} Cavalry units`;if(h==='Castle')return `${n} Castle cells`;if(h==='Elves')return `${n} Elves`;if(h==='unidentified core unit')return `${n} unidentified core units`;if(h==='Hero')return `${n} Heroes`;return `${n} ${h}s`;};return order.map(h=>plural(h,counts.get(h))).join(', ');}
const naturalList=a=>a.length<2?(a[0]||''):a.length===2?a.join(' and '):a.slice(0,-1).join(', ')+' and '+a.at(-1);
export function mountBattleLog(memory){
 let attack=null;const state=()=>memory.log??={round:null,last:null,opening:[],starter:null,openingDone:false};
 function add(text,major=false,merge=null){if(!text)return;const l=state(),round=Math.max(1,l.snapshot.round||1);if(l.round!==round){memory.rows.push({text:`ROUND ${round}`,round:true});l.round=round;}const last=memory.rows.at(-1);if(merge&&last.merge===merge){last.count=(last.count||1)+1;const [side,type]=merge.split(':'),n=({2:'two',3:'three',4:'four',5:'five'})[last.count]||String(last.count),plural=type==='inf'?'Infantry units':'Archers';last.text=side==='self'?`The enemy destroys ${n} of your ${plural}.`:`You destroy ${n} enemy ${plural}.`;return;}memory.rows.push({text,major,...(merge?{merge,count:1}:{})});}
 function observed(s,e){if(e.cell&&s.heroPresentation?.some(m=>m.side===e.side&&same(m.cell,e.cell)&&['hit','wounded','dead'].includes(m.state)))return {kind:'hero'};return e.side==='self'?s.owned.find(u=>u.cells.some(c=>same(c,e.cell))):s.opponent.find(c=>same(c.cell,e.cell));}
 function label(s,e){return names[observed(s,e)?.kind]||'unidentified core unit';}
 function finalize(){const l=state();if(l.openingDone||!l.starter)return;l.openingDone=true;const own=l.starter==='self',hits=l.opening.filter(h=>h.side!==(own?'self':'opponent')),n=l.opening.length;let text;if(!n)text=own?'You start the battle without hitting anything.':'The enemy starts the battle without hitting anything.';else if(n===1){const list=naturalList(hits.map(h=>h.label)),danger=hits.some(h=>['necro','demon','dragon'].includes(h.kind));text=own?(danger?`You start the battle rather badly by hitting ${list}.`:`You start strong by hitting ${list}.`):(danger?`The enemy starts the battle rather badly by hitting ${list}.`:`The enemy starts strong by hitting ${list}.`);}else if(n<=3)text=own?`You start the battle with a busy opening. ${n} units are caught in the fighting.`:`The enemy starts the battle with a busy opening. ${n} units are caught in the fighting.`;else if(n<=6)text=own?`Your opening turn becomes a bloodbath. ${n} units are caught in the fighting.`:`The enemy opening turn becomes a bloodbath. ${n} units are caught in the fighting.`;else text=own?`The battle erupts into a massacre during your opening turn. ${n} units are caught in the chaos.`:`The battle erupts into a massacre during the enemy opening turn. ${n} units are caught in the chaos.`;memory.rows[0].text=text;}
 function consume(update){const s=update.snapshot,l=state();l.snapshot=s;if(s.phase==='placement')return;l.starter??=s.active;if(!l.openingDone&&(s.active!==l.starter||s.round>1||s.phase==='finished'))finalize();for(const e of update.events){if(e.kind!=='impact'||!e.cell)continue;const o=observed(s,e),type=o?.kind,hitLabel=label(s,e);if(!l.openingDone){const id=e.side+':'+(o?.handle||(['hero','monk','dwarf','elf','goblin','cleric','wizard','demon','dragon'].includes(type)?type:e.cell.x+','+e.cell.y));if(!l.opening.some(h=>h.id===id))l.opening.push({id,side:e.side,kind:type,label:hitLabel});}if(attack){attack.hits.push(hitLabel);continue;}const own=e.side==='self',last=(s.strips?.[e.side]?.[type]?.destroyed||0)>=(s.rosters[e.side]?.[type]||Infinity);if(!type){add('You hit an unidentified enemy core unit.');continue;}
 if(type==='inf'||type==='archer'){const name=names[type],phrase=type==='inf'?(last?'your last Infantry unit':'one of your Infantry units'):(last?'your last Archer':'one of your Archers');add(own?`The enemy destroys ${phrase}.`:`You destroy ${last?'the last enemy':'an enemy'} ${name}.`,false,e.side+':'+type);}
 else if(type==='hero'){const n=s.strips?.[e.side]?.hero?.heroHits||1;add(own?(n===1?'Your Hero has been hit!':n===2?'Your Hero has been hit again!':'Your Hero is struck for the third and final time!'):(n===1?'The enemy Hero has been hit!':n===2?'The enemy Hero has been hit again!':'The enemy Hero is struck for the third and final time!'),true);}
 else if(type==='cav'){const dead=o?.destroyed||o?.knownDestroyed;add(dead?(own?`The enemy destroys ${last?'your last Cavalry unit':'one of your Cavalry units'}.`:`You destroy ${last?'the last enemy':'an enemy'} Cavalry.`):(own?'The enemy hits your Cavalry.':'You hit an unidentified enemy core unit.'));}
 else if(type==='castle'){const dead=o?.destroyed||o?.knownDestroyed;const tag=e.side+':castle:'+s.round;if(dead)add(own?`The enemy destroys ${last?'your last Castle':'one of your Castles'}.`:'You finally destroy the enemy Castle.');else if(l.castle!==tag){add(own?'The enemy damages your Castle.':'You reveal part of an enemy Castle.');l.castle=tag;}}
 else if(type==='monk'||type==='cleric')add(own?`The enemy destroys your ${names[type]}.`:`You destroy the enemy ${names[type]}.`);
 else if(type==='necro')add(own?`The enemy destroys ${last?'your last Necromancer':'one of your Necromancers'}.${last?'':' They prepare the Plague.'}`:`You destroy ${last?'the last enemy':'an enemy'} Necromancer.${last?'':' They prepare the Plague.'}`);
 else add(own?`The enemy hits your ${names[type]}.`:`You hit the enemy ${names[type]}.`);
 }}
 function begin(frames,coverage=null,allFrames=frames){const c=frames[0]?.animation;if(!c||c.kind==='enemy-shot')return;state().snapshot=frames[0].snapshot;const full=c.kind==='goblin'?allFrames.filter(f=>f.animation?.kind==='goblin'&&f.animation.group===c.group):frames,gkey=frames[0].snapshot.battle+':'+frames[0].snapshot.revision+':'+c.group;const groups=state().goblins??={};if(c.kind==='goblin'&&groups[gkey]){attack=groups[gkey];attack.final=frames.at(-1).snapshot.eventPosition===full.at(-1).snapshot.eventPosition;return;}attack={kind:c.kind,own:c.ownerSide==='self',count:full.length,hits:[],coverage,gkey,final:frames.at(-1).snapshot.eventPosition===full.at(-1).snapshot.eventPosition,castleStop:frames.length>1&&(()=>{const f=frames.at(-1),cell=f.animation.cell;return c.side==='self'?f.snapshot.owned.some(u=>u.kind==='castle'&&u.cells.some(p=>same(p,cell))):f.snapshot.opponent.some(p=>p.kind==='castle'&&same(p.cell,cell));})()};if(c.kind==='goblin')groups[gkey]=attack;const a=attack;const flavor={catapult:a.own?'You launch a Catapult stone!':'The enemy launches a Catapult stone!',goblin:`${a.own?'Your Goblins':'The enemy Goblins'} unleashes ${a.count} bombs across ${a.own?'the enemy lands':'your lands'}!`,demon:`${a.own?'The Demon invokes a terrible ritual across the enemy lands!':'The enemy Demon invokes a terrible ritual across your lands!'} Ancient runes ignite as the spell reaches its terrible conclusion!`,dragon:a.own?'The enraged Dragon takes to the skies, scorching the enemy lands with fire!':'The enemy Dragon takes to the skies, scorching your lands with fire!',wizard:a.own?'The Wizard summons a mighty meteor and hurls it into the enemy lands!':'The enemy Wizard summons a mighty meteor and hurls it into your lands!'}[a.kind];if(flavor)add(flavor,true);}
 function end(){if(!attack)return;const a=attack;attack=null;if(a.kind==='goblin'){if(!a.final)return;delete state().goblins[a.gkey];}const verb={demon:'The Demon devastates',dragon:'The Dragon scorches',wizard:'The meteor devastates'}[a.kind];if(verb&&a.coverage!==null)add(`${verb} ${a.count} of ${a.coverage} possible cells.`);if(a.kind==='catapult')add(`The stone rolls through ${a.count} ${a.count===1?'cell':'cells'} before coming to a stop${a.castleStop?` when it hits ${a.own?'an enemy Castle wall':'your Castle wall'}`:''}.`,a.castleStop);if(a.kind==='archer')add(`${a.own?'Your Archer':'The enemy Archer'} fires ${a.count} ${a.count===1?'arrow':'arrows'}${a.hits.length?'.':' but hits nothing.'}`,!!a.hits.length);if(a.kind==='goblin'&&!a.hits.length)add(`${a.own?'Your Goblins':'The enemy Goblins'} hits nothing.`);if(a.hits.length)add(`Damage: ${damageSummary(a.hits)} hit.`);}
 return {consume,begin,end};
}
