import {lastGameLogSnapshot} from './game-log.js';
const css=document.createElement('link');css.rel='stylesheet';css.href='/styles-feedback.css';document.head.append(css);
const dialog=document.createElement('dialog');dialog.id='csFeedback';dialog.setAttribute('aria-labelledby','csFeedbackTitle');document.body.append(dialog);dialog.addEventListener('click',e=>e.stopPropagation());
const el=(tag,text,attrs={})=>{const n=document.createElement(tag);n.textContent=text||'';Object.assign(n,attrs);return n;};
const button=(text,fn)=>{const b=el('button',text,{type:'button'});b.onclick=fn;return b;};
function base(title){dialog.replaceChildren(el('p','CHAIN SIEGE',{className:'cf-kicker'}),el('h2',title,{id:'csFeedbackTitle'}));if(!dialog.open)dialog.showModal();}
export function openFeedback(){base('FEEDBACK');const choices=el('div','',{className:'cf-choices'});choices.append(button('REPORT A BUG',()=>form('BUG')),button('SHARE AN IDEA',()=>form('IDEA')));dialog.append(el('p','Help shape the next battle.'),choices,button('BACK',()=>dialog.close()));}
function form(type){base(type==='BUG'?'REPORT A BUG':'SHARE AN IDEA');let image=null,gameLog=null,busy=false,loading=0;
 const guidance=type==='BUG'?['Please describe what happened as clearly as possible.','Tell us step by step what you were doing, what happened, and what you expected to happen instead.','If you have a screenshot, you can attach it below.','If the problem happened during a battle, press ATTACH LAST GAME LOG. Your most recent game log will be included with this report and may help us find the problem.']:['Got an idea for CHAIN SIEGE?','Tell us what you would like to see, change or improve.'];const help=el('div','',{className:'cf-guidance'});for(const text of guidance)help.append(el('p',text));dialog.append(help);
 const f=el('form'),label=el('label',type==='BUG'?'What happened?':'Your idea'),description=el('textarea','',{name:'description',required:true,maxLength:8000,rows:6});label.append(description);f.append(label);
 const attachments=el('div','',{className:'cf-attachments'}),file=el('input','',{type:'file',accept:'.png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp'});file.hidden=true;const imageState=el('p','PNG, JPG or WEBP · Maximum 3 MB',{className:'cf-note'}),logState=el('p','',{className:'cf-note'}),status=el('p','',{className:'cf-status'});status.setAttribute('role','status');imageState.setAttribute('aria-live','polite');logState.setAttribute('aria-live','polite');
 const attach=button('ATTACH SCREENSHOT',()=>file.click());file.onchange=async()=>{const selected=file.files[0];if(!selected)return;image=null;if(!['image/png','image/jpeg','image/webp'].includes(selected.type)||selected.size>3*1024*1024){imageState.textContent='Use PNG, JPG or WEBP, up to 3 MB.';file.value='';return;}attach.disabled=true;loading++;send.disabled=true;try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(selected);});image={mime:selected.type,data};imageState.textContent='Screenshot attached: '+selected.name;}catch{imageState.textContent='Unable to read screenshot. Try again.';}finally{attach.disabled=false;loading--;send.disabled=busy||loading>0;}};
 attachments.append(attach,file,imageState);if(type==='BUG'){const log=button('ATTACH LAST GAME LOG',async()=>{gameLog=null;log.disabled=true;loading++;send.disabled=true;try{const snapshot=await lastGameLogSnapshot();if(!snapshot){logState.textContent='No recorded game log available. Enable Game Log in Options to record future battles.';return;}if(new TextEncoder().encode(snapshot.text).length>8*1024*1024){logState.textContent='This log exceeds the 8 MB report limit. Your Game Log history remains available.';return;}gameLog=snapshot.text;logState.textContent='Game log snapshot attached: '+snapshot.label;}catch{logState.textContent='Unable to read the game log. You can still send your report.';}finally{log.disabled=false;loading--;send.disabled=busy||loading>0;}});attachments.append(log,logState);}f.append(attachments,status);
 const actions=el('div','',{className:'cf-actions'}),send=el('button',type==='BUG'?'SEND REPORT':'SEND IDEA',{type:'submit'}),cancel=button('CANCEL / BACK',openFeedback);actions.append(send,cancel);f.append(actions);dialog.append(f);
 f.onsubmit=async e=>{e.preventDefault();if(busy||loading)return;if(!description.value.trim()){status.textContent='Please enter a description.';description.focus();return;}busy=true;send.disabled=cancel.disabled=attach.disabled=true;description.readOnly=true;status.textContent='Sending…';try{const response=await fetch('/api/registry/feedback-submit',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,description:description.value,screen:'Options',...(image?{screenshot:image}:{}),...(gameLog?{gameLog}:{})})});const result=await response.json();if(!response.ok){status.textContent=response.status===429?'Please wait before sending more feedback.':response.status===400?result.error:'Unable to send feedback right now. Your text is still here; please try again.';return;}base(type==='BUG'?'BUG REPORT SENT':'IDEA SENT');dialog.append(el('p','Thank you.'),button('OK',()=>dialog.close()));}catch{status.textContent='Unable to send feedback. Please check your connection and try again.';}finally{busy=false;send.disabled=cancel.disabled=attach.disabled=false;description.readOnly=false;}};
 dialog.oncancel=e=>{if(busy)e.preventDefault();};description.focus();
}
const control=document.getElementById('stBugReport');if(control){control.removeAttribute('href');control.textContent='FEEDBACK';control.onclick=e=>{e.preventDefault();e.stopPropagation();openFeedback();};}
