// Optional Game Log. Collect only explicitly selected public fields and numeric timings.
let enabled=false,match=null,seat=null,phase=null,serial=0,action=0,requestSerial=0,context={},lastState='',publicSequence=0,lastInput=null,activeAction=null;
const preferenceKey='stoneThrow.gameLog.enabled.v1';
try{enabled=localStorage.getItem(preferenceKey)==='1';}catch{}
export function gameLogEnabled(){return enabled;}
function syncSetting(){const b=document.getElementById('stGameLogSetting');if(b){b.textContent=enabled?'ON':'OFF';b.classList.toggle('on',enabled);b.setAttribute('aria-pressed',String(enabled));}syncLog();}
function setEnabled(value){enabled=!!value;try{localStorage.setItem(preferenceKey,enabled?'1':'0');}catch{}if(!enabled){pending.length=0;activeAction=null;if(panel){panel.hidden=true;panel.style.display='none';}}syncSetting();}
function installSetting(){const settings=document.getElementById('stSettings');if(!settings||document.getElementById('stGameLogSetting'))return;const row=document.createElement('div');row.className='st-setting-row st-toggle-row';const label=document.createElement('span');label.textContent='Game Log';const button=document.createElement('button');button.id='stGameLogSetting';button.type='button';button.className='st-toggle';button.setAttribute('aria-label','Game Log');button.onclick=()=>setEnabled(!enabled);row.append(label,button);settings.querySelector('.st-settings-title')?.after(row);syncSetting();}
const page=Date.now().toString(36)+'-'+Math.floor(performance.now()*1000),start=performance.now(),rows=[],pending=[],samples=new Map();let dbPromise=null,flushing=null,panel=null,pre=null,button=null,dropped=0,storageFailure=false;
function database(){return dbPromise??=new Promise(resolve=>{try{const r=indexedDB.open('StoneThrow-temporary-beta-log',1);r.onupgradeneeded=()=>{const s=r.result.createObjectStore('rows',{keyPath:'id'});s.createIndex('match','match');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve(null);}catch{resolve(null);}});}
export function betaEnabled(){return enabled&&!!match;}
export function logEvent(event,data={}){if(!betaEnabled())return;const r={id:page+'-'+(++serial),match,wall:new Date().toISOString(),ms:performance.now()-start,page,event,action:activeAction?.id??action,...data};if(JSON.stringify(r).length>8192){dropped++;return;}rows.push(r);pending.push(r);if(pending.length>22000){pending.splice(0,pending.length-22000);storageFailure=true;}if(rows.length>22000){rows.splice(0,2000);dropped+=2000;}if(pre&&!panel.hidden){pre.append(document.createTextNode(line(r)+'\n'));while(pre.childNodes.length>2000)pre.firstChild.remove();}}
function line(r){return `${r.wall} | +${r.ms.toFixed(1)} ms | ${r.event} | ${JSON.stringify(Object.fromEntries(Object.entries(r).filter(([k])=>!['wall','ms','event','id','match'].includes(k))))}`;}
async function flush(){if(!enabled){pending.length=0;return;}if(flushing)return flushing;if(!pending.length)return;const batch=pending.splice(0);flushing=(async()=>{try{const db=await database();if(!db)return false;return await new Promise(resolve=>{const tx=db.transaction('rows','readwrite');const store=tx.objectStore('rows');for(const r of batch)store.put(r);const count=store.count();count.onsuccess=()=>{let excess=count.result-22000;if(excess<=0)return;const cursor=store.openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(c&&excess-->0){c.delete();c.continue();}};};tx.oncomplete=()=>resolve(true);tx.onerror=tx.onabort=()=>resolve(false);});}catch{return false;}})();const ok=await flushing;flushing=null;if(!ok)storageFailure=true;}
export async function logText(){await flush();if(flushing)await flushing;const db=await database();let saved=[];if(db)saved=await new Promise(resolve=>{const r=db.transaction('rows').objectStore('rows').index('match').getAll(match);r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve([]);});const all=new Map([...saved,...rows.filter(r=>r.match===match)].map(r=>[r.id,r]));return 'STONE THROW — GAME LOG\n'+JSON.stringify({match,seat,context,page,clock:'ISO UTC wall + page-relative performance.now milliseconds; server clocks separate',coverage:'observer-public only; no private host, credentials or RNG; DOM paint records are rAF opportunities, not physical display measurements',memoryRowsEvicted:dropped,storageAvailable:!!db,storageFailure})+'\n\n'+[...all.values()].sort((a,b)=>a.wall.localeCompare(b.wall)||a.ms-b.ms).map(line).join('\n');}
export async function saveLog(){logEvent('SAVE LOG');const text=await logText(),blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='StoneThrow_match_'+String(match).replace(/[^a-z0-9_-]/gi,'_')+'_'+new Date().toISOString().replace(/[:.]/g,'-')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return text;}
async function openLog(){if(!panel){panel=document.createElement('section');panel.id='stBetaGameLogPanel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','GAME LOG');panel.style.cssText='position:fixed;inset:4vh 3vw;z-index:2147483647;background:#15191f;color:#eee;border:2px solid #c6a35d;padding:14px;display:flex;flex-direction:column;gap:10px';const bar=document.createElement('div');for(const [text,fn]of [['SAVE LOG',()=>saveLog()],['CLOSE',()=>{panel.hidden=true;panel.style.display='none';logEvent('GAME LOG CLOSED');button?.focus();}]]){const b=document.createElement('button');b.className='st-btn';b.textContent=text;b.onclick=fn;bar.append(b);}pre=document.createElement('pre');pre.style.cssText='overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;flex:1;font-size:12px;user-select:text';panel.append(bar,pre);document.body.append(panel);}panel.hidden=false;panel.style.display='flex';logEvent('GAME LOG OPENED');pre.replaceChildren(...(await logText()).split('\n').slice(-2000).map(s=>document.createTextNode(s+'\n')));pre.scrollTop=pre.scrollHeight;}
export function syncLog(){const central=document.getElementById('stCenterStart');if(!central)return;if(!button&&enabled){button=document.createElement('button');button.id='stBetaGameLog';button.type='button';button.className=central.className;button.textContent='GAME LOG';button.onclick=openLog;central.before(button);}for(const id of ['resultOverlay','heroConfirmOverlay']){const host=document.querySelector('#'+id+' .result-actions,#'+id+' .hero-confirm-actions');if(host&&enabled&&!host.querySelector('[data-beta-log]')){const b=document.createElement('button');b.type='button';b.dataset.betaLog='1';b.textContent='GAME LOG';b.className='st-btn';b.onclick=openLog;host.append(b);}const b=host?.querySelector('[data-beta-log]');if(b)b.hidden=!enabled||!match||!document.body.classList.contains('st-multiplayer-mode');}if(button)button.hidden=!enabled||!match||!document.body.classList.contains('st-multiplayer-mode')||document.body.classList.contains('st-main-menu-mode');}
export function serverMetrics(value,request){if(!value||!enabled)return;logEvent('SERVER REQUEST METRICS',{request:request?.id,commandAction:request?.action,serverWall:value.wall,startupMetrics:value.startupMetrics,requestMs:value.requestMs,queueMs:value.queueMs,metrics:value.metrics});syncLog();}
export function requestLog(route,body){if(!betaEnabled())return null;const intent=body?.intent;const id=++requestSerial,t=performance.now();if(route==='command')action++;if(route==='command')activeAction={id:action,t};logEvent(route==='command'?'COMMAND REQUEST':'HTTP REQUEST',{request:id,route,kind:intent?.kind,cell:intent?.cell,placementCells:intent?.cells?.length,revision:body?.revision});return{id,t,route,action};}
export function responseLog(req,result){observeLog(result?.update??result);if(req)logEvent('RESPONSE DELIVERED',{request:req.id,route:req.route,durationMs:performance.now()-req.t,accepted:result?.accepted,error:result?.error});}
export function observeLog(u){if(!enabled)return;const s=u?.snapshot,m=u?.lan;if(u?.rejoin)logEvent('REJOIN STATUS',{available:u.rejoin.available,remainingMs:u.rejoin.remainingMs});if(m&&!s)logEvent('HEARTBEAT / CONNECTION',{presence:m.presence?.map(p=>({connected:p.connected,policy:p.policy,remainingMs:p.remainingMs,episode:!!p.episode})),controllers:m.controllers});if(m&&s){const id=m.code+'-'+(m.recoveryBattle||s.groupRoom||m.code+'-'+s.battle)+'-seat-'+m.self;if(match!==id){match=id;seat=m.self;phase=null;lastState='';publicSequence=0;samples.clear();context={mode:m.group?'Group Battle':'Duel',players:m.names.length,names:m.names,controllers:m.controllers};logEvent('MATCH OBSERVED',{...context,room:m.code,round:s.round});}context={mode:m.group?'Group Battle':'Duel',players:m.names.length,names:m.names,controllers:m.controllers};const state={names:m.names,phase:s.phase,round:s.round,revision:s.revision,shots:s.shotsLeft,choice:s.choice?.kind??null,active:s.active,current:m.current,target:m.target,ring:m.ring,eliminated:m.eliminated,complete:m.complete,presence:m.presence?.map(p=>({connected:p.connected,policy:p.policy,remainingMs:p.remainingMs,episode:!!p.episode})),controllers:m.controllers,ready:m.ready};const key=JSON.stringify({...state,presence:state.presence?.map(({remainingMs,...p})=>p)});if(key!==lastState){logEvent('PUBLIC AUTHORITY STATE',state);lastState=key;}if(phase!==s.phase){logEvent(s.phase==='placement'?'PLACEMENT':s.phase==='finished'?'MATCH END / OBSERVER ELIMINATED':phase==='placement'?'MATCH START':'PHASE',{phase:s.phase});phase=s.phase;}
 const group=s.stats?.group,players=group?.players??[m.self,1-m.self].map((seat,j)=>({seat,name:m.names[seat],strength:(s.stats?.strength||[]).map(v=>({round:v.round,value:j?v.enemy:v.player}))}));for(const p of players){const countKey='length:'+p.seat,from=Math.max(0,(samples.get(countKey)||0)-1),history=p.strength||[];samples.set(countKey,history.length);for(let i=from;i<history.length;i++){const v=history[i];const key=p.id+':'+p.seat+':'+i,encoded=JSON.stringify(v);if(samples.get(key)!==encoded){samples.set(key,encoded);logEvent('PUBLIC STRENGTH SAMPLE',{player:p.name,seat:p.seat,index:i,round:v.round,value:v.value,known:Number.isFinite(v.value)});}}}
 logEvent('PUBLIC UPDATE',{frames:u.presentation?.length||0,events:u.events?.length||0,eventPosition:s.eventPosition,graphSamples:group?.players?.reduce((n,p)=>n+(p.strength?.length||0),0)});syncLog();}else if(s&&!s.groupRoom&&document.body.classList.contains('st-main-menu-mode')){match=null;syncLog();}}
export function paintLog(s){if(!betaEnabled())return;for(const e of s.groupLog||[]){if(e.sequence<=publicSequence)continue;if(e.sequence>publicSequence+1)logEvent('PUBLIC HISTORY NOT OBSERVED',{from:publicSequence+1,to:e.sequence-1});publicSequence=e.sequence;logEvent('PUBLIC ORDERED EVENT',{sequence:e.sequence,text:e.text});}const t=performance.now();logEvent('DOM RENDER COMPLETE',{revision:s.revision,eventPosition:s.eventPosition,phase:s.phase,choice:s.choice?.kind,rows:document.getElementById('stEventList')?.children.length});requestAnimationFrame(()=>logEvent('MARKER PAINT OPPORTUNITY',{revision:s.revision,eventPosition:s.eventPosition,afterRenderMs:performance.now()-t}));}
export function dragLog(event,data={}){logEvent(event,data);}
if(typeof document!=='undefined'){
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installSetting,{once:true});else installSetting();
 window.addEventListener('storage',e=>{if(e.key===preferenceKey||e.key===null){let value=false;try{value=localStorage.getItem(preferenceKey)==='1';}catch{}setEnabled(value);}});
 for(const type of ['pointerdown','click','pointerup'])document.addEventListener(type,e=>{if(!betaEnabled()||e.target.closest('#stBetaGameLogPanel'))return;const c=e.target.closest('#playerGrid .cell,#enemyGrid .cell'),unit=e.target.closest('#playerUnitStrip [data-unit]');if(c||unit)logEvent(type.toUpperCase(),{grid:c?.parentElement.id,cell:c?{x:Number(c.dataset.x),y:Number(c.dataset.y)}:undefined,unit:unit?.dataset.unit});},true);
 setInterval(()=>{if(!betaEnabled())return;const v=window.__stoneThrowViewState?.();if(v){const key=JSON.stringify([v.phase,v.inputLocked,v.shotsLeft]);if(key!==lastInput||activeAction&&!v.inputLocked){lastInput=key;const legal=!v.inputLocked&&(['play','player-spy','player-catapult','player-resurrect','hero-relocate','place','ready'].includes(v.phase));logEvent(legal?'NEXT LEGAL INPUT ENABLED':'INPUT STATE',{phase:v.phase,locked:v.inputLocked,shots:v.shotsLeft,...(legal&&activeAction?{requestToEnabledMs:performance.now()-activeAction.t}:{})});if(legal)activeAction=null;}}syncLog();},100);
 setInterval(()=>{void flush();},2000);window.addEventListener('pagehide',()=>{void flush();});
}
