// Optional Game Log. Collect only explicitly selected public fields and numeric timings.
let lastObservation=null,localMode='Single Player';
let enabled=false,match=null,seat=null,phase=null,serial=0,action=0,requestSerial=0,context={},lastState='',publicSequence=0,lastInput=null,activeAction=null;
const preferenceKey='stoneThrow.gameLog.enabled.v1';
try{enabled=localStorage.getItem(preferenceKey)==='1';}catch{}
export function gameLogEnabled(){return enabled;}
function syncSetting(){const b=document.getElementById('stGameLogSetting');if(b){b.textContent=enabled?'ON':'OFF';b.classList.toggle('on',enabled);b.setAttribute('aria-pressed',String(enabled));}syncLog();}
function setEnabled(value){const wasEnabled=enabled;enabled=!!value;try{localStorage.setItem(preferenceKey,enabled?'1':'0');}catch{}if(!enabled){pending.length=0;activeAction=null;if(panel){panel.hidden=true;panel.style.display='none';}}if(enabled&&!wasEnabled&&lastObservation){phase=null;lastState='';observeLog(lastObservation);}syncSetting();}
function installSetting(){const settings=document.getElementById('stSettings');if(!settings||document.getElementById('stGameLogSetting'))return;const row=document.createElement('div');row.className='st-setting-row st-toggle-row';const label=document.createElement('span');label.textContent='Game Log';const button=document.createElement('button');button.id='stGameLogSetting';button.type='button';button.className='st-toggle';button.setAttribute('aria-label','Game Log');button.onclick=()=>setEnabled(!enabled);row.append(label,button);const viewer=document.createElement('button');viewer.type='button';viewer.className='st-btn';viewer.textContent='OPEN GAME LOG HISTORY';viewer.onclick=openLog;row.append(viewer);settings.querySelector('.st-settings-title')?.after(row);syncSetting();}
const page=Date.now().toString(36)+'-'+Math.floor(performance.now()*1000),start=performance.now(),rows=[],pending=[],samples=new Map();let commitTimer=null;
// Recording owns persistence; opening/exporting the viewer never commits or starts capture.
function scheduleCommit(){if(commitTimer===null)commitTimer=setTimeout(()=>{commitTimer=null;void flush();},100);}
let dbPromise=null,flushing=null,panel=null,pre=null,button=null,dropped=0,storageFailure=false;
const MAX_MATCHES=20,MAX_ROWS=22000,MAX_BYTES=8*1024*1024,encoder=new TextEncoder(),metadata=new Map();let selectedMatch=null,selector=null,viewSerial=0;
const byteSize=r=>encoder.encode(JSON.stringify(r)).length;
const chronological=(a,b)=>(a.order??Date.parse(a.startedAt))-(b.order??Date.parse(b.startedAt))||a.id.localeCompare(b.id);
function metadataFrom(r){return {id:r.match,room:r.room||null,mode:r.mode||'Unknown (legacy log)',players:r.players??null,seat:r.seat??(r.match?.match(/-seat-(\d+)$/)?Number(r.match.match(/-seat-(\d+)$/)[1]):null),startedAt:r.wall,order:Date.parse(r.wall),endedAt:null,rowCount:0,bytes:0,trimmedRows:0};}
function database(){return dbPromise??=new Promise(resolve=>{try{const r=indexedDB.open('StoneThrow-temporary-beta-log',2);r.onupgradeneeded=()=>{const db=r.result,tx=r.transaction,store=db.objectStoreNames.contains('rows')?tx.objectStore('rows'):db.createObjectStore('rows',{keyPath:'id'});if(!store.indexNames.contains('match'))store.createIndex('match','match');store.createIndex('chronology',['match','wall','ms','id']);const sessions=db.createObjectStore('sessions',{keyPath:'id'}),old=new Map(),q=store.openCursor();q.onsuccess=()=>{const c=q.result;if(!c){const ordered=[...old.values()].sort(chronological);while(ordered.length>MAX_MATCHES){const at=ordered.findIndex(m=>m.id!==match),gone=ordered.splice(at,1)[0],del=store.index('match').openCursor(IDBKeyRange.only(gone.id));del.onsuccess=()=>{const row=del.result;if(row){row.delete();row.continue();}};}for(const m of ordered)sessions.put(m);return;}const row=c.value,m=old.get(row.match)||metadataFrom(row);m.startedAt=m.startedAt<row.wall?m.startedAt:row.wall;m.order=Math.min(m.order,Date.parse(row.wall));if(row.event==='MATCH OBSERVED')Object.assign(m,{room:row.room||m.room,mode:row.mode||m.mode,players:row.players??m.players});if(row.event==='PUBLIC AUTHORITY STATE'&&row.complete)m.endedAt=row.wall;m.rowCount++;m.bytes+=byteSize(row);old.set(m.id,m);c.continue();};};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>resolve(null);}catch{resolve(null);}});}
export async function logHistory(){const db=await database();let saved=[];if(db)saved=await new Promise(resolve=>{const q=db.transaction('sessions').objectStore('sessions').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve([]);});const all=new Map(saved.map(m=>[m.id,m]));for(const [id,m]of metadata){const old=all.get(id);all.set(id,{...old,...m,startedAt:old&&old.startedAt<m.startedAt?old.startedAt:m.startedAt,order:Math.min(old?.order??Infinity,m.order??Infinity),endedAt:m.endedAt||old?.endedAt||null});}return [...all.values()].sort(chronological);}
export function betaEnabled(){return enabled&&!!match;}
export function logEvent(event,data={}){if(!betaEnabled())return;if(!metadata.has(match))metadata.set(match,{id:match,room:context.room||null,mode:context.mode||'Unknown',players:context.players??null,seat,startedAt:new Date().toISOString(),order:performance.timeOrigin+performance.now(),endedAt:null});const r={id:page+'-'+(++serial),match,wall:new Date().toISOString(),ms:performance.now()-start,page,event,action:activeAction?.id??action,...data};if(JSON.stringify(r).length>8192){dropped++;return;}rows.push(r);pending.push(r);scheduleCommit();if(pending.length>22000){pending.splice(0,pending.length-22000);storageFailure=true;}if(rows.length>22000){rows.splice(0,2000);dropped+=2000;}if(pre&&!panel.hidden&&(selectedMatch||match)===r.match){pre.append(document.createTextNode(line(r)+'\n'));while(pre.childNodes.length>2000)pre.firstChild.remove();}}
function line(r){return `${r.wall} | +${r.ms.toFixed(1)} ms | ${r.event} | ${JSON.stringify(Object.fromEntries(Object.entries(r).filter(([k])=>!['wall','ms','event','id','match'].includes(k))))}`;}
async function flush(){if(!enabled){pending.length=0;return;}if(flushing)return flushing;if(!pending.length)return;const batch=pending.splice(0),meta=new Map(metadata);flushing=(async()=>{try{const db=await database();if(!db)return false;return await new Promise(resolve=>{const tx=db.transaction(['rows','sessions'],'readwrite'),store=tx.objectStore('rows'),sessions=tx.objectStore('sessions'),q=sessions.getAll();q.onsuccess=()=>{const all=new Map(q.result.map(m=>[m.id,m])),changed=new Set();for(const r of batch){const old=all.get(r.match)||{...metadataFrom(r),...meta.get(r.match)},m={...old,...meta.get(r.match),startedAt:old.startedAt<meta.get(r.match)?.startedAt?old.startedAt:(meta.get(r.match)?.startedAt||old.startedAt),order:Math.min(old.order??Infinity,meta.get(r.match)?.order??Infinity),endedAt:meta.get(r.match)?.endedAt||old.endedAt,rowCount:old.rowCount+1,bytes:old.bytes+byteSize(r),trimmedRows:old.trimmedRows||0};all.set(m.id,m);changed.add(m.id);store.put(r);}const ordered=[...all.values()].sort(chronological);let excess=ordered.length-MAX_MATCHES;for(const m of ordered){if(excess<=0)break;if(m.id===match)continue;excess--;all.delete(m.id);changed.delete(m.id);sessions.delete(m.id);metadata.delete(m.id);for(let i=rows.length-1;i>=0;i--)if(rows[i].match===m.id)rows.splice(i,1);const del=store.index('match').openCursor(IDBKeyRange.only(m.id));del.onsuccess=()=>{const c=del.result;if(c){c.delete();c.continue();}};}
for(const id of changed){const m=all.get(id);sessions.put(m);if(m.rowCount<=MAX_ROWS&&m.bytes<=MAX_BYTES)continue;const trim=store.index('chronology').openCursor(IDBKeyRange.bound([id],[id,[]]));trim.onsuccess=()=>{const c=trim.result;if(c&&(m.rowCount>MAX_ROWS||m.bytes>MAX_BYTES)){m.rowCount--;m.bytes-=byteSize(c.value);m.trimmedRows++;c.delete();const index=rows.findIndex(r=>r.id===c.value.id);if(index>=0)rows.splice(index,1);c.continue();}else sessions.put(m);};}};tx.oncomplete=()=>resolve(true);tx.onerror=tx.onabort=()=>resolve(false);});}catch{return false;}})();const ok=await flushing;flushing=null;if(!ok)storageFailure=true;}
function formatLog(saved=[],selected=match,meta={}){const all=new Map([...saved,...rows.filter(r=>r.match===selected)].map(r=>[r.id,r]));const first=[...all.values()].reduce((at,r)=>!at||r.wall<at?r.wall:at,meta.startedAt);meta={...meta,startedAt:first};return 'CHAIN SIEGE — GAME LOG\n'+JSON.stringify({...meta,match:selected,clock:'ISO UTC wall + page-relative performance.now milliseconds; server clocks separate',coverage:'observer-public only; no private host, credentials or RNG; DOM paint records are rAF opportunities, not physical display measurements',storageFailure})+'\n\n'+[...all.values()].sort((a,b)=>a.wall.localeCompare(b.wall)||a.ms-b.ms).map(line).join('\n');}
export async function logText(selected=selectedMatch||match){const history=await logHistory();selected=selected||history.at(-1)?.id;const db=await database();let saved=[];if(db&&selected)saved=await new Promise(resolve=>{const r=db.transaction('rows').objectStore('rows').index('match').getAll(selected);r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve([]);});return formatLog(saved,selected,history.find(m=>m.id===selected));}
export async function allLogText(){const history=await logHistory(),parts=[];for(const m of history)parts.push(await logText(m.id));return parts.join('\n\n==================== NEXT MATCH ====================\n\n');}
export async function saveLog(all=false){const text=await(all?allLogText():logText()),blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='StoneThrow_'+(all?'all_matches':String(selectedMatch||match).replace(/[^a-z0-9_-]/gi,'_'))+'_'+new Date().toISOString().replace(/[:.]/g,'-')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return text;}
export async function clearLogHistory(){pending.length=0;await flushing;pending.length=0;rows.length=0;metadata.clear();selectedMatch=null;lastInput=null;const db=await database();if(db)await new Promise(resolve=>{const tx=db.transaction(['rows','sessions'],'readwrite');tx.objectStore('rows').clear();tx.objectStore('sessions').clear();tx.oncomplete=tx.onerror=tx.onabort=()=>resolve();});await refreshViewer();}
async function refreshViewer(){if(!panel||panel.hidden)return;const generation=++viewSerial,history=await logHistory();if(generation!==viewSerial)return;selector.replaceChildren();for(const m of [...history].reverse()){const o=document.createElement('option');o.value=m.id;o.textContent=`${m.id===match?'Current · ':''}${m.startedAt} · ${m.mode} · ${m.players??'?'} players · seat ${m.seat??'?'} · ${m.id}`;selector.append(o);}if(!history.some(m=>m.id===selectedMatch))selectedMatch=history.some(m=>m.id===match)?match:history.at(-1)?.id||null;selector.value=selectedMatch||'';pre.textContent=formatLog([],selectedMatch,history.find(m=>m.id===selectedMatch)).split('\n').slice(-2000).join('\n');const text=await logText(selectedMatch);if(generation!==viewSerial||panel.hidden)return;pre.textContent=text.split('\n').slice(-2000).join('\n');pre.scrollTop=pre.scrollHeight;}
async function openLog(){if(!panel){panel=document.createElement('section');panel.id='stBetaGameLogPanel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','GAME LOG');panel.style.cssText='position:fixed;inset:4vh 3vw;z-index:2147483647;background:#15191f;color:#eee;border:2px solid #c6a35d;padding:14px;display:flex;flex-direction:column;gap:10px';const bar=document.createElement('div');bar.style.cssText='display:flex;flex-wrap:wrap;gap:8px';for(const [text,fn]of [['SAVE LOG',()=>saveLog()],['EXPORT ALL',()=>saveLog(true)],['CLEAR LOG HISTORY',async()=>{if(confirm('Delete all retained Game Logs? Recording preference will not change.'))await clearLogHistory();}],['CLOSE',()=>{panel.hidden=true;panel.style.display='none';button?.focus();}]]){const b=document.createElement('button');b.className='st-btn';b.textContent=text;b.onclick=fn;bar.append(b);}selector=document.createElement('select');selector.setAttribute('aria-label','Match log history');selector.style.cssText='width:100%;min-width:0';selector.onchange=()=>{selectedMatch=selector.value;void refreshViewer();};const note=document.createElement('small');note.textContent='Up to 20 matches; each keeps the latest 22,000 rows / 8 MiB. Older rows may be trimmed. Exports include all retained rows.';pre=document.createElement('pre');pre.style.cssText='overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;flex:1;font-size:12px;user-select:text';panel.append(bar,selector,note,pre);document.body.append(panel);}panel.hidden=false;panel.style.display='flex';await refreshViewer();}
export function syncLog(){const central=document.getElementById('stCenterStart');if(!central)return;const single=!document.body.classList.contains('st-multiplayer-mode')&&!document.body.classList.contains('story-mode-active'),gear=document.getElementById('stGear');if(!button&&(enabled||single)){button=document.createElement('button');button.id='stBetaGameLog';button.type='button';button.className=central.className;button.textContent='GAME LOG';button.onclick=openLog;central.before(button);}for(const id of ['resultOverlay','heroConfirmOverlay']){const host=document.querySelector('#'+id+' .result-actions,#'+id+' .hero-confirm-actions');if(host&&enabled&&!host.querySelector('[data-beta-log]')){const b=document.createElement('button');b.type='button';b.dataset.betaLog='1';b.textContent='GAME LOG';b.className='st-btn';b.onclick=openLog;host.append(b);}const b=host?.querySelector('[data-beta-log]');if(b)b.hidden=!enabled||!match;}if(button){const local=!document.body.classList.contains('st-multiplayer-mode');const anchor=local&&gear?gear:central;const leave=local&&document.getElementById('stLocalLeave');if(leave){if(leave.nextElementSibling!==button)leave.after(button);}else if(button.nextElementSibling!==anchor)anchor.before(button);button.className=local?'st-btn':central.className;button.setAttribute('aria-controls','stBetaGameLogPanel');button.setAttribute('aria-label','Open Game Log viewer');button.hidden=document.body.classList.contains('st-main-menu-mode')||(!single&&(!enabled||!match));}}
export function serverMetrics(value,request){if(!value||!enabled)return;logEvent('SERVER REQUEST METRICS',{request:request?.id,commandAction:request?.action,serverWall:value.wall,startupMetrics:value.startupMetrics,requestMs:value.requestMs,queueMs:value.queueMs,metrics:value.metrics});syncLog();}
export function requestLog(route,body){if(!betaEnabled())return null;const intent=body?.intent;const id=++requestSerial,t=performance.now();if(route==='command')action++;if(route==='command')activeAction={id:action,t};logEvent(route==='command'?'COMMAND REQUEST':'HTTP REQUEST',{request:id,route,kind:intent?.kind,cell:intent?.cell,placementCells:intent?.cells?.length,revision:body?.revision});return{id,t,route,action,story:body?.configuration?.story};}
export function responseLog(req,result){if(result?.configuration)localMode=result.configuration.story?'Story':'Single Player';else if(typeof req?.story==='boolean'&&result?.accepted!==false)localMode=req.story?'Story':'Single Player';observeLog(result?.update??result);if(req)logEvent('RESPONSE DELIVERED',{request:req.id,route:req.route,durationMs:performance.now()-req.t,accepted:result?.accepted,error:result?.error});}
export function observeLog(u){if(u?.configuration)localMode=u.configuration.story?'Story':'Single Player';if(u?.snapshot)lastObservation={snapshot:u.snapshot,lan:u.lan,localGroup:u.localGroup};if(!enabled)return;const s=u?.snapshot;const localGroup=!!u?.localGroup;let m=u?.lan||(localGroup?{...u.localGroup,code:u.localGroup.id,recoveryBattle:s.online?.room||s.battle}:null);const local=!!s&&!m&&!s.groupRoom;if(local){let scope;try{scope=sessionStorage.getItem('stoneThrow.gameLog.localScope.v1');if(!scope){scope=crypto.randomUUID();sessionStorage.setItem('stoneThrow.gameLog.localScope.v1',scope);}}catch{scope=page;}m={code:'local-'+scope+'-'+(localMode==='Story'?'story':'single'),recoveryBattle:s.battle,self:0,names:['You','Opponent'],controllers:['human','ai']};}if(u?.rejoin)logEvent('REJOIN STATUS',{available:u.rejoin.available,remainingMs:u.rejoin.remainingMs});if(m&&!s)logEvent('HEARTBEAT / CONNECTION',{presence:m.presence?.map(p=>({connected:p.connected,policy:p.policy,remainingMs:p.remainingMs,episode:!!p.episode})),controllers:m.controllers});if(m&&s){const id=m.code+'-'+(m.recoveryBattle||s.groupRoom||m.code+'-'+s.battle)+'-seat-'+m.self;if(match!==id){match=id;seat=m.self;phase=null;lastState='';lastInput=null;activeAction=null;publicSequence=0;samples.clear();context={room:m.code,mode:localGroup?'Single Player':local?localMode:m.group?'Group Battle':'Duel',players:m.names.length,names:m.names,controllers:m.controllers};metadata.set(match,{id:match,room:m.code,mode:context.mode,players:context.players,seat,startedAt:new Date().toISOString(),order:performance.timeOrigin+performance.now(),endedAt:null});if(panel&&!panel.hidden)void refreshViewer();logEvent('MATCH OBSERVED',{...context,room:m.code,round:s.round});}context={...context,players:m.names.length,names:m.names,controllers:m.controllers};if(s.phase==='finished'&&(!s.groupRoom||m.complete||s.online?.complete)){const info=metadata.get(match);if(info&&!info.endedAt)info.endedAt=new Date().toISOString();}const state={names:m.names,phase:s.phase,round:s.round,revision:s.revision,shots:s.shotsLeft,choice:s.choice?.kind??null,active:s.active,current:m.current,target:m.target,ring:m.ring,eliminated:m.eliminated,complete:m.complete,presence:m.presence?.map(p=>({connected:p.connected,policy:p.policy,remainingMs:p.remainingMs,episode:!!p.episode})),controllers:m.controllers,ready:m.ready};const key=JSON.stringify({...state,presence:state.presence?.map(({remainingMs,...p})=>p)});if(key!==lastState){logEvent('PUBLIC AUTHORITY STATE',state);lastState=key;}if(phase!==s.phase){logEvent(s.phase==='placement'?'PLACEMENT':s.phase==='finished'?'MATCH END / OBSERVER ELIMINATED':phase==='placement'?'MATCH START':'PHASE',{phase:s.phase});phase=s.phase;}
 const group=s.stats?.group,players=group?.players??[m.self,1-m.self].map((seat,j)=>({seat,name:m.names[seat],strength:(s.stats?.strength||[]).map(v=>({round:v.round,value:j?v.enemy:v.player}))}));for(const p of players){const countKey='length:'+p.seat,from=Math.max(0,(samples.get(countKey)||0)-1),history=p.strength||[];samples.set(countKey,history.length);for(let i=from;i<history.length;i++){const v=history[i];const key=p.id+':'+p.seat+':'+i,encoded=JSON.stringify(v);if(samples.get(key)!==encoded){samples.set(key,encoded);logEvent('PUBLIC STRENGTH SAMPLE',{player:p.name,seat:p.seat,index:i,round:v.round,value:v.value,known:Number.isFinite(v.value)});}}}
 logEvent('PUBLIC UPDATE',{frames:u.presentation?.length||0,events:u.events?.length||0,eventPosition:s.eventPosition,graphSamples:group?.players?.reduce((n,p)=>n+(p.strength?.length||0),0)});syncLog();}}
export function paintLog(s){if(!betaEnabled())return;for(const e of s.groupLog||[]){if(e.sequence<=publicSequence)continue;if(e.sequence>publicSequence+1)logEvent('PUBLIC HISTORY NOT OBSERVED',{from:publicSequence+1,to:e.sequence-1});publicSequence=e.sequence;logEvent('PUBLIC ORDERED EVENT',{sequence:e.sequence,text:e.text});}const t=performance.now();logEvent('DOM RENDER COMPLETE',{revision:s.revision,eventPosition:s.eventPosition,phase:s.phase,choice:s.choice?.kind,rows:document.getElementById('stEventList')?.children.length});requestAnimationFrame(()=>logEvent('MARKER PAINT OPPORTUNITY',{revision:s.revision,eventPosition:s.eventPosition,afterRenderMs:performance.now()-t}));}
export function dragLog(event,data={}){logEvent(event,data);}
if(typeof document!=='undefined'){
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installSetting,{once:true});else installSetting();
 window.addEventListener('storage',e=>{if(e.key===preferenceKey||e.key===null){let value=false;try{value=localStorage.getItem(preferenceKey)==='1';}catch{}setEnabled(value);}});
 for(const type of ['pointerdown','click','pointerup'])document.addEventListener(type,e=>{if(!betaEnabled()||e.target.closest('#stBetaGameLogPanel'))return;const c=e.target.closest('#playerGrid .cell,#enemyGrid .cell'),unit=e.target.closest('#playerUnitStrip [data-unit]');if(c||unit)logEvent(type.toUpperCase(),{grid:c?.parentElement.id,cell:c?{x:Number(c.dataset.x),y:Number(c.dataset.y)}:undefined,unit:unit?.dataset.unit});},true);
 // State changes and one-shot input-ready latency are separate: an unlocked
 // non-interactive state must retire the request without forcing repeated rows.
 setInterval(()=>{syncLog();if(!betaEnabled())return;const v=window.__stoneThrowViewState?.();if(v){const key=JSON.stringify([v.phase,v.inputLocked,v.shotsLeft]);const legal=!v.inputLocked&&(['play','player-spy','player-catapult','player-resurrect','hero-relocate','place','ready'].includes(v.phase));if(key!==lastInput||legal&&activeAction){lastInput=key;logEvent(legal?'NEXT LEGAL INPUT ENABLED':'INPUT STATE',{phase:v.phase,locked:v.inputLocked,shots:v.shotsLeft,...(legal&&activeAction?{requestToEnabledMs:performance.now()-activeAction.t}:{})});}if(!v.inputLocked)activeAction=null;}syncLog();},100);
 setInterval(()=>{void flush();},2000);window.addEventListener('pagehide',()=>{void flush();});
}
