const MODES=['Duel','3 Players','4 Players'];
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function identity(row){const span=node('span'),valid=/^[A-Z]{2}$/.test(row.country||''),f=node(valid?'img':'span',valid?undefined:'—');f.className='cs-hof-flag';if(valid){f.src='/assets/ui/flags/'+row.country.toLowerCase()+'.svg';f.alt=new Intl.DisplayNames(['en'],{type:'region'}).of(row.country);}else f.setAttribute('aria-label','Nationality not set');span.append(f,document.createTextNode(' '+row.displayName));return span;}
const value=(v,k)=>['winRatio','lossRatio','accuracy'].includes(k)?(100*v).toFixed(1)+'%':String(v);
let launchHall=null;
export function installHallOfFame(parent){
 const open=node('button','HALL OF FAME');open.id='csHallOfFame';open.type='button';parent.append(open);if(launchHall){open.onclick=launchHall;return;}let mode='Duel',category=null,generation=0;
 let dialog=document.getElementById('csHofDialog');if(!dialog){dialog=node('dialog');dialog.id='csHofDialog';dialog.setAttribute('aria-label','Hall of Fame');document.body.append(dialog);}
 const button=(text,fn)=>{const b=node('button',text);b.type='button';b.className='st-btn';b.onclick=fn;return b;};
 async function render(){const ticket=++generation;dialog.replaceChildren(node('h2','HALL OF FAME'));const tabs=node('div');tabs.className='cs-hof-tabs';for(const m of MODES){const b=button(m.toUpperCase(),()=>{mode=m;category=null;render();});b.setAttribute('aria-selected',String(m===mode));tabs.append(b);}dialog.append(tabs);const body=node('div','Loading…');dialog.append(body);const actions=node('div');actions.className='cs-hof-actions';actions.append(button('REFRESH',render),button('CLOSE',()=>{generation++;dialog.close();}));dialog.append(actions);try{const response=await fetch('/api/registry/hall-of-fame',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});if(!response.ok)throw Error('Hall of Fame is unavailable.');const data=await response.json();if(ticket!==generation||!dialog.open)return;body.replaceChildren();if(data.qualification.bypass)body.append(node('p','Playtest rankings — qualification bypass enabled. Public qualification: 10 Full games in this mode.'));if(category===null){const cards=node('div');cards.className='cs-hof-cards';for(const c of data.categories){const card=button('',()=>{category=c.key;render();});card.className='cs-hof-card';card.append(node('strong',c.title.toUpperCase()),node('span',c.description));if(c.leader){card.append(identity(c.leader),node('span',value(c.leader.value,c.key)));if(c.leaderTies>1)card.append(node('span',c.leaderTies+' tied leaders'));}else card.append(node('span','No qualifying entries yet'));cards.append(card);}body.append(cards);}else{const c=data.categories.find(c=>c.key===category);body.append(button('BACK TO CATEGORIES',()=>{category=null;render();}),node('h3',c.title.toUpperCase()),node('p',c.viewer?'Your rank: '+c.viewer.rank:c.viewerStatus==='not-qualified'?'Not yet qualified: '+data.qualification.viewerFull+' / 10 Full games.':c.viewerStatus==='guest'?'Log in to see your personal rank.':c.viewerStatus==='no-metric'?'No ordinary-shot accuracy available.':'No finalized games in this mode.'),node('p','Top 10 and nearby players. Equal values share a rank.'));for(const r of c.rows){const row=node('div');row.className='cs-hof-row'+(r.playerId===c.viewer?.playerId?' cs-hof-own':'');row.append(node('span','#'+r.rank),identity(r),node('span',value(r.value,c.key)));body.append(row);}}}catch(e){if(ticket===generation)body.textContent=e.message;}}
 launchHall=()=>{category=null;dialog.showModal();render();};open.onclick=launchHall;dialog.addEventListener('cancel',()=>generation++);
}
