const MODES=[['All','ALL'],['Duel','DUEL'],['3 Players','3 PLAYER'],['4 Players','4 PLAYER']];
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function identity(row){const span=node('span',undefined,'cs-hof-identity');if(row.playerId){span.dataset.profileId=row.playerId;span.tabIndex=0;span.setAttribute('role','button');span.setAttribute('aria-label','View '+row.displayName+' player card');}const valid=/^[A-Z]{2}$/.test(row.country||''),flag=node(valid?'img':'span',valid?undefined:'⚑','cs-hof-flag');if(valid){flag.src='/assets/ui/flags/'+row.country.toLowerCase()+'.svg';flag.alt=new Intl.DisplayNames(['en'],{type:'region'}).of(row.country);}else flag.setAttribute('aria-label','Nationality not set');span.append(flag,node('span',row.displayName));return span;}
const value=(v,k)=>['winRatio','lossRatio','accuracy'].includes(k)?(100*v).toFixed(1).replace(/\.0$/, '')+'%':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v);
function rankRow(r,key,own){const row=node('div',undefined,'cs-hof-row'+(own?' cs-hof-own':''));row.append(node('span','#'+r.rank,'cs-hof-rank'),identity(r),node('span',value(r.value,key),'cs-hof-value'));if(own){row.setAttribute('aria-label','Your ranking');row.querySelector('.cs-hof-identity').append(node('small','YOU','cs-hof-you'));}return row;}
let launchHall=null;
export function installHallOfFame(parent){
 const open=node('button','HALL OF FAME');open.id='csHallOfFame';open.type='button';parent.append(open);if(launchHall){open.onclick=launchHall;return;}let mode='All',generation=0;
 let dialog=document.getElementById('csHofDialog');if(!dialog){dialog=node('dialog');dialog.id='csHofDialog';dialog.setAttribute('aria-label','Hall of Fame');document.body.append(dialog);}
 const button=(text,fn)=>{const b=node('button',text,'st-btn');b.type='button';b.onclick=fn;return b;};
 async function render(){const ticket=++generation;const shell=document.createDocumentFragment();const header=node('header',undefined,'cs-hof-heading');header.append(node('span','CHAIN SIEGE','cs-hof-kicker'),node('h2','HALL OF FAME'));shell.append(header);const tabs=node('div',undefined,'cs-hof-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Player count');for(const [m,label] of MODES){const b=button(label,()=>{mode=m;render();});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(m===mode));tabs.append(b);}shell.append(tabs);const body=node('div','Loading…','cs-hof-content');body.setAttribute('aria-live','polite');shell.append(body);const actions=node('footer',undefined,'cs-hof-actions');actions.append(button('REFRESH',render),button('CLOSE',()=>{generation++;dialog.close();}));shell.append(actions);
 try{const response=await fetch('/api/registry/hall-of-fame',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});if(!response.ok)throw Error('Hall of Fame is unavailable.');const data=await response.json();if(ticket!==generation)return;body.replaceChildren();
 const records=node('div',undefined,'cs-hof-records');body.append(records);for(const [metric,heading] of [['topScores','TOP 3 BEST SCORES'],['topChains','TOP 3 BEST CHAINS']]){const best=node('section',undefined,'cs-hof-best');best.append(node('h3',heading));const periods=node('div',undefined,'cs-hof-periods');for(const [key,title]of [['month','THIS MONTH'],['year','THIS YEAR'],['all','ALL TIME']]){const col=node('section',undefined,'cs-hof-period');col.dataset.period=key;col.append(node('h4',title));const entries=data[metric]?.[key]||[];for(const r of entries)col.append(rankRow(r,'score',r.own));for(let i=entries.length;i<3;i++)col.append(node('p',(i+1)+'.  —','cs-hof-empty'));periods.append(col);}best.append(periods);records.append(best);}
 const cards=node('div',undefined,'cs-hof-cards');for(const c of data.categories){const card=node('section',undefined,'cs-hof-card');card.dataset.category=c.key;card.append(node('h3',c.title),node('p',c.description,'cs-hof-description'));const top=node('div',undefined,'cs-hof-top');for(const r of c.rows.slice(0,10))top.append(rankRow(r,c.key,r.playerId===c.viewer?.playerId));if(!top.children.length)top.append(node('p','No qualifying entries yet.','cs-hof-empty'));card.append(top);
 const index=c.rows.findIndex(r=>r.playerId===c.viewer?.playerId);if(index>=10){const near=node('div',undefined,'cs-hof-near');near.append(node('p','… YOUR POSITION','cs-hof-context-label'));for(const r of c.rows.slice(Math.max(10,index-1),index+2))near.append(rankRow(r,c.key,r.playerId===c.viewer.playerId));card.append(near);}else if(!c.viewer)card.append(node('p',c.viewerStatus==='guest'?'Log in to see your rank.':c.viewerStatus==='not-qualified'?data.qualification.viewerFull+' / '+data.qualification.requiredFull+' completed games to qualify.':c.viewerStatus==='no-metric'?'No qualifying metric yet.':'No finalized games in this filter.','cs-hof-status'));cards.append(card);}body.append(cards);
 const notes=node('p',undefined,'cs-hof-notes');notes.textContent='Registered players · Match scores from naturally completed games · Calendar periods use UTC.'+(' Eligibility: '+data.qualification.requiredFull+' fully completed games across all modes, or finish Story Mode.')+' Rankings use exact values; display is rounded.'+(data.coverage.excludedUnclassifiedOrMissingSummaries?' Incomplete or unclassified historical records are excluded.':' Retained authoritative history only.');body.append(notes);
 }catch(e){if(ticket===generation)body.textContent=e.message;}finally{if(ticket===generation){dialog.replaceChildren(shell);if(!dialog.open)dialog.showModal();document.getElementById('csHallOfFame')?.removeAttribute('aria-busy');}}}
 launchHall=()=>{const trigger=document.getElementById('csHallOfFame');if(trigger?.getAttribute('aria-busy')==='true')return;trigger?.setAttribute('aria-busy','true');void render();};open.onclick=launchHall;dialog.addEventListener('cancel',()=>generation++);
}
