export function installLan(session,browserClient,opened){
 let meta=opened?.update?.lan,revision=opened?.update?.snapshot.revision,battle=opened?.update?.snapshot.battle,busy=false;
 const bar=document.createElement('aside');bar.id='stLanStatus';bar.style.cssText='position:fixed;top:0;left:0;right:0;z-index:100000;background:#171717;color:white;padding:6px;font:13px sans-serif';document.body.append(bar);
 const panel=document.createElement('div');panel.id='stLanLobby';panel.style.cssText='display:none;position:fixed;inset:15% 20%;z-index:100002;background:#171717;color:white;padding:24px;border:1px solid #ab9';panel.innerHTML='<h2>LAN Game</h2><label>Seats <select id="stLanSeats"><option>2</option><option>3</option><option>4</option></select></label><div id="stLanControllers"></div><label>Display name <input id="stLanName" maxlength="24"></label><label> Game code <input id="stLanCode" maxlength="6"></label><p><button id="stLanMake">Make Game</button> <button id="stLanJoin">Join Game</button> <button id="stLanClose">Close</button></p><p id="stLanMessage" role="status"></p>';document.body.append(panel);
 const seats=document.getElementById('stLanSeats'),controllers=document.getElementById('stLanControllers');function setup(){controllers.replaceChildren();for(let i=1;i<Number(seats.value);i++){const label=document.createElement('label');label.textContent='Seat '+(i+1)+' ';const select=document.createElement('select');select.id='stLanController'+i;for(const value of ['human','ai']){const option=document.createElement('option');option.value=value;option.textContent=value==='human'?'Human':'AI';select.append(option);}select.disabled=Number(seats.value)===2;label.append(select);controllers.append(label);}}seats.onchange=setup;setup();
 const action=async(kind)=>{try{await session.request('pvp/'+kind,{name:document.getElementById('stLanName').value,code:document.getElementById('stLanCode').value,...(kind==='make'&&Number(seats.value)>2?{seats:Number(seats.value),controllers:['human',...Array.from({length:Number(seats.value)-1},(_,i)=>document.getElementById('stLanController'+(i+1)).value)]}:{})});location.reload();}catch(e){document.getElementById('stLanMessage').textContent=e.code||e.message;}};
 document.getElementById('stLanMake').onclick=()=>action('make');document.getElementById('stLanJoin').onclick=()=>action('join');document.getElementById('stLanClose').onclick=()=>panel.style.display='none';
 document.addEventListener('click',async e=>{if(meta&&e.target.closest('#playAgainBtn')){e.preventDefault();e.stopImmediatePropagation();document.getElementById('stLanRematch')?.click();return;}if(e.target.closest('#stMenuOnline')){e.preventDefault();e.stopImmediatePropagation();if(await window.__stoneThrowSelectMultiplayer?.()){document.body.classList.remove('st-main-menu-mode');}else panel.style.display='block';}},true);
 function observe(update){if(!update.lan){meta=null;bar.style.display='none';for(const id of ['playerGrid','enemyGrid','playerUnitStrip','enemyUnitStrip']){const el=document.getElementById(id);el.hidden=false;el.style.removeProperty('display');}return;}bar.style.display='';document.documentElement.dataset.lanRevision=String(update.snapshot.revision);meta=update.lan;revision=update.snapshot.revision;battle=update.snapshot.battle;const s=update.snapshot,other=1-meta.self;bar.replaceChildren();const label=document.createElement('span');label.textContent=`Game ${meta.code} · ${meta.names[meta.self]} vs ${meta.names[other]||'waiting for player'} · `+(meta.closed?'Game closed':s.phase==='placement'?(meta.ready[meta.self]?'Ready — waiting':'Place your army, then Ready'):s.phase==='finished'?s.outcome:s.choice?'Your decision':meta.waiting?'Waiting for opponent decision':s.active==='self'?'Your turn':'Opponent’s turn')+(!meta.connected[other]?' · opponent disconnected/waiting':'');if(update.error==='stale')label.textContent+=' · State updated; please retry your action.';if(meta.ring){label.textContent='Game '+meta.code+' · '+meta.names.map((name,i)=>(name||'Waiting')+' ('+meta.controllers[i]+')'+(meta.eliminated.includes(i)?' eliminated':meta.ready[i]?' ready':'')+(!meta.connected[i]?' disconnected/waiting':'')).join(' · ')+' · Ring: '+(meta.ring.length?meta.ring.map(i=>meta.names[i]||'Waiting').join(' → '):'drawn at start')+' · '+(meta.closed?'Game closed':meta.eliminated.includes(meta.self)?'You are eliminated':s.choice?'Your decision':meta.waiting?'Waiting for opponent decision':s.phase==='placement'?'Place your army, then Ready':s.active==='self'?'Your turn':'Waiting for turn')+' · Target: '+(meta.target===null?'none':meta.names[meta.target]);if(update.error==='stale')label.textContent+=' · State updated; please retry your action.';
   for(const [id,visible]of [['playerGrid',meta.ownBoardVisible],['enemyGrid',meta.targetBoardVisible]]){const el=document.getElementById(id);el.hidden=!visible;el.style.setProperty('display',visible?'':'none',visible?'':'important');if(!visible)el.replaceChildren();}for(const [id,visible]of [['playerUnitStrip',meta.ownBoardVisible],['enemyUnitStrip',meta.targetBoardVisible]]){const el=document.getElementById(id);el.hidden=!visible;el.style.setProperty('display',visible?'':'none',visible?'':'important');if(!visible)el.replaceChildren();}
  }bar.append(label);
  const leave=document.createElement('button');leave.textContent='Leave';leave.id='stLanLeave';leave.onclick=async()=>{await session.request('pvp/leave');location.reload();};bar.append(leave);if(s.phase==='finished'&&(!meta.ring||meta.complete)){const rematch=document.createElement('button');rematch.id='stLanRematch';rematch.textContent=meta.rematch[meta.self]?'Rematch requested':'Rematch';rematch.disabled=meta.rematch[meta.self]||meta.closed;rematch.onclick=async()=>browserClient.apply(await session.request('pvp/rematch'));bar.append(rematch);const play=document.getElementById('playAgainBtn');play.textContent='REMATCH';play.onclick=e=>{e.stopImmediatePropagation();rematch.click();};}
  if(s.phase==='placement'){const start=document.getElementById('startBtn');start.disabled=meta.ready[meta.self]||start.disabled;const visible=document.getElementById('stStart');if(visible)visible.textContent=meta.ready[meta.self]?'WAITING':'READY';}
 }
 if(meta)observe(opened.update);else{bar.style.display='none';}
 // Poll only public state; no private checkpoint ever enters this adapter.
 const timer=setInterval(async()=>{if(!meta||busy||window.__stoneThrowViewState?.().inputLocked)return;busy=true;try{const update=await session.client.read();if(!meta)return;if(update.snapshot.revision!==revision||update.snapshot.battle!==battle)await browserClient.apply(update);else observe(update);}catch(e){bar.textContent='LAN connection: '+(e.code||'unavailable')+' — reload to reconnect';}finally{busy=false;}},700);
 window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
 return {observe,blocked:()=>!!meta&&(meta.closed||meta.eliminated?.includes(meta.self)||meta.waiting||meta.ready[meta.self]&&window.__stoneThrowViewState?.().phase==='ready')};
}
