import {paintDeployment} from './deployment-overlay.js';
import {installOnlineEntry} from './online-entry.js';
import {observeLog,syncLog} from './game-log.js';
import {installGroup} from './group-lan.js';
import {mountDisconnect,clockText,resolveReturn} from './rejoin.js';
export function installLan(session,browserClient,opened){
 let meta=opened?.update?.lan,last=opened?.update?.snapshot,revision=last?.revision,battle=last?.battle,busy=false,polling=false,listBusy=false,shownAt=Date.now(),generation=0,detached=false,dismissedResult=null;
 const disconnect=mountDisconnect(session);
 const by=id=>document.getElementById(id),link=document.createElement('link');link.rel='stylesheet';link.href='styles-multiplayer.css';document.head.append(link);
 const bar=document.createElement('aside');bar.id='stLanStatus';bar.className='st-mp-status st-frame';bar.hidden=true;by('stoneThrowShell').querySelector('.st-topbar').after(bar);
 const headerLeave=document.createElement('button');headerLeave.id='stHeaderLeave';headerLeave.className='st-btn';headerLeave.textContent='LEAVE';headerLeave.hidden=true;headerLeave.onclick=()=>by(meta?.group?'stGroupLeave':'stLanLeave')?.click();by('stRandom').after(headerLeave);
 const syncHeaderLeave=()=>{headerLeave.hidden=!meta||bar.hidden;headerLeave.disabled=busy;};new MutationObserver(syncHeaderLeave).observe(bar,{attributes:true,attributeFilter:['hidden'],childList:true});
 const {panel,showSetup,refreshGames}=installOnlineEntry(session,()=>navigateSeat(true));
 const group=installGroup(session,browserClient,bar,navigateSeat);
 const consent=document.createElement('div');consent.id='stLanQuickDialog';consent.className='st-mp-overlay';consent.hidden=true;consent.innerHTML='<section class="st-mp-dialog st-frame" role="dialog" aria-modal="true" aria-labelledby="stLanQuickTitle"><h2 id="stLanQuickTitle">QUICK START</h2><p id="stLanQuickProposal"></p><p>Accept to randomly place both armies and begin the duel. Decline to keep your placements and use READY. This proposal cannot be repeated after a decline.</p><div class="st-mp-actions"><button id="stLanQuickAccept" class="st-btn">ACCEPT</button><button id="stLanQuickDecline" class="st-btn">DECLINE</button></div><p id="stLanQuickMessage" role="status"></p></section>';document.body.append(consent);
 let notice='',noticeUntil=0;const quickLabel=by('stQuickStart')?.textContent;
 const clearOnlineEntryRemnants=()=>{generation++;meta=null;group.clear();disconnect.observe(null,last);bar.replaceChildren();bar.hidden=true;consent.hidden=true;headerLeave.hidden=true;by('stLanResultMenu')?.remove();by('csDeployment')&&(by('csDeployment').hidden=true);document.querySelectorAll('.st-mp-newsflash').forEach(e=>e.remove());};
 window.addEventListener('stone-throw-online-entry',clearOnlineEntryRemnants);
 const errors={'seat-handed-to-ai':'This seat has already been handed to AI.','kick-unavailable':'The player can still rejoin. Kick is available only after the grace period.','invalid-name':'Enter a display name (up to 24 characters).','bad-game-code':'Game not found. Check the code and try again.','game-full':'This game is full.','already-seated':'You already have a seat in this game.','lan-disabled':'LAN play is not enabled. Start this candidate with PLAYTEST-LAN.cmd.','stale':'The game changed. Please try again.','quick-unavailable':'Quick Start is unavailable for this lobby.','illegal':'That action is not available. Check your placement and readiness.','unknown-seat':'This seat is no longer available. Return to the menu and join a game.'};
 const message=e=>errors[e?.code||e?.error||e?.message]||'Connection unavailable. Try again or reload to rejoin.';

 async function run(operation,placementReady=false){const version=generation;if(detached)return;if(busy||!placementReady&&window.__stoneThrowViewState?.().inputLocked)return;busy=true;syncControls();try{const update=await operation();if(detached||version!==generation)return;if(update?.snapshot){await browserClient.apply(update);if(detached||version!==generation)return;observe(update);if(update.accepted===false){notice=message(update);noticeUntil=Date.now()+5000;}}}catch(error){notice=message(error);noticeUntil=Date.now()+5000;by('stLanQuickMessage').textContent=notice;}finally{busy=false;syncControls();renderBar();}}
 const quick=action=>run(async()=>{const s=(await session.client.read()).snapshot;return session.request('pvp/quick',{battle:s.battle,revision:s.revision,action});});
 const ready=()=>run(async()=>{const s=(await session.client.read()).snapshot;return session.client.dispatch({contract:s.contract,battle:s.battle,revision:s.revision,intent:{kind:'start'}});},true);
 by('stLanQuickAccept').onclick=()=>quick('accept');by('stLanQuickDecline').onclick=()=>quick('decline');
 document.addEventListener('click',async e=>{if(meta?.group&&meta.complete&&e.target.closest('#stCenterStart')){e.preventDefault();e.stopImmediatePropagation();window.dispatchEvent(new Event('cs-open-group-results'));return;}if(meta&&last?.phase==='finished'&&e.target.closest('#resultCloseBtn,#stCenterStart')){e.preventDefault();e.stopImmediatePropagation();const close=!!e.target.closest('#resultCloseBtn');dismissedResult=close?resultKey():null;by('resultOverlay').style.display=close?'none':'flex';return;}if(meta?.group&&group.handleClick(e))return;if(meta&&e.target.closest('#playAgainBtn')){e.preventDefault();e.stopImmediatePropagation();by('stLanRematch')?.click();return;}if(meta&&e.target.closest('#stQuickStart')){e.preventDefault();e.stopImmediatePropagation();return;}if(meta&&last?.phase==='placement'&&e.target.closest('#stCenterStart,#stStart,#startBtn')){e.preventDefault();e.stopImmediatePropagation();ready();return;}if(e.target.closest('#stMenuOnline')){e.preventDefault();e.stopImmediatePropagation();try{if(await window.__stoneThrowSelectMultiplayer?.())document.body.classList.remove('st-main-menu-mode');else await showSetup();}catch(e){if(['rejoin-required','seat-handed-to-ai'].includes(e.code)){detachView();}else await showSetup(e);}}},true);
 function syncControls(){if(!meta)return;if(meta.group){group.sync();syncResultActions();return;}syncResultActions();const placement=last?.phase==='placement',self=meta.self,valid=Object.entries(last?.rosters.self||{}).every(([kind,n])=>last.owned.filter(u=>u.kind===kind).length===n),waitingQuick=meta.quickStart?.status==='pending';document.body.classList.add('st-multiplayer-mode');if(placement){const start=by('stCenterStart');start.hidden=false;start.textContent=meta.ready[self]?'UNREADY':'READY';start.disabled=busy||!valid||waitingQuick||meta.closed;const status=by('stStatus');status.style.display='';status.textContent=meta.ready[self]?'WAITING FOR OPPONENT':waitingQuick?'QUICK START PROPOSED':'PLACE YOUR ARMY';by('stRandom').disabled=busy||!!meta.ready[self];const q=by('stQuickStart');q.hidden=true;q.disabled=busy||meta.closed||meta.names.some(n=>!n)||meta.ready.some((v,i)=>v&&meta.controllers?.[i]!=='ai')||(meta.quickStart?.status||'available')!=='available';q.textContent=meta.quickStart?.status==='declined'?'QUICK START DECLINED':waitingQuick?'QUICK START PROPOSED':'QUICK START';}
 const show=placement&&!meta.ring&&self===1&&waitingQuick&&!meta.closed;const was=consent.hidden;consent.hidden=!show;by('stLanQuickAccept').disabled=busy;by('stLanQuickDecline').disabled=busy;by('stLanQuickProposal').textContent=(meta.names[0]||'Host')+' proposes Quick Start';if(show&&was)by('stLanQuickAccept').focus();}
 function soloAiResult(){return meta&&!meta.ring&&last?.phase==='finished'&&meta.controllers?.[1-meta.self]==='ai';}
 function resultKey(){return (meta?.recoveryBattle||last?.battle)+':'+meta?.self+':'+!!meta?.complete+':'+last?.outcome;}
 function syncResultActions(){const localMenu=by('stLocalResultMenu');if(localMenu)localMenu.hidden=!!meta;let menu=by('stLanResultMenu');if(!meta||last?.phase!=='finished'){menu?.remove();dismissedResult=null;return;}const again=by('playAgainBtn'),rematch=by(meta.group?'stGroupRematch':'stLanRematch'),waiting=meta.group?meta.rematchCommitted.includes(meta.self)&&!meta.complete:!!meta.rematch[meta.self];again.hidden=!!(meta.group&&meta.complete);again.textContent=waiting?'WAITING FOR REMATCH':'REMATCH';again.disabled=busy||waiting||meta.closed;const close=by('resultCloseBtn');close.textContent='×';close.setAttribute('aria-label','Close results');close.style.display=meta.group&&meta.complete?'none':'block';if(!menu){menu=document.createElement('button');menu.id='stLanResultMenu';menu.type='button';menu.className=again.className;menu.onclick=()=>by(meta.group?'stGroupLeave':'stLanLeave')?.click();again.after(menu);}menu.hidden=!!(meta.group&&meta.complete);menu.textContent='MAIN MENU';menu.disabled=busy;const action=by('stCenterStart');action.textContent='RESULTS';action.hidden=false;action.disabled=false;for(const id of ['stGroupLeave','stGroupRematch','stLanLeave','stLanRematch']){const e=by(id);if(e){e.hidden=true;e.style.display='none';}}if(dismissedResult===resultKey()||meta.group&&waiting)by('resultOverlay').style.display='none';}
 window.__stoneThrowSyncMultiplayerControls=syncControls;
 window.__stoneThrowMultiplayerQuickStart=()=>meta?(meta.ring?Promise.resolve():quick('propose')):null;
 function renderBar(){if(!meta)return;if(meta.group)return group.render();bar.hidden=false;bar.replaceChildren();const heading=document.createElement('strong');heading.textContent='DUEL · '+meta.code;heading.id='stLanGameCode';bar.append(heading);const seats=document.createElement('div');seats.className='st-mp-seats';for(let i=0;i<meta.names.length;i++){const row=document.createElement('span');row.className='st-mp-seat';row.textContent=(meta.names[i]||'Waiting for player')+(meta.controllers?.[i]==='ai'?' (AI)':'')+'  '+(meta.ready[i]?'✅ READY':'❌ NOT READY');seats.append(row);}bar.append(seats);const status=document.createElement('p');status.id='stLanLiveStatus';status.setAttribute('role','status');status.textContent=Date.now()<noticeUntil?notice:meta.closed?'Game closed':last.phase==='placement'?(meta.quickStart?.status==='declined'?'Quick Start declined. Keep placing your army, then press READY.':meta.quickStart?.status==='pending'?'Quick Start proposed — waiting for the other player.':meta.ready[meta.self]?'Ready — waiting for your opponent.':'Place your army, then press READY.'):last.phase==='finished'?(last.outcome==='win'?'You win.':last.outcome==='loss'?'You lose.':'Draw.'):last.choice?'Your decision':meta.waiting?'Waiting for opponent decision':last.active==='self'?'Your turn':'Opponent’s turn';const other=1-meta.self,disconnected=meta.presence?.[other];if(meta.names[other]&&!meta.connected[other]){const remaining=disconnected?.remainingMs===null||disconnected?.remainingMs===undefined?null:disconnected.remainingMs-(Date.now()-shownAt);status.textContent=meta.names[other]+' disconnected'+(remaining===null?' — waiting':' — '+clockText(remaining)+' remaining');}bar.append(status);const actions=document.createElement('div');actions.className='st-mp-actions';const leave=document.createElement('button');leave.className='st-btn';leave.id='stLanLeave';leave.textContent='LEAVE';leave.onclick=async()=>{if(busy)return;busy=true;generation++;try{await session.request('pvp/leave');await navigateSeat();busy=false;}catch(e){busy=false;notice=message(e);noticeUntil=Date.now()+5000;renderBar();}};actions.append(leave);if(last.phase==='finished'&&(!meta.ring||meta.complete)){const rematch=document.createElement('button');rematch.className='st-btn';rematch.id='stLanRematch';rematch.textContent=meta.rematch[meta.self]?'REMATCH REQUESTED':'REMATCH';rematch.disabled=busy||meta.rematch[meta.self]||meta.closed;rematch.onclick=()=>run(()=>session.request('pvp/rematch'));actions.append(rematch);by('playAgainBtn').textContent=rematch.textContent;by('playAgainBtn').disabled=rematch.disabled;}actions.hidden=!!soloAiResult();if(soloAiResult())actions.style.display='none';bar.append(actions);syncResultActions();}
 function observe(update){observeLog(update);paintDeployment(update.lan,update.snapshot);if(detached)return;if(update.lan?.group){meta=update.lan;last=update.snapshot;group.observe(update);syncResultActions();return;}if(meta?.group&&!update.lan&&update.snapshot?.groupRoom===last?.groupRoom)return;if(meta?.group)group.clear();if(!update.lan&&meta&&update.snapshot?.battle===battle)return;if(!update.lan&&meta)generation++;disconnect.observe(update.lan,update.snapshot);if(!update.lan){meta=null;last=update.snapshot;by('stLanResultMenu')?.remove();bar.hidden=true;consent.hidden=true;document.body.classList.remove('st-multiplayer-mode');for(const id of ['playerGrid','enemyGrid','playerUnitStrip','enemyUnitStrip']){const el=by(id);el.hidden=false;el.style.removeProperty('display');}by('playAgainBtn').disabled=false;by('stRandom').disabled=false;by('stQuickStart').disabled=false;by('stQuickStart').hidden=false;by('stQuickStart').textContent=quickLabel;return;}const prev=meta,previousBattle=battle;meta=update.lan;shownAt=Date.now();last=update.snapshot;revision=last.revision;battle=last.battle;document.documentElement.dataset.lanRevision=String(revision);if(previousBattle===battle&&prev)for(let i=0;i<meta.ready.length;i++)if(meta.ready[i]&&!prev.ready[i]){notice=(meta.names[i]||'Player '+(i+1))+' READY!';noticeUntil=Date.now()+2400;}
 if(meta.ring)for(const [id,visible]of [['playerGrid',meta.ownBoardVisible],['enemyGrid',meta.targetBoardVisible],['playerUnitStrip',meta.ownBoardVisible],['enemyUnitStrip',meta.targetBoardVisible]]){const el=by(id);el.hidden=!visible;el.style.setProperty('display',visible?'':'none',visible?'':'important');if(!visible)el.replaceChildren();}
 syncControls();renderBar();}
 if(meta)observe(opened.update);if(opened.multiplayerMenu){document.body.classList.add('st-main-menu-mode');void showSetup();}
 // Explicit room transitions preserve the document; server cookies remain authoritative.
 async function navigateSeat(deployment=false){generation++;meta=null;group.clear();disconnect.observe(null,last);bar.hidden=true;consent.hidden=true;panel.hidden=true;browserClient.unmount();document.body.classList.remove('st-multiplayer-mode');document.body.classList.add('st-main-menu-mode');by('resultOverlay').style.display='none';by('stLanResultMenu')?.remove();
  let out;try{out=await resolveReturn(session,await session.open());await browserClient.enterOpened(out);observe(out.update);}catch(error){location.reload();throw error;} // Exceptional failed remount reboots through the cold entry gate.
  if(out.update?.lan&&(deployment||out.reconnected&&!out.mainMenu&&!out.multiplayerMenu))document.body.classList.remove('st-main-menu-mode');
 }
 function detachView(){if(detached)return;detached=true;generation++;meta=null;disconnect.observe(null,last);bar.hidden=true;consent.hidden=true;browserClient.unmount();clearInterval(timer);clearInterval(listTimer);clearInterval(heartbeat);document.body.classList.add('st-main-menu-mode');location.reload();}
 const heartbeat=setInterval(async()=>{if(!meta||meta.ring||detached)return;const version=generation;try{const out=await session.request('pvp/heartbeat');if(detached||version!==generation||!meta)return;meta=out.lan;shownAt=Date.now();disconnect.observe(meta,last);renderBar();}catch(e){if(detached||version!==generation)return;if(['rejoin-required','seat-handed-to-ai'].includes(e.code))location.reload();}},2000);
 const listTimer=setInterval(refreshGames,2000);const timer=setInterval(async()=>{if(!meta||meta.group||busy||polling||last?.phase!=='placement'&&window.__stoneThrowViewState?.().inputLocked)return;polling=true;const expected=battle,version=generation;try{const update=await session.client.read();if(detached||version!==generation||!meta||battle!==expected)return;if(update.snapshot.revision!==revision||update.snapshot.battle!==battle)await browserClient.apply(update);if(detached||version!==generation||!meta||battle!==expected)return;observe(update);}catch(e){if(detached||version!==generation)return;if(['rejoin-required','seat-handed-to-ai'].includes(e.code)){detachView();return;}notice=message(e)+' — reload to rejoin.';noticeUntil=Date.now()+5000;renderBar();}finally{polling=false;}},700);
 window.addEventListener('pagehide',()=>{clearInterval(timer);clearInterval(listTimer);clearInterval(heartbeat);},{once:true});
 return {observe,blocked:()=>meta?.group?group.blocked():!!meta&&(busy||meta.closed||meta.eliminated?.includes(meta.self)||meta.waiting||meta.ready[meta.self]&&last?.phase==='placement')};
}
