import {avatarById,DEFAULT_AVATAR} from '../assets/avatars/catalog.mjs';
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
export function installMainMenu(accountBar){
 const css=node('link');css.rel='stylesheet';css.href='/styles-main-menu.css';document.head.append(css);
 const menu=document.querySelector('#stMainMenu'),utility=menu.querySelector('.st-menu-utility-row');
 utility.before(accountBar);const identity=node('div',null,'cs-menu-identity');identity.id='csMenuIdentity';menu.querySelector('.st-menu-brand').append(identity);
 const exit=document.getElementById('stMenuExit');exit.classList.add('cs-menu-exit');menu.querySelector('.st-menu-frame').append(exit);
 const about=node('button',null,'st-menu-button');about.id='csMenuAbout';about.type='button';about.innerHTML='<span class="st-menu-button-layout"><span class="st-menu-icon cs-menu-info" aria-hidden="true">i</span><span class="st-menu-button-text"><span class="st-menu-button-title">ABOUT</span><span class="st-menu-button-copy">About the game &amp; credits</span></span></span>';utility.append(about);
 const dialog=node('dialog',null,'cs-about');dialog.id='csAboutDialog';dialog.setAttribute('aria-labelledby','csAboutTitle');const heading=node('h2','ABOUT / CREDITS');heading.id='csAboutTitle';dialog.append(node('small','CHAIN SIEGE'),heading);
 const content=node('div',null,'cs-about-content');content.tabIndex=0;content.setAttribute('aria-label','About and credits content');
 // A future archive photo can be inserted as a figure in the first section.
 for(const [title,paragraphs] of [["ABOUT THE GAME", ["CHAIN SIEGE began as a game I created as a child.", "It started with Battleship. A friend had grown tired of the original game, so I began changing the rules to make it more exciting. After discovering role-playing games and fantasy, the idea gradually became something very different — larger battles, strange units, special abilities and chain reactions where one hit could suddenly change everything.", "The game was played, changed and expanded over many years with friends and family. Old ideas disappeared, new ones were added, and eventually my sons began contributing units and ideas of their own.", "In 2025, after suffering a heart attack, I decided it was time to finally turn the old game into a proper playable prototype. One reason was simple: if anything ever happened to me, I wanted my sons to have something real they could continue from rather than just stories, sketches and old rules.", "That prototype eventually became CHAIN SIEGE."]], ["VISION / FUTURE", ["The goal has never been to turn CHAIN SIEGE into chess.", "It is meant to be easy to understand, unpredictable and social — a game where good placement and clever choices matter, but where no player is ever completely safe.", "The best moments are the ones nobody planned: a plague that spreads too far, an Assassin that changes everything, a chain reaction that destroys half a battlefield, or a player who looked certain to win suddenly fighting for survival.", "The aim is to keep developing the game around that idea: faster battles, less dead time, more variety and more “oh shit” moments.", "If CHAIN SIEGE grows beyond the prototype stage, the hope is to continue improving the artwork, sound, presentation and online systems while keeping the strange little game at its core intact."]], ["DEVELOPMENT & AI", ["The digital version of CHAIN SIEGE would not exist in its current form without modern AI tools.", "Early programming work began with GitHub Copilot, and the majority of the prototype was later developed with extensive help from ChatGPT and Codex — programming, debugging, system design, testing support and turning game-design ideas into working features.", "AI tools were also used to create and develop some of the prototype artwork and visual assets.", "The game design, rules, characters, ideas and creative direction remain the work of its creator, family and playtesters. AI has been the tool that made it possible to turn a decades-old paper game into a functioning digital game without a traditional development studio.", "If the game grows, the hope is that more of the prototype artwork can eventually be replaced or refined by human artists."]]]){const section=node('section');section.append(node('h3',title));for(const paragraph of paragraphs)section.append(node('p',paragraph));content.append(section);}
 const credits=node('section');credits.append(node('h3','CREDITS'));for(const [title,lines] of [["Created & Designed by", ["Þorsteinn Jóhannsson"]], ["Playtesting & Game Ideas", ["Matti", "Wolfraven"]], ["Additional Ideas & Playtesting", ["Family and friends who have played and helped shape the game over the years."]], ["Development Tools", ["ChatGPT", "OpenAI Codex", "GitHub Copilot"]], ["Prototype Artwork", ["Created and developed using a mixture of original direction, existing assets and AI-assisted tools."]], ["Music", []], ["OpenGameArt:", ["Medieval: Exploration — RandomMind — CC0", "Fantasy: Rising Moon — RandomMind — CC0", "Eye of the Storm — Indieteur — CC0", "Aftermath — Indieteur — CC0", "Medieval: Victory Theme — RandomMind — CC0", "Medieval: Defeat Theme — RandomMind — CC0"]], ["Pixabay:", ["Eerie Ambiance — Shut_Up_Ghost"]]]){const group=node('div',null,'cs-credit-group');group.append(node('h4',title));for(const line of lines)group.append(node('p',line));credits.append(group);}content.append(credits);dialog.append(content);
 const back=node('button','BACK TO MAIN MENU','st-btn');back.type='button';back.onclick=()=>dialog.close();dialog.append(back);document.body.append(dialog);about.onclick=()=>dialog.showModal();
 const panel=node('section',null,'cs-world');panel.setAttribute('aria-label','Global battle statistics');
 const title=node('div','THE WAR SO FAR','cs-world-title'),stats=node('div',null,'cs-world-stats');
 const values={};for(const [key,label]of [['battles','BATTLES FOUGHT'],['unitsDestroyed','PLAYER UNIT KILLS'],['biggestChain','BEST PLAYER CHAIN']]){const cell=node('div');values[key]=node('strong','—');cell.append(values[key],node('span',label));stats.append(cell);}
 const rivalry=node('div',null,'cs-rivalry'),labels=node('div',null,'cs-rivalry-labels'),human=node('span','HUMANS'),ai=node('span','AI');labels.append(human,node('span','GLOBAL CONTEST','cs-rivalry-caption'),ai);
 const meter=node('div',null,'cs-rivalry-meter'),fill=node('div');meter.append(fill);meter.setAttribute('role','img');meter.setAttribute('aria-label','Global contest loading');
 const status=node('div','Loading global results…','cs-world-status');status.setAttribute('aria-live','polite');rivalry.append(labels,meter,status);panel.append(title,stats,rivalry);exit.before(panel);
 let pending=false,last=0;
 async function refresh(){if(pending||Date.now()-last<30000)return;pending=true;try{const r=await fetch('/api/registry/global-stats',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error();const data=await r.json();const format=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);for(const key of Object.keys(values)){values[key].textContent=Number.isFinite(data[key])?format(data[key]):'—';values[key].parentElement.title=data.coverage;}
 const h=data.factions.humanScore,a=data.factions.aiScore,total=h+a,percent=total?Math.round(h/total*100):0;human.textContent='HUMANS'+(total?'  '+percent+'%':'');ai.textContent=(total?(100-percent)+'%  ':'')+'AI';fill.style.width=total?(h/total*100)+'%':'0%';meter.classList.toggle('empty',!total);meter.setAttribute('aria-label',total?`Humans ${percent} percent, AI ${100-percent} percent`:'No faction points yet');status.textContent=total?`${h===a?'Evenly matched':h>a?'Humanity leads':'AI leads'} · ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(h)} : ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(a)} faction points`:'The contest awaits its first points';panel.dataset.loaded='true';last=Date.now();}catch{status.textContent='Global results temporarily unavailable';meter.setAttribute('aria-label','Global contest unavailable');}finally{pending=false;}}
 new MutationObserver(()=>{if(document.body.classList.contains('st-main-menu-mode'))void refresh();}).observe(document.body,{attributes:true,attributeFilter:['class']});void refresh();
}

export function arrangeMenuAccount(bar,account){
 const status=document.getElementById('csMenuIdentity');status.replaceChildren();
 if(account){const username=node('button',account.displayName,'cs-menu-player');username.type='button';username.setAttribute('aria-label','Open your Profile: '+account.displayName);username.onclick=()=>bar.querySelector('#csProfile')?.click();status.append(username);if(Number.isInteger(account.currentStreak)&&account.currentStreak>=0)status.append(node('span',account.currentStreak+' DAY STREAK','cs-menu-streak'));const logout=bar.querySelector('#csLogout');if(logout)status.append(logout);}
 for(const span of [...bar.querySelectorAll(':scope > span')])span.remove();
 for(const b of bar.querySelectorAll('button')){b.classList.add('st-menu-button');const label=b.textContent;b.replaceChildren();const text=node('span',null,'st-menu-button-text');text.append(node('span',label,'st-menu-button-title'));const copy={csProfile:'Your player record',csHallOfFame:'Legends of the battlefield',csRegister:'Join the ranks',csLogin:'Return to your account'}[b.id];if(copy)text.append(node('span',copy,'st-menu-button-copy'));if(['csProfile','csHallOfFame'].includes(b.id)){const layout=node('span',null,'st-menu-button-layout');const icon=node(b.id==='csProfile'?'img':'span',null,'st-menu-icon'+(b.id==='csHallOfFame'?' cs-menu-award':''));if(b.id==='csProfile'){icon.src='/'+(avatarById(account?.avatarId)||avatarById(DEFAULT_AVATAR)).assetPath;icon.alt='';}else icon.setAttribute('aria-hidden','true');layout.append(icon,text);b.append(layout);}else b.append(text);}
}
