import {AVATARS} from '../assets/avatars/catalog.mjs';
// Online entry only. Placement, rematch, seat recovery and combat stay in their accepted controllers.
export function installOnlineEntry(session,enter){
 const by=id=>document.getElementById(id),link=document.createElement('link');link.rel='stylesheet';link.href='styles-online-entry.css';document.head.append(link);
 const panel=document.createElement('div');panel.id='stLanLobby';panel.className='st-mp-overlay';panel.hidden=true;
 panel.innerHTML=`<section class="st-mp-dialog st-frame cs-entry" role="dialog" aria-modal="true" aria-labelledby="stLanTitle"><header><small>CHAIN SIEGE</small><h2 id="stLanTitle">ONLINE GAME</h2><p>Create a battlefield or join a waiting game.</p></header><div class="st-mp-tabs" role="tablist" aria-label="Online game"><button id="stLanCreateTab" role="tab">CREATE GAME</button><button id="stLanJoinTab" role="tab">JOIN GAME</button></div><form id="stLanForm"><div id="csEntryCreate"><div id="csEntrySeats"></div><fieldset id="csEntryVisibility"><legend>Room access</legend><button type="button" data-visibility="public" aria-pressed="true">PUBLIC</button><button type="button" data-visibility="private" aria-pressed="false">PRIVATE</button><p id="csAccessHelp">Anyone can join from the game list.</p></fieldset><p id="csEntryFormat"></p></div><div id="stLanCodeField" hidden><label for="stLanCode">Game code (6 characters)</label><input id="stLanCode" maxlength="64" autocapitalize="characters" autocomplete="off" spellcheck="false"><p id="csPrivatePrompt" hidden>Private game — enter its code to join.</p><button id="csCancelPrivate" type="button" hidden>Cancel private selection</button></div><div class="st-mp-actions"><button id="stLanMake" class="st-btn" type="submit">CREATE GAME</button><button id="stLanJoin" class="st-btn" type="submit" hidden>JOIN</button><button id="stLanClose" class="st-btn" type="button">MAIN MENU</button></div></form><p id="stLanMessage" role="status" aria-live="polite"></p><section id="stLanGames"><h3 id="csGamesTitle">AVAILABLE GAMES</h3><div id="stLanGamesList"></div></section><section id="csOnlineHome" hidden><h3>MULTIPLAYER</h3><p>Create or join an online battlefield.</p><button id="csOnlineReturn" class="st-btn">CREATE / JOIN GAME</button><button id="csOnlineMain" class="st-btn">MAIN MENU</button></section></section>`;document.body.append(panel);
 let mode='make',visibility='public',slots=['human','human','empty','empty'],identity=null,busy=false,listBusy=false,selectedRoom=null,games=[],home=false;
 const errors={'bad-game-code':'Game not found, or the code does not match this private game.','game-full':'This game is full.','already-seated':'You already have a seat in this game.','invalid-configuration':'Check the room setup.','lan-disabled':'Launch using PLAYTEST-LAN.cmd.'};
 const message=e=>errors[e?.code||e?.message]||'Connection unavailable. Please try again.';
 function controls(){for(const id of ['stLanMake','stLanJoin'])by(id).disabled=busy||!identity;}
 function seatCards(){const list=by('csEntrySeats');list.replaceChildren();slots.forEach((value,i)=>{const card=document.createElement('article');card.className='cs-entry-seat';card.dataset.seat=String(i);const heading=document.createElement('h3');heading.textContent='SEAT '+(i+1)+(i===0?' · HOST':'');card.append(heading);const who=document.createElement('p');who.textContent=i===0?'Room creator':value==='human'?'Waiting for a player':value==='ai'?'Random unique NPC':'Not participating';card.append(who);if(i===0){const avatar=identity?.avatarSrc||AVATARS.find(a=>a.id===identity?.avatarId)?.assetPath;if(avatar){const img=document.createElement('img');img.src=avatar;img.alt='';card.prepend(img);}const input=document.createElement('input');input.id='stLanName';input.readOnly=true;input.setAttribute('aria-label','Registered or Guest display name');input.value=identity?.displayName||'';card.append(input);}if(i<2){const fixed=document.createElement('strong');fixed.textContent='PLAYER';card.append(fixed);}else{const group=document.createElement('div');group.className='cs-seat-options';for(const option of ['human','ai','empty']){const button=document.createElement('button');button.type='button';button.textContent=option==='human'?'PLAYER':option.toUpperCase();button.dataset.option=option;button.setAttribute('aria-pressed',String(value===option));button.onclick=()=>{slots[i]=option;seatCards();};group.append(button);}card.append(group);}list.append(card);});const n=slots.filter(x=>x!=='empty').length;by('csEntryFormat').textContent=n===2?'DUEL · 2 players':n+'-PLAYER GROUP';}
 function select(next){mode=next;home=false;by('csOnlineHome').hidden=true;by('stLanForm').hidden=false;panel.querySelector('.st-mp-tabs').hidden=false;by('stLanGames').hidden=false;by('csEntryCreate').hidden=mode!=='make';by('stLanCodeField').hidden=mode!=='join';by('stLanCode').required=mode==='join';by('stLanMake').hidden=mode!=='make';by('stLanJoin').hidden=mode!=='join';by('stLanCreateTab').setAttribute('aria-selected',String(mode==='make'));by('stLanJoinTab').setAttribute('aria-selected',String(mode==='join'));by('csGamesTitle').textContent='AVAILABLE GAMES';renderGames();void refreshGames();}
 function clearSelection(){selectedRoom=null;by('csPrivatePrompt').hidden=true;by('csCancelPrivate').hidden=true;}
 by('csCancelPrivate').onclick=clearSelection;
 by('stLanCreateTab').onclick=()=>{clearSelection();select('make');};by('stLanJoinTab').onclick=()=>{clearSelection();select('join');};
 for(const b of panel.querySelectorAll('[data-visibility]'))b.onclick=()=>{visibility=b.dataset.visibility;for(const x of panel.querySelectorAll('[data-visibility]'))x.setAttribute('aria-pressed',String(x===b));by('csAccessHelp').textContent=visibility==='private'?'Listed as private. Players need your game code.':'Anyone can join from the game list.';};
 function onlineHome(){home=true;document.body.classList.add('st-main-menu-mode');by('stLanForm').hidden=true;panel.querySelector('.st-mp-tabs').hidden=true;by('stLanGames').hidden=true;by('stLanMessage').textContent='';by('csOnlineHome').hidden=false;}
 by('stLanClose').onclick=()=>{home=true;clearSelection();document.body.classList.add('st-main-menu-mode');panel.hidden=true;};by('csOnlineReturn').onclick=()=>select(mode);by('csOnlineMain').onclick=()=>{document.body.classList.add('st-main-menu-mode');panel.hidden=true;};
 async function submit(code){if(busy||!identity)return;busy=true;controls();by('stLanMessage').textContent=mode==='make'?'Creating game…':'Joining game…';try{await session.request('pvp/'+mode,mode==='make'?{slots:[...slots],visibility}:{code:(code||by('stLanCode').value).trim().toUpperCase(),...(selectedRoom?{roomId:selectedRoom}:{})});clearSelection();await enter();}catch(e){by('stLanMessage').textContent=message(e);await refreshGames();}finally{busy=false;controls();}}
 by('stLanForm').onsubmit=e=>{e.preventDefault();void submit();};
 function renderGames(){const list=by('stLanGamesList');list.replaceChildren();const visible=games.filter(g=>mode==='join'||!g.full);if(!visible.length){list.textContent=mode==='make'?'No open games.':'No waiting games.';return;}for(const g of visible){const row=document.createElement('div');row.className='cs-game-row';row.dataset.roomId=g.roomId;const info=document.createElement('div'),name=document.createElement('strong'),details=document.createElement('span');name.textContent=g.creator;details.textContent=g.type+' · '+g.occupied+'/'+g.seats+' occupied · '+(g.visibility==='private'?'🔒 Private':'Public');info.append(name,details);const status=document.createElement('span');status.className=g.full?'cs-full':'cs-open';status.textContent=g.full?'● FULL':'● OPEN';const join=document.createElement('button');join.className='st-btn';join.textContent=g.full?'FULL':'JOIN';join.disabled=g.full;join.onclick=()=>{select('join');clearSelection();if(g.visibility==='private'){selectedRoom=g.roomId;by('stLanCode').value='';by('csPrivatePrompt').hidden=false;by('csCancelPrivate').hidden=false;by('stLanCode').focus();}else{by('stLanCode').value=g.code;void submit(g.code);}};row.append(info,status,join);list.append(row);}}
 async function refreshGames(){if(listBusy||panel.hidden||home)return;listBusy=true;try{({games}=await session.request('pvp/list'));renderGames();}catch(e){by('stLanGamesList').textContent=message(e);}finally{listBusy=false;}}
 async function showSetup(error){panel.hidden=false;document.body.classList.add('st-main-menu-mode');select(mode);identity=null;controls();try{({identity}=await session.request('pvp/identity'));seatCards();by('stLanMessage').textContent=error?message(error):'';}catch(e){by('stLanMessage').textContent=message(e);}controls();await refreshGames();}
 seatCards();controls();select('make');return {panel,showSetup,refreshGames};
}
