import {avatarBadges,medalArt} from './avatar-badges.js';
import {renderReliability} from './reliability-bar.js';
import {AVATARS} from '../assets/avatars/catalog.mjs';
import {buildResultScreen} from './result-screen.js';
import {mountReplayViewer} from './replay-viewer.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const awardNames=['Lucky Shooter','The Blind One','Eagle Eye','Most Fierce','Chain Master','Purple Death'];
const badgeTiers=[{at:50,name:'Bronze',style:'bronze'},{at:150,name:'Silver',style:'silver'},{at:300,name:'Gold',style:'gold'},{at:500,name:'Platinum',style:'platinum'}];
export function awardProgress(count){const earned=badgeTiers.filter(t=>count>=t.at).at(-1)||null,next=badgeTiers.find(t=>count<t.at)||null;return {earned,next,label:next?count+' / '+next.at:count+' / 500'};}
const awardDescriptions=['Longest hit streak in a battle.','Longest miss streak in a battle.','Highest accuracy, with at least 5 shots and 1 hit.','Most units destroyed in a battle.','Largest chain in a battle.','Most Plague cells in a battle.'];
const badgeInfo=(name,i,count)=>{const p=awardProgress(count);return name+' — '+awardDescriptions[i]+' Bronze: 50; Silver: 150; Gold: 300; Platinum: 500. '+(p.earned?p.earned.name+' badge earned. ':'No badge earned yet. ')+(p.next?'Progress: '+p.label+' toward '+p.next.name+'.':count+' awards. Highest tier reached.');};
const number=n=>n===null||n===undefined?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
const percent=n=>n===null||n===undefined?'Unrated':Number(n).toFixed(1).replace(/\.0$/, '')+'%';
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
const labels={lifetimeScore:'Lifetime Score',averageScore:'Average Match Score',highestScore:'Highest Match Score',millennial:'The Millennial',games:'Games',wins:'Wins',losses:'Losses',draws:'Draws',winRate:'Win Rate',rewards:'Result Rewards',shots:'Shots',hits:'Hits',misses:'Misses',unitsKilled:'Units destroyed',coreKills:'Core kills',heroHits:'Hero hits',plagueCells:'Plague cells',scoutInspected:'Scouted cells',scoutFound:'Units found scouting',destructiveCells:'Cells struck',unitCellsHit:'Unit cells struck',castleCatapultHits:'Catapult Castle hits',elvesKilled:'Elves destroyed',dragonsActivated:'Dragons activated',perfectVolleys:'Perfect volleys',monkDeflections:'Monk deflections',resurrections:'Resurrections',dwarfHits:'Dwarf hits',wizardHits:'Wizard hits',wizardAttackHits:'Wizard attack hits',goblinBombs:'Goblin bombs',demonKills:'Demons destroyed',biggestChain:'Best Chain',hitRate:'Hit Rate'};
export function installProfile({api,onAccount,editAccount}){
 const css=el('link');css.rel='stylesheet';css.href='/styles-profile.css';document.head.append(css);
 const dialog=el('dialog',undefined,'cs-profile');dialog.id='csProfileWindow';dialog.setAttribute('aria-label','Player Profile');document.body.append(dialog);
 let data=null,tab='PROFILE',page=0,sub=0,generation=0,returnTab='BATTLES',savedOverflow='',replayCleanup=null;
 const compact=()=>innerWidth<700||innerHeight<650;
 const close=()=>{generation++;replayCleanup?.();replayCleanup=null;dialog.close();document.documentElement.style.overflow=savedOverflow;};
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 function show(){if(!dialog.open){savedOverflow=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';dialog.showModal();}}
 function shell(title){dialog.classList.remove('cp-with-tabs');replayCleanup?.();replayCleanup=null;dialog.replaceChildren();const header=el('header',undefined,'cp-header');header.append(el('div','CHAIN SIEGE','cp-kicker'),el('h1',title),button('CLOSE',close));dialog.append(header);const body=el('main',undefined,'cp-body');dialog.append(body);return body;}
 function status(error){const body=shell('PROFILE');body.append(el('p',error.message||String(error)),button('TRY AGAIN',()=>open(data?.identity.playerId)));}
 async function open(playerId){dialog.classList.remove('cp-card');show();shell('PROFILE').append(el('p','Loading player…'));const ticket=++generation;try{const next=await api('profile-view',playerId?{playerId}:{});if(ticket!==generation||!dialog.open)return;data=next;tab='PROFILE';page=0;sub=0;render();}catch(e){if(ticket===generation)status(e);}}
 function pager(parent,index,total,change){if(total<=1)return;const nav=el('nav',undefined,'cp-pager');nav.setAttribute('aria-label','Pages');const prev=button('PREVIOUS',()=>change(index-1)),next=button('NEXT',()=>change(index+1));prev.disabled=index===0;next.disabled=index>=total-1;nav.append(prev,el('span',(index+1)+' / '+total),next);parent.append(nav);}
 function tiles(parent,entries){const grid=el('dl',undefined,'cp-tiles');for(const [label,value]of entries){const cell=el('div');cell.append(el('dt',label),el('dd',value));grid.append(cell);}parent.append(grid);}
 function identity(parent,editable=false){const section=el('section',undefined,'cp-identity'),art=el('div',undefined,'cp-avatar-wrap'),img=el('img');img.src='/'+data.identity.avatar;img.alt=data.identity.displayName;art.append(img);avatarBadges(art,data.rewards);const text=el('div');text.append(el('h2',data.identity.displayName+(data.moderationNotice?.kind==='WARNING'?' — WARNING':data.moderationNotice?.kind==='FLAG'?' — FLAGGED':'')));if(data.moderationNotice)text.querySelector('h2').title='Look in your profile for more info.';if(data.moderationNotice)text.append(el('p',(data.moderationNotice.kind==='WARNING'?'Warning: ':'FLAGGED — public scores hidden: ')+data.moderationNotice.reason,'cp-moderation-notice'));if(/^[A-Z]{2}$/.test(data.identity.country)){const flag=el('img',undefined,'cp-flag');flag.src='/assets/ui/flags/'+data.identity.country.toLowerCase()+'.svg';flag.alt=data.identity.country;text.append(flag);}text.append(el('p',data.identity.bio||'No biography yet.','cp-bio'));if(editable)text.append(button('EDIT PROFILE',()=>{editAccount();}));section.append(art,text);parent.append(section);}
 function battleRows(parent,battles,savedList=false){const list=el('div',undefined,'cp-battles');if(!battles.length)list.append(el('p','No finalized battles yet.'));for(const b of battles){const row=el('article',undefined,'cp-battle');row.append(el('strong',new Date(b.date).toLocaleDateString()+' · '+b.mode+' · '+b.format),el('span',b.outcome+(b.placement?' · #'+b.placement:'')+' · Score '+number(b.score)),el('span',b.participants.map(p=>p.name+(p.ai?' (AI)':'')).join(' · '),'cp-participants'));if(data.owner){const actions=el('div',undefined,'cp-row-actions');if(b.resultAvailable)actions.append(button('RESULT',()=>historical(b.matchId)));else actions.append(el('span','Result unavailable / partial'));if(b.replayAvailable)actions.append(button('REPLAY',()=>replay(b.matchId)));else actions.append(el('span','Replay unavailable'));if(b.resultAvailable&&b.replayAvailable){const save=button(b.saved?'SAVED':'SAVE BATTLE',()=>saveBattle(b.matchId,save));save.disabled=!!b.saved;actions.append(save);}if(savedList){const remove=button('DELETE',()=>deleteBattle(b.matchId,remove));actions.append(remove);}row.append(actions);}list.append(row);}parent.append(list);}
 function reliabilityBar(parent){const bar=el('section',undefined,'cp-reliability');renderReliability(bar,data.reliability);bar.querySelector('.cs-reliability-title').textContent=(data.owner?'YOUR ONLINE RELIABILITY':'ONLINE RELIABILITY')+' — '+(data.reliability.percent===null?'UNRATED':Number(data.reliability.percent).toFixed(1).replace(/\.0$/, '')+'%');parent.append(bar);}
 function connections(parent){parent.append(el('h2','YOUR CHAINEST FRIENDS'));const friends=data.coplayers.slice(0,5);if(!friends.length)parent.append(el('p','No shared registered-player battles yet.'));for(const [index,friend] of friends.entries()){const row=el('div',undefined,'cp-friend');row.append(el('span','#'+(index+1),'cp-friend-rank'));if(/^[A-Z]{2}$/.test(friend.country||'')){const flag=el('img');flag.src='/assets/ui/flags/'+friend.country.toLowerCase()+'.svg';flag.alt=friend.country;row.append(flag);}const name=button(friend.name,()=>open(friend.playerId));name.className='cp-friend-link';row.append(name,el('span',friend.battles+' battles together'));parent.append(row);}}
 function awardCounts(parent){const box=el('section',undefined,'cp-award-counts');box.append(el('h2','BATTLE AWARDS'),el('p','Bronze 50 · Silver 150 · Gold 300 · Platinum 500','cp-award-note'));const grid=el('div',undefined,'cp-award-grid');for(const [i,name] of awardNames.entries()){const row=el('div',undefined,'cp-award-count'),icon=el('span',undefined,'cs-medal');medalArt(icon,i);icon.setAttribute('aria-hidden','true');icon.dataset.tier=awardProgress(data.rewards[name]||0).earned?.style||'locked';row.title=badgeInfo(name,i,data.rewards[name]||0);row.tabIndex=0;row.setAttribute('aria-label',row.title);row.append(icon,el('span',name),el('strong',awardProgress(data.rewards[name]||0).label));grid.append(row);}box.append(grid);if(data.rewardCoverage.available<data.rewardCoverage.total)box.append(el('p','Known awards from retained battle records.','cp-award-note'));parent.append(box);}
 function savedBattles(parent){parent.append(el('h2','SAVED BATTLES '+data.saved.length+'/10'));if(!data.saved.length)parent.append(el('p','No saved battles yet.'));else battleRows(parent,data.saved,true);}
 function streakBox(parent){if(data.streak){const box=el('section',undefined,'cp-streak');box.append(el('h2','DAILY STREAK'));const current=el('div',undefined,'cp-streak-current');current.append(el('strong',String(data.streak.current)),el('span',data.streak.current===1?'DAY RUNNING':'DAYS RUNNING'));const records=el('div',undefined,'cp-streak-records');for(const [label,value]of [['PERSONAL BEST',data.streak.highest],['GLOBAL RECORD',data.streak.global]]){const item=el('div');item.append(el('span',label),el('strong',value+(value===1?' day':' days')));records.append(item);}box.append(current,records);parent.append(box);}}

 async function refreshSavedBattles(control){const current=data;const updated=await api('profile-view',{});if(data!==current)return;data.saved=updated.saved;data.recent=updated.recent;control.textContent='SAVED';control.disabled=true;if(dialog.querySelector('.cp-tabs')){const scroll=dialog.querySelector('.cp-body')?.scrollTop||0;render();dialog.querySelector('.cp-body').scrollTop=scroll;}}
 async function deleteBattle(matchId,control){const confirm=el('dialog',undefined,'cp-save-confirm');confirm.append(el('h2','Delete this saved battle?'),el('p','This removes it from your Saved Battles. Your battle history and statistics are kept.'),button('DELETE',async()=>{confirm.close();confirm.remove();control.disabled=true;try{await api('delete-saved-battle',{matchId});await refreshSavedBattles(control);}catch(e){control.disabled=false;control.textContent=e.message;}}),button('CANCEL',()=>{confirm.close();confirm.remove();}));confirm.addEventListener('cancel',()=>confirm.remove());document.body.append(confirm);confirm.showModal();}
 async function saveBattle(matchId,control){control.disabled=true;try{let r=await api('save-battle',{matchId});if(r.full){const confirm=el('dialog',undefined,'cp-save-confirm');confirm.append(el('h2','You have reached maximum number of saved battles.'),button('SAVE AND DELETE OLDEST',async()=>{confirm.close();confirm.remove();try{await api('save-battle',{matchId,replaceOldest:true});await refreshSavedBattles(control);}catch(e){control.disabled=false;control.textContent=e.message;}}),button('CANCEL',()=>{confirm.close();confirm.remove();control.disabled=false;}));confirm.addEventListener('cancel',()=>{control.disabled=false;confirm.remove();});document.body.append(confirm);confirm.showModal();return;}await refreshSavedBattles(control);}catch(e){control.disabled=false;control.textContent=e.message;}}
 function render(){const body=shell(data.identity.displayName),nav=el('nav',undefined,'cp-tabs');nav.setAttribute('aria-label','Profile views');for(const t of ['PROFILE','BATTLES']){const b=button(t==='BATTLES'?(data.owner?'SAVED BATTLES '+data.saved.length+'/10':'RECENT BATTLES'):t,()=>{tab=t;page=0;sub=0;render();});b.setAttribute('aria-current',String(tab===t));nav.append(b);}body.before(nav);dialog.classList.add('cp-with-tabs');
  if(tab==='PROFILE'){
   const entries=Object.entries(data.core).map(([k,v])=>k==='draws'?['biggestChain',data.statistics.find(g=>g.title==='Overall')?.biggestChain??0]:[k,v]).map(([k,v])=>[k==='rewards'&&data.rewardCoverage.available<data.rewardCoverage.total?'Known Result Rewards':labels[k],k==='winRate'?percent(v):number(v)]);
   if(compact()){const names=['Identity','Career','Recent five','Connections'];body.append(el('h2',names[sub]));if(sub===0){identity(body,data.owner);streakBox(body);reliabilityBar(body);tiles(body,entries.slice(0,4));}if(sub===1)tiles(body,entries.slice(4));if(sub===2)battleRows(body,data.recent);if(sub===3){connections(body);awardCounts(body);}pager(dialog,sub,names.length,n=>{sub=n;render();});}
   else {const columns=el('div',undefined,'cp-overview'),left=el('section'),right=el('section');const intro=el('div',undefined,'cp-profile-intro');identity(intro,data.owner);streakBox(intro);left.append(intro);reliabilityBar(left);tiles(left,entries.filter(([label])=>!['Result Rewards','Known Result Rewards'].includes(label)));right.append(el('h2','RECENT FIVE BATTLES'));battleRows(right,data.recent);const c=el('div',undefined,'cp-connections');const friends=el('section');for(const [label,value] of entries.filter(([label])=>['Result Rewards','Known Result Rewards'].includes(label)))left.append(el('p',label+': '+value,'cp-awards-total'));connections(friends);c.append(friends);awardCounts(c);left.append(c);columns.append(left,right);body.append(columns);}
  }else if(tab==='BATTLES'){if(data.owner)savedBattles(body);else{body.append(el('h2','RECENT BATTLES'));battleRows(body,data.recent);}}
  else if(tab==='HALL OF FAME'){const size=compact()?3:6;for(const h of data.hof.slice(page*size,(page+1)*size)){const row=el('article',undefined,'cp-rank');row.append(el('h2',h.title),el('p',h.mode+' · '+(h.rank===null?(h.status==='not-qualified'?'10 full games or finish Story Mode required':h.status==='no-metric'?'Metric unavailable':'No finalized games'):'#'+h.rank+' · '+number(h.value))));body.append(row);}pager(dialog,page,Math.ceil(data.hof.length/size),n=>{page=n;render();});}
  else statistics(body);
 }
 function statistics(body){const categories=[...data.statistics.map(g=>g.title),'Result Rewards','Co-players','Reliability','PLAYER vs AI'];const select=el('select');select.setAttribute('aria-label','Statistics category');categories.forEach((c,i)=>{const o=el('option',c);o.value=i;select.append(o);});select.value=page;select.onchange=()=>{page=+select.value;sub=0;render();};body.append(select);const title=categories[page];body.append(el('h2',title));let entries=[];
  if(page<data.statistics.length){const g=data.statistics[page];entries=Object.entries(g).filter(([k,v])=>k!=='title'&&k!=='placements'&&(typeof v==='number'||v===null)).map(([k,v])=>[labels[k]||k,['winRate','hitRate'].includes(k)?percent(v):number(v)]);for(const [place,count]of Object.entries(g.placements))entries.push(['Placement #'+place,number(count)]);}
  else if(title==='Result Rewards'){entries=Object.entries(data.rewards);body.append(el('p','Canonical recipients, including ties. Available for '+data.rewardCoverage.available+' / '+data.rewardCoverage.total+' battles.'));if(!entries.length)body.append(el('p','No retained Result Rewards.'));}
  else if(title==='Co-players'){entries=data.coplayers.map(p=>[p.name,p.battles+' battles']);if(!entries.length)body.append(el('p','No registered co-players yet.'));}
  else if(title==='Reliability'){const r=data.reliability;entries=[['Reliability',percent(r.percent)],['Rated online games',number(r.games)]];if(data.owner){entries.push(['Finished',number(r.finished)],['Disconnect yellow cards',number(r.disconnect)],['Outstanding AFK cards',number(r.outstandingAFK)],['Forgiven AFK',number(r.forgivenAFK)],['AFK Recovery',r.cleanStreak+' / 10']);body.append(el('p',r.gamesUntilForgiveness===null?'No outstanding AFK cards.':'You need '+r.gamesUntilForgiveness+' more full games to remove one AFK card.'));}}
  else {const f=data.factions;entries=[['PLAYER faction score',number(f.playerScore)],['AI faction score',number(f.aiScore)],['Qualifying global matches',number(f.qualifyingMatchCount)]];body.append(el('p','Global faction totals; separate from your personal Match Score.'));}
  const size=compact()?6:12;tiles(body,entries.slice(sub*size,(sub+1)*size));pager(dialog,sub,Math.ceil(entries.length/size),n=>{sub=n;render();});
 }
 async function edit(){const body=shell('EDIT PROFILE');const bio=el('textarea');bio.value=data.identity.bio;bio.maxLength=280;bio.setAttribute('aria-label','Public biography');const status=el('p','', 'cp-status');body.append(el('label','Public biography (280 characters)'),bio,button('SAVE BIO',async()=>{try{const r=await api('profile',{bio:bio.value});onAccount(r.account);await open(data.identity.playerId);}catch(e){status.textContent=e.message;}}),button('CHOOSE AVATAR',()=>avatarPage(0)),button('ACCOUNT SETTINGS',()=>{editAccount();}),status,button('BACK TO PROFILE',render));}
 function avatarPage(index){const body=shell('CHOOSE AVATAR'),avatars=AVATARS.filter(a=>['peasant','hero'].includes(a.access)),size=compact()?6:12,grid=el('div',undefined,'cp-avatar-grid'),status=el('p','Hero portraits unlock after finishing Story or winning five games.');for(const a of avatars.slice(index*size,(index+1)*size)){const b=button('',async()=>{try{b.disabled=true;const r=await api('avatar',{avatarId:a.id});onAccount(r.account);await open(data.identity.playerId);}catch(e){status.textContent=e.message;b.disabled=false;}}),img=el('img');img.src='/'+a.assetPath;img.alt=a.group+' '+a.id.split('-').at(-1);b.append(img);b.disabled=a.access==='hero'&&!data.avatarUnlocked;grid.append(b);}body.append(grid,status,button('BACK',edit));pager(dialog,index,Math.ceil(avatars.length/size),avatarPage);}
 async function historical(matchId){returnTab=tab;const ticket=++generation;const body=shell('STORED RESULT');body.append(el('p','Loading retained Result…'));try{const result=await api('profile-view',{playerId:data.identity.playerId,section:'result',matchId});if(ticket!==generation||!body.isConnected)return;body.replaceChildren();const panel=buildResultScreen(result,{historical:true,back:()=>{tab=returnTab;render();}});panel.classList.add('cp-historical');const save=button(data.saved.some(s=>s.matchId===matchId)?'SAVED':'SAVE BATTLE',()=>saveBattle(matchId,save));save.disabled=data.saved.some(s=>s.matchId===matchId);panel.querySelector('.cs-result-actions').prepend(save);body.append(panel);}catch(e){if(body.isConnected)body.replaceChildren(el('p',e.message),button('BACK',render));}}
 async function replay(matchId){const ticket=++generation,body=shell('STORED REPLAY');try{const r=await api('profile-view',{playerId:data.identity.playerId,section:'replay',matchId});if(ticket!==generation||!body.isConnected)return;body.append(button('BACK TO PROFILE',()=>{tab='PROFILE';render();}));const slot=el('div',undefined,'cp-replay-slot');body.append(slot);const viewer=mountReplayViewer(slot,r);let board=0;const choose=()=>{const boards=slot.querySelectorAll('.cs-replay-board');boards.forEach((b,i)=>b.hidden=Math.floor(i/2)!==board);};const observer=new MutationObserver(choose);observer.observe(slot.querySelector('.cs-replay-boards'),{childList:true});choose();pager(body,board,Math.ceil(r.participants.length/2),n=>{board=n;body.querySelector('.cp-pager')?.remove();choose();drawPager();});function drawPager(){pager(body,board,Math.ceil(r.participants.length/2),n=>{board=n;body.querySelector('.cp-pager')?.remove();choose();drawPager();});}replayCleanup=()=>{observer.disconnect();viewer.unmount();};}catch(e){if(body.isConnected)body.append(el('p',e.message),button('BACK',render));}}
 async function card(playerId){show();const ticket=++generation,body=shell('PLAYER CARD');try{const r=await api('profile-view',{playerId});if(ticket!==generation||!body.isConnected)return;data=r;dialog.classList.add('cp-card');identity(body);tiles(body,[['Games',number(r.core.games)],['Win Rate',percent(r.core.winRate)],['Average Match Score',number(r.core.averageScore)],['Reliability',percent(r.reliability.percent)],[r.rewardCoverage.available<r.rewardCoverage.total?'Known Result Rewards':'Result Rewards',number(r.core.rewards)]]);body.append(button('VIEW PROFILE',()=>{dialog.classList.remove('cp-card');open(playerId);}));}catch(e){if(body.isConnected)body.append(el('p',e.message));}}
 dialog.addEventListener('close',()=>dialog.classList.remove('cp-card'));
 document.addEventListener('click',e=>{const target=e.target.closest('[data-profile-id]');if(!target)return;e.preventDefault();e.stopPropagation();void card(target.dataset.profileId);},true);
 document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const target=e.target.closest('[data-profile-id]');if(target){e.preventDefault();void card(target.dataset.profileId);}},true);
 window.addEventListener('resize',()=>{if(dialog.open&&data&&dialog.querySelector('.cp-tabs')){sub=0;page=0;render();}});
 return {open};
}
