import {AVATARS} from '../assets/avatars/catalog.mjs';
import {buildResultScreen} from './result-screen.js';
import {mountReplayViewer} from './replay-viewer.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const number=n=>n===null||n===undefined?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
const percent=n=>n===null||n===undefined?'Unrated':number(n)+'%';
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
const labels={lifetimeScore:'Lifetime Score',averageScore:'Average Match Score',highestScore:'Highest Match Score',millennial:'The Millennial',games:'Games',wins:'Wins',losses:'Losses',draws:'Draws',winRate:'Win Rate',rewards:'Result Rewards',shots:'Shots',hits:'Hits',misses:'Misses',unitsKilled:'Units destroyed',coreKills:'Core kills',heroHits:'Hero hits',plagueCells:'Plague cells',scoutInspected:'Scouted cells',scoutFound:'Units found scouting',destructiveCells:'Cells struck',unitCellsHit:'Unit cells struck',castleCatapultHits:'Catapult Castle hits',elvesKilled:'Elves destroyed',dragonsActivated:'Dragons activated',perfectVolleys:'Perfect volleys',monkDeflections:'Monk deflections',resurrections:'Resurrections',dwarfHits:'Dwarf hits',wizardHits:'Wizard hits',wizardAttackHits:'Wizard attack hits',goblinBombs:'Goblin bombs',demonKills:'Demons destroyed',biggestChain:'Biggest Chain',hitRate:'Hit Rate'};
export function installProfile({api,onAccount,editAccount}){
 const css=el('link');css.rel='stylesheet';css.href='/styles-profile.css';document.head.append(css);
 const dialog=el('dialog',undefined,'cs-profile');dialog.id='csProfileWindow';dialog.setAttribute('aria-label','Player Profile');document.body.append(dialog);
 let data=null,tab='PROFILE',page=0,sub=0,generation=0,returnTab='BATTLES',savedOverflow='',replayCleanup=null;
 const compact=()=>innerWidth<700||innerHeight<650;
 const close=()=>{generation++;replayCleanup?.();replayCleanup=null;dialog.close();document.documentElement.style.overflow=savedOverflow;};
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 function show(){if(!dialog.open){savedOverflow=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';dialog.showModal();}}
 function shell(title){dialog.classList.remove('cp-with-tabs');replayCleanup?.();replayCleanup=null;dialog.replaceChildren();const header=el('header',undefined,'cp-header');header.append(el('div','CHAIN SIEGE','cp-kicker'),el('h1',title),button('CLOSE',close));dialog.append(header);const body=el('main',undefined,'cp-body');dialog.append(body);return body;}
 function status(error){const body=shell('PROFILE');body.append(el('p',error.message||String(error)),button('TRY AGAIN',()=>open(data?.identity.playerId)));}
 async function open(playerId){dialog.classList.remove('cp-card');show();shell('PROFILE').append(el('p','Loading player…'));const ticket=++generation;try{const next=await api('profile-view',playerId?{playerId}:{});if(ticket!==generation||!dialog.open)return;data=next;tab='PROFILE';page=0;sub=0;render();}catch(e){if(ticket===generation)status(e);}}
 function pager(parent,index,total,change){if(total<=1)return;const nav=el('nav',undefined,'cp-pager');nav.setAttribute('aria-label','Pages');const prev=button('PREVIOUS',()=>change(index-1)),next=button('NEXT',()=>change(index+1));prev.disabled=index===0;next.disabled=index>=total-1;nav.append(prev,el('span',(index+1)+' / '+total),next);parent.append(nav);}
 function tiles(parent,entries){const grid=el('dl',undefined,'cp-tiles');for(const [label,value]of entries){const cell=el('div');cell.append(el('dt',label),el('dd',value));grid.append(cell);}parent.append(grid);}
 function identity(parent,editable=false){const section=el('section',undefined,'cp-identity'),art=el('div',undefined,'cp-avatar-wrap'),img=el('img');img.src='/'+data.identity.avatar;img.alt=data.identity.displayName;art.append(img);const badges=el('div',undefined,'cp-badges');badges.setAttribute('aria-label','Six reserved badge positions');for(let i=0;i<6;i++)badges.append(el('span'));art.append(badges);const text=el('div');text.append(el('h2',data.identity.displayName));if(/^[A-Z]{2}$/.test(data.identity.country)){const flag=el('img',undefined,'cp-flag');flag.src='/assets/ui/flags/'+data.identity.country.toLowerCase()+'.svg';flag.alt=data.identity.country;text.append(flag);}text.append(el('p',data.identity.bio||'No biography yet.','cp-bio'));if(editable)text.append(button('EDIT AVATAR / BIO',edit));section.append(art,text);parent.append(section);}
 function battleRows(parent,battles){const list=el('div',undefined,'cp-battles');if(!battles.length)list.append(el('p','No finalized battles yet.'));for(const b of battles){const row=el('article',undefined,'cp-battle');row.append(el('strong',new Date(b.date).toLocaleDateString()+' · '+b.mode+' · '+b.format),el('span',b.outcome+(b.placement?' · #'+b.placement:'')+' · Score '+number(b.score)),el('span',b.participants.map(p=>p.name+(p.ai?' (AI)':'')).join(' · '),'cp-participants'));if(data.owner){const actions=el('div',undefined,'cp-row-actions');if(b.resultAvailable)actions.append(button('RESULT',()=>historical(b.matchId)));else actions.append(el('span','Result unavailable / partial'));if(b.replayAvailable)actions.append(button('REPLAY',()=>replay(b.matchId)));else actions.append(el('span','Replay unavailable'));row.append(actions);}list.append(row);}parent.append(list);}
 function connections(parent){parent.append(el('h2','YOUR CHAINEST FRIEND'));if(data.friend){parent.append(button(data.friend.name,()=>card(data.friend.playerId)),el('p',data.friend.battles+' battles together'));}else parent.append(el('p','No shared registered-player battles yet.'));parent.append(el('h2','HALL OF FAME'));const best=data.hof.filter(h=>h.rank!==null).sort((a,b)=>a.rank-b.rank||a.title.localeCompare(b.title)||a.mode.localeCompare(b.mode)).slice(0,3);for(const h of best)parent.append(el('p',h.title+' · '+h.mode+' — #'+h.rank));if(!best.length)parent.append(el('p','No qualified ranks yet.'));parent.append(button('VIEW ALL',()=>{tab='HALL OF FAME';page=0;render();}));}
 function render(){const body=shell(data.identity.displayName),nav=el('nav',undefined,'cp-tabs');nav.setAttribute('aria-label','Profile views');for(const t of ['PROFILE','BATTLES','HALL OF FAME','STATISTICS']){const b=button(t==='STATISTICS'&&data.owner?'YOUR STATISTICS':t,()=>{tab=t;page=0;sub=0;render();});b.setAttribute('aria-current',String(tab===t));nav.append(b);}body.before(nav);dialog.classList.add('cp-with-tabs');
  if(tab==='PROFILE'){
   const entries=Object.entries(data.core).map(([k,v])=>[k==='rewards'&&data.rewardCoverage.available<data.rewardCoverage.total?'Known Result Rewards':labels[k],k==='winRate'?percent(v):number(v)]);entries.push(['Reliability',percent(data.reliability.percent)]);
   if(compact()){const names=['Identity','Career','Recent five','Connections'];body.append(el('h2',names[sub]));if(sub===0){identity(body,data.owner);tiles(body,entries.slice(0,4));}if(sub===1)tiles(body,entries.slice(4));if(sub===2)battleRows(body,data.recent);if(sub===3)connections(body);pager(dialog,sub,4,n=>{sub=n;render();});}
   else {const columns=el('div',undefined,'cp-overview'),left=el('section'),right=el('section');identity(left,data.owner);tiles(left,entries);right.append(el('h2','RECENT FIVE BATTLES'));battleRows(right,data.recent);const c=el('div',undefined,'cp-connections');connections(c);left.append(c);columns.append(left,right);body.append(columns);}
  }else if(tab==='BATTLES'){body.append(el('h2',data.owner?'BATTLE HISTORY':'RECENT BATTLES'));const ticket=++generation;api('profile-view',{playerId:data.identity.playerId,section:'battles',page}).then(r=>{if(ticket!==generation||!body.isConnected)return;battleRows(body,r.battles);pager(dialog,r.page,r.pages,n=>{page=n;render();});}).catch(e=>{if(body.isConnected)body.append(el('p',e.message));});}
  else if(tab==='HALL OF FAME'){const size=compact()?3:6;for(const h of data.hof.slice(page*size,(page+1)*size)){const row=el('article',undefined,'cp-rank');row.append(el('h2',h.title),el('p',h.mode+' · '+(h.rank===null?(h.status==='not-qualified'?'10 Full games required':h.status==='no-metric'?'Metric unavailable':'No finalized games'):'#'+h.rank+' · '+number(h.value))));body.append(row);}pager(dialog,page,Math.ceil(data.hof.length/size),n=>{page=n;render();});}
  else statistics(body);
 }
 function statistics(body){const categories=[...data.statistics.map(g=>g.title),'Result Rewards','Co-players','Reliability','PLAYER vs AI'];const select=el('select');select.setAttribute('aria-label','Statistics category');categories.forEach((c,i)=>{const o=el('option',c);o.value=i;select.append(o);});select.value=page;select.onchange=()=>{page=+select.value;sub=0;render();};body.append(select);const title=categories[page];body.append(el('h2',title));let entries=[];
  if(page<data.statistics.length){const g=data.statistics[page];entries=Object.entries(g).filter(([k,v])=>k!=='title'&&k!=='placements'&&(typeof v==='number'||v===null)).map(([k,v])=>[labels[k]||k,['winRate','hitRate'].includes(k)?percent(v):number(v)]);for(const [place,count]of Object.entries(g.placements))entries.push(['Placement #'+place,number(count)]);}
  else if(title==='Result Rewards'){entries=Object.entries(data.rewards);body.append(el('p','Canonical recipients, including ties. Available for '+data.rewardCoverage.available+' / '+data.rewardCoverage.total+' battles.'));if(!entries.length)body.append(el('p','No retained Result Rewards.'));}
  else if(title==='Co-players'){entries=data.coplayers.map(p=>[p.name,p.battles+' battles']);if(!entries.length)body.append(el('p','No registered co-players yet.'));}
  else if(title==='Reliability'){const r=data.reliability;entries=[['Reliability',percent(r.percent)],['Rated online games',number(r.games)]];if(data.owner){entries.push(['Finished',number(r.finished)],['Disconnect yellow cards',number(r.disconnect)],['Outstanding AFK cards',number(r.outstandingAFK)],['Forgiven AFK',number(r.forgivenAFK)],['AFK Recovery',r.cleanStreak+' / 10']);body.append(el('p',r.gamesUntilForgiveness===null?'No outstanding AFK cards.':'You need '+r.gamesUntilForgiveness+' more full games to remove one AFK card.'));}}
  else {const f=data.factions;entries=[['PLAYER faction score',number(f.playerScore)],['AI faction score',number(f.aiScore)],['Qualifying global matches',number(f.qualifyingMatchCount)]];body.append(el('p','Global faction totals; separate from your personal Match Score.'));}
  const size=compact()?6:12;tiles(body,entries.slice(sub*size,(sub+1)*size));pager(dialog,sub,Math.ceil(entries.length/size),n=>{sub=n;render();});
 }
 async function edit(){const body=shell('EDIT PROFILE');const bio=el('textarea');bio.value=data.identity.bio;bio.maxLength=280;bio.setAttribute('aria-label','Public biography');const status=el('p','', 'cp-status');body.append(el('label','Public biography (280 characters)'),bio,button('SAVE BIO',async()=>{try{const r=await api('profile',{bio:bio.value});onAccount(r.account);await open(data.identity.playerId);}catch(e){status.textContent=e.message;}}),button('CHOOSE AVATAR',()=>avatarPage(0)),button('ACCOUNT SETTINGS',()=>{close();editAccount();}),status,button('BACK TO PROFILE',render));}
 function avatarPage(index){const body=shell('CHOOSE AVATAR'),avatars=AVATARS.filter(a=>['peasant','hero'].includes(a.access)),size=compact()?6:12,grid=el('div',undefined,'cp-avatar-grid'),status=el('p','Hero portraits unlock after finishing Story or winning five games.');for(const a of avatars.slice(index*size,(index+1)*size)){const b=button('',async()=>{try{b.disabled=true;const r=await api('avatar',{avatarId:a.id});onAccount(r.account);await open(data.identity.playerId);}catch(e){status.textContent=e.message;b.disabled=false;}}),img=el('img');img.src='/'+a.assetPath;img.alt=a.group+' '+a.id.split('-').at(-1);b.append(img);b.disabled=a.access==='hero'&&!data.avatarUnlocked;grid.append(b);}body.append(grid,status,button('BACK',edit));pager(dialog,index,Math.ceil(avatars.length/size),avatarPage);}
 async function historical(matchId){returnTab=tab;const ticket=++generation;const body=shell('STORED RESULT');body.append(el('p','Loading retained Result…'));try{const result=await api('profile-view',{playerId:data.identity.playerId,section:'result',matchId});if(ticket!==generation||!body.isConnected)return;body.replaceChildren(el('p','Read-only Result · portraits show current account appearance.'));let resultPage=0;const draw=()=>{body.querySelector('.cs-results')?.remove();body.querySelector('.cp-pager')?.remove();const panel=buildResultScreen(result,{historical:true,back:()=>{tab=returnTab;render();}});panel.classList.add('cp-historical');panel.dataset.page=String(resultPage);body.append(panel);pager(body,resultPage,2,n=>{resultPage=n;draw();});};draw();}catch(e){if(body.isConnected)body.replaceChildren(el('p',e.message),button('BACK',render));}}
 async function replay(matchId){const ticket=++generation,body=shell('STORED REPLAY');try{const r=await api('profile-view',{playerId:data.identity.playerId,section:'replay',matchId});if(ticket!==generation||!body.isConnected)return;body.append(button('BACK TO BATTLES',()=>{tab='BATTLES';render();}));const slot=el('div',undefined,'cp-replay-slot');body.append(slot);const viewer=mountReplayViewer(slot,r);let board=0;const choose=()=>{const boards=slot.querySelectorAll('.cs-replay-board');boards.forEach((b,i)=>b.hidden=i!==board);};const observer=new MutationObserver(choose);observer.observe(slot.querySelector('.cs-replay-boards'),{childList:true});choose();pager(body,board,r.participants.length,n=>{board=n;body.querySelector('.cp-pager')?.remove();choose();drawPager();});function drawPager(){pager(body,board,r.participants.length,n=>{board=n;body.querySelector('.cp-pager')?.remove();choose();drawPager();});}replayCleanup=()=>{observer.disconnect();viewer.unmount();};}catch(e){if(body.isConnected)body.append(el('p',e.message),button('BACK',render));}}
 async function card(playerId){show();const ticket=++generation,body=shell('PLAYER CARD');try{const r=await api('profile-view',{playerId});if(ticket!==generation||!body.isConnected)return;data=r;dialog.classList.add('cp-card');identity(body);tiles(body,[['Games',number(r.core.games)],['Win Rate',percent(r.core.winRate)],['Average Match Score',number(r.core.averageScore)],['Reliability',percent(r.reliability.percent)],[r.rewardCoverage.available<r.rewardCoverage.total?'Known Result Rewards':'Result Rewards',number(r.core.rewards)]]);body.append(button('VIEW PROFILE',()=>{dialog.classList.remove('cp-card');open(playerId);}));}catch(e){if(body.isConnected)body.append(el('p',e.message));}}
 dialog.addEventListener('close',()=>dialog.classList.remove('cp-card'));
 document.addEventListener('click',e=>{const target=e.target.closest('[data-profile-id]');if(!target)return;e.preventDefault();e.stopPropagation();void card(target.dataset.profileId);},true);
 document.addEventListener('keydown',e=>{if(!['Enter',' '].includes(e.key))return;const target=e.target.closest('[data-profile-id]');if(target){e.preventDefault();void card(target.dataset.profileId);}},true);
 window.addEventListener('resize',()=>{if(dialog.open&&data&&dialog.querySelector('.cp-tabs')){sub=0;page=0;render();}});
 return {open};
}
