import {setStoryAccount} from './story-account.js';
// Registry is an optional account layer. It never supplies match commands or seat credentials.
const SKIP='chainSiege.registry.guestSkip.v1';let statisticsEnabled=false;let account=null,pending=null,ready=false,bypass=false,streakMessage='';
const css=document.createElement('link');css.rel='stylesheet';css.href='/styles-registry.css';document.head.append(css);
const bar=document.createElement('div');bar.id='csAccountBar';bar.className='cs-account-bar';document.querySelector('#stMainMenu .st-menu-frame').append(bar);
const dialog=document.createElement('dialog');dialog.id='csRegistryDialog';dialog.setAttribute('aria-label','Chain Siege account');document.body.append(dialog);
const el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text)n.textContent=text;Object.assign(n,attrs);return n;};
const button=(text,fn,id)=>{const b=el('button',text,{type:'button'});if(id)b.id=id;b.onclick=fn;return b;};
let countries=[];const countryCodes='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' '),regionNames=new Intl.DisplayNames(['en'],{type:'region'});countries=countryCodes.map(code=>[code,regionNames.of(code)]).sort((a,b)=>a[1].localeCompare(b[1]));
async function api(action,body={}){const r=await fetch('/api/registry/'+action,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),value=await r.json();if(!r.ok){if(r.status===401){account=null;streakMessage='';paint();}throw Object.assign(Error(value.error||'Account request failed.'),{status:r.status});}return value;}
function paint(){void setStoryAccount(account).catch(error=>{document.getElementById('status').textContent=error.message;});bar.replaceChildren();if(account){bar.append(el('span',account.displayName),button('PROFILE',()=>show('profile'),'csProfile'),button('LOGOUT',async()=>{try{await api('logout');account=null;streakMessage='';paint();}catch(e){showError(e.message);}},'csLogout'));if(streakMessage)bar.append(el('span',streakMessage));}else bar.append(button('REGISTER',()=>show('register'),'csRegister'),button('LOGIN',()=>show('login'),'csLogin'));if(statisticsEnabled)bar.append(button('TEST STATISTICS',showStatistics,'csStatistics'));}
function close(){dialog.close();dialog.replaceChildren();}
function resume(){const target=pending;pending=null;close();if(target){bypass=true;try{target.click();}finally{bypass=false;}}}
function showError(text){show('message',text);}
function field(form,label,name,type='text',value='',required=true){const wrap=el('label',label),input=el('input',null,{name,type,value,required});input.id='cs-'+name;wrap.append(input);form.append(wrap);return input;}
function countryField(form,value){const label=el('label','Nationality'),select=el('select',null,{name:'country',required:true});select.id='cs-country';select.append(el('option','Select your country',{value:''}));for(const[code,name]of countries)select.append(el('option',name,{value:code}));select.value=value||'';label.append(select);form.append(label);return select;}
function show(mode,message){dialog.replaceChildren();const title=el('h2',mode==='guest'?'Play as Guest':mode==='profile'?'Your profile':mode==='register'?'Register — Chain Siege':mode==='login'?'Log in — Chain Siege':'Account');dialog.append(title);
 if(mode==='guest'){dialog.append(el('p','Guest players do not participate in Hall of Fame or career statistics.'));const actions=el('div',null,{className:'cs-actions'});actions.append(button('REGISTER',()=>show('register')),button('LOGIN',()=>show('login')),button('SKIP',()=>{try{localStorage.setItem(SKIP,'1');}catch{}resume();},'csGuestSkip'));dialog.append(actions);}
 else if(mode==='message'){dialog.append(el('p',message),button('CLOSE',close));}
 else {const form=el('form'),status=el('p','',{className:'cs-status'});status.setAttribute('role','status');dialog.append(form);const profile=mode==='profile',register=mode==='register';
 if(profile){form.append(el('p','Username: '+account.username+' (permanent)'));const name=field(form,'Display name','displayName','text',account.displayName);name.maxLength=14;if(account.gamesUntilNameChange>0){name.disabled=true;form.append(el('p',`You need to fully play ${account.gamesUntilNameChange} more games to change your name.`));}else form.append(el('p',account.displayNameChanges===0?'You have one free display-name change.':'Your next display-name change is available.'));
 const co=countryField(form,account.country);co.disabled=account.countryChanges>=1;form.append(el('p',account.countryChanges>=1?'Nationality is permanent now.':'You can change nationality once after registration.'));const confirm=field(form,'I understand: after changing nationality, it cannot be changed again.','confirmCountryChange','checkbox','',false);confirm.closest('label').hidden=true;co.onchange=()=>{confirm.closest('label').hidden=co.value===account.country;confirm.required=co.value!==account.country;};
 const bioLabel=el('label','Public profile bio (plain text, up to 280 characters)'),bio=el('textarea',null,{name:'bio',value:account.bio,maxLength:280});bio.id='cs-bio';bioLabel.append(bio);form.append(bioLabel);field(form,'Email (optional)','email','email',account.email,false);form.append(el('p','Used for password and account recovery. Verification and recovery delivery are not available yet.'),el('p',`You have a ${account.currentStreak}-day streak! Your record is ${account.longestStreak} days. Days use UTC.`),el('p','Avatar selection is coming later. Unlock rule: Finish Story OR win 5 games.'));
 }else{const name=field(form,'Username','username');name.maxLength=14;name.autocomplete='username';form.append(el('p','3–14 letters or numbers. International letters are welcome. Username is permanent.'));const pass=field(form,'Password','password','password');pass.autocomplete=register?'new-password':'current-password';pass.maxLength=256;
 if(register){form.append(el('p','At least 8 characters, including uppercase, lowercase and a number.'));field(form,'Confirm Password','confirmPassword','password').autocomplete='new-password';field(form,'Email (optional)','email','email','',false);form.append(el('p','Used for password and account recovery. Verification and recovery delivery are not available yet.'));countryField(form);const trap=field(form,'Leave empty','website','text','',false);trap.tabIndex=-1;trap.autocomplete='off';trap.closest('label').className='cs-honeypot';trap.closest('label').setAttribute('aria-hidden','true');const question=field(form,'Loading human check…','answer');question.inputMode='numeric';const id=field(form,'','challengeId','hidden');id.closest('label').hidden=true;api('challenge').then(c=>{question.closest('label').firstChild.textContent=c.question;id.value=c.id;}).catch(e=>status.textContent=e.message);}}
 const submit=el('button',profile?'SAVE':register?'REGISTER':'LOGIN',{type:'submit'});submit.id='csAccountSubmit';form.append(status,submit,button('CANCEL',()=>{pending=null;close();}));
 form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;status.textContent='Saving…';try{const data=Object.fromEntries(new FormData(form));if(profile)data.confirmCountryChange=form.elements.confirmCountryChange.checked;const result=await api(profile?'profile':mode,data);account=result.account;streakMessage=result.newDay?`You have a ${account.currentStreak}-day streak! Your record is ${account.longestStreak} days.`:'';paint();if(profile){show('profile');dialog.querySelector('.cs-status').textContent='Saved.';}else{resume();}}catch(error){if(profile&&error.status===401){show('login');dialog.querySelector('.cs-status').textContent=error.message;return;}status.textContent=error.message;if(register){try{const c=await api('challenge');form.elements.challengeId.value=c.id;const answer=form.elements.answer;answer.value='';answer.closest('label').firstChild.textContent=c.question;}catch{}}}finally{submit.disabled=false;}};
 }
 if(!dialog.open)dialog.showModal();}
function skipped(){try{return localStorage.getItem(SKIP)==='1';}catch{return false;}}
const loaded=api('me').then(r=>{statisticsEnabled=!!r.statisticsInspector;account=r.account;if(r.newDay&&account)streakMessage=`You have a ${account.currentStreak}-day streak! Your record is ${account.longestStreak} days.`;}).catch(()=>{account=null;}).finally(()=>{ready=true;paint();});paint();
window.addEventListener('click',e=>{const target=e.target.closest?.('#stMenuFull,#stMenuOnline');if(!target||bypass)return;if(ready&&(account||skipped()))return;e.preventDefault();e.stopImmediatePropagation();pending=target;loaded.then(()=>{if(account||skipped())resume();else show('guest');});},true);
dialog.addEventListener('cancel',()=>{pending=null;});

async function showStatistics(){
 dialog.replaceChildren(el('h2','Playtest statistics — read only'));const body=el('div');dialog.append(body,button('REFRESH',refresh),button('CLOSE',close));if(!dialog.open)dialog.showModal();await refresh();
 async function refresh(){body.replaceChildren(el('p','Loading…'));try{const data=await api('statistics');body.replaceChildren(el('p','Finalized matches only. AI has no career or global Human credit. Scores are not calculated.'),el('h3','Global counters'),el('pre',JSON.stringify(data.global,null,2)));if(!data.modes.length)body.append(el('p','No finalized registered matches yet. Guests contribute global counters only.'));for(const mode of data.modes){const details=el('details'),title=el('summary',mode.mode);details.append(title,el('pre',JSON.stringify(mode,null,2)));body.append(details);}}catch(e){body.replaceChildren(el('p',e.message));}}
}
