import './options-ui.js';
import {renderReliability} from './reliability-bar.js';
import {installMainMenu,arrangeMenuAccount} from './main-menu.js';
import {installProfile} from './profile.js';
import {DEFAULT_AVATAR} from '../assets/avatars/catalog.mjs';
import {avatarControl} from './avatar-picker.js';
import {installHallOfFame} from './hall-of-fame.js';
import {setStoryAccount} from './story-account.js';
// Registry is an optional account layer. It never supplies match commands or seat credentials.
const SKIP='chainSiege.registry.guestSkip.v1';let statisticsEnabled=false;let account=null,pending=null,ready=false,bypass=false,streakMessage='';
const css=document.createElement('link');css.rel='stylesheet';css.href='/styles-registry.css';document.head.append(css);
const bar=document.createElement('div');bar.id='csAccountBar';bar.className='cs-account-bar';document.querySelector('#stMainMenu .st-menu-frame').append(bar);
installMainMenu(bar);
const dialog=document.createElement('dialog');dialog.id='csRegistryDialog';dialog.setAttribute('aria-label','Chain Siege account');document.body.append(dialog);
const el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text)n.textContent=text;Object.assign(n,attrs);return n;};
const button=(text,fn,id)=>{const b=el('button',text,{type:'button'});if(id)b.id=id;b.onclick=fn;return b;};
let countries=[];const countryCodes='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' '),regionNames=new Intl.DisplayNames(['en'],{type:'region'});countries=countryCodes.map(code=>[code,regionNames.of(code)]).sort((a,b)=>a[1].localeCompare(b[1]));
async function api(action,body={}){const r=await fetch('/api/registry/'+action,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),value=await r.json();if(!r.ok){if(r.status===401){account=null;streakMessage='';paint();}throw Object.assign(Error(value.error||'Account request failed.'),{status:r.status});}return value;}
function paint(){void setStoryAccount(account).catch(error=>{document.getElementById('status').textContent=error.message;});bar.replaceChildren();if(account){bar.append(el('span',account.displayName),button('PROFILE',()=>profileUI.open(),'csProfile'),button('LOGOUT',async()=>{try{await api('logout');account=null;streakMessage='';paint();}catch(e){showError(e.message);}},'csLogout'));if(streakMessage)bar.append(el('span',streakMessage));}else bar.append(button('REGISTER',()=>show('register'),'csRegister'),button('LOGIN',()=>show('login'),'csLogin'));installHallOfFame(bar);arrangeMenuAccount(bar,account);}
function close(){dialog.close();dialog.replaceChildren();}
function resume(){const target=pending;pending=null;close();if(target){bypass=true;try{target.click();}finally{bypass=false;}}}
function showError(text){show('message',text);}
function field(form,label,name,type='text',value='',required=true){const wrap=el('label',label),input=el('input',null,{name,type,value,required});input.id='cs-'+name;wrap.append(input);form.append(wrap);return input;}
function countryField(form,value){const label=el('label','Nationality'),select=el('select',null,{name:'country',required:true});select.id='cs-country';select.append(el('option','Select your country',{value:''}));for(const[code,name]of countries)select.append(el('option',name,{value:code}));select.value=value||'';label.append(select);form.append(label);return select;}
const registrationMessages=new Set(['Use 3â€“14 letters or numbers, without surrounding spaces.','Use 3â€“14 letters or numbers.','Password needs 8+ characters, uppercase, lowercase and a number (maximum 256).','Enter a valid optional email.','Select a country.','Avatar is not available for this account.','Too many attempts. Please try again later.','Please try again shortly.','Human check failed. Please try a new question.','Passwords do not match.','Username is already taken.','Display name is already taken.']);
const registrationError=error=>registrationMessages.has(error.message)?error.message:'Unable to create your account right now. Please try again.';
function polishRegistration(form,status,submit){
 const hints=[...form.querySelectorAll(':scope > p')].filter(p=>p!==status),wrap=name=>form.elements[name].closest('label');
 const layout=el('div',null,{className:'cs-register-columns'}),details=el('section',null,{className:'cs-register-section'}),banner=el('section',null,{className:'cs-register-section'});layout.append(details,banner);form.append(layout);
 details.append(el('h3','ACCOUNT DETAILS'),wrap('username'),hints[0],wrap('password'),hints[1],wrap('confirmPassword'),wrap('email'),hints[2]);
 hints.forEach((hint,i)=>{hint.className='cs-register-help';hint.id='cs-register-help-'+i;});form.elements.username.setAttribute('aria-describedby',hints[0].id);form.elements.password.setAttribute('aria-describedby',hints[1].id);form.elements.email.setAttribute('aria-describedby',hints[2].id);
 const avatar=form.querySelector('.cs-avatar-current');banner.append(el('h3','YOUR BANNER'),avatar,wrap('country'));
 const flag=el('img',null,{className:'cs-register-flag',alt:''}),country=form.elements.country;flag.hidden=true;wrap('country').insertBefore(flag,country);
 country.addEventListener('change',()=>{flag.hidden=!country.value;if(country.value){flag.src='/assets/ui/flags/'+country.value.toLowerCase()+'.svg';flag.alt=regionNames.of(country.value);}});
 const check=el('div',null,{className:'cs-register-check'});check.append(el('h3','HUMAN CHECK'),wrap('answer'));banner.append(check);
 const actions=el('div',null,{className:'cs-register-actions'}),cancel=[...form.querySelectorAll('button')].find(b=>b.textContent==='CANCEL');submit.textContent='CREATE ACCOUNT';actions.append(submit,cancel);form.append(status,actions);
 status.id='cs-register-status';status.setAttribute('role','alert');status.setAttribute('aria-live','polite');
 const confirm=form.elements.confirmPassword,password=form.elements.password;
 const match=()=>confirm.setCustomValidity(confirm.value&&confirm.value!==password.value?'Passwords do not match.':'');confirm.addEventListener('input',match);password.addEventListener('input',match);
 form.addEventListener('invalid',e=>{e.target.setAttribute('aria-invalid','true');status.textContent=e.target.validity.valueMissing?'Please complete the required fields.':e.target.validationMessage;},true);
 form.addEventListener('input',e=>{if(e.target.checkValidity?.()){e.target.removeAttribute('aria-invalid');status.textContent='';}});
}
function polishAccountSettings(form,status,submit){
 const paragraphs=[...form.querySelectorAll(':scope > p')].filter(p=>p!==status),wrap=name=>form.elements[name].closest('label');
 const grid=el('div',null,{className:'cs-account-columns'}),identity=el('section'),details=el('section');
 identity.append(el('h3','PLAYER IDENTITY'),form.querySelector('.cs-avatar-current'),paragraphs[1],wrap('displayName'),paragraphs[2],wrap('country'),paragraphs[3],wrap('confirmCountryChange'));
 details.append(el('h3','ABOUT YOU'),wrap('bio'),wrap('email'),paragraphs[4],paragraphs[5]);grid.append(identity,details);
 paragraphs[0].className='cs-account-reliability';const actions=el('div',null,{className:'cs-account-actions'});actions.append(submit,[...form.querySelectorAll('button')].find(b=>b.textContent==='CANCEL'));form.append(paragraphs[0],grid,status,actions);
}
function show(mode,message){dialog.dataset.mode=mode;dialog.replaceChildren();const title=el('h2',mode==='guest'?'Play as Guest':mode==='profile'?'EDIT PROFILE':mode==='register'?'Register â€” Chain Siege':mode==='login'?'Log in â€” Chain Siege':'Account');dialog.append(title);if(mode==='register'){title.textContent='CREATE YOUR ACCOUNT';dialog.insertBefore(el('p','CHAIN SIEGE',{className:'cs-register-kicker'}),title);}
 if(mode==='guest'){dialog.append(el('p','Guest players do not participate in Hall of Fame or career statistics.'));const actions=el('div',null,{className:'cs-actions'});actions.append(button('REGISTER',()=>show('register')),button('LOGIN',()=>show('login')),button('SKIP',()=>{try{localStorage.setItem(SKIP,'1');}catch{}resume();},'csGuestSkip'));dialog.append(actions);}
 else if(mode==='message'){dialog.append(el('p',message),button('CLOSE',close));}
 else {const form=el('form'),status=el('p','',{className:'cs-status'});status.setAttribute('role','status');dialog.append(form);const profile=mode==='profile',register=mode==='register';
 if(profile){const owner=account.playerId;const reliability=el('p','Loading Online Player Reliabilityâ€¦');form.append(reliability);api('reliability').then(r=>{if(!reliability.isConnected||account?.playerId!==owner)return;renderReliability(reliability,r);}).catch(()=>{reliability.textContent='Online Player Reliability unavailable.';});form.append(avatarControl({value:account.avatarId,unlocked:account.avatarUnlocked,onSelect:async avatarId=>{const r=await api('avatar',{avatarId});if(account?.playerId!==owner)throw Error('Account changed. Reopen Profile.');account=r.account;}}));form.append(el('p','Username: '+account.username+' (permanent)'));const name=field(form,'Display name','displayName','text',account.displayName);name.maxLength=14;if(account.gamesUntilNameChange>0){name.disabled=true;form.append(el('p',`You need to fully play ${account.gamesUntilNameChange} more games to change your name.`));}else form.append(el('p',account.displayNameChanges===0?'You have one free display-name change.':'Your next display-name change is available.'));
 const co=countryField(form,account.country);co.disabled=account.countryChanges>=1;form.append(el('p',account.countryChanges>=1?'Nationality is permanent now.':'You can change nationality once after registration.'));const confirm=field(form,'I understand: after changing nationality, it cannot be changed again.','confirmCountryChange','checkbox','',false);confirm.closest('label').hidden=true;co.onchange=()=>{confirm.closest('label').hidden=co.value===account.country;confirm.required=co.value!==account.country;};
 const bioLabel=el('label','Public profile bio (plain text, up to 280 characters)'),bio=el('textarea',null,{name:'bio',value:account.bio,maxLength:280});bio.id='cs-bio';bioLabel.append(bio);form.append(bioLabel);field(form,'Email (optional)','email','email',account.email,false);form.append(el('p','Used for password and account recovery. Verification and recovery delivery are not available yet.'),el('p',`You have a ${account.currentStreak}-day streak! Your record is ${account.longestStreak} days. Days use UTC.`));
 }else{const name=field(form,'Username','username');name.maxLength=14;name.autocomplete='username';form.append(el('p','3â€“14 letters or numbers. International letters are welcome. Username is permanent.'));const pass=field(form,'Password','password','password');pass.autocomplete=register?'new-password':'current-password';pass.maxLength=256;
 if(register){const avatar=field(form,'','avatarId','hidden',DEFAULT_AVATAR);avatar.closest('label').hidden=true;form.append(avatarControl({value:avatar.value,onSelect:async id=>{avatar.value=id;}}));form.append(el('p','At least 8 characters, including uppercase, lowercase and a number.'));field(form,'Confirm Password','confirmPassword','password').autocomplete='new-password';field(form,'Email (optional)','email','email','',false);form.append(el('p','Used for password and account recovery. Verification and recovery delivery are not available yet.'));countryField(form);const trap=field(form,'Leave empty','website','text','',false);trap.tabIndex=-1;trap.autocomplete='off';trap.closest('label').className='cs-honeypot';trap.closest('label').setAttribute('aria-hidden','true');const question=field(form,'Loading human checkâ€¦','answer');question.inputMode='numeric';const id=field(form,'','challengeId','hidden');id.closest('label').hidden=true;api('challenge').then(c=>{question.closest('label').firstChild.textContent=c.question;id.value=c.id;}).catch(()=>status.textContent='Unable to load the human check. Please reopen Register and try again.');}}
 const submit=el('button',profile?'SAVE':register?'REGISTER':'LOGIN',{type:'submit'});submit.id='csAccountSubmit';form.append(status,submit,button('CANCEL',()=>{pending=null;close();}));if(register)polishRegistration(form,status,submit);if(profile)polishAccountSettings(form,status,submit);
 form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;status.textContent=register?'Creating your accountâ€¦':'Savingâ€¦';try{const data=Object.fromEntries(new FormData(form));if(profile)data.confirmCountryChange=form.elements.confirmCountryChange.checked;const result=await api(profile?'profile':mode,data);account=result.account;streakMessage=result.newDay?`You have a ${account.currentStreak}-day streak! Your record is ${account.longestStreak} days.`:'';paint();if(profile){show('profile');dialog.querySelector('.cs-status').textContent='Saved.';}else{resume();}}catch(error){if(profile&&error.status===401){show('login');dialog.querySelector('.cs-status').textContent=error.message;return;}status.textContent=register?registrationError(error):error.message;if(register){try{const c=await api('challenge');form.elements.challengeId.value=c.id;const answer=form.elements.answer;answer.value='';answer.closest('label').firstChild.textContent=c.question;}catch{}}}finally{submit.disabled=false;}};
 }
 if(!dialog.open)dialog.showModal();}
function skipped(){try{return localStorage.getItem(SKIP)==='1';}catch{return false;}}
const loaded=api('me').then(r=>{statisticsEnabled=!!r.statisticsInspector;account=r.account;if(r.newDay&&account)streakMessage=`You have a ${account.currentStreak}-day streak! Your record is ${account.longestStreak} days.`;}).catch(()=>{account=null;}).finally(()=>{ready=true;paint();});paint();
// Read-only presentation view of the existing authoritative /me response.
export const startupAccount=loaded.then(()=>account?{displayName:account.displayName}:null);
window.addEventListener('click',e=>{const target=e.target.closest?.('#stMenuFull,#stMenuOnline');if(!target||bypass)return;if(ready&&(account||skipped()))return;e.preventDefault();e.stopImmediatePropagation();pending=target;loaded.then(()=>{if(account||skipped())resume();else show('guest');});},true);
dialog.addEventListener('cancel',()=>{pending=null;});

async function showStatistics(){
 dialog.dataset.mode='statistics';dialog.replaceChildren(el('h2','Playtest statistics â€” read only'));const body=el('div');dialog.append(body,button('REFRESH',refresh),button('CLOSE',close));if(!dialog.open)dialog.showModal();await refresh();
 async function refresh(){body.replaceChildren(el('p','Loadingâ€¦'));try{const data=await api('statistics');body.replaceChildren(el('p','Finalized matches only. AI has no career or global Human credit. Scores are not calculated.'),el('h3','Global counters'),el('pre',JSON.stringify(Object.fromEntries([['PLAYER SHOTS','playerShots'],['CELLS HIT','cellsHit'],['UNIT CELLS HIT','unitCellsHit'],['PLAGUE CELLS','plagueCells'],['SCOUTED CELLS','scoutedCells']].map(([label,key])=>[label,data.global[key]??0])),null,2)));if(!data.modes.length)body.append(el('p','No finalized registered matches yet. Guests contribute global counters only.'));for(const mode of data.modes){const details=el('details'),title=el('summary',mode.mode);details.append(title,el('pre',JSON.stringify(mode,null,2)));body.append(details);}}catch(e){body.replaceChildren(el('p',e.message));}}
}

dialog.addEventListener('close',()=>{if(dialog.dataset.mode==='profile')void profileUI.open();});
const profileUI=installProfile({api,editAccount:()=>show('profile'),onAccount:value=>{account=value;paint();}});

// Only the authenticated owner endpoint carries manual REVIEW status.
const reviewDialog=document.createElement('dialog');reviewDialog.id='csReviewNotice';reviewDialog.setAttribute('aria-labelledby','csReviewNoticeTitle');document.body.append(reviewDialog);
let acknowledgedReview=null;
async function refreshReviewNotice(){try{const {notice,playerId}=await api('review-notice');const noticeKey=playerId+':'+notice?.revision;if(!notice){acknowledgedReview=null;if(reviewDialog.open)reviewDialog.close();return;}if(acknowledgedReview===noticeKey||reviewDialog.open||document.querySelector('dialog[open]'))return;
 reviewDialog.replaceChildren(el('h2','YOUR ACCOUNT IS UNDER REVIEW',{id:'csReviewNoticeTitle'}),el('p','Unusual gameplay patterns have been detected on your account.'),el('p','You may continue playing normally, but new leaderboard scores will be held until the review is complete.'),el('p','No scores will be lost while the review is pending.'),button('OK',()=>{acknowledgedReview=noticeKey;reviewDialog.close();}));reviewDialog.oncancel=()=>{acknowledgedReview=noticeKey;};reviewDialog.showModal();}catch{/* Optional notice must never block gameplay. */}}
loaded.then(refreshReviewNotice);setInterval(()=>{if(!document.hidden)void refreshReviewNotice();},15000);
