// Public-only disconnect/rejoin presentation. No gameplay RNG or authority imports.
import {logEvent} from './game-log.js';
export const clockText=ms=>{const seconds=Math.ceil(Math.abs(ms)/1000);return (ms<0?'-':'')+Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');};
function styles(){if(!document.querySelector('link[href="styles-multiplayer.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='styles-multiplayer.css';document.head.append(l);}}
export function newsflash(event){logEvent('NEWSFLASH START',{kind:event.kind,seat:event.seat});document.querySelectorAll('.st-mp-newsflash').forEach(e=>e.remove());const el=document.createElement('aside');el.className='st-mp-newsflash';el.setAttribute('role','status');const title=document.createElement('div');title.className='st-sales-title';title.textContent=event.name.toUpperCase()+(event.kind==='disconnected'?' DISCONNECTED!':event.kind==='rejoined'?' REJOINED!':event.kind==='rematch'?' WANTS A REMATCH!':event.reason==='connection'?' IS HAVING CONNECTION DIFFICULTIES!':event.reason==='surrender'?' HAS SURRENDERED!':' LEFT!');el.append(title);if(event.replacement){const line=document.createElement('div');line.className='st-sales-line';line.textContent=event.replacement[0].toUpperCase()+event.replacement.slice(1)+' takes over the battle.';el.append(line);}const host=document.getElementById('stEnemyGridHost'),layer=host?.closest('.st-board-wrap')||host;if(layer&&host.getBoundingClientRect().width){const h=host.getBoundingClientRect(),l=layer.getBoundingClientRect();el.style.position='absolute';el.style.left=(h.left-l.left+h.width/2)+'px';el.style.top=(h.top-l.top+h.height*.25)+'px';el.style.width=h.width+'px';layer.append(el);}else document.body.append(el);setTimeout(()=>{el.remove();logEvent('NEWSFLASH END',{kind:event.kind,seat:event.seat});},4000);}
function popup(id){styles();const box=document.createElement('div');box.id=id;box.className='st-mp-overlay';box.innerHTML='<section class="st-mp-dialog st-frame" role="dialog" aria-modal="true"><h2></h2><p class="st-mp-clock" role="timer"></p><div class="st-mp-actions"></div><p class="st-mp-error" role="alert"></p></section>';document.body.append(box);return box;}
function button(box,text,id,action){const b=document.createElement('button');b.className='st-btn';b.id=id;b.textContent=text;b.onclick=action;box.querySelector('.st-mp-actions').append(b);return b;}
export async function resolveReturn(session,opened){if(!opened.returning)return opened;document.getElementById('stLoadingScreen')?.remove();document.body.classList.add('st-main-menu-mode');const box=popup('stRejoinDialog');let info=opened.rejoin,at=Date.now(),pending=false,polling=false,generation=0,ended=false,timer=null;
 return new Promise(resolve=>{const done=out=>{ended=true;clearInterval(timer);box.remove();resolve(out);};const run=async action=>{if(pending||ended)return;pending=true;generation++;try{if(action==='rejoin'){const out=await session.request('pvp/rejoin',{battle:info.battle,episode:info.episode});done(out);}else{if(action==='surrender'){const out=await session.request('pvp/surrender',{battle:info.battle,episode:info.episode});}else await session.request('pvp/dismiss-return');done(await session.open());}}catch(e){box.querySelector('.st-mp-error').textContent=e.code==='stale'?'The game changed. Please try again.':'Unable to rejoin. Please try again.';try{info=(await session.request('pvp/return-status')).rejoin;at=Date.now();paint();}catch{}}finally{pending=false;}};
 function paint(){if(!info.available)clearInterval(timer);box.querySelector('h2').textContent=info.available?'Welcome back! Hurry and rejoin your game!':"Awww, snap! You were kicked from your last battle and can't rejoin.";box.querySelector('.st-mp-clock').textContent=info.available&&info.remainingMs!==null?clockText(info.remainingMs-(Date.now()-at))+' remaining':'';let detail=box.querySelector('.st-takeover-detail'),helper=box.querySelector('.st-takeover-helper');if(!info.available){if(!detail){detail=document.createElement('p');detail.className='st-takeover-detail';box.querySelector('.st-mp-clock').after(detail);helper=document.createElement('p');helper.className='st-takeover-helper';box.querySelector('.st-mp-actions').before(helper);}detail.textContent=(info.replacement||'AI')+' has taken over the battle.';helper.textContent='Going offline or surrendering may restrict your choices online.';}const actions=box.querySelector('.st-mp-actions');const mode=info.available?'available':'taken';if(actions.dataset.mode===mode)return;actions.dataset.mode=mode;actions.replaceChildren();if(info.available){button(box,'REJOIN','stRejoin',()=>run('rejoin'));button(box,'I GIVE UP','stRejoinGiveUp',()=>run('surrender'));}else button(box,'OH WELL THEN','stRejoinDismiss',()=>run('dismiss'));}
 // Background status must never consume a REJOIN / I GIVE UP click. Discard replies predating a user action.
 paint();if(info.available)timer=setInterval(async()=>{paint();if(pending||polling||ended)return;polling=true;const version=generation;try{const out=await session.request('pvp/return-status');if(!ended&&version===generation&&out.rejoin){info=out.rejoin;at=Date.now();paint();}}catch{if(!ended&&version===generation)box.querySelector('.st-mp-error').textContent='Connection unavailable. Waiting to rejoin…';}finally{polling=false;}},500);
 });}
export function mountDisconnect(session){const box=popup('stDisconnectDialog');box.hidden=true;let meta,last,at=Date.now(),episode=null,dismissed=null,busy=false,seen=0,battle=null,queued=[];
 async function choose(action){if(busy)return;busy=true;try{const a=meta.presence[1-meta.self];const out=await session.request('pvp/disconnect-policy',{battle:last.battle,episode:a.episode,action});observe(out.lan,out.snapshot);}catch(e){box.querySelector('.st-mp-error').textContent='The disconnect state changed. Please try again.';}finally{busy=false;}}
 function paint(){const lobby=last?.phase==='placement',section=box.querySelector('section');/* Pre-start policy remains visible without blocking placement/Ready underneath it. */if(lobby){const bar=document.getElementById('stLanStatus');if(bar&&box.previousElementSibling!==bar)bar.after(box);box.style.position='static';box.style.background='transparent';box.style.overflow='visible';section.setAttribute('aria-modal','false');}else{if(box.parentElement!==document.body)document.body.append(box);for(const name of ['position','background','overflow'])box.style.removeProperty(name);section.setAttribute('aria-modal','true');}const a=meta?.presence?.[1-meta.self];/* An episode is confirmed at the server's settled/preserved-decision boundary. Local playback must not suppress its controls. */if(window.__stoneThrowViewState?.().inputLocked&&!a?.episode){box.hidden=true;return;}for(const e of queued.splice(0))newsflash(e);if(!meta||meta.ring||!a?.episode||last.phase==='finished'||meta.closed){box.hidden=true;return;}box.hidden=dismissed===a.episode;box.querySelector('h2').textContent=meta.names[1-meta.self]+' is disconnected';box.querySelector('.st-mp-clock').textContent=clockText(a.remainingMs-(Date.now()-at))+' remaining';const mode=a.episode+':'+a.policy,actions=box.querySelector('.st-mp-actions');if(actions.dataset.mode===mode)return;actions.dataset.mode=mode;actions.replaceChildren();box.querySelector('#stDisconnectDismiss')?.remove();box.querySelector('.st-mp-error').textContent='';if(a.policy==='choice'){button(box,'AUTO KICK','stAutoKick',()=>choose('auto'));button(box,'WAIT','stWait',()=>choose('wait'));}else if(a.policy==='wait'){button(box,'KICK','stKick',()=>choose('kick'));}else{const x=button(box,'X','stDisconnectDismiss',()=>{dismissed=a.episode;box.hidden=true;});box.querySelector('section').append(x);x.setAttribute('aria-label','Dismiss popup; Auto Kick remains active');}}
 function observe(m,s){if(!m){meta=null;queued=[];box.hidden=true;document.querySelectorAll('.st-mp-newsflash').forEach(e=>e.remove());return;}if(battle!==s.battle){battle=s.battle;seen=m.news?.at(-1)?.id||0;queued=[];}meta=m;last=s;at=Date.now();for(const e of m.news||[]){if(e.id>seen&&e.seat!==m.self)queued.push(e);seen=Math.max(seen,e.id);}const a=m.presence?.[1-m.self];if(episode!==a?.episode){episode=a?.episode;dismissed=null;}paint();}
 const timer=setInterval(paint,200);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});return {observe};}
