import {createReplayCursor} from './replay-state.js';
import {paintOverview} from './overview-board.js';
// Reusable shell only; production navigation does not mount this component.
export function mountReplayViewer(container,replay){
 const cursor=createReplayCursor(replay),root=document.createElement('section');root.className='cs-replay';
 const style=document.createElement('style');style.textContent=`.cs-replay{background:#10171b;color:#edce83;padding:18px;font:16px Georgia;max-width:1000px;margin:auto;border:1px solid #967943}.cs-replay h2{margin:0 0 8px}.cs-replay nav{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.cs-replay button{background:#23251f;color:#ffe3a0;border:1px solid #967943;padding:10px;cursor:pointer}.cs-replay input{width:100%}.cs-replay-boards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.cs-replay-board h3{margin:8px 0}.cs-replay-grid{display:grid;border:3px double #b29964;aspect-ratio:1}.cs-replay-cell{min-width:0;min-height:0;line-height:1;overflow:hidden;border:1px solid #303a3e;background:#10171b;display:grid;place-items:center;font:clamp(9px,2vw,18px) Arial;color:#b3bfc9}.cs-replay-cell.hit{color:#ffac83;background:#432522}.cs-replay-cell.plague{background:#61326f}.cs-replay-cell.lit{outline:2px solid #ffcf57;outline-offset:-2px}.cs-replay-cell img{width:100%;height:100%;object-fit:contain}.cs-replay-status{min-height:26px}.cs-replay-board.eliminated h3{opacity:.6}@media(max-width:540px){.cs-replay{padding:10px}.cs-replay-boards{gap:8px}.cs-replay button{padding:8px;font-size:12px}.cs-replay-board h3{font-size:14px}}`;
 const title=document.createElement('h2');title.textContent='BATTLE REPLAY';const meta=document.createElement('p');meta.textContent=`${replay.format.toUpperCase()} · ${replay.mode} · ${new Date(replay.startedAt).toLocaleDateString()} · ${replay.coverage}`;
 const nav=document.createElement('nav'),slider=document.createElement('input');slider.type='range';slider.min=0;slider.max=cursor.length;slider.value=0;slider.setAttribute('aria-label','Replay timeline');
 const status=document.createElement('div');status.className='cs-replay-status';status.setAttribute('aria-live','polite');const boards=document.createElement('div');boards.className='cs-replay-boards';let index=0;
 function show(value){const state=cursor.seek(value);index=state.index;slider.value=index;status.textContent=`${index} / ${cursor.length} · Round ${state.round??'—'} · Turn ${state.turn??'—'} · ${state.notice}`;const event=replay.timeline[index-1],art=event?.kind==='special'?({'monk-deflect':'monk','catapult-shot':'catapult'}[event.name]||event.name):event?.kind==='catapult'?'catapult':null;if(['archer','monk','catapult','dwarf','goblin','wizard','demon','dragon'].includes(art)){const icon=document.createElement('img');icon.src='/assets/unit-info/'+art+'.png';icon.alt='';icon.style.cssText='width:26px;height:26px;vertical-align:middle;margin-left:8px';status.append(icon);}boards.replaceChildren();for(const b of state.boards){const wrap=document.createElement('div');wrap.className='cs-replay-board'+(b.eliminated?' eliminated':'');const name=document.createElement('h3');const p=replay.participants.find(p=>p.seat===b.seat);name.textContent=p.name+(p.ai?' (AI)':'')+(b.eliminated?' — ELIMINATED':'');const grid=document.createElement('div');grid.className='cs-replay-grid';paintOverview(grid,document.createElement('div'),{size:replay.size,cells:Object.values(b.cells).map(c=>({...c,cell:{x:c.x,y:c.y}})),roster:{},strip:{},plague:[],hero:[]});grid.style.gridTemplateColumns=`repeat(${replay.size},minmax(0,1fr))`;grid.style.gridTemplateRows=`repeat(${replay.size},minmax(0,1fr))`;for(let y=0;y<replay.size;y++)for(let x=0;x<replay.size;x++){const c=b.cells[x+','+y],cell=grid.children[y*replay.size+x];cell.className='cs-replay-cell'+(c?.observation==='hit'?' hit':'')+(c?.plague?' plague':'')+(state.highlight.some(h=>h.board===b.seat&&h.x===x&&h.y===y)?' lit':'');cell.textContent=c?.observation==='hit'?'?':c?.observation==='miss'?'·':'';if(['inf','cav','castle','archer','monk','dwarf','goblin','catapult','elf','cleric','necro','wizard','demon','dragon','hero'].includes(c?.kind)){const art=document.createElement('img');art.src=c.kind==='castle'&&Number.isInteger(c.castleMask)?'/assets/units/castle/tile-'+String(c.castleMask).padStart(2,'0')+'.png':'/assets/unit-info/'+c.kind+'.png';art.alt=c.kind;cell.replaceChildren(art);}}wrap.append(name,grid);boards.append(wrap);}}
 for(const [label,value]of [['BEGINNING',()=>0],['PREVIOUS EVENT',()=>index-1],['NEXT EVENT',()=>index+1],['END',()=>cursor.length]]){const button=document.createElement('button');button.textContent=label;button.onclick=()=>show(value());nav.append(button);}slider.oninput=()=>show(+slider.value);
 root.append(style,title,meta,nav,slider,status,boards);container.append(root);show(0);return {seek:show,unmount:()=>root.remove()};
}
