// Local-only setup: no Online room, join, code, presence or Ready controls.
import {AVATARS,AI_AVATARS} from '../assets/avatars/catalog.mjs';
export function installSingleEntry(session,client){
 const by=id=>document.getElementById(id),panel=document.createElement('div');panel.id='stSingleSetup';panel.className='st-mp-overlay';panel.hidden=true;
 panel.innerHTML=`<section class="st-mp-dialog st-frame cs-entry" role="dialog" aria-modal="true" aria-labelledby="csSingleTitle"><header><small>CHAIN SIEGE</small><h2 id="csSingleTitle">SINGLE PLAYER</h2><p>Choose your AI opponents.</p></header><div id="csSingleSeats" class="cs-setup-seats"></div><p id="csSingleFormat"></p><div class="st-mp-actions"><button id="csSingleStart" class="st-btn">CONTINUE TO DEPLOYMENT</button><button id="csSingleBack" class="st-btn">MAIN MENU</button></div><p id="csSingleMessage" role="status"></p></section>`;document.body.append(panel);
 let identity=null,names=[null,null,null],busy=false;
 function assign(i){const available=Object.keys(AI_AVATARS).filter(n=>!names.includes(n)),value=new Uint32Array(1);crypto.getRandomValues(value);names[i]=available[value[0]%available.length];}
 function cards(){const root=by('csSingleSeats');root.replaceChildren();for(let i=0;i<4;i++){const ai=i>0,npc=ai?names[i-1]:null,card=document.createElement('article');card.className='cs-entry-seat';card.dataset.seat=String(i);const title=document.createElement('h3');title.textContent='SEAT '+(i+1);card.append(title);const avatar=AVATARS.find(a=>a.id===(ai?AI_AVATARS[npc]:identity?.avatarId));if(avatar){const image=document.createElement('img');image.src=avatar.assetPath;image.alt=ai?npc:identity?.displayName||'Player';card.append(image);}const name=document.createElement('p');name.textContent=ai?(npc||'Empty'):identity?.displayName||'You';card.append(name);const marker=document.createElement('span');marker.className='cs-seat-nationality';if(!ai&&/^[A-Z]{2}$/.test(identity?.country||'')){const flag=document.createElement('img');flag.src='assets/ui/flags/'+identity.country.toLowerCase()+'.svg';flag.alt=identity.country;marker.append(flag);}else marker.textContent=ai&&npc?'(AI)':!ai?'—':'';card.append(marker);if(i<2){const fixed=document.createElement('strong');fixed.textContent=ai?'AI':'PLAYER';card.append(fixed);}else{const options=document.createElement('div');options.className='cs-seat-options';for(const choice of ['AI','EMPTY']){const b=document.createElement('button');b.textContent=choice;b.dataset.choice=choice;b.setAttribute('aria-pressed',String(choice==='AI'?!!npc:!npc));b.onclick=()=>{if(choice==='AI'&&!names[i-1])assign(i-1);else if(choice==='EMPTY')names[i-1]=null;cards();};options.append(b);}card.append(options);}root.append(card);}by('csSingleFormat').textContent='1 PLAYER + '+names.filter(Boolean).length+' AI · '+(1+names.filter(Boolean).length)+' PARTICIPANTS';}
 async function show(){names=[null,null,null];assign(0);document.body.classList.add('st-main-menu-mode');panel.hidden=false;by('csSingleStart').disabled=true;try{({identity}=await session.request('single/identity'));cards();by('csSingleMessage').textContent='';by('csSingleStart').disabled=false;}catch(e){by('csSingleMessage').textContent=e.code||'Unable to load player identity.';}}
 by('csSingleBack').onclick=()=>{panel.hidden=true;document.body.classList.add('st-main-menu-mode');};
 by('csSingleStart').onclick=async()=>{if(busy)return;busy=true;by('csSingleStart').disabled=true;try{const opened=await session.request('single/setup',{npcNames:names.filter(Boolean)});await client.enterLocal(opened);panel.hidden=true;document.body.classList.remove('st-main-menu-mode');}catch(e){by('csSingleMessage').textContent=e.code||e.message;}finally{busy=false;by('csSingleStart').disabled=false;}};
 document.addEventListener('click',async e=>{if(!e.target.closest('#stMenuFull'))return;e.preventDefault();e.stopImmediatePropagation();if(busy)return;busy=true;try{if(await window.__stoneThrowResumeActiveGameFromMenu?.()){document.body.classList.remove('st-main-menu-mode');return;}await show();}catch(e){by('csSingleMessage').textContent=e.code||e.message;}finally{busy=false;}},true);
 return {hide:()=>panel.hidden=true};
}
