import {mountReplayViewer} from './replay-viewer.js';
export function spectatorCheckpoint(data){return {kind:'checkpoint',round:data.round,turn:null,active:data.current,boards:data.boards.map(b=>({seat:b.seat,eliminated:!!b.eliminated,hero:b.hero||[],cells:b.cells.map(c=>({x:c.x,y:c.y,observation:c.hit?'hit':'miss',kind:c.kind,...(c.plague?{plague:true}:{}),...(c.kind==='castle'?{corePresentation:'identified',castleMask:0}: {})}))}))};}
export async function spectate(session,code){
 const initial=await session.request('pvp/spectate',{code,after:0,epoch:''});
 if(!document.querySelector('link[href="/styles-spectator.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='/styles-spectator.css';document.head.append(css);}
 // The animation resolver anchors observer effects inside this modal top layer.
 const dialog=document.createElement('dialog');dialog.className='cs-spectator';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-label','Spectating game');
 const header=document.createElement('header'),title=document.createElement('h2'),leave=document.createElement('button'),status=document.createElement('p'),host=document.createElement('div');title.textContent='SPECTATING · '+code;leave.textContent='LEAVE SPECTATING';leave.className='st-btn';header.append(title,leave);dialog.append(header,status,host);document.body.append(dialog);
 const replay={replayVersion:'CHAIN_SIEGE_PUBLIC_REPLAY_V1',matchId:code,format:initial.boards.length+'p',mode:'live',size:initial.boards[0].size,participants:initial.boards.map(b=>({seat:b.seat,name:b.name,ai:!!b.ai})),timeline:[spectatorCheckpoint(initial)]};
 const viewer=mountReplayViewer(host,replay,{live:true});let stopped=false,busy=false,cursor=initial.cursor,epoch=initial.epoch,resync=false;
 const label=data=>data.phase==='placement'?'Waiting for deployment. Hidden placements stay private.':data.phase==='finished'?'Battle finished.':data.reset?'Caught up to the current public battlefield.':'Live public battle — player thinking time is not replayed.';
 status.textContent=label(initial);
 const stop=()=>{if(stopped)return;stopped=true;clearInterval(timer);viewer.unmount();dialog.close();dialog.remove();document.removeEventListener('keydown',escape);};leave.onclick=stop;const escape=e=>{if(e.key==='Escape'){e.preventDefault();stop();}};document.addEventListener('keydown',escape);dialog.addEventListener('cancel',e=>{e.preventDefault();stop();});dialog.showModal();leave.focus();
 const timer=setInterval(async()=>{if(stopped||busy||!viewer.playing||document.hidden)return;busy=true;try{const data=await session.request('pvp/spectate',{code,after:resync?0:cursor??0,epoch:resync?'':epoch??''});if(stopped)return;if(data.cursor===cursor&&data.epoch===epoch&&!resync)return;const accepted=await viewer.append(data.events||[],spectatorCheckpoint(data),{reset:data.reset||data.epoch!==epoch});if(stopped)return;if(accepted){cursor=data.cursor;epoch=data.epoch;resync=false;status.textContent=label(data);}else{resync=true;status.textContent='Paused. Resume catches up to the current public battlefield.';}}catch{if(!stopped)status.textContent='Connection interrupted. Retrying without replaying received events…';}finally{busy=false;}},1000);
 return {close:stop};
}
