const icons={inf:'infantry',cav:'cavalry',archer:'archer',monk:'monk-earlier',hero:'hero-alive',catapult:'catapult',dwarf:'dwarf',elf:'elf',goblin:'goblin',cleric:'cleric',necro:'necromancer',wizard:'wizard',dragon:'dragon',demon:'demon',assassin:'assassin/assassin'};
export async function spectate(session,code){
 const initial=await session.request('pvp/spectate',{code});
 if(!document.querySelector('link[href="styles-spectator.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='styles-spectator.css';document.head.append(css);}
 const dialog=document.createElement('dialog');dialog.className='cs-spectator';dialog.setAttribute('aria-label','Spectating game');
 const header=document.createElement('header'),title=document.createElement('h2'),leave=document.createElement('button'),status=document.createElement('p'),boards=document.createElement('div');boards.className='cs-spectator-boards';leave.textContent='LEAVE SPECTATING';leave.className='st-btn';header.append(title,leave);dialog.append(header,status,boards);document.body.append(dialog);
 let stopped=false,busy=false,key='';const stop=()=>{stopped=true;clearInterval(timer);dialog.close();dialog.remove();};leave.onclick=stop;dialog.addEventListener('cancel',e=>{e.preventDefault();stop();});
 function paint(data){title.textContent='SPECTATING · '+data.code;status.textContent=data.phase==='placement'?'Waiting for deployment — hidden placements stay private.':data.phase==='finished'?'Battle finished.':('Round '+data.round+' · '+(data.boards[data.current]?.name||'Resolving chain')+' · Public cells only');const next=JSON.stringify(data);if(key===next)return;key=next;boards.replaceChildren();for(const board of data.boards){const section=document.createElement('section'),name=document.createElement('h3'),grid=document.createElement('div');name.textContent=board.name+(board.seat===data.current?' — CURRENT PLAYER':'');grid.className='cs-spectator-grid';grid.style.setProperty('--size',board.size);const known=new Map(board.cells.map(c=>[c.x+','+c.y,c]));for(let y=0;y<board.size;y++)for(let x=0;x<board.size;x++){const cell=document.createElement('span'),c=known.get(x+','+y);if(c){cell.className=c.hit?'hit':'miss';cell.title=c.hit?(c.kind||'Unidentified core unit'):'Miss';if(c.kind&&icons[c.kind]){const img=document.createElement('img');img.src='assets/units/'+icons[c.kind]+'.png';img.alt=c.kind;cell.append(img);}else cell.textContent=c.hit?'×':'·';}grid.append(cell);}section.append(name,grid);boards.append(section);}}
 paint(initial);dialog.showModal();const timer=setInterval(async()=>{if(stopped||busy)return;busy=true;try{const data=await session.request('pvp/spectate',{code});if(!stopped)paint(data);}catch{if(!stopped)status.textContent='Connection interrupted or game unavailable. Retrying…';}finally{busy=false;}},1000);
}
