let identity=undefined,progress=null,lifetime=null,runId=null,loading=Promise.resolve(),generation=0,bypass=false;
export function setStoryAccount(account){const id=account?.playerId||null;if(id===identity)return loading;identity=id;progress=null;lifetime=null;runId=null;generation++;window.dispatchEvent(new Event('stone-throw-story-account'));return refreshAccountStory();}
export async function refreshAccountStory(){const version=generation,id=identity;if(!id){loading=Promise.resolve();return null;}loading=(async()=>{const response=await fetch('/api/registry/story-progress',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw Error('Account Story progression could not be loaded. Please retry.');const value=await response.json();if(version!==generation)return null;if(value.playerId!==id)throw Error('Account changed. Please log in again.');progress=value.progress;lifetime=value.lifetime;runId=value.runId;window.dispatchEvent(new Event('stone-throw-story-account-progress'));return progress;})();return loading;}
window.__stoneThrowStoryAccount=()=>({playerId:identity||null,progress,lifetime,runId});
window.__stoneThrowLoadAccountStory=async()=>{await loading.catch(()=>{});return refreshAccountStory();};
window.__stoneThrowStoryStorageKey=key=>identity?key+'.account.'+identity:key;
window.addEventListener('click',e=>{const target=e.target.closest?.('#stMenuStory,#stMenuStoryContinue');if(!target||!identity||bypass)return;e.preventDefault();e.stopImmediatePropagation();refreshAccountStory().then(()=>{bypass=true;try{target.click();}finally{bypass=false;}}).catch(error=>{document.getElementById('status').textContent=error.message;});},true);

window.__stoneThrowRestartAccountStory=async()=>{if(!identity)return;const r=await fetch('/api/registry/story-restart',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Story restart failed; please retry.');await refreshAccountStory();};
