import {serverMetrics,requestLog,responseLog,logEvent,gameLogEnabled} from './game-log.js';
function headersLog(response,trace){try{serverMetrics(JSON.parse(response.headers.get('X-St-Beta-Metrics')),trace);}catch{}}
export class TransportError extends Error {constructor(code){super(code);this.code=code;}}
export function createHttpSession(){
 let latest=null,group=false;
 async function request(route,body={}){const trace=requestLog(route,body);let response;try{response=await fetch('/api/'+route,{method:'POST',headers:{...(gameLogEnabled()?{'X-St-Game-Log':'1'}:{}),'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)});}catch{throw new TransportError('server-unavailable');}let result;try{result=await response.json();}catch{throw new TransportError('invalid-response');}headersLog(response,trace);responseLog(trace,result);if(!response.ok)throw new TransportError(result.error||'server-unavailable');if(result.lan)group=!!result.lan.group;if(result.update?.lan)group=!!result.update.lan.group;if(result.snapshot)latest=result.snapshot;if(result.update?.snapshot)latest=result.update.snapshot;return result;}
 async function commandWithPreview(command,preview){const trace=requestLog('command',command);let response;try{response=await fetch('/api/command',{method:'POST',headers:{...(gameLogEnabled()?{'X-St-Game-Log':'1'}:{}),'Content-Type':'application/json',Accept:'application/x-ndjson'},credentials:'same-origin',body:JSON.stringify(command)});}catch{throw new TransportError('server-unavailable');}headersLog(response,trace);if(!response.ok){let error;try{error=await response.json();}catch{}throw new TransportError(error?.error||'server-unavailable');}if(!response.headers.get('content-type')?.includes('application/x-ndjson')){const update=await response.json();responseLog(trace,update);if(update.snapshot)latest=update.snapshot;return update;}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',result=null;for(;;){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let newline;while((newline=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,newline);buffer=buffer.slice(newline+1);if(!line)continue;const item=JSON.parse(line);if(item.betaGameLog)serverMetrics(item.betaGameLog,trace);logEvent('STREAM '+item.type.toUpperCase(),{frames:item.update?.presentation?.length||0,eventPosition:item.update?.snapshot?.eventPosition});if(item.type==='progress')preview({snapshot:item.update.snapshot,progress:item.update});else if(item.type==='preview')await preview(item.frame);else if(item.type==='result')result=item.update;else if(item.type==='error')throw new TransportError(item.error);}if(done)break;}if(!result)throw new TransportError('invalid-response');responseLog(trace,result);latest=result.snapshot;return result;}
 // Group placement revisions also change when another seat places or joins.
 // Refresh only placement intents; never retry a shot or a pending decision.
 async function dispatch(command,preview){const placement=group&&['place','move','remove','random-placement','start'].includes(command.intent?.kind);if(placement){const u=await request('read');if(u.snapshot.battle!==command.battle||u.snapshot.phase!=='placement')return {...u,accepted:false,error:'stale',events:[],presentation:[]};command={...command,revision:u.snapshot.revision};}return preview?commandWithPreview(command,preview):request('command',command);}
 const client=Object.freeze({read:after=>request('read',{after:after??0}),dispatch});
 return Object.freeze({client,open:fresh=>request('open',fresh?{fresh:true}:{}),configure:async (configuration,storyContext)=>{if(!latest)await client.read();return request('configure',{battle:latest.battle,revision:latest.revision,configuration,...(storyContext?{storyContext}:{})});},request});
}
