import assert from 'node:assert/strict';
import {createHost,place} from '../canonical/compiled/host/initialization.js';
import {syncRing} from '../canonical/compiled/host/ring.js';
import {startResolution,stepResolution} from '../canonical/compiled/combat/resolver.js';
import {serializeResolution,deserializeResolution} from '../canonical/compiled/combat/serialization.js';
import {resurrectionCandidates,resurrect} from '../canonical/compiled/combat/units/cleric.js';
import {legacyRandomPlacement} from '../canonical/compiled/policy/placement-legacy.js';
import {createRuleRng} from '../canonical/compiled/combat/rng.js';
let checks=0;
function fixture(n=4,kinds=['wizard']){
 const roster={inf:2,assassin:1,...Object.fromEntries(kinds.map(k=>[k,1]))};
 const h=createHost({matchId:'assassin-test',rulesVersion:'stone-throw-pacing-v1',size:15,story:false,seed:42,players:Array.from({length:n},(_,i)=>({id:'p'+i,boardId:'b'+i,roster,decisionMode:'interactive'}))});
 for(let i=0;i<n;i++)for(const [j,x]of [12,14].entries())place(h,{unitId:'inf'+i+'x'+j,ownerId:'p'+i,boardId:'b'+i,type:'inf',cells:[{x,y:14}]});
 place(h,{unitId:'assassin0',ownerId:'p0',boardId:'b0',type:'assassin',cells:[{x:12,y:13}]});
 for(const [j,type]of kinds.entries())place(h,{unitId:type+'0',ownerId:'p0',boardId:'b0',type,cells:[{x:2+j*3,y:2}]});
 if(h.state.ring)syncRing(h.state);return h;
}
const meta=(source='direct-human')=>({actorId:'p1',ownerId:'p1',targetPlayerId:'p0',targetBoardId:'b0',sourceUnitId:null,source,origin:{x:4,y:4}});
const impact=(source='direct-human')=>({kind:'impact',meta:meta(source),cell:{x:12,y:13},deferReactions:false});
function run(h,ops=[impact()],restore=true){let r=startResolution(h.state,'assassin-root','shot','p1',ops,h.rng,'boundary-comparison');let steps=0;while(r.status==='running'){assert.ok(++steps<10000);stepResolution(r,{deferTerminal:true});if(restore)r=deserializeResolution(serializeResolution(r));}assert.equal(r.status,'complete');return r;}
// Exact placement exemption, but never overlap/out of bounds.
{const h=fixture();assert.equal(h.state.match.units.find(u=>u.type==='assassin').cells[0].y,13);for(const cell of [{x:12,y:14},{x:-1,y:0},{x:15,y:0}]){const fresh=fixture();fresh.state.match.units=fresh.state.match.units.filter(u=>u.type!=='assassin');assert.throws(()=>place(fresh,{unitId:'bad',ownerId:'p0',boardId:'b0',type:'assassin',cells:[cell]}));}checks++;}
// Assassin never creates a spacing barrier, but its cell stays occupied.
for(const type of ['inf','cav','castle']){const h=createHost({matchId:'spacing',rulesVersion:'stone-throw-pacing-v1',size:15,story:false,seed:42,players:[0,1].map(i=>({id:'p'+i,boardId:'b'+i,roster:{assassin:1,[type]:2},decisionMode:'interactive'}))});place(h,{unitId:'a',ownerId:'p0',boardId:'b0',type:'assassin',cells:[{x:4,y:4}]});const cells=type==='castle'?[0,1,2,3,4].map(i=>({x:3+i,y:5})):type==='cav'?[{x:4,y:5},{x:5,y:5}]:[{x:4,y:5}];place(h,{unitId:'u',ownerId:'p0',boardId:'b0',type,cells});assert.throws(()=>place(h,{unitId:'overlap',ownerId:'p0',boardId:'b0',type,cells:cells.map(c=>({x:c.x,y:c.y-1}))}));checks++;}
for(const n of [2,3,4])for(const type of ['demon','dragon','wizard','goblin']){
 const h=fixture(n,[type]),r=run(h),attack=r.events.find(e=>e.kind==='attack-started'&&e.reason===type);assert.ok(attack);assert.equal(attack.meta.targetPlayerId,h.state.seats[0].reactionTarget.playerId);assert.ok(r.state.seats[0].shots.includes('2,2'));const strike=r.events.find(e=>e.kind==='attack-started'&&e.reason==='assassin');assert.ok(strike);assert.equal(strike.meta.targetPlayerId,'p1');assert.ok(strike.sequence>attack.sequence);const hits=r.events.filter(e=>e.kind==='impact'&&e.meta?.source==='assassin'&&e.meta.targetPlayerId==='p1');assert.equal(hits.length,1);assert.equal(hits[0].statistics.unitType,'inf');assert.equal(serializeResolution(r),serializeResolution(run(h,[impact()],false)));assert.ok(!resurrectionCandidates(r,'p0').includes('assassin0'));checks++;
}
// Incoming source, duplicate contact, original-chain remainder and eliminated attacker.
for(const source of ['direct-human','direct-ai','archer','wizard','plague']){const h=fixture(),r=run(h,[impact(source),impact(source)]);assert.equal(r.events.filter(e=>e.kind==='attack-started'&&e.reason==='assassin').length,source==='plague'?0:1);checks++;}
{const h=fixture(),ops=[impact(),...h.state.match.units.filter(u=>u.ownerId==='p1').map(u=>({kind:'impact',meta:{...meta('chain'),targetPlayerId:'p1',targetBoardId:'b1'},cell:u.cells[0],deferReactions:false}))],r=run(h,ops);assert.equal(r.events.filter(e=>e.kind==='attack-started').length,0);assert.ok(!r.state.seats[0].shots.includes('2,2'));checks++;}
// Fallback: three unique legal cells and no forced hidden-occupancy targeting.
{const h=fixture(4,[]),r=run(h),hits=r.events.filter(e=>e.kind==='impact'&&e.meta?.source==='assassin');assert.equal(hits.length,3);assert.equal(new Set(hits.map(e=>JSON.stringify(e.cells[0]))).size,3);checks++;}
// Candidate random choice is canonical and covers each chain type over deterministic seeds.
{const found=new Set();for(let seed=1;seed<=24;seed++){const h=fixture(4,['demon','dragon','wizard','goblin']);h.rng=createRuleRng(seed,[((seed-1)%4)/4]);const r=run(h);found.add(r.events.find(e=>e.kind==='impact'&&e.meta?.source==='assassin').statistics.unitType);}assert.deepEqual([...found].sort(),['demon','dragon','goblin','wizard']);checks++;}
for(const profile of ['first-seat','second-seat']){const placements=legacyRandomPlacement(profile,15,{inf:5,elf:2,assassin:1},createRuleRng(42));assert.equal(placements.filter(p=>p.type==='assassin').length,1);assert.equal(new Set(placements.flatMap(p=>p.cells)).size,placements.flatMap(p=>p.cells).length);checks++;}
// The second chain can eliminate B: skip the final guaranteed strike.
{const h=fixture(3,['wizard']);h.config.players[2].roster.demon=1;place(h,{unitId:'demon2',ownerId:'p2',boardId:'b2',type:'demon',cells:[{x:2,y:2}]});for(const u of h.state.match.units.filter(u=>u.ownerId==='p1'))u.cells[0].y=2;h.state.seats[1].occupied=['12,2','14,2'];const r=run(h);assert.ok(r.events.some(e=>e.reason==='demon'));assert.equal(r.events.filter(e=>e.kind==='attack-started'&&e.reason==='assassin').length,0);assert.ok(r.state.seats[1].shots.includes('12,2')&&r.state.seats[1].shots.includes('14,2'));checks++;}
// Untouched Hero excluded, activated Hero eligible. Its normal third-hit death runs.
for(const active of [false,true]){const h=fixture();h.config.players[1].roster.hero=1;place(h,{unitId:'hero1',ownerId:'p1',boardId:'b1',type:'hero',cells:[{x:10,y:10}]});const hero=h.state.match.units.find(u=>u.id==='hero1');if(active){hero.hero.activated=true;hero.hero.hitsTaken=2;hero.damage.hitsTaken=2;h.state.seats[1].shots.push('12,14','14,14');}const r=run(h),hit=r.events.find(e=>e.kind==='impact'&&e.meta?.source==='assassin'&&e.meta.targetPlayerId==='p1');assert.equal(hit.statistics.unitType,active?'hero':'inf');if(active)assert.ok(r.events.some(e=>e.kind==='hero-killed'&&e.unitId==='hero1'));checks++;}
// A revived Cavalry cell is eligible; normal resurrection discovery still applies.
{const h=fixture();h.config.players[1].roster.cav=1;place(h,{unitId:'cav1',ownerId:'p1',boardId:'b1',type:'cav',cells:[{x:10,y:10},{x:11,y:10}]});h.state.seats[1].shots.push('12,14','14,14','10,10','11,10');const pre=startResolution(h.state,'rez','rez','p1',[],h.rng,'boundary-comparison');resurrect(pre,'p1','cav1');h.state=pre.state;const r=run(h),hit=r.events.find(e=>e.kind==='impact'&&e.meta?.source==='assassin'&&e.meta.targetPlayerId==='p1');assert.equal(hit.unitId,'cav1');assert.ok(r.events.some(e=>e.kind==='resurrection-discovered'&&e.unitId==='cav1'));checks++;}
// Fallback excludes already-fired and impossible cells beside destroyed footprints.
{const h=fixture(4,[]);h.state.seats[1].shots.push('12,14');const r=run(h),hits=r.events.filter(e=>e.kind==='impact'&&e.meta?.source==='assassin');for(const e of hits){const c=e.cells[0];assert.ok(Math.abs(c.x-12)>1||Math.abs(c.y-14)>1);}checks++;}

// Policy: 50/50 style draw, both placement profiles, deterministic replay.
for(const profile of ['first-seat','second-seat']){const styles=new Set();for(let seed=1;seed<=40;seed++){const rng=createRuleRng(seed),roster={inf:5,castle:2,assassin:1},out=legacyRandomPlacement(profile,15,roster,rng),a=out.find(u=>u.type==='assassin').cells[0].split(',').map(Number),style=rng.draws.find(d=>d.purpose==='placement:assassin-style').value<.5;styles.add(style);const others=out.filter(u=>u.type!=='assassin');if(style)assert.ok(others.flatMap(u=>u.cells).every(k=>{const c=k.split(',').map(Number);return Math.max(Math.abs(c[0]-a[0]),Math.abs(c[1]-a[1]))>1;}));else assert.ok(others.filter(u=>u.type==='castle').flatMap(u=>u.cells).some(k=>{const c=k.split(',').map(Number);return Math.abs(c[0]-a[0])+Math.abs(c[1]-a[1])===1;}));assert.deepEqual(out,legacyRandomPlacement(profile,15,roster,createRuleRng(seed)));}assert.equal(styles.size,2);checks++;}
// Existing first-hit bait category includes an unhit Assassin.
{const {firstHeroRelocation}=await import('../canonical/compiled/policy/first-hero-relocation.js');const h=fixture(2,[]);h.rng=createRuleRng(42,[.6,0]);assert.equal(firstHeroRelocation(h,'p0',['11,13','0,0']),'11,13');checks++;}
// Scout knowledge excludes Assassin even from the active-Hero search and clue pools.
{const {normalPolicy,emptyNormalMemory}=await import('../canonical/compiled/local-host/normal-policy.js');const {autoMatchTarget}=await import('../canonical/compiled/policy/auto-target.js');for(const known of [false,true])for(const plagueAware of [false,true]){const h=fixture(2,[]);h.config.players[0].roster.hero=1;place(h,{unitId:'hero0',ownerId:'p0',boardId:'b0',type:'hero',cells:[{x:5,y:5}]});const hero=h.state.match.units.find(u=>u.type==='hero');hero.hero.activated=true;hero.hero.hitsTaken=2;const m=emptyNormalMemory();m.heroHunt=['12,13'];h.brains[1].heroHunt=['12,13'];if(known){m.scoutKnowledge=[['12,13','special']];h.brains[1].scoutKnowledge=[{cell:'12,13',classification:'special'}];}const normal=normalPolicy(h,m).target(plagueAware),auto=autoMatchTarget(h,'p1',plagueAware);if(known){assert.notEqual(normal,'12,13');assert.notEqual(auto,'12,13');}else{assert.equal(normal,'12,13');assert.equal(auto,'12,13');}checks++;}}
// Aim Assist stays enabled with a living Assassin and never reveals its location.
{const {publicAimAssist}=await import('../canonical/compiled/local-host/resurrection-disclosure.js');const h=fixture(2,[]);h.status='awaiting-command';h.state.seats[1].shots.push('12,14');h.config.players[1].roster.assassin=1;h.status='placement';place(h,{unitId:'enemy-assassin',ownerId:'p1',boardId:'b1',type:'assassin',cells:[{x:12,y:13}]});h.status='awaiting-command';const before=JSON.stringify(h),a=publicAimAssist(h);assert.ok(a.some(c=>c.x===12&&c.y===13));assert.equal(JSON.stringify(h),before);const u=h.state.match.units.find(u=>u.id==='enemy-assassin');u.cells=[{x:0,y:0}];assert.deepEqual(publicAimAssist(h),a);u.cells=[{x:12,y:13}];h.state.seats[1].shots.push('12,13');const after=publicAimAssist(h);assert.ok(!after.some(c=>c.x===12&&c.y===12),'dead Assassin creates no spacing exclusion');checks++;}
console.log(JSON.stringify({passed:true,checks,restoreEveryStep:true,formats:[2,3,4]}));
