import os from 'node:os';import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {createHash} from 'node:crypto';
import {openRegistry} from '../server/registry.mjs';import {AVATARS,DEFAULT_AVATAR,AI_AVATARS} from '../assets/avatars/catalog.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'chain-siege-avatar-check-'));let r=openRegistry(dir);const ctx={browser:'avatar-test',ip:'test'},password='Password42',accounts=[];
async function register(name,avatarId){const c=await r.handle('challenge',{},ctx),n=c.question.match(/\d+/g);return r.handle('register',{username:name,password,confirmPassword:password,country:'IS',avatarId,challengeId:c.id,answer:String(+n[0]+ +n[1])},ctx);}
const me=a=>r.handle('me',{}, {...ctx,token:a.token}),select=(a,id)=>r.handle('avatar',{avatarId:id},{...ctx,token:a.token});
const capture=(a,mode,n,{ended=true,kind='account',outcome='Win'}={})=>r.statistics.capture({id:'avatar-'+a.account.playerId+'-'+n,mode,build:'test',epoch:1,startedAt:1,...(ended?{endedAt:2}:{}),participants:[{actor:'a',seat:0,kind,playerId:kind==='account'?a.account.playerId:null,outcome,reliability:'Full'},{actor:'ai',seat:1,kind:'ai',playerId:null}]},{config:{rulesVersion:'test'},events:[],history:[]});
try{
assert.equal(AVATARS.length,63);for(const a of AVATARS){const bytes=fs.readFileSync(path.join(root,a.assetPath));assert.equal(createHash('sha256').update(bytes).digest('hex'),a.sha256);if(process.env.ST_AVATAR_SOURCE)assert.deepEqual(bytes,fs.readFileSync(path.join(process.env.ST_AVATAR_SOURCE,path.basename(a.assetPath))));}for(const[n,id]of Object.entries(AI_AVATARS))assert.equal(AVATARS.find(a=>a.id===id).assetPath,'assets/avatars/'+n.toLowerCase()+'_a.png');
for(const id of ['hero-human-male-01','guest-goblin-goblin-01','ai-cruns','ai-snurk','ai-rackler','unknown'])await assert.rejects(register('ForgedUser',id),/Avatar/);
const a=await register('AvatarOne','peasant-human-female-03'),b=await register('AvatarTwo',DEFAULT_AVATAR),story=await register('StoryHero',DEFAULT_AVATAR);accounts.push(a,b,story);assert.equal(a.account.avatarId,'peasant-human-female-03');assert.equal(a.account.avatarUnlocked,false);
for(const id of ['hero-human-male-01','guest-goblin-goblin-01','ai-cruns','ai-snurk','ai-rackler','unknown'])await assert.rejects(select(a,id),/Avatar/);
for(let i=0;i<15;i++)assert.equal((await select(a,i%2?'peasant-human-male-02':'peasant-human-female-05')).account.avatarId,i%2?'peasant-human-male-02':'peasant-human-female-05');
const modes=['Single Player','Duel','3 Players','4 Players'];for(let i=0;i<4;i++)capture(a,modes[i],i);assert.equal((await me(a)).account.avatarUnlocked,false);capture(a,'Duel',0);capture(a,'Duel','pending',{ended:false});capture(a,'Duel','guest',{kind:'guest'});capture(a,'Duel','ai',{kind:'ai'});capture(a,'Story','storywin');assert.equal((await me(a)).account.avatarUnlocked,false);capture(a,'Duel',4);assert.equal((await me(a)).account.avatarUnlocked,true);assert.equal((await select(a,'hero-elf-female-05')).account.avatarId,'hero-elf-female-05');assert.equal((await me(b)).account.avatarUnlocked,false);
r.completeStory(story.account.playerId,{version:1,battle:29,finished:false});assert.equal((await me(story)).account.avatarUnlocked,false);const before=r.statistics.inspect(story.account.playerId);r.completeStory(story.account.playerId,{version:1,battle:30,finished:true});assert.equal((await me(story)).account.avatarUnlocked,true);await select(story,'hero-dwarf-male-01');assert.deepEqual(r.statistics.inspect(story.account.playerId),before);
const second=await r.handle('login',{username:'AvatarOne',password},{browser:'second',ip:'second'});assert.equal(second.account.avatarId,'hero-elf-female-05');await r.handle('logout',{}, {...ctx,token:a.token});assert.equal((await me(a)).account,null);r.close();r=openRegistry(dir);assert.equal((await me(second)).account.avatarId,'hero-elf-female-05');assert.equal((await me(story)).account.avatarUnlocked,true);
// Isolated legacy account fixture: reserved fallback column, no other fields rewritten.
r.close();const db=new DatabaseSync(dir+'/registry.sqlite');db.prepare("UPDATE accounts SET avatar_id='registered-default' WHERE id=?").run(b.account.playerId);const legacy=db.prepare('SELECT * FROM accounts WHERE id=?').get(b.account.playerId);assert.equal(db.prepare("SELECT count(*) n FROM accounts WHERE username='ForgedUser'").get().n,0);db.close();r=openRegistry(dir);assert.equal((await me(b)).account.avatarId,DEFAULT_AVATAR);const read=new DatabaseSync(dir+'/registry.sqlite');const after=read.prepare('SELECT * FROM accounts WHERE id=?').get(b.account.playerId);assert.deepEqual({...after,avatar_id:legacy.avatar_id},{...legacy});assert.equal(read.prepare('SELECT avatar_unlocked FROM accounts WHERE id=?').get(a.account.playerId).avatar_unlocked,1);read.close();
const result={passed:true,assets:63,atomicRegistration:true,forgedDenied:12,unlimitedChanges:15,fiveFinalizedWinsAcrossModes:true,fourWinsLocked:true,storyCompletion:true,guestAiUnfinishedDuplicateExcluded:true,multiSessionRestart:true,fallback:true,specialA:true};console.log(JSON.stringify(result));
}finally{r.close();}
