import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {openRegistry} from '../server/registry.mjs';import {screenshot,FEEDBACK_LIMITS} from '../server/feedback.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cs-feedback-'));let registry=openRegistry(dir),checks=0;const ctx={browser:'b'.repeat(48),ip:'isolated-feedback'};
async function register(username){const c=await registry.handle('challenge',{},ctx),n=c.question.match(/\d+/g);return registry.handle('register',{username,password:'Password42',confirmPassword:'Password42',country:'IS',challengeId:c.id,answer:String(+n[0]+ +n[1])},ctx);}
const user=await register('FeedbackPlayer'),admin=await register('FeedbackAdmin');const db=new DatabaseSync(registry.file);db.prepare("UPDATE accounts SET moderation_role='admin' WHERE id=?").run(admin.account.playerId);db.close();
const api=(a,b={},token=user.token)=>registry.handle(a,b,{...ctx,token,feedbackContext:{build:'test-build',mode:'online',matchId:'test-match'}});
const png={mime:'image/png',data:fs.readFileSync(new URL('../assets/unit-info/assassin.png',import.meta.url)).toString('base64')};
try{assert.throws(()=>screenshot({mime:'image/svg+xml',data:Buffer.from('<svg/>').toString('base64')}));assert.throws(()=>screenshot({mime:'image/png',data:Buffer.from('<html/>').toString('base64')}));assert.throws(()=>screenshot({...png,filename:'../../secret'}));assert.throws(()=>screenshot({mime:'image/png',data:'A'.repeat(4*Math.ceil(FEEDBACK_LIMITS.screenshot/3)+4)}));checks+=4;
 await assert.rejects(api('feedback-submit',{type:'BUG',description:'  '}),e=>e.status===400);checks++;
 const bug=await api('feedback-submit',{type:'BUG',description:'The archer stopped after a chain.',screenshot:png,gameLog:'CHAIN SIEGE — GAME LOG\npublic diagnostic snapshot',screen:'Options'});assert.ok(bug.id);checks++;
 const idea=await api('feedback-submit',{type:'IDEA',description:'An idea from a guest.'},null);assert.ok(idea.id);checks++;
 await assert.rejects(api('dev-feedback-list',{}),e=>e.status===403);await assert.rejects(api('dev-feedback-get',{id:bug.id},null),e=>e.status===403);await assert.rejects(api('dev-feedback-status',{id:bug.id,status:'RESOLVED'}),e=>e.status===403);checks+=3;
 let list=await api('dev-feedback-list',{type:'BUG',status:'NEW'},admin.token);assert.equal(list.items.length,1);assert.equal(list.items[0].id,bug.id);checks++;
 const report=await api('dev-feedback-get',{id:bug.id},admin.token);assert.equal(report.playerId,user.account.playerId);assert.deepEqual(report.screenshot,png);assert.equal(report.build,'test-build');assert.equal(report.matchId,'test-match');assert.ok(!/password|salt|token|email/.test(JSON.stringify(report)));checks+=5;
 await api('dev-feedback-status',{id:bug.id,status:'REVIEWED'},admin.token);assert.equal((await api('dev-feedback-get',{id:bug.id},admin.token)).status,'REVIEWED');await api('dev-feedback-status',{id:bug.id,status:'RESOLVED'},admin.token);assert.equal((await api('dev-feedback-list',{status:'RESOLVED'},admin.token)).items.length,1);checks+=2;
 registry.close();registry=openRegistry(dir);const persisted=await api('dev-feedback-get',{id:bug.id},admin.token);assert.equal(persisted.status,'RESOLVED');assert.equal(persisted.gameLog,report.gameLog);assert.deepEqual(persisted.screenshot,png);assert.equal((await api('dev-feedback-list',{type:'IDEA'},admin.token)).items.length,1);checks+=4;
 console.log(JSON.stringify({passed:true,checks,isolatedStorage:true,persistence:true,developerAuthorization:true}));
}finally{registry.close();}
