import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {DatabaseSync} from 'node:sqlite';import {pathToFileURL} from 'node:url';
import {openRegistry} from '../server/registry.mjs';import {startServer} from '../server/main.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dir=fs.mkdtempSync(path.resolve(root,'../registry-check-'));let time=Date.parse('2026-09-19T12:00:00Z'),r=openRegistry(path.join(dir,'accounts'),{now:()=>time}),checks=0;
const context={ip:'192.168.1.1',browser:'browser-a'};
async function register(username,extra={},ctx=context){const c=await r.handle('challenge',{},ctx),numbers=c.question.match(/\d+/g);return r.handle('register',{username,password:'Password42',confirmPassword:'Password42',country:'IS',challengeId:c.id,answer:String(+numbers[0]+ +numbers[1]),...extra},ctx);}
async function bad(fn,pattern){await assert.rejects(fn,pattern);checks++;}
const a=await register('Þórður');assert.equal(a.account.username,'Þórður');assert.equal(a.account.displayName,'Þórður');assert.equal(a.account.currentStreak,1);assert.equal(a.account.email,'');checks++;
await bad(()=>register('ÞÓRÐUR'),/Username/);await bad(()=>register('bad!name'),/letters/);await bad(()=>register(' Leading'),/spaces/);
for(const password of ['Short1','lowercase1','UPPERCASE1','NoNumbers'])await bad(()=>register('Invalid',{password,confirmPassword:password}),/Password/);
await bad(()=>register('Mismatch',{confirmPassword:'Other'}),/match/);
const b=await register('Ásdís',{email:'asdis@example.test'},{...context,browser:'browser-b'});assert.notEqual(b.account.playerId,a.account.playerId);checks++;
let profile=await r.handle('profile',{displayName:'Steini',bio:'Ég spila Chain Siege.'},{...context,token:a.token});assert.equal(profile.account.gamesUntilNameChange,100);checks++;
await bad(()=>r.handle('profile',{displayName:'STEINI'},{...context,token:b.token}),/taken/);
await bad(()=>register('Steini'),/Display name/);
await bad(()=>r.handle('profile',{displayName:'Another'},{...context,token:a.token}),/100 more games/);
await bad(()=>r.handle('profile',{country:'DK'},{...context,token:a.token}),/Confirm/);
profile=await r.handle('profile',{country:'DK',confirmCountryChange:true},{...context,token:a.token});assert.equal(profile.account.countryChanges,1);checks++;
await bad(()=>r.handle('profile',{country:'GB',confirmCountryChange:true},{...context,token:a.token}),/only be changed once/);
await bad(()=>r.handle('profile',{bio:'<script>no</script>'},{...context,token:a.token}),/plain text/);
await bad(()=>r.handle('profile',{username:'Renamed'},{...context,token:a.token}),/Unsupported/);
await bad(()=>r.handle('login',{username:'Þórður',password:'WrongPassword42'},context),/Incorrect/);
const login=await r.handle('login',{username:'ÞÓRÐUR',password:'Password42'},context);assert.equal(login.account.playerId,a.account.playerId);assert.equal(login.account.currentStreak,1);checks++;
let token=login.token;r.close();for(let i=0;i<3;i++){r=openRegistry(path.join(dir,'accounts'),{now:()=>time});const restored=await r.handle('me',{}, {...context,token});assert.equal(restored.account.bio,'Ég spila Chain Siege.');assert.equal(restored.account.country,'DK');r.close();checks++;}r=openRegistry(path.join(dir,'accounts'),{now:()=>time});
time+=86400000;assert.equal((await r.handle('me',{}, {...context,token})).account.currentStreak,2);assert.equal((await r.handle('me',{}, {...context,token})).newDay,false);time+=2*86400000;profile=await r.handle('me',{}, {...context,token});assert.equal(profile.account.currentStreak,1);assert.equal(profile.account.longestStreak,2);checks++;
await r.handle('logout',{}, {...context,token});assert.equal((await r.handle('me',{}, {...context,token})).account,null);assert.equal((await r.handle('me',{}, {...context,token:'forged'})).account,null);checks++;
await bad(()=>register('Honeypot',{website:'spam'},{...context,ip:'trap'}),/Human check/);await bad(()=>register('BadAnswer',{answer:'99'},{...context,ip:'answer'}),/Human check/);
const c=await r.handle('challenge',{},context);await bad(()=>r.handle('register',{challengeId:c.id,answer:'1'},{...context,browser:'foreign'}),/Human check/);
for(let i=0;i<20;i++)await bad(()=>r.handle('register',{}, {...context,ip:'limited'}),/Human check/);await bad(()=>r.handle('register',{}, {...context,ip:'limited'}),/Too many/);
const exp=await r.handle('login',{username:'Þórður',password:'Password42'},context);time+=31*86400000;assert.equal((await r.handle('me',{}, {...context,token:exp.token})).account,null);checks++;r.close();
const db=new DatabaseSync(path.join(dir,'accounts/registry.sqlite'));const rows=db.prepare('SELECT * FROM accounts').all();assert.equal(rows.length,2);assert.ok(rows.every(a=>a.password_hash.length===128&&!JSON.stringify(a).includes('Password42')));assert.ok(db.prepare('SELECT * FROM sessions').all().every(s=>s.token_hash!==exp.token));db.close();checks++;
let app=await startServer({port:0,registryDir:path.join(dir,'http'),playtestSnapshotOnly:true,logger:()=>{}});let cookie='';async function request(action,body={},origin=app.origin){const response=await fetch(app.origin+'/api/registry/'+action,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify(body)});for(const v of response.headers.getSetCookie()){const pair=v.split(';')[0],name=pair.split('=')[0];cookie=cookie.split('; ').filter(p=>p&&!p.startsWith(name+'=')).concat(pair).join('; ');}return {response,value:await response.json()};}
try{const gameResponse=await fetch(app.origin+'/api/open',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json'},body:'{}'});await gameResponse.json();const gameToken=gameResponse.headers.getSetCookie()[0].split(';')[0].slice(8),beforeGame=await app.checkpoint(gameToken);let ch=(await request('challenge')).value,nums=ch.question.match(/\d+/g);let created=await request('register',{username:'HttpUser',password:'Password42',confirmPassword:'Password42',country:'IS',challengeId:ch.id,answer:String(+nums[0]+ +nums[1])});assert.equal(created.response.status,200);assert.ok(created.response.headers.getSetCookie().some(c=>c.includes('HttpOnly')&&c.includes('SameSite=Strict')));assert.ok(!JSON.stringify(created.value).includes('password_hash'));assert.equal((await request('me',{},'http://foreign.test')).response.status,403);assert.equal(await app.checkpoint(gameToken),beforeGame);checks++;await app.close();const replacement=path.join(dir,'replacement-build');fs.cpSync(root,replacement,{recursive:true});const {startServer:replacementServer}=await import(pathToFileURL(path.join(replacement,'server/main.mjs')).href);app=await replacementServer({port:0,registryDir:path.join(dir,'http'),playtestSnapshotOnly:true,logger:()=>{}});assert.equal((await request('me')).value.account.username,'HttpUser');assert.equal((await fetch(app.origin+'/registry.sqlite')).status,404);assert.equal((await request('logout')).value.account,null);assert.equal((await request('me')).value.account,null);checks+=6;}finally{await app.close();}
console.log(JSON.stringify({passed:true,checks,dir,sqliteRestarts:3,httpRestart:true,serverDay:'UTC',replacementBuildSameAccounts:true,gameplayCheckpointUnchanged:true}));
