import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {migrateReplays,finalizeReplay,recentMatches,replayForProfile,backfillReplays,captureReplayCheckpoint} from '../server/replay-store.mjs';
import {buildReplay,publicCheckpoint} from '../server/replay.mjs';import {createReplayCursor} from '../client-v13/replay-state.js';
let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++;},dir=fs.mkdtempSync(path.join(os.tmpdir(),'cs-replay-')),file=path.join(dir,'registry.sqlite');let db=new DatabaseSync(file);
db.exec('CREATE TABLE stat_matches(id TEXT PRIMARY KEY,mode TEXT,player_count INTEGER,started_at INTEGER,ended_at INTEGER,descriptor TEXT,finalized INTEGER,event_cursor INTEGER);CREATE TABLE stat_participants(match_id TEXT,player_id TEXT,actor TEXT,kind TEXT,outcome TEXT,reliability TEXT,placement INTEGER,match_score REAL,score_components TEXT);CREATE TABLE stat_facts(match_id TEXT,kind TEXT,sequence INTEGER,payload TEXT,PRIMARY KEY(match_id,kind,sequence));');migrateReplays(db);
function add(id,time,players=['A','B'],mode='Duel',reliability='Full'){
 const d={id,mode,startedAt:time-1,endedAt:time,build:'test',configuration:{size:5,rulesVersion:'v1',players:[{id:'p0',boardId:'b0'},{id:'p1',boardId:'b1'}]},participants:players.map((p,i)=>({actor:'p'+i,seat:i,playerId:p,kind:p?'account':'guest',displayName:p||'Guest',reliability,takeover:reliability==='Quit'?'surrender':undefined})),initialRng:{secret:true},initialPlacements:[{secret:true}]};
 const facts=[{index:0,turnIndex:1,event:{kind:'impact',unitId:'SECRET-UNIT',cells:[{x:1,y:1}],meta:{ownerId:'p0',targetBoardId:'b1',source:'direct-human'},statistics:{unitType:'castle',private:'SECRET'}}},{index:1,turnIndex:2,event:{kind:'attack-started',reason:'archer',meta:{ownerId:'p1'},statistics:{plannedCells:[{x:4,y:4}]}}},{index:2,turnIndex:2,event:{kind:'impact',unitId:null,cells:[{x:2,y:2}],meta:{ownerId:'p1',targetBoardId:'b0',source:'plague'},statistics:{eliminationBoundary:{dead:['p0']}}}}];
 db.prepare('INSERT INTO stat_matches VALUES(?,?,?,?,?,?,1,?)').run(id,mode,2,time-1,time,JSON.stringify(d),facts.length);for(const p of d.participants)db.prepare('INSERT INTO stat_participants VALUES(?,?,?,?,?,?,?,NULL,NULL)').run(id,p.playerId,p.actor,p.kind,'Loss',p.reliability,2);for(const f of facts)db.prepare("INSERT INTO stat_facts VALUES(?,'event',?,?)").run(id,f.index,JSON.stringify(f));finalizeReplay(db,d,facts);return {d,facts};
}
const first=add('shared',1);eq(recentMatches(db,'A')[0].matchId,'shared');eq(recentMatches(db,'B')[0].matchId,'shared');eq(db.prepare('SELECT count(*) n FROM stat_replays').get().n,1);
for(let i=2;i<=6;i++)add('A'+i,i,['A',null],'Single Player');eq(recentMatches(db,'A').map(r=>r.matchId),['A6','A5','A4','A3','A2']);eq(!!replayForProfile(db,'B','shared'),true);eq(replayForProfile(db,'A','shared'),null);
for(let i=7;i<=11;i++)add('B'+i,i,['B',null]);eq(db.prepare("SELECT count(*) n FROM stat_replays WHERE match_id='shared'").get().n,0);
add('story',12,['A',null],'Story');eq(recentMatches(db,'A').some(r=>r.matchId==='story'),false);add('guest',13,[null,null]);eq(db.prepare("SELECT count(*) n FROM stat_replays WHERE match_id='guest'").get().n,0);
const quit=add('surrender',14,['A',null],'Duel','Quit');eq(recentMatches(db,'A')[0].participation,'Disconnect/Abandon');eq(recentMatches(db,'A')[0].departureReason,'surrender');add('disconnect',15,['A',null],'Duel','Disconnect');eq(recentMatches(db,'A')[0].participation,'Disconnect/Abandon');
const count=db.prepare('SELECT count(*) n FROM stat_replays').get().n;finalizeReplay(db,quit.d,quit.facts);eq(db.prepare('SELECT count(*) n FROM stat_replays').get().n,count);db.close();db=new DatabaseSync(file);eq(recentMatches(db,'A')[0].matchId,'disconnect');eq(!!replayForProfile(db,'A','surrender'),true);
const replay=buildReplay(first.d,first.facts),text=JSON.stringify(replay);for(const secret of ['SECRET','initialRng','initialPlacements','plannedCells','unitId','playerId','castle'])eq(text.includes(secret),false);
const cursor=createReplayCursor(replay),end=cursor.seek(cursor.length);eq(end.boards[0].eliminated,true);eq(end.boards[0].cells['2,2'].plague,true);eq(end.boards[1].cells['1,1'].kind,undefined);eq(cursor.seek(0).boards[1].cells,{});eq(cursor.seek(cursor.length),end);eq(cursor.seek(2).boards[1].cells['1,1'].observation,'hit');eq(cursor.seek(1).turn,1);
const h={events:[],round:1,turnIndex:1,activePlayerId:'p0',config:{size:5,players:first.d.configuration.players},state:{match:{knowledge:{p0:{boards:{p1:{cells:[{cell:{x:1,y:1},observation:'impact',unitType:null}]}}},p1:{boards:{p0:{cells:[]}}}},units:[{secret:true}],rng:{secret:true}}}};
eq(JSON.stringify(publicCheckpoint(h)).includes('secret'),false);captureReplayCheckpoint(db,quit.d,h);h.events=[{}];captureReplayCheckpoint(db,quit.d,h);captureReplayCheckpoint(db,quit.d,h);eq(db.prepare("SELECT count(*) n FROM stat_facts WHERE match_id=? AND kind='public-replay'").get(quit.d.id).n,2);
const r=buildReplay(first.d,first.facts,[{cursor:0,value:{round:1,turn:1,active:0,boards:[]}},{cursor:3,value:{round:2,turn:2,active:1,boards:[]}}]);eq(createReplayCursor(r).seek(r.timeline.length).round,2);eq(createReplayCursor(r).seek(1).round,1);
const a=backfillReplays(db,{apply:true}),b=backfillReplays(db,{apply:true});eq(a,b);db.close();console.log(JSON.stringify({passed:true,checks,dir}));
