import {startResolution} from '../canonical/compiled/combat/resolver.js';
import assert from 'node:assert/strict';
import {createHost,place} from '../canonical/compiled/host/initialization.js';
import {pumpHost} from '../canonical/compiled/host/lifecycle.js';
import {serializeHost,deserializeHost} from '../canonical/compiled/host/serialization.js';
import {heroOnly,observeRevolt,earnedScores} from '../canonical/compiled/host/revolt.js';
import {finalPlacements} from '../server/result-screen.mjs';
import {summarizeMatch} from '../server/statistics-metrics.mjs';
import {tacticalScoreFacts} from '../server/score-tactics.mjs';
import {createReplayCursor} from '../client-v13/replay-state.js';
import {publicStatistics,emptyStatistics} from '../canonical/compiled/local-host/public-statistics.js';
import {syncRing} from '../canonical/compiled/host/ring.js';
import {createPrivateReplay,recordReplayStep,replayPrivate} from '../canonical/compiled/host/replay.js';
import {roomPresentation} from '../server/room-presentation.mjs';
import {groupPresentation} from '../server/group-presentation.mjs';
import {calculateScores} from '../server/match-score.mjs';
import {prepareStatistics} from '../server/statistics-capture.mjs';
import {buildReplay} from '../server/replay.mjs';
let checks=0;
function fixture(n=2,forced=false,extra={}){const h=createHost({matchId:'revolt-test',rulesVersion:'stone-throw-pacing-v1',size:15,story:false,seed:42,players:Array.from({length:n},(_,i)=>({id:'p'+i,boardId:'b'+i,roster:{hero:1,...extra},decisionMode:'interactive'}))});for(let i=0;i<n;i++){place(h,{unitId:'hero'+i,ownerId:'p'+i,boardId:'b'+i,type:'hero',cells:[{x:14,y:14}]});const u=h.state.match.units.at(-1);u.hero.activated=true;u.hero.hitsTaken=2;u.damage.hitsTaken=2;u.hero.originalCell={x:14,y:14};if(forced)for(let y=0;y<15;y++)for(let x=0;x<15;x++)if(x!==14||y!==14)h.state.seats[i].shots.push(x+','+y);}
 h.activePlayerId='p0';h.starterId='p0';h.round=1;h.turnIndex=1;h.status='running';h.turnStep='enter';pumpHost(h);return h;}
function turn(h,resume=false){h.status='running';h.turnStep='finish';pumpHost(h,100000,resume?{observePresentationStep:live=>{Object.assign(live,deserializeHost(serializeHost(live)));}}:undefined);if(h.status==='awaiting-turn'){h.status='running';pumpHost(h);}return h;}
const impacts=h=>h.events.filter(r=>r.event.kind==='impact'&&r.event.meta?.source==='revolt');
for(const n of [2,3,4]){const h=fixture(n);assert.ok(heroOnly(h));for(let i=0;i<n*2;i++)turn(h);assert.equal(h.state.revolt.rounds,2);assert.equal(impacts(h).length,0);for(let i=0;i<n;i++)turn(h);assert.equal(h.state.revolt.level,1);assert.equal(impacts(h).length,n);for(let i=0;i<n;i++)turn(h);assert.equal(h.state.revolt.level,2);assert.equal(impacts(h).length,n*3);for(const id of h.config.players.map(p=>p.id)){const hits=impacts(h).filter(r=>r.event.meta.targetPlayerId===id).map(r=>r.event.cells[0]);assert.equal(new Set(hits.map(c=>c.x+','+c.y)).size,3);}assert.deepEqual(h.counters.map(c=>[c.shots,c.cellsAffected,c.biggestAttack]),Array.from({length:n},()=>[0,0,0]));checks+=5;}
{const h=fixture();h.state.match.units[0].hero.activated=false;assert.equal(heroOnly(h),false);h.state.match.units[0].hero.activated=true;h.state.match.units.push({ ...structuredClone(h.state.match.units[0]),id:'inf',type:'inf',hero:null,cells:[{x:5,y:5}]});assert.equal(heroOnly(h),false);h.state.match.units.at(-1).type='wizard';assert.equal(heroOnly(h),true);turn(h);turn(h);assert.equal(h.state.revolt.rounds,1);h.state.match.units.at(-1).type='inf';observeRevolt(h);assert.equal(h.state.revolt.rounds,0);assert.equal(h.state.revolt.qualifying,false);checks+=5;}
for(const n of [2,3,4]){const h=fixture(n,true),resumed=structuredClone(h);for(let i=0;i<n*3&&h.status!=='complete';i++)turn(h);for(let i=0;i<n*3&&resumed.status!=='complete';i++)turn(resumed,true);assert.equal(serializeHost(resumed),serializeHost(h));assert.equal(h.status,'complete');assert.equal(impacts(h).length,n);assert.equal(h.state.match.units.filter(u=>u.hero?.currentCell).length,0);assert.equal(h.state.match.outcome.kind,n===2?'draw':'win');const facts=h.events.map((r,index)=>({...r,index})),d={participants:h.config.players.map(p=>({actor:p.id,kind:'guest',reliability:'Full'})),configuration:h.config,endedAt:1};for(const row of impacts(h)){assert.equal(row.event.meta.actorId,null);assert.equal(row.event.meta.ownerId,null);assert.equal(row.event.statistics.rootActorId,null);}for(const m of Object.values(summarizeMatch(d,facts))){assert.equal(m.shots,0);assert.equal(m.unitsKilled,0);assert.equal(m.coreKills,0);assert.equal(m.biggestChain,0);}for(const m of Object.values(tacticalScoreFacts(d,facts))){assert.equal(m.kills,0);assert.deepEqual(m.issues,[]);}const replay=buildReplay(d,facts);assert.equal(replay.timeline.filter(e=>e.kind==='revolt').length,n);assert.equal(replay.timeline.filter(e=>e.name==='peasant-revolt').length,1);assert.ok(replay.timeline.filter(e=>e.kind==='revolt').every(e=>e.actor===-1));checks+=8;}
// Unequal earned scores, deliberately opposite technical resolution order.
for(const n of [3,4]){const h=fixture(n,true);for(let i=0;i<n;i++)h.events.push({turnIndex:0,event:{sequence:i+1,rootId:'scout-'+i,workId:null,kind:'scouted',meta:null,unitId:null,cells:[],amount:null,reason:'scout',statistics:{scout:{actorId:'p'+i,boardId:'b'+((i+1)%n),cells:Array.from({length:i+1},(_,j)=>({cell:{x:j,y:0},unitId:'seen'+i+'x'+j,unitType:'inf'}))}}}});const before=earnedScores(h);assert.ok(Number(before['p'+(n-1)].n)>Number(before.p0.n));for(let i=0;i<n*3&&h.status!=='complete';i++)turn(h);assert.deepEqual(finalPlacements(h),Array.from({length:n},(_,i)=>n-i));assert.deepEqual(h.state.match.outcome.winnerIds,['p'+(n-1)]);const boundary=h.events.at(-1).event.statistics.eliminationBoundary;assert.deepEqual(boundary.revoltScores,before);checks+=3;}

// Qualifying starts mid-turn: that partial turn cannot count as a full round.
{const h=fixture();delete h.state.revolt;observeRevolt(h);turn(h);assert.equal(h.state.revolt.rounds,0);turn(h);assert.equal(h.state.revolt.rounds,0);turn(h);assert.equal(h.state.revolt.rounds,1);checks++;}
// Two remaining players in an originally four-player game still draw together.
{const h=fixture(4,true);for(const i of [2,3]){h.state.match.units[i].hero.currentCell=null;h.state.match.units[i].cells=[];h.state.match.units[i].lifecycle='destroyed';}h.state.ring.order=['p0','p1'];h.state.ring.eliminated=['p2','p3'];h.events.push({turnIndex:0,event:{sequence:1,rootId:'earlier',workId:null,kind:'resolution-completed',meta:null,unitId:null,cells:[],amount:null,reason:null,statistics:{eliminationBoundary:{dead:['p2','p3'],survivors:2}}}});syncRing(h.state);for(let i=0;i<6&&h.status!=='complete';i++)turn(h);assert.equal(h.state.match.outcome.kind,'draw');assert.deepEqual(finalPlacements(h).slice(0,2),[1,1]);checks++;}
// Simultaneous partial casualties remain a single score-ordered elimination boundary.
for(const n of [3,4]){const h=fixture(n,true);h.state.seats[n-1].shots=[];for(let i=0;i<n;i++)h.events.push({turnIndex:0,event:{sequence:i+1,rootId:'earned-'+i,workId:null,kind:'scouted',meta:null,unitId:null,cells:[],amount:null,reason:'scout',statistics:{scout:{actorId:'p'+i,boardId:'b'+((i+1)%n),cells:Array.from({length:i+1},(_,j)=>({cell:{x:j,y:0},unitId:'known'+i+'x'+j,unitType:'inf'}))}}}});for(let i=0;i<n*3&&h.status!=='complete';i++)turn(h);assert.equal(h.status,'complete');assert.deepEqual(finalPlacements(h),Array.from({length:n},(_,i)=>n-i));assert.equal(h.events.at(-1).event.statistics.eliminationBoundary.dead.length,n-1);checks++;}
// Public replay seek and displayed kill counters also preserve neutral attribution.
{const h=fixture(2,true);for(let i=0;i<6&&h.status!=='complete';i++)turn(h);const stats=publicStatistics(h,emptyStatistics());assert.equal(stats.playerUnitsDestroyed,0);assert.equal(stats.enemyUnitsDestroyed,0);assert.equal(stats.playerCoreDestroyed,0);assert.equal(stats.enemyCoreDestroyed,0);const facts=h.events.map((r,index)=>({...r,index})),d={participants:h.config.players.map((p,i)=>({seat:i,actor:p.id,displayName:'Player '+i,kind:'guest',reliability:'Full'})),configuration:h.config,endedAt:1};const replay=buildReplay(d,facts),cursor=createReplayCursor(replay),last=cursor.seek(cursor.length);assert.ok(last.boards.every(b=>b.cells['14,14'].observation==='hit'));assert.ok(replay.timeline.filter(e=>e.kind==='announcement').every(e=>!e.cells));checks+=2;}

// Private replay reproduces the round boundary, target draws and all authoritative facts.
{const h=fixture();h.state.revolt.rounds=2;h.state.revolt.waiting=['p0'];h.state.revolt.started=['p0'];h.status='awaiting-turn';h.turnStep='finish';const record=createPrivateReplay(h),out=recordReplayStep(record,h,{kind:'command',command:{id:'boundary',kind:'advance-turn'}});assert.equal(out.state.revolt.level,1);assert.equal(serializeHost(replayPrivate(record)),serializeHost(out));checks++;}
// The actual server adapters route neutral impacts to every board for every observer.
for(const n of [2,4]){const h=fixture(n,true),r={host:h,epoch:1,memory:{},seats:Array.from({length:n},(_,i)=>({name:'Player '+i,controller:'human'}))};const project=(room,i)=>({snapshot:{eventPosition:room.host.state.match.knowledge['p'+i].events.length,battle:'test',revision:1,size:15},events:[]}),adapter=n===2?roomPresentation(project,(r,i)=>1-i):groupPresentation(project,(r,i)=>(i+1)%n);for(let i=0;i<n*3-1;i++)turn(h);adapter.begin(r);h.status='running';h.turnStep='finish';pumpHost(h,100000,adapter.execution(r));adapter.finish?.(r);for(let i=0;i<n;i++){const frames=r.presentation[i].filter(f=>f.animation?.kind==='revolt');assert.equal(frames.length,n);assert.deepEqual(frames.map(f=>f.animation.targetSeat).sort(),Array.from({length:n},(_,i)=>i));assert.ok(frames.every(f=>!('scores'in f.animation)&&!('players'in f.animation)));}checks+=n;}
// Score ordering does not follow the physical ring / impact order.
for(const order of [['p0','p1','p2','p3'],['p0','p3','p2','p1']]){const h=fixture(4,true);h.state.ring.order=order;syncRing(h.state);for(let i=0;i<4;i++)h.events.push({turnIndex:0,event:{sequence:i+1,rootId:'earned-'+i,workId:null,kind:'scouted',meta:null,unitId:null,cells:[],amount:null,reason:'scout',statistics:{scout:{actorId:'p'+i,boardId:'b'+((i+1)%4),cells:Array.from({length:i+1},(_,j)=>({cell:{x:j,y:0},unitId:'known'+i+'x'+j,unitType:'inf'}))}}}});for(let i=0;i<12&&h.status!=='complete';i++)turn(h);assert.deepEqual(finalPlacements(h),[4,3,2,1]);checks++;}

// A normal Hero elimination does not reset an otherwise uninterrupted Hero-only count.
{const h=fixture(4);h.state.revolt.rounds=2;const u=h.state.match.units[3];u.hero.currentCell=null;u.cells=[];u.lifecycle='destroyed';observeRevolt(h);assert.equal(h.state.revolt.rounds,2);assert.ok(!h.state.revolt.waiting.includes('p3'));checks++;}
// Canonical special-unit reactions are retained, with the whole causal pulse uncredited.
{const h=fixture(2,true,{wizard:1});for(let i=0;i<2;i++){h.status='placement';place(h,{unitId:'wizard'+i,ownerId:'p'+i,boardId:'b'+i,type:'wizard',cells:[{x:0,y:0}]});h.state.seats[i].shots=h.state.seats[i].shots.filter(k=>k!=='0,0');}h.status='awaiting-command';for(let i=0;i<6;i++)turn(h);assert.ok(h.events.some(r=>r.event.kind==='attack-started'&&r.event.reason==='wizard'));const facts=h.events.map((r,index)=>({...r,index})),d={participants:h.config.players.map(p=>({actor:p.id,kind:'guest',reliability:'Full'}))};for(const m of Object.values(summarizeMatch(d,facts))){assert.equal(m.shots,0);assert.equal(m.unitsKilled,0);assert.equal(m.biggestChain,0);}for(const m of Object.values(tacticalScoreFacts(d,facts)))assert.deepEqual(m.issues,[]);checks++;}

for(const n of [2,3,4]){const h=fixture(n,true);for(let i=0;i<n*3&&h.status!=='complete';i++)turn(h);const facts=h.events.map((r,index)=>({...r,index})),participants=h.config.players.map((p,i)=>({name:'Player '+i,controller:i===n-1?'ai':'human',identity:{kind:'guest'}})),descriptor=prepareStatistics({},h,1,{mode:n===2?'Duel':n+' Players',build:'test',now:()=>1,participants});const scores=calculateScores(descriptor,facts).scores;assert.ok(scores.every(s=>s.issues.length===0));for(const s of scores)for(const k of ['efficiency','biggestChain','specialAbilityKills'])assert.equal(s.components[k].n,'0');checks++;}

// If the last unfinished seat dies, the completed survivors receive the pulse before another turn.
{const h=fixture(4);h.activePlayerId='p3';h.state.revolt.rounds=2;h.state.revolt.waiting=['p3'];h.state.revolt.started=['p3'];const u=h.state.match.units[3];u.hero.currentCell=null;u.cells=[];u.lifecycle='destroyed';h.pendingRoot=startResolution(h.state,'ending-turn','ending-turn','p3',[],h.rng);h.rootPurpose='shot';h.rootEventCursor=0;h.status='running';pumpHost(h);assert.equal(h.state.revolt.level,1);assert.equal(impacts(h).length,3);assert.equal(h.activePlayerId,'p0');assert.equal(h.status,'awaiting-command');assert.equal(h.turnStep,'actions');checks++;}
console.log(JSON.stringify({passed:true,checks}));
