import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {profileFixture} from './profile-fixture.mjs';
import {spectatorView} from '../server/spectator.mjs';import {startServer} from '../server/main.mjs';
const {launch}=await import(process.env.ST_BROWSER_HARNESS||'playwright');let checks=0;
function fixture(n){return {code:'ABC123',revision:1,seats:Array.from({length:n},(_,i)=>({name:'Player '+(i+1),token:'PRIVATE-TOKEN'})),host:{round:2,status:'awaiting-command',activePlayerId:'p0',config:{size:15,players:Array.from({length:n},(_,i)=>({id:'p'+i,boardId:'b'+i}))},state:{match:{units:[{id:'hit',ownerId:'p0',type:'archer',cells:[{x:1,y:1}]},{id:'secret',ownerId:'p0',type:'wizard',cells:[{x:9,y:9}]}]}},events:[{event:{kind:'impact',unitId:'hit',meta:{targetBoardId:'b0'},cells:[{x:1,y:1}]}},{event:{kind:'impact',unitId:null,meta:{targetBoardId:'b0'},cells:[{x:2,y:2}]}}]}};}
for(const n of [2,3,4]){const r=fixture(n),before=JSON.stringify(r),view=spectatorView(r);assert.equal(view.boards.length,n);assert.equal(view.boards[0].cells.length,2);assert.ok(!/PRIVATE|secret|wizard|ownerId|boardId|unitId/.test(JSON.stringify(view)));assert.equal(JSON.stringify(r),before);r.host.state.match.units[0].cells=[{x:8,y:8}];assert.deepEqual(spectatorView(r),view);r.host.status='placement';assert.ok(spectatorView(r).boards.every(b=>b.cells.length===0));checks+=5;}
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cs-spectate-')),fixtureAccount=await profileFixture(dir),token=fixtureAccount.users[0].token;fixtureAccount.registry.close();
const app=await startServer({port:0,lan:true,registryDir:dir,playtestSnapshotOnly:true,logger:()=>{}}),browser=await launch();
try{const host=await browser.newContext(),watch=await browser.newContext();const post=(c,route,data={})=>c.request.post(app.origin+'/api/'+route,{headers:{Origin:app.origin},data});await post(host,'open');await post(watch,'open');const made=await (await post(host,'pvp/make',{slots:['human','human','ai','ai']})).json(),code=made.update.lan.code,room=app.pvp.rooms.get(code),before=JSON.stringify(room.seats);const observed=await post(watch,'pvp/spectate',{code});assert.equal(observed.status(),200);assert.equal((await observed.json()).boards.length,4);assert.equal(JSON.stringify(room.seats),before);await host.close();await watch.close();checks+=3;for(const width of [1440,390]){const p=await browser.newPage({viewport:{width,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.context().addCookies([{name:'csAccount',value:token,url:app.origin},{name:'csRegistryBrowser',value:'a'.repeat(48),url:app.origin}]);await p.goto(app.origin);await p.locator('#stStartupEnter').click();await p.waitForFunction(()=>document.documentElement.dataset.localHost==='connected');const missing=await p.evaluate(async()=>{const r=await fetch('/api/pvp/spectate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'ZZZZZZ'})});return r.status;});assert.equal(missing,404);await p.route('**/api/pvp/spectate',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(spectatorView(fixture(4)))}));await p.evaluate(()=>window.__stoneThrowOpenMainMenu());await p.locator('#stMenuOnline').click();await p.locator('#csSpectateTab').click();await p.locator('#stLanCode').fill('ABC123');await p.locator('#stLanJoin').click();await p.locator('.cs-spectator').waitFor();assert.equal(await p.locator('.cs-spectator-grid').count(),4);assert.equal(await p.locator('.cs-spectator-grid .hit').count(),1);assert.equal(await p.locator('.cs-spectator').evaluate(e=>e.scrollWidth>e.clientWidth),false,JSON.stringify(await p.locator('.cs-spectator').evaluate(e=>({width:innerWidth,client:e.clientWidth,scroll:e.scrollWidth,children:[...e.querySelectorAll('*')].filter(x=>x.getBoundingClientRect().right>e.getBoundingClientRect().right).map(x=>[x.className,x.getBoundingClientRect().width]).slice(0,20)}))));await p.screenshot({path:path.join(os.tmpdir(),'chain-siege-spectator-'+width+'.png')});await p.getByRole('button',{name:'LEAVE SPECTATING',exact:true}).click();assert.equal(await p.locator('.cs-spectator').count(),0);assert.deepEqual(errors,[]);checks+=6;await p.close();}console.log(JSON.stringify({passed:true,checks}));}finally{await browser.close();await app.close();}
