import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {DatabaseSync} from 'node:sqlite';
import {openRegistry as phase1} from '../../../registry-phase1/candidate/server/registry.mjs';
import {openRegistry} from '../server/registry.mjs';import {summarizeMatch,reliabilityAccounting,aggregate,futureHallOfFameEligible} from '../server/statistics-metrics.mjs';import {prepareStatistics} from '../server/statistics-capture.mjs';
import {createHost} from '../canonical/compiled/host/initialization.js';
import {createPvpService} from '../server/multiplayer.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dir=fs.mkdtempSync(path.resolve(root,'../statistics-check-'));let checks=0;
const context={ip:'local',browser:'test'},old=phase1(dir);const ch=await old.handle('challenge',{},context),n=ch.question.match(/\d+/g);const account=await old.handle('register',{username:'StatsUser',password:'Password42',confirmPassword:'Password42',country:'IS',challengeId:ch.id,answer:String(+n[0]+ +n[1])},context);old.close();
let db=new DatabaseSync(path.join(dir,'registry.sqlite'));const before=db.prepare('SELECT * FROM accounts').all(),sessions=db.prepare('SELECT * FROM sessions').all();db.close();let registry=openRegistry(dir);assert.ok(fs.existsSync(registry.migrationBackup));db=new DatabaseSync(registry.file);assert.equal(db.prepare('PRAGMA user_version').get().user_version,2);assert.deepEqual(db.prepare('SELECT * FROM accounts').all(),before.map(a=>Object.assign(Object.create(null),a,{avatar_id:a.avatar_id==='registered-default'?'peasant-human-male-01':a.avatar_id})));assert.deepEqual(db.prepare('SELECT * FROM sessions').all(),sessions);checks++;
const backup=new DatabaseSync(registry.migrationBackup,{readOnly:true});assert.deepEqual(backup.prepare('SELECT * FROM accounts').all(),before);assert.equal(backup.prepare('PRAGMA user_version').get().user_version,1);backup.close();checks++;
const players=[{actor:'a',seat:0,kind:'account',playerId:account.account.playerId,outcome:'Win',reliability:'Full'},{actor:'b',seat:1,kind:'guest',playerId:null,outcome:'Loss',reliability:'Full'},{actor:'c',seat:2,kind:'ai',playerId:null}];
const descriptor={id:'metrics',epoch:1,mode:'3 Players',build:'test',startedAt:1,endedAt:2,participants:players};let facts=[];
function event(kind,owner='a',type=null,source='direct-human',extra={}){const i=facts.length,e={kind,rootId:extra.rootId||'root-'+i,workId:extra.workId||'frame-'+i,meta:{ownerId:owner,actorId:owner,targetPlayerId:'b',targetBoardId:'board-b',source,sourceUnitId:'source'},unitId:type?'unit-'+i:null,cells:[{x:i%15,y:0}],statistics:{unitType:type,unitOwner:'b',rootActorId:owner},...extra};facts.push({index:i,event:e});return e;}
for(const type of ['inf','inf',null,'inf',null,null])event('impact','a',type);let sum=summarizeMatch(descriptor,facts).a;assert.equal(sum.shots,6);assert.equal(sum.hits,3);assert.equal(sum.bestHitStreak,2);assert.equal(sum.bestMissStreak,2);assert.equal(sum.oneHitWonder,1);assert.equal(sum.accuracy,.5);checks++;
for(const [type,source]of [['castle','catapult-shot'],['dwarf','direct-human'],['hero','plague'],['wizard','wizard'],['demon','archer'],['elf','archer']]){const e=event('impact','a',type,source);event('unit-destroyed','a',type,source,{unitId:e.unitId,rootId:e.rootId});}
event('attack-started','a','dragon','dragon',{reason:'dragon'});event('attack-started','a','monk','monk-deflect',{reason:'monk-deflect'});event('resurrection','a','cav','chain',{cells:[{x:1,y:1},{x:2,y:1}],statistics:{unitOwner:'a',unitType:'cav'}});
for(let i=0;i<9;i++)event('impact','a','inf','archer',{rootId:'volley',workId:'volley'});
event('attack-started','a','goblin','goblin',{reason:'goblin',statistics:{plannedCells:[{x:1,y:1},{x:2,y:1}]}});event('impact','a',null,'goblin');event('scouted','a',null,'chain',{statistics:{scout:{actorId:'a',cells:[{unitId:'found'}, {unitId:null}]}}});
sum=summarizeMatch(descriptor,facts).a;for(const k of ['castleCatapultHits','dwarfHits','heroHits','wizardHits','demonKills','elvesKilled','dragonsActivated','monkDeflections','resurrections','perfectVolleys','plagueCells','scoutFound'])assert.equal(sum[k],1,k);assert.equal(sum.goblinBombs,2);assert.equal(sum.wizardAttackHits,1);assert.equal(sum.scoutInspected,2);assert.equal(sum.biggestChain,9);assert.equal(sum.cellBlaster.denominator,1);checks++;
const tied=structuredClone(facts);for(const f of facts){const e=structuredClone(f.event);if(e.meta){e.meta.ownerId='b';e.meta.actorId='b';}e.statistics={...e.statistics,rootActorId:'b',unitOwner:'a'};if(e.statistics.scout)e.statistics.scout={...e.statistics.scout,actorId:'b'};tied.push({index:tied.length,event:{...e,rootId:'b-'+e.rootId,unitId:e.unitId?'b-'+e.unitId:null}});}const tie=summarizeMatch(descriptor,tied);assert.ok(tie.a.awards.includes('Lucky Shooter'));assert.ok(tie.b.awards.includes('Lucky Shooter'));checks++;
let rel=reliabilityAccounting(null,'AFK','afk');for(let i=0;i<9;i++)rel=reliabilityAccounting(rel,'Full','f'+i);rel=reliabilityAccounting(rel,'AFK','again');assert.equal(rel.cleanStreak,0);for(let i=0;i<10;i++)rel=reliabilityAccounting(rel,'Full','g'+i);assert.equal(rel.activeAFK,1);assert.equal(rel.forgiven,1);assert.equal(rel.effectiveFull,20);assert.equal(rel.total,21);rel=reliabilityAccounting(rel,'Kick','kick');assert.equal(rel.Kick,1);assert.equal(rel.total,22);checks++;
let ag;for(let i=0;i<10;i++){ag=aggregate(ag,sum,'a'+i);assert.equal(futureHallOfFameEligible(ag),i===9);}checks++;
event('impact','b','inf');event('impact','c','inf');event('impact','c',null,'plague');
const host=createHost({matchId:'metrics-host',rulesVersion:'stone-throw-v1.427',size:15,story:false,seed:42,players:players.map(p=>({id:p.actor,boardId:'board-'+p.actor,roster:{inf:1},decisionMode:'interactive'}))});host.events=facts.map(f=>({event:f.event}));registry.statistics.capture(descriptor,host);const inspected=registry.statistics.inspect(account.account.playerId);assert.equal(inspected.global.playerShots,sum.shots+1);assert.equal(inspected.global.cellsHit,sum.destructiveCells+1);assert.equal(inspected.global.plagueCells,1);assert.equal(inspected.modes.find(x=>x.mode==='3 Players').games,1);assert.equal(db.prepare('SELECT count(*) n FROM stat_participants WHERE player_id IS NOT NULL').get().n,1);assert.equal(db.prepare('SELECT match_score FROM stat_participants LIMIT 1').get().match_score,null);const first=JSON.stringify(inspected);for(let i=0;i<3;i++){registry.close();registry=openRegistry(dir);assert.equal(registry.migrationBackup,null);registry.statistics.capture(descriptor,host);assert.equal(JSON.stringify(registry.statistics.inspect(account.account.playerId)),first);}checks++;
// Real Duel/Group authoritative actions; capture is observational, independent of gameplay RNG.
for(const count of [2,3,4]){const service=createPvpService({inf:1},{seed:42});try{const made=await service.lobby('make',{seats:count,controllers:Array(count).fill('human'),name:'Stats',identity:{kind:'account',playerId:account.account.playerId}},'a'),room=service.rooms.get(made.update.lan.code),clients=[{token:made.token,binding:'a'}];for(let i=1;i<count;i++){const j=await service.lobby('join',{code:room.code,name:'Guest'+i,identity:{kind:'guest'}},'b'+i);clients.push({token:j.token,binding:'b'+i});}
 const capture=()=>{const before=JSON.stringify(room.host),d=prepareStatistics(room,room.host,room.epoch,{mode:count===2?'Duel':count+' Players',build:'test',now:()=>100,participants:room.seats,news:room.news});if(d)registry.statistics.capture(d,room.host);assert.equal(JSON.stringify(room.host),before);return d;};capture();
 for(let i=0;i<count;i++){const c=clients[i];let u=await service.route(c.token,c.binding,'read');await service.route(c.token,c.binding,'command',{contract:u.snapshot.contract,battle:u.snapshot.battle,revision:u.snapshot.revision,intent:{kind:'place',unit:'inf',cells:[{x:5,y:5}]}});u=await service.route(c.token,c.binding,'read');const out=await service.route(c.token,c.binding,'command',{contract:u.snapshot.contract,battle:u.snapshot.battle,revision:u.snapshot.revision,intent:{kind:'start'}});assert.notEqual(out.accepted,false,JSON.stringify(out));capture();}
 assert.notEqual(room.host.status,'placement');let d=capture();const id=d.id;capture();assert.equal(room.matchStatistics.id,id);const target=room.host.state.match.units.find(u=>u.ownerId!==room.host.activePlayerId),i=room.host.config.players.findIndex(p=>p.id===room.host.activePlayerId),c=clients[i],u=await service.route(c.token,c.binding,'read');const out=await service.route(c.token,c.binding,'command',{contract:u.snapshot.contract,battle:u.snapshot.battle,revision:u.snapshot.revision,intent:{kind:'shoot',cell:target.cells[0]}});assert.notEqual(out.accepted,false,JSON.stringify(out));capture();assert.equal(room.matchStatistics.id,id);let finish=0;while(room.host.status!=='complete'){assert.ok(++finish<5);const who=room.host.config.players.findIndex(p=>p.id===room.host.activePlayerId),client=clients[who],view=await service.route(client.token,client.binding,'read'),shot=await service.route(client.token,client.binding,'command',{contract:view.snapshot.contract,battle:view.snapshot.battle,revision:view.snapshot.revision,intent:{kind:'shoot',cell:{x:5,y:5}}});assert.notEqual(shot.accepted,false);capture();}assert.ok(room.matchStatistics.endedAt);assert.equal(db.prepare('SELECT finalized FROM stat_matches WHERE id=?').get(id).finalized,1);if(count===2){for(const c of clients)await service.route(c.token,c.binding,'rematch');capture();assert.notEqual(room.matchStatistics.id,id);}checks++;
 }finally{await service.close();}}
const prior=registry.statistics.inspect(account.account.playerId);const draw={...descriptor,id:'draw',mode:'Duel',participants:players.map(p=>({...p,outcome:'Draw',reliability:p.kind==='ai'?null:'Full'}))};registry.statistics.capture(draw,{...host,events:[]});assert.equal(registry.statistics.inspect(account.account.playerId).modes.find(m=>m.mode==='Duel').draws,1);assert.equal(registry.statistics.leaderboard('3 Players')['Siege Champion'].length,1);assert.ok(registry.statistics.inspect(account.account.playerId).modes.every(m=>!('eligible' in m)));assert.equal(db.prepare('SELECT count(*) n FROM stat_career WHERE player_id IS NULL').get().n,0);checks++;
registry.close();db.close();console.log(JSON.stringify({passed:true,checks,dir,migrationPopulated:true,backup:true,idempotentRestarts:3,liveDuelGroup:true}));
