// Private server-only review foundation. Signals never change account status.
export const REVIEW_POLICY=Object.freeze({version:1,illegalTargetWeight:10,independentOpeningWeight:10,heroFirstWeight:2,heroEarlyWeight:1,highAccuracyWeight:2,highAccuracyMinimumShots:50,highAccuracyRatio:0.8,hiddenStreak:8,coreStreak:10,extremeScore:2500,extremeChain:150});
const parse=value=>value?JSON.parse(value):null;
export function migrateReview(db){db.exec(`
 CREATE TABLE IF NOT EXISTS review_retention(match_id TEXT PRIMARY KEY REFERENCES stat_matches(id),version INTEGER NOT NULL,coverage TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS review_metrics(match_id TEXT NOT NULL REFERENCES review_retention(match_id),player_id TEXT NOT NULL REFERENCES accounts(id),value TEXT NOT NULL,PRIMARY KEY(match_id,player_id));
 CREATE TABLE IF NOT EXISTS review_signals(id INTEGER PRIMARY KEY,player_id TEXT NOT NULL REFERENCES accounts(id),match_id TEXT NOT NULL REFERENCES stat_matches(id),type TEXT NOT NULL,reason TEXT NOT NULL,weight REAL NOT NULL,created_at INTEGER NOT NULL,measurements TEXT NOT NULL,UNIQUE(player_id,match_id,reason));
 CREATE INDEX IF NOT EXISTS review_signals_player ON review_signals(player_id,id);
 CREATE TRIGGER IF NOT EXISTS review_signals_no_delete BEFORE DELETE ON review_signals BEGIN SELECT RAISE(ABORT,'Review signal audit is append-only'); END;
 CREATE TRIGGER IF NOT EXISTS review_signals_no_update BEFORE UPDATE ON review_signals BEGIN SELECT RAISE(ABORT,'Review signal audit is append-only'); END;
 CREATE TABLE IF NOT EXISTS review_accounts(player_id TEXT PRIMARY KEY REFERENCES accounts(id),status TEXT NOT NULL CHECK(status IN ('NORMAL','REVIEW','CLEARED')),revision INTEGER NOT NULL DEFAULT 0,cleared_through INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS review_decisions(id INTEGER PRIMARY KEY,player_id TEXT NOT NULL REFERENCES accounts(id),developer_id TEXT NOT NULL REFERENCES accounts(id),action TEXT NOT NULL,created_at INTEGER NOT NULL,signal_watermark INTEGER NOT NULL);
 CREATE TRIGGER IF NOT EXISTS review_decisions_no_delete BEFORE DELETE ON review_decisions BEGIN SELECT RAISE(ABORT,'Review decision audit is append-only'); END;
 CREATE TRIGGER IF NOT EXISTS review_decisions_no_update BEFORE UPDATE ON review_decisions BEGIN SELECT RAISE(ABORT,'Review decision audit is append-only'); END;
 CREATE TABLE IF NOT EXISTS review_pending(player_id TEXT NOT NULL REFERENCES accounts(id),match_id TEXT NOT NULL REFERENCES stat_matches(id),status TEXT NOT NULL CHECK(status IN ('PENDING REVIEW','RELEASED')),PRIMARY KEY(player_id,match_id));
 CREATE TABLE IF NOT EXISTS review_career_hold(player_id TEXT NOT NULL,mode TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(player_id,mode));
 CREATE TRIGGER IF NOT EXISTS review_protect_events_delete BEFORE DELETE ON stat_facts WHEN OLD.kind IN ('event','command') AND EXISTS(SELECT 1 FROM review_retention WHERE match_id=OLD.match_id) BEGIN SELECT RAISE(ABORT,'Retained review evidence: migrate and verify before cleanup'); END;
 CREATE TRIGGER IF NOT EXISTS review_protect_events_update BEFORE UPDATE ON stat_facts WHEN OLD.kind IN ('event','command') AND EXISTS(SELECT 1 FROM review_retention WHERE match_id=OLD.match_id) BEGIN SELECT RAISE(ABORT,'Retained review evidence is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS review_protect_matches_delete BEFORE DELETE ON stat_matches WHEN EXISTS(SELECT 1 FROM review_retention WHERE match_id=OLD.id) BEGIN SELECT RAISE(ABORT,'Retained review match'); END;
 CREATE TRIGGER IF NOT EXISTS review_protect_matches_update BEFORE UPDATE ON stat_matches WHEN EXISTS(SELECT 1 FROM review_retention WHERE match_id=OLD.id) BEGIN SELECT RAISE(ABORT,'Retained review match is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS review_protect_results_delete BEFORE DELETE ON stat_participants WHEN EXISTS(SELECT 1 FROM review_retention WHERE match_id=OLD.match_id) BEGIN SELECT RAISE(ABORT,'Retained review result'); END;
 CREATE TRIGGER IF NOT EXISTS review_protect_results_update BEFORE UPDATE ON stat_participants WHEN EXISTS(SELECT 1 FROM review_retention WHERE match_id=OLD.match_id) BEGIN SELECT RAISE(ABORT,'Retained review result is immutable'); END;
 `);}
export function ordinaryShots(db,match,participant){
 const events=db.prepare("SELECT sequence,payload FROM stat_facts WHERE match_id=? AND kind='event' ORDER BY sequence").all(match.id).map(r=>({...parse(r.payload),index:r.sequence}));
 const byIndex=new Map(events.map(f=>[f.index,f]));
 const commands=db.prepare("SELECT payload FROM stat_facts WHERE match_id=? AND kind='command' ORDER BY sequence").all(match.id).map(r=>parse(r.payload));
 const shots=[];
 for(const r of commands){const c=r.command;if(c?.kind!=='shoot'||c.actorId!==participant.actor||participant.cutoff!==undefined&&r.eventStart>=participant.cutoff)continue;
  let impact;for(let i=r.eventStart;i<r.eventEnd;i++){const f=byIndex.get(i);if(f&&['impact','repeat-ignored','suspect-eliminated'].includes(f.event.kind)&&['direct-human','direct-ai'].includes(f.event.meta?.source)&&f.event.meta.ownerId===c.actorId){impact=f;break;}}
  const a=r.shotAudit,hit=a?a.hit:!!(impact?.event.kind==='impact'&&impact.event.unitId),type=a?.unitType||impact?.event.statistics?.unitType||null;
  shots.push({index:shots.length+1,eventIndex:r.eventStart,commandSequence:r.sequence,targetBoard:c.boardId,cell:c.cell,hit,type,unitId:a?.unitId||impact?.event.unitId||null,core:a?a.core:hit&&['inf','cav','archer','monk','castle'].includes(type),previouslyKnown:a?a.previouslyKnown:null,unitPreviouslyKnown:a?a.unitPreviouslyKnown:null,knowledgeCoverage:a?'pre-shot-authority':'historical-unknown'});
 }
 return shots;
}
export function reviewStore(db,{now=Date.now,policy=REVIEW_POLICY}={}){
 const one=(sql,...a)=>db.prepare(sql).get(...a),all=(sql,...a)=>db.prepare(sql).all(...a),run=(sql,...a)=>db.prepare(sql).run(...a);
 const state=id=>one('SELECT status,revision,cleared_through FROM review_accounts WHERE player_id=?',id)||{status:'NORMAL',revision:0,cleared_through:0};
 function retain(matchId){
  if(one('SELECT 1 FROM review_retention WHERE match_id=?',matchId))return;
  const m=one('SELECT * FROM stat_matches WHERE id=? AND finalized=1',matchId);if(!m)return;const d=parse(m.descriptor),players=d.participants.filter(p=>p.kind==='account'&&p.playerId);if(!players.length)return;
  const counts=all('SELECT kind,count(*) n,min(sequence) lo,max(sequence) hi FROM stat_facts WHERE match_id=? GROUP BY kind',m.id),complete=['event','command'].every(kind=>{const c=counts.find(c=>c.kind===kind),n=m[kind+'_cursor'];return n===0?!c:c?.n===n&&c.lo===0&&c.hi===n-1;});
  run('INSERT INTO review_retention VALUES(?,?,?)',m.id,policy.version,complete?'ordered-facts-complete':'historical-gaps');
  for(const p of players){const shots=ordinaryShots(db,m,p),row=one('SELECT summary,match_score,score_components FROM stat_participants WHERE match_id=? AND actor=?',m.id,p.actor),summary=parse(row?.summary)||{};
   let hidden=0,core=0,longestHidden=0,longestCore=0,beforeMiss=0,missed=false;const discoveries=[],seen=new Set();
   for(const s of shots){const blind=s.hit&&s.previouslyKnown===false&&s.unitPreviouslyKnown===false;hidden=blind?hidden+1:0;core=s.hit&&s.core?core+1:0;longestHidden=Math.max(hidden,longestHidden);longestCore=Math.max(core,longestCore);if(!missed&&s.hit)beforeMiss++;else missed=true;if(blind&&s.core&&!seen.has(s.unitId)){seen.add(s.unitId);discoveries.push(s.index);}}
   const metrics={shots:shots.length,hits:shots.filter(s=>s.hit).length,hitRatio:shots.length?shots.filter(s=>s.hit).length/shots.length:null,firstHeroShot:shots.find(s=>s.hit&&s.type==='hero')?.index??null,firstBlindHeroShot:shots.find(s=>s.hit&&s.type==='hero'&&s.previouslyKnown===false&&s.unitPreviouslyKnown===false)?.index??null,independentCoreDiscoveries:discoveries,firstTwoIndependentCore:shots.length>=2&&shots.slice(0,2).every(s=>s.hit&&s.core&&s.previouslyKnown===false&&s.unitPreviouslyKnown===false)&&shots[0].unitId!==shots[1].unitId,longestHiddenHitStreak:longestHidden,longestCoreHitStreak:longestCore,hitsBeforeFirstMiss:beforeMiss,matchScore:row?.match_score??null,biggestChain:summary.biggestChain??null,knowledgeCoveredShots:shots.filter(s=>s.knowledgeCoverage==='pre-shot-authority').length,complete};
   run('INSERT INTO review_metrics VALUES(?,?,?)',m.id,p.playerId,JSON.stringify(metrics));
   const signal=(reason,weight,measurements)=>run("INSERT OR IGNORE INTO review_signals(player_id,match_id,type,reason,weight,created_at,measurements) VALUES(?,?,'STATISTICAL',?,?,?,?)",p.playerId,m.id,reason,weight,m.ended_at,JSON.stringify({policyVersion:policy.version,...measurements}));
   if(complete){if(metrics.firstTwoIndependentCore)signal('two-independent-unknown-core-openers',policy.independentOpeningWeight,{shotIndexes:[1,2]});if(metrics.firstBlindHeroShot<=3&&metrics.firstBlindHeroShot!==null)signal('early-blind-hero',metrics.firstBlindHeroShot===1?policy.heroFirstWeight:policy.heroEarlyWeight,{shot:metrics.firstBlindHeroShot});if(metrics.shots>=policy.highAccuracyMinimumShots&&metrics.hitRatio>=policy.highAccuracyRatio)signal('high-ordinary-accuracy',policy.highAccuracyWeight,{shots:metrics.shots,hits:metrics.hits,ratio:metrics.hitRatio});if(longestHidden>=policy.hiddenStreak)signal('long-hidden-hit-streak',1,{length:longestHidden});if(longestCore>=policy.coreStreak)signal('long-core-hit-streak',1,{length:longestCore,includesKnownFollowups:true});if(metrics.matchScore>=policy.extremeScore)signal('high-score-observation',1,{score:metrics.matchScore});if(metrics.biggestChain>=policy.extremeChain)signal('large-chain-observation',1,{cells:metrics.biggestChain});}
   if(state(p.playerId).status==='REVIEW')run("INSERT OR IGNORE INTO review_pending VALUES(?,?,'PENDING REVIEW')",p.playerId,m.id);
  }
 }
 function backfill(){for(const m of all("SELECT m.id FROM stat_matches m WHERE finalized=1 AND NOT EXISTS(SELECT 1 FROM review_retention r WHERE r.match_id=m.id) AND EXISTS(SELECT 1 FROM stat_participants p WHERE p.match_id=m.id AND p.kind='account')"))retain(m.id);}
 function account(id){const s=state(id),signals=all('SELECT id,match_id AS matchId,type,reason,weight,created_at AS timestamp,measurements FROM review_signals WHERE player_id=? ORDER BY id DESC',id).map(r=>({...r,measurements:parse(r.measurements)}));const matches=all('SELECT r.match_id,m.mode,m.player_count,m.ended_at,r.value FROM review_metrics r JOIN stat_matches m ON m.id=r.match_id WHERE player_id=? ORDER BY m.ended_at DESC',id).map(r=>({...r,metrics:parse(r.value),value:undefined}));
  const relations=all("SELECT b.player_id AS playerId,count(*) AS matches,sum(CASE WHEN a.outcome='Win' THEN 1 ELSE 0 END) AS wins,sum(CASE WHEN a.outcome='Win' AND b.reliability='Quit' THEN 1 ELSE 0 END) AS winsAfterOtherQuit FROM stat_participants a JOIN stat_participants b ON b.match_id=a.match_id AND b.player_id<>a.player_id WHERE a.player_id=? AND b.kind='account' GROUP BY b.player_id",id);
  const recent=matches.slice(0,20),shots=recent.reduce((n,r)=>n+r.metrics.shots,0),hits=recent.reduce((n,r)=>n+r.metrics.hits,0);
  return {player:one('SELECT id AS playerId,display_name AS displayName FROM accounts WHERE id=?',id),...s,totalSignals:signals.length,technicalSignals:signals.filter(s=>s.type==='TECHNICAL').length,statisticalSignals:signals.filter(s=>s.type==='STATISTICAL').length,reviewWeight:signals.filter(r=>r.id>s.cleared_through).reduce((n,r)=>n+r.weight,0),signals,matches,relationships:relations,rolling:{matches:recent.length,shots,hits,ratio:shots?hits/shots:null},decisions:all('SELECT developer_id AS developerId,action,created_at AS timestamp,signal_watermark FROM review_decisions WHERE player_id=? ORDER BY id',id)};
 }
 function detail(id){const m=one('SELECT id,mode,player_count,rules_version,build,started_at,ended_at,descriptor FROM stat_matches WHERE id=?',id);if(!m)return null;const d=parse(m.descriptor);return {matchId:m.id,mode:m.mode,participantCount:m.player_count,rulesVersion:m.rules_version,build:m.build,startedAt:m.started_at,endedAt:m.ended_at,coverage:one('SELECT coverage FROM review_retention WHERE match_id=?',id)?.coverage,participants:all('SELECT actor,player_id AS playerId,kind,seat,outcome,reliability,placement,summary,match_score,score_components FROM stat_participants WHERE match_id=?',id).map(p=>({...p,summary:parse(p.summary),score_components:parse(p.score_components),shots:p.kind==='account'?ordinaryShots(db,m,d.participants.find(x=>x.actor===p.actor)):[]})),signals:all('SELECT player_id AS playerId,type,reason,weight,measurements FROM review_signals WHERE match_id=?',id).map(r=>({...r,measurements:parse(r.measurements)})),resultReference:id,replayAvailable:!!one('SELECT 1 FROM stat_replays WHERE match_id=?',id)};}
 function decide(id,developer,action){if(!['REVIEW','CLEAR','KEEP UNDER REVIEW'].includes(action)||!one('SELECT 1 FROM accounts WHERE id=?',id))throw Object.assign(Error('Invalid review decision.'),{status:400});const previous=state(id),watermark=one('SELECT coalesce(max(id),0) n FROM review_signals WHERE player_id=?',id).n;if(action==='KEEP UNDER REVIEW'&&previous.status!=='REVIEW')throw Object.assign(Error('Account is not under review.'),{status:400});
  run('INSERT INTO review_decisions(player_id,developer_id,action,created_at,signal_watermark) VALUES(?,?,?,?,?)',id,developer,action,now(),watermark);
  const status=action==='CLEAR'?'CLEARED':'REVIEW';run('INSERT INTO review_accounts VALUES(?,?,?,?) ON CONFLICT(player_id) DO UPDATE SET status=excluded.status,revision=excluded.revision,cleared_through=excluded.cleared_through',id,status,previous.revision+(status!==previous.status?1:0),action==='CLEAR'?watermark:previous.cleared_through);
  if(status==='REVIEW'&&previous.status!=='REVIEW')run('INSERT OR REPLACE INTO review_career_hold SELECT player_id,mode,value FROM stat_career WHERE player_id=?',id);
  if(status==='CLEARED'){run("UPDATE review_pending SET status='RELEASED' WHERE player_id=?",id);run('DELETE FROM review_career_hold WHERE player_id=?',id);}return {status};
 }
 function rejected({playerId,matchId,request,result,size}){
  // Only an objectively off-board, fresh rejected ordinary shot. No stale,
  // unsupported, read/replay, reconnect, duplicate or AFK traffic is scored.
  if(result?.accepted!==false||result.error!=='illegal'||request?.intent?.kind!=='shoot'||request.battle!==result.snapshot?.battle||request.revision!==result.snapshot?.revision||request.contract!==result.snapshot?.contract||!Number.isInteger(size))return;
  const c=request.intent.cell;if(!c||!Number.isFinite(c.x)||!Number.isFinite(c.y)||!Number.isInteger(c.x)||!Number.isInteger(c.y)||c.x>=0&&c.y>=0&&c.x<size&&c.y<size)return;
  if(!one('SELECT 1 FROM stat_matches WHERE id=? AND finalized=0',matchId)||!one('SELECT 1 FROM accounts WHERE id=?',playerId))return;
  run("INSERT OR IGNORE INTO review_signals(player_id,match_id,type,reason,weight,created_at,measurements) VALUES(?,?,'TECHNICAL','fresh-off-board-shot',?,?,?)",playerId,matchId,policy.illegalTargetWeight,now(),JSON.stringify({x:c.x,y:c.y,size,policyVersion:policy.version}));
 }
 function search({metric='matchScore',limit=50}={}){const allowed=['matchScore','biggestChain','firstHeroShot','firstBlindHeroShot','firstTwoIndependentCore','longestHiddenHitStreak','longestCoreHitStreak','hitsBeforeFirstMiss','hitRatio'];if(!allowed.includes(metric)||!Number.isInteger(limit)||limit<1||limit>100)throw Object.assign(Error('Invalid anomaly query.'),{status:400});return all('SELECT r.player_id AS playerId,r.match_id AS matchId,r.value,m.mode,m.player_count AS participantCount FROM review_metrics r JOIN stat_matches m ON m.id=r.match_id').map(r=>({...r,metrics:parse(r.value),value:undefined})).filter(r=>r.metrics[metric]!==null).sort((a,b)=>(metric.startsWith('first')&&metric!=='firstTwoIndependentCore'?1:-1)*(Number(a.metrics[metric])-Number(b.metrics[metric]))||a.matchId.localeCompare(b.matchId)).slice(0,limit);}
 return {retain,backfill,account,detail,decide,rejected,search,notice:id=>state(id).status==='REVIEW'?{status:'REVIEW',revision:state(id).revision}:null};
}
