import {randomUUID} from 'node:crypto';
export const FEEDBACK_LIMITS={screenshot:3*1024*1024,log:8*1024*1024,text:8000};
const fail=message=>{throw Object.assign(Error(message),{status:400});};
export function screenshot(value){if(value==null)return null;if(!value||Object.keys(value).sort().join(',')!=='data,mime'||!['image/png','image/jpeg','image/webp'].includes(value.mime)||typeof value.data!=='string'||value.data.length>4*Math.ceil(FEEDBACK_LIMITS.screenshot/3)||! /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value.data))fail('Use a PNG, JPG or WEBP screenshot up to 3 MB.');
 const b=Buffer.from(value.data,'base64');if(!b.length||b.length>FEEDBACK_LIMITS.screenshot)fail('Screenshot is too large. Maximum 3 MB.');let width=0,height=0,valid=false;
 if(value.mime==='image/png'&&b.length>=45&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))){let p=8,idat=false,header=false;while(p+12<=b.length){const n=b.readUInt32BE(p);if(n>b.length-p-12)break;const type=b.toString('ascii',p+4,p+8);if(p===8){if(type!=='IHDR'||n!==13)break;header=true;width=b.readUInt32BE(p+8);height=b.readUInt32BE(p+12);}if(type==='IDAT')idat=true;p+=n+12;if(type==='IEND'){valid=header&&idat&&n===0&&p===b.length;break;}}}
 if(value.mime==='image/jpeg'&&b.length>=12&&b[0]===255&&b[1]===216&&b.at(-2)===255&&b.at(-1)===217){let p=2;while(p+4<b.length){if(b[p++]!==255)break;let marker=b[p++];while(marker===255)marker=b[p++];if(marker===218){valid=width>0;break;}if(marker===216||marker===1||marker>=208&&marker<=215)continue;const n=b.readUInt16BE(p);if(n<2||p+n>b.length)break;if([192,193,194].includes(marker)&&n>=8){height=b.readUInt16BE(p+3);width=b.readUInt16BE(p+5);}p+=n;}}
 if(value.mime==='image/webp'&&b.length>=30&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP'&&b.readUInt32LE(4)===b.length-8){const kind=b.toString('ascii',12,16),n=b.readUInt32LE(16);if(n<=b.length-20){if(kind==='VP8X'&&n>=10){width=1+b.readUIntLE(24,3);height=1+b.readUIntLE(27,3);}else if(kind==='VP8 '&&n>=10&&b[23]===157&&b[24]===1&&b[25]===42){width=b.readUInt16LE(26)&16383;height=b.readUInt16LE(28)&16383;}else if(kind==='VP8L'&&n>=5&&b[20]===47){const bits=b.readUInt32LE(21);width=1+(bits&16383);height=1+((bits>>>14)&16383);}valid=width>0;}}
 if(!valid||width<1||height<1||width>8192||height>8192||width*height>24000000)fail('The screenshot is not a supported image, is damaged, or is too large.');return {mime:value.mime,bytes:b,width,height};
}
export function migrateFeedback(db){db.exec(`CREATE TABLE IF NOT EXISTS feedback(id TEXT PRIMARY KEY,type TEXT NOT NULL CHECK(type IN ('BUG','IDEA')),status TEXT NOT NULL CHECK(status IN ('NEW','REVIEWED','RESOLVED')),created_at INTEGER NOT NULL,player_id TEXT,guest_id TEXT,guest_name TEXT,build TEXT NOT NULL,mode TEXT,screen TEXT,match_id TEXT,description TEXT NOT NULL,screenshot_id TEXT,screenshot_mime TEXT,screenshot BLOB,game_log TEXT);
 CREATE INDEX IF NOT EXISTS feedback_filter ON feedback(type,status,created_at);
 CREATE TABLE IF NOT EXISTS feedback_actions(id INTEGER PRIMARY KEY,feedback_id TEXT NOT NULL REFERENCES feedback(id),developer_id TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL);`);}
export function feedbackStore(db,{now=Date.now}={}){
 function submit(b,{playerId=null,guest=null,build='unknown',mode=null,matchId=null}={}){
 if(Object.keys(b).some(k=>!['type','description','screenshot','gameLog','screen'].includes(k))||!['BUG','IDEA'].includes(b.type)||typeof b.description!=='string'||!b.description.trim()||b.description.length>FEEDBACK_LIMITS.text)fail('Please describe your feedback (up to 8,000 characters).');
 if(b.gameLog!==undefined&&(b.type!=='BUG'||typeof b.gameLog!=='string'||!b.gameLog.startsWith('CHAIN SIEGE')||Buffer.byteLength(b.gameLog)>FEEDBACK_LIMITS.log))fail('The game log is invalid or exceeds 8 MB.');
 if(b.screen!==undefined&&!['Options','Battle','Main Menu'].includes(b.screen))fail('Invalid feedback screen.');
 const image=screenshot(b.screenshot),id=randomUUID();db.prepare("INSERT INTO feedback VALUES(?,?,'NEW',?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,b.type,now(),playerId,playerId?null:guest?.guestId||null,playerId?null:guest?.displayName||'Guest',build,mode,b.screen||null,matchId,b.description.trim(),image?randomUUID():null,image?.mime||null,image?.bytes||null,b.gameLog||null);return {id,sent:true};
 }
 const fields='id,type,status,created_at AS timestamp,player_id AS playerId,guest_id AS guestId,guest_name AS guestName,build,mode,screen,match_id AS matchId,description,screenshot_id AS screenshotId,screenshot_mime AS screenshotMime';
 // Keep the original status column and API values compatible. IGNORE is an audited
 // inbox decision; its underlying REVIEWED value remains readable by older builds.
 const inbox=`CASE WHEN (SELECT status FROM feedback_actions WHERE feedback_id=feedback.id ORDER BY id DESC LIMIT 1)='IGNORED' THEN 'IGNORED' WHEN status='REVIEWED' THEN 'TODO' WHEN status='RESOLVED' THEN 'FINISHED' ELSE 'NEW' END`;
 function list({type='ALL',status='ALL',offset=0}={}){if(!['ALL','BUG','IDEA'].includes(type)||!['ALL','NEW','REVIEWED','RESOLVED','TODO','IGNORED','FINISHED'].includes(status)||!Number.isInteger(offset)||offset<0)fail('Invalid feedback filter.');const workflow=['TODO','IGNORED','FINISHED','NEW'].includes(status);return db.prepare(`SELECT id,type,status,${inbox} AS inboxStatus,created_at AS timestamp,substr(description,1,160) AS preview FROM feedback WHERE (?='ALL' OR type=?) AND (?='ALL' OR ${workflow?inbox:'status'}=?) ORDER BY created_at DESC,id LIMIT 50 OFFSET ?`).all(type,type,status,status,offset);}
 function get(id){if(typeof id!=='string'||id.length>64)fail('Invalid feedback ID.');const row=db.prepare('SELECT '+fields+','+inbox+' AS inboxStatus,(SELECT display_name FROM accounts WHERE id=feedback.player_id) AS displayName,screenshot,game_log AS gameLog FROM feedback WHERE id=?').get(id);if(!row)throw Object.assign(Error('Feedback not found.'),{status:404});return {...row,screenshot:row.screenshot?{mime:row.screenshotMime,data:Buffer.from(row.screenshot).toString('base64')}:null};}
 function mark(id,status,developer){if(!['REVIEWED','RESOLVED','TODO','IGNORED','FINISHED'].includes(status))fail('Invalid feedback status.');get(id);const stored={TODO:'REVIEWED',IGNORED:'REVIEWED',FINISHED:'RESOLVED'}[status]||status;db.prepare('UPDATE feedback SET status=? WHERE id=?').run(stored,id);db.prepare('INSERT INTO feedback_actions(feedback_id,developer_id,status,created_at) VALUES(?,?,?,?)').run(id,developer,status,now());return {id,status:stored};}
 function counts(){
  const types={ALL:0,BUG:0,IDEA:0},statuses={NEW:0,REVIEWED:0,RESOLVED:0};
  for(const row of db.prepare('SELECT type,status,count(*) n FROM feedback GROUP BY type,status').all()){types.ALL+=row.n;types[row.type]+=row.n;statuses[row.status]+=row.n;}
  return {types,statuses};
 }
 function inboxCounts(){const totals={NEW:0,TODO:0,IGNORED:0,FINISHED:0};for(const row of db.prepare(`SELECT ${inbox} AS name,count(*) n FROM feedback GROUP BY name`).all())totals[row.name]=row.n;return totals;}
 return {submit,list,get,mark,counts,inboxCounts,forPlayer:playerId=>db.prepare(`SELECT id,type,${inbox} AS inboxStatus,created_at AS timestamp,substr(description,1,160) AS preview FROM feedback WHERE player_id=? ORDER BY created_at DESC,id LIMIT 50`).all(playerId)};
}
