import {createRingService} from './ring-pvp.mjs';
import {AVATARS} from '../assets/avatars/catalog.mjs';
import {serveMusic} from './music-assets.mjs';
import {storyContext,completedStory} from './story-progress.mjs';
import {prepareStatistics} from './statistics-capture.mjs';
import {openRegistry,registryDirectory,countries} from './registry.mjs';
import {metricsContext,measured,measuredAsync} from './beta-metrics.mjs';
import {openStore,checkpointId} from './store.mjs';
import {createHash} from 'node:crypto';
import os from 'node:os';import {createPvpService} from './multiplayer.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {randomBytes,randomInt} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {createLocalSession} from '../canonical/compiled/local-host/session.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const roster={inf:5,cav:3,archer:3,monk:1,castle:2,dwarf:1,goblin:1,catapult:2,elf:1,cleric:1,demon:1,dragon:1,wizard:1,necro:2,hero:1};
// Upgrade only the retired Guest placeholder; immutable random guestId gives a stable pool choice.
const guestAvatars=AVATARS.filter(a=>a.access==='guest-goblin');
function guestAvatar(identity){if(identity?.kind!=='guest'||identity.avatarId!=='guest-goblin-fallback')return identity;const a=guestAvatars[createHash('sha256').update(identity.guestId).digest().readUInt32BE(0)%guestAvatars.length];return {...identity,avatarId:a.id,avatarSrc:a.assetPath};}
const initial=()=>({size:15,story:false,battle:0,player:{size:15,...roster},enemy:{size:15,...roster}});
function configuration(c,seed){
 if(c?.singlePlayer&&(c.story||!Array.isArray(c.singlePlayer.npcNames)||![1,2,3].includes(c.singlePlayer.npcNames.length)||new Set(c.singlePlayer.npcNames).size!==c.singlePlayer.npcNames.length||c.singlePlayer.npcNames.some(n=>!['Cruns','Snurk','Rackler'].includes(n))))throw Error('invalid-configuration');
 if(!c||Object.keys(c).filter(k=>k!=='singlePlayer').sort().join(',')!=='battle,enemy,player,size,story'||typeof c.story!=='boolean'||!Number.isInteger(c.size)||c.size<5||c.size>15||!Number.isInteger(c.battle)||c.battle<0||c.battle>100)throw Error('invalid-configuration');
 const army=a=>{if(!a||typeof a!=='object'||Array.isArray(a))throw Error('invalid-configuration');const out={};for(const[k,v]of Object.entries(a)){if(k==='size'){if(v!==c.size)throw Error('invalid-configuration');continue;}if(!Object.hasOwn(roster,k)||!Number.isInteger(v)||v<0||v>20)throw Error('invalid-configuration');out[k]=v;}return out;};
 return {matchId:'node-private-match',rulesVersion:'stone-throw-v1.427',size:c.size,story:c.story,seed,players:[{id:'node-human',boardId:'node-home',roster:army(c.player),decisionMode:'interactive'},{id:'node-ai',boardId:'node-away',roster:army(c.enemy),decisionMode:'policy'}]};
}
export async function startServer({registryDir=registryDirectory(),port=3211,betaGameLog=false,development=false,seed,now=Date.now,lan=false,bind,stateDir,publicOrigin,secureCookies=false,playtestSnapshotOnly=false,statisticsInspector=false,hofPlaytest=false,recoverLocalSession,logger=event=>console.log(JSON.stringify(event))}={}){
 if(path.resolve(registryDir)===root||path.resolve(registryDir).startsWith(root+path.sep))throw Error('Registry directory must be outside the build');
 let registry;const getRegistry=()=>registry||(registry=openRegistry(registryDir,{now}));
 betaGameLog=!!betaGameLog&&!publicOrigin; // Explicit local launcher option; never a URL/global toggle.
 if(!Number.isInteger(port)||port<0||port>65535)throw Error('invalid-port');
 if(publicOrigin){const u=new URL(publicOrigin);if(!['http:','https:'].includes(u.protocol)||u.origin!==publicOrigin)throw Error('invalid-public-origin');secureCookies=u.protocol==='https:';}
 const log=(event,extra={})=>logger({event,...extra});
 const build=createHash('sha256').update(fs.readFileSync(path.join(root,'build-manifest.json'))).digest('hex'),started=Date.now();let recovery='disabled',fatal=false,stopping=false,requestQueue=Promise.resolve();
 const sessions=new Map(),pvp=createPvpService(roster,{seed,now,refreshIdentity:i=>i?.kind==='account'?(getRegistry().identityById(i.playerId)||i):i});let origin;const addresses=['127.0.0.1',...Object.values(os.networkInterfaces()).flat().filter(a=>a?.family==='IPv4').map(a=>a.address)];const address=bind||(lan?'0.0.0.0':'127.0.0.1');if(!['0.0.0.0',...addresses].includes(address))throw Error('Select a local interface');if(!lan&&address!=='127.0.0.1')throw Error('Non-loopback bind requires --lan');
 // Persist browser credentials across a browser close; revocation remains authoritative.
 const cookieFlags='; HttpOnly; SameSite=Strict; Path=/'+(secureCookies?'; Secure':'');
 const startupMetrics=betaGameLog?{}:undefined;let store;try{store=metricsContext.run(startupMetrics,()=>openStore(stateDir,build,development?'development':'production',{journalEnabled:!playtestSnapshotOnly}));}catch(e){log('restore-failed',{reason:['checkpoint-unavailable','incompatible-checkpoint','state-locked'].includes(e.message)?e.message:'state-unavailable'});throw Error('Server state unavailable; inspect operator checkpoint');}
 const localGroups=createRingService(roster,{seed,now,workers:false});
 const localSession=(c,checkpoint,identity)=>c.singlePlayer?.npcNames.length>1?localGroups.localSession({identity,npcNames:c.singlePlayer.npcNames},checkpoint):createLocalSession(configuration(c,seed??randomInt(0,0x100000000)),checkpoint,development);
 const make=(c=initial(),checkpoint)=>{const token=randomBytes(32).toString('hex'),config=configuration(c,seed??randomInt(0,0x100000000)),session=createLocalSession(config,checkpoint,development),entry={session,configuration:structuredClone(c),queue:Promise.resolve()};sessions.set(token,entry);log('session-created');return {token,entry};};
 // Each browser identity owns independent local sessions; multiplayer retains its seat token.
 const modeOf=c=>c.story?'story':'single';
 function slots(e){return e.slots||(e.slots={[modeOf(e.configuration)]:{session:e.session,configuration:e.configuration}});}
 function select(e,mode){const slot=slots(e)[mode];if(!slot)return false;e.session=slot.session;e.configuration=slot.configuration;e.mode=mode;return true;}
 const ordered=(e,fn)=>{const task=e.queue.then(fn);e.queue=task.catch(()=>{});return task;};
 function detachFormerPlayers(){for(const r of pvp.rooms.values()){for(const seat of r.seats){if(seat?.controller!=='ai'||!seat.takeover)continue;const e=sessions.get(seat.binding);if(!e||e.seatToken!==seat.token)continue;e.seatToken=null;e.mode='main-menu';e.recoveryNotice={available:false,noticeId:seat.takeover.id,replacement:seat.takeover.replacement};}}}
 const resumable=(slot,u)=>u.snapshot.phase!=='finished'&&(slot.configuration.story||u.snapshot.phase!=='placement'||u.snapshot.owned.length>0);
 async function localResumeModes(e,identity){const found=[];for(const [mode,slot]of Object.entries(slots(e))){if(mode==='story'&&slot.storyOwnerId&&getRegistry().storyState(slot.storyOwnerId).runId!==(slot.storyRunId||'legacy'))continue;if(mode==='story'&&slot.storyOwnerId!==undefined&&(slot.storyOwnerId||null)!==(identity?.playerId||null))continue;const u=await slot.session.client.read();if(resumable(slot,u))found.push(mode);}return found;}
 async function save(){return measuredAsync('persistence',saveInner);}
 async function saveInner(){
  detachFormerPlayers();const captures=[];
  for(const e of sessions.values())for(const slot of Object.values(slots(e)))await slot.session.visitStatistics((h,epoch,gaveUp)=>{const progress=completedStory(slot,h,epoch,gaveUp);if(progress){getRegistry().completeStory(slot.storyOwnerId,progress,slot.storyRunId||'legacy');slot.storyCapturedEpoch=epoch;}const d=prepareStatistics(slot,h,epoch,{mode:'Single Player',build,now,gaveUp,participants:slot.session.participants?slot.session.participants.map((p,i)=>i===0?{...p,identity:slot.statIdentity||p.identity}:p):[{controller:'human',identity:slot.statIdentity||null},{controller:'ai'}]});if(d)captures.push([d,h]);});
  for(const r of pvp.rooms.values()){const d=prepareStatistics(r,r.host,r.epoch,{mode:r.seats.length===2?'Duel':r.seats.length+' Players',build,now,participants:r.seats,news:r.news,closed:r.closed});if(d)captures.push([d,r.host]);}
  if(store){const local=[];for(const [token,e]of sessions){const savedSlots={};for(const [mode,slot]of Object.entries(slots(e)))savedSlots[mode]={configuration:slot.configuration,checkpoint:await slot.session.serializePrivate(),matchStatistics:slot.matchStatistics,statIdentity:slot.statIdentity,storyOwnerId:slot.storyOwnerId,storyRunId:slot.storyRunId,storyContext:slot.storyContext,storyCapturedEpoch:slot.storyCapturedEpoch};local.push({token,guestIdentity:e.guestIdentity||null,seatToken:e.seatToken||null,recoveryNotice:e.recoveryNotice||null,localRecoveryToken:e.localRecoveryToken||null,unavailableLocalRecoveryToken:e.unavailableLocalRecoveryToken||null,configuration:e.configuration,checkpoint:await e.session.serializePrivate(),mode:e.mode||modeOf(e.configuration),slots:savedSlots});}store.write({local,multiplayer:pvp.exportState(true)});}
  // Commit facts only after the durable game snapshot. Recovery retries safely by Match ID.
  for(const [d,h]of captures)getRegistry().statistics.capture(d,h);
 }

 function restoreEntry(e){
  const restore=(c,checkpoint,metadata={})=>{const saved=JSON.parse(checkpoint);let session;if(saved.contract==='local-group-session-v1'){session=localSession(c,checkpoint);}else{saved.epoch=randomInt(1,2**48);saved.revision++;saved.unitHandles=[];saved.choiceHandles=[];saved.presentation=[];session=createLocalSession(configuration(c,0),JSON.stringify(saved),development);}const epoch=session.epoch??saved.epoch;return {...metadata,configuration:c,session,matchStatistics:metadata.matchStatistics?{...metadata.matchStatistics,epoch}:null,storyCapturedEpoch:metadata.storyCapturedEpoch===JSON.parse(checkpoint).epoch?epoch:undefined};};
  const entry={...restore(e.configuration,e.checkpoint),queue:Promise.resolve()};if(e.slots){entry.slots={};for(const [mode,slot]of Object.entries(e.slots)){if(!['single','story'].includes(mode)||modeOf(slot.configuration)!==mode)throw Error('invalid-slot');const {checkpoint,...metadata}=slot;entry.slots[mode]=restore(slot.configuration,checkpoint,metadata);}select(entry,e.mode==='multiplayer'?modeOf(e.configuration):e.mode);entry.mode=e.mode;}entry.localRecoveryToken=e.localRecoveryToken||null;entry.unavailableLocalRecoveryToken=e.unavailableLocalRecoveryToken||null;entry.guestIdentity=guestAvatar(e.guestIdentity)||null;entry.seatToken=e.seatToken||null;entry.recoveryNotice=e.recoveryNotice||null;return entry;
 }
 try{if(store?.value){for(const e of store.value.local){sessions.set(e.token,restoreEntry(e));}pvp.restoreState(store.value.multiplayer);for(const r of pvp.rooms.values())for(const seat of r.seats)if(seat?.identity)seat.identity=guestAvatar(seat.identity);recovery='restored';await save();log('restore-success');}else if(store)recovery='new';}catch{store?.release();log('restore-failed',{reason:'checkpoint-unavailable'});throw Error('Checkpoint unavailable; no sessions served');}
 const assets=JSON.parse(fs.readFileSync(path.join(root,'asset-manifest.json'))).assets.map(a=>a.file);
 const narrationAssets=Object.values(JSON.parse(fs.readFileSync(path.join(root,'assets/story/audio/narration-manifest.json')))).map(chapter=>chapter.wav);
 const musicAssets=JSON.parse(fs.readFileSync(path.join(root,'assets/audio/music/manifest.json'))).tracks.map(t=>t.file);
 const staticFiles=new Set([...["assets/result-screen/1st place duo.png", "assets/result-screen/1st place solo.png", "assets/result-screen/2nd place.png", "assets/result-screen/3rd place.png", "assets/result-screen/4th place no player.png", "assets/result-screen/4th place.png", "assets/result-screen/Background.png", "assets/result-screen/fantasy_medal_icon_collection.png"],"client-v13/result-screen.js","styles-result-screen.css","client-v13/online-overview.js","client-v13/overview-board.js","styles-online-overview.css","assets/avatars/catalog.mjs","client-v13/avatar-picker.js","styles-avatars.css",...AVATARS.map(a=>a.assetPath),...countries.map(c=>'assets/ui/flags/'+c.toLowerCase()+'.svg'),...assets,...narrationAssets,...musicAssets,'styles-phase3.css','client/audio-options.js','client-v13/hall-of-fame.js','styles-startup.css','styles-registry.css','client-v13/registry.js','client-v13/single-entry.js','client-v13/local-group.js','styles-online-entry.css','client-v13/online-entry.js','styles-multiplayer.css','asset-manifest.json','client/story-presentation.js','client/loading-screen.js',...Array.from({length:23},(_,i)=>'styles-'+String(i).padStart(2,'0')+'.css'),...['placement','coordinates','footprints'].map(x=>'public-rules/'+x+'.js'),...['startup','music','strength-public','strength-dataset','strength-renderer','game-log','combat-playback','legacy-animations','shell','presentation','action-instructions','resurrection-sparks','combat-feedback','battle-log','placement-feedback','castle-art-ready','story-account','story-browser','story-policy','story-tutorials','transport','bootstrap-production','lan','group-lan','rejoin',...(development?['bootstrap-development','node-development']:[])].map(x=>'client-v13/'+x+'.js'),'StoneThrow-v1.427-stage13-'+(development?'development':'production')+'.html']);
 const handle=async(req,res)=>metricsContext.run(betaGameLog&&req.headers['x-st-game-log']==='1'?{}:undefined,()=>handleInner(req,res));
 const handleInner=async(req,res)=>{const betaStart=performance.now(),betaWall=new Date().toISOString();const betaData=()=>({wall:betaWall,...(req.url==='/api/open'?{startupMetrics}:{}),requestMs:performance.now()-req.betaArrival,queueMs:betaStart-req.betaArrival,metrics:metricsContext.getStore()});
  const reply=async(status,body)=>{if(body?.snapshot||body?.update?.snapshot)metricsContext.getStore()&&(metricsContext.getStore()['public-result-boundary']={ms:performance.now()-betaStart,count:1});detachFormerPlayers();if(!req.groupLight&&req.url.startsWith('/api/')&&!fatal){try{await save();}catch{fatal=true;log('checkpoint-write-failed');status=503;body={error:'server-recovery-unavailable'};}}const text=measured('response-serialization',()=>JSON.stringify(body));if(metricsContext.getStore())res.setHeader('X-St-Beta-Metrics',JSON.stringify(betaData()));res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(text);};
  try{
   if(!(publicOrigin?req.headers.host===new URL(publicOrigin).host:addresses.some(a=>req.headers.host===a+':'+server.address().port)))return reply(403,{error:'invalid-host'});
   const url=new URL(req.url,origin);
   if(fatal||stopping)return reply(503,{error:'server-recovering'});
   if(url.pathname==='/health'&&req.method==='GET')return reply(200,{healthy:true,checkpoint:checkpointId,build,mode:development?'development':'production',recovery,uptimeSeconds:Math.floor((Date.now()-started)/1000),sessions:sessions.size,games:pvp.rooms.size});
   if(!url.pathname.startsWith('/api/')){let name=decodeURIComponent(url.pathname.slice(1));if(!name)name='StoneThrow-v1.427-stage13-'+(development?'development':'production')+'.html';if(req.method!=='GET'||!staticFiles.has(name))return reply(404,{error:'not-found'});const file=path.join(root,name);if(path.extname(file)==='.mp3')return serveMusic(req,res,file);res.writeHead(200,{...(path.extname(file)==='.wav'?{'Content-Length':fs.statSync(file).size}:{}),'Content-Type':({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.wav':'audio/wav','.webp':'image/webp','.svg':'image/svg+xml','.json':'application/json'})[path.extname(file)],'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});return res.end(fs.readFileSync(file));}
   if(req.method!=='POST')return reply(405,{error:'method-not-allowed'});
   if(req.headers.origin&&req.headers.origin!==(publicOrigin||'http://'+req.headers.host))return reply(403,{error:'invalid-origin'});
   if(req.headers['content-type']?.split(';')[0].trim().toLowerCase()!=='application/json')return reply(400,{error:'malformed-request'});
let body;try{body=JSON.parse(req.intake||Buffer.alloc(0));if(!body||typeof body!=='object'||Array.isArray(body))throw Error();}catch{return reply(400,{error:'malformed-request'});}
   if(url.pathname.startsWith('/api/registry/')){
    // Account persistence and credentials are independent of gameplay snapshots and seat cookies.
    if(req.headers.origin!==(publicOrigin||'http://'+req.headers.host))return reply(403,{error:'invalid-origin'});
    const cookies=Object.fromEntries((req.headers.cookie||'').split(';').map(s=>s.trim().split('=')));
    let browser=cookies.csRegistryBrowser;const setCookies=[];
    if(!/^[a-f0-9]{48}$/.test(browser||'')){browser=randomBytes(24).toString('hex');setCookies.push('csRegistryBrowser='+browser+cookieFlags+'; Max-Age=2592000');}
    try{if(url.pathname==='/api/registry/hall-of-fame'){if(Object.keys(body).some(k=>k!=='mode')||!['Duel','3 Players','4 Players'].includes(body.mode))return reply(400,{error:'malformed-request'});const identity=getRegistry().identity(cookies.csAccount);return reply(200,getRegistry().statistics.hallOfFame(body.mode,identity?.playerId||null,{bypass:!publicOrigin&&(hofPlaytest||development)}));}if(url.pathname==='/api/registry/statistics'){if(!statisticsInspector||publicOrigin)return reply(404,{error:'not-found'});if(Object.keys(body).length!==0)return reply(400,{error:'malformed-request'});const identity=getRegistry().identity(cookies.csAccount);return reply(200,getRegistry().statistics.inspect(identity?.playerId||null));}const result=await getRegistry().handle(url.pathname.slice('/api/registry/'.length),body,{token:cookies.csAccount,browser,ip:req.socket.remoteAddress||'local'});
     if(url.pathname==='/api/registry/me')result.statisticsInspector=!!statisticsInspector&&!publicOrigin;
     if(result.token){setCookies.push('csAccount='+result.token+cookieFlags+'; Max-Age=2592000');delete result.token;}
     if(result.clearCookie){setCookies.push('csAccount='+cookieFlags+'; Max-Age=0');delete result.clearCookie;}
     if(setCookies.length)res.setHeader('Set-Cookie',setCookies);return reply(200,result);
    }catch(e){if(setCookies.length)res.setHeader('Set-Cookie',setCookies);return reply(e.status||503,{error:e.status?e.message:'Registry temporarily unavailable. Gameplay remains available.'});}
   }
   const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('st11sid='))?.slice(8);let entry=token&&sessions.get(token);
   if(url.pathname==='/api/open'&&token&&!entry&&!body.fresh&&!body.menuOnly&&recoverLocalSession){try{const prior=recoverLocalSession(token);if(prior){entry=restoreEntry(prior);sessions.set(token,entry);log('local-session-handoff');}}catch(e){return reply(409,{error:e.message==='local-session-in-use'?'local-session-in-use':'local-recovery-unavailable'});}}
   const seatToken=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('st12seat='))?.slice(9);
   function onlineIdentity(){
    const accountToken=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('csAccount='))?.slice(10);
    const account=accountToken?getRegistry().identity(accountToken):null;if(account)return account;
    if(!entry.guestIdentity){const pool=AVATARS.filter(a=>a.access==='guest-goblin').map(a=>({avatarId:a.id,avatarSrc:a.assetPath}));entry.guestIdentity={kind:'guest',playerId:null,guestId:'guest-'+randomBytes(16).toString('hex'),displayName:'Guest'+randomInt(100,1000),...pool[randomInt(pool.length)]};}
    return structuredClone(entry.guestIdentity);
   }
   if(['/api/pvp/identity','/api/single/identity'].includes(url.pathname)){if(url.pathname==='/api/pvp/identity'&&!lan)return reply(403,{error:'lan-disabled'});if(!entry)return reply(404,{error:'unknown-session'});if(Object.keys(body).length)return reply(400,{error:'malformed-request'});return reply(200,{identity:onlineIdentity()});}
   detachFormerPlayers();
   if(entry?.recoveryNotice&&['/api/open','/api/pvp/return-status'].includes(url.pathname)){res.setHeader('Set-Cookie','st12seat='+cookieFlags+'; Max-Age=0');return reply(200,{returning:true,rejoin:entry.recoveryNotice});}
   if(entry?.recoveryNotice&&['/api/read','/api/command','/api/configure'].includes(url.pathname))return reply(409,{error:'seat-handed-to-ai'});
   if(url.pathname==='/api/single/rematch'){
    if(!entry||entry.mode!=='single'||Object.keys(body).length)return reply(400,{error:'invalid-request'});const target=slots(entry).single;if(!target||!target.session.participants)return reply(400,{error:'invalid-request'});const current=await target.session.client.read();if(current.snapshot.phase!=='finished')return reply(400,{error:'not-complete'});const update=await target.session.configure();return reply(200,{configuration:target.configuration,update});
   }
   if(url.pathname==='/api/single/setup'){
    if(!entry)return reply(404,{error:'unknown-session'});
    if(Object.keys(body).join(',')!=='npcNames')return reply(400,{error:'malformed-request'});
    const c={...initial(),singlePlayer:{npcNames:body.npcNames}};try{configuration(c,0);}catch{return reply(400,{error:'invalid-configuration'});}
    const identity=onlineIdentity(),target={configuration:c,session:localSession(c,undefined,identity),statIdentity:identity};slots(entry).single=target;select(entry,'single');return reply(200,{configuration:c,update:await target.session.client.read()});
   }
   if(url.pathname==='/api/pvp/dismiss-return'){if(!entry)return reply(404,{error:'unknown-session'});if(Object.keys(body).length)return reply(400,{error:'malformed-request'});if(entry.seatToken)return reply(409,{error:'seat-still-available'});entry.recoveryNotice=null;entry.mode='main-menu';res.setHeader('Set-Cookie','st12seat='+cookieFlags+'; Max-Age=0');return reply(200,{released:true});}
   if(req.groupLight&&pvp.isGroup(seatToken)){try{if(url.pathname==='/api/pvp/heartbeat'){if(Object.keys(body).length)throw Error('malformed-request');return reply(200,pvp.heartbeat(seatToken,token));}if(url.pathname==='/api/read'&&entry?.mode==='multiplayer'){if(Object.keys(body).some(k=>k!=='after'))throw Error('malformed-request');const live=pvp.liveRead(seatToken,token,body.after??0);if(live)return reply(200,live);}}catch(e){return reply(400,{error:e.message});}}
   if(url.pathname==='/api/command'&&entry?.mode==='multiplayer'&&pvp.isGroup(seatToken)&&req.headers.accept?.includes('application/x-ndjson')){res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});const send=v=>{if(!res.destroyed)res.write(measured('stream-serialization',()=>JSON.stringify(metricsContext.getStore()&&v.type==='result'?{...v,betaGameLog:betaData()}:v))+'\n');};try{const update=await pvp.stream(seatToken,token,body,u=>send({type:'progress',update:u}));if(metricsContext.getStore())metricsContext.getStore()['authoritative-commit-boundary']={ms:performance.now()-betaStart,count:1};await save();send({type:'result',update});}catch(e){send({type:'error',error:'group-command-failed'});}return res.end();}
   if(url.pathname==='/api/pvp/list'){if(!lan)return reply(403,{error:'lan-disabled'});if(!entry)return reply(404,{error:'unknown-session'});if(Object.keys(body).length)return reply(400,{error:'malformed-request'});return reply(200,{games:pvp.list(token)});}
   if(url.pathname==='/api/mode'){
    if(!entry)return reply(404,{error:'unknown-session'});
    if(Object.keys(body).some(k=>!['mode','fallback'].includes(k))||!['single','story','multiplayer'].includes(body.mode)||body.fallback!==undefined&&body.fallback!==true||body.mode==='multiplayer'&&body.fallback!==undefined)return reply(400,{error:'malformed-request'});
    if(body.mode==='multiplayer'){if(!lan||!seatToken)return reply(200,{available:false});try{const opened=await pvp.route(seatToken,token,pvp.requiresExplicitReturn(seatToken)?'return':'open',{});entry.mode='multiplayer';if(opened.returning)return reply(409,{error:'rejoin-required'});return reply(200,{available:true,...opened});}catch(e){return reply(400,{error:e.message==='seat-handed-to-ai'?'seat-handed-to-ai':'unknown-seat'});}}
    if(entry.localRecoveryToken){try{const prior=recoverLocalSession?.(entry.localRecoveryToken);if(!prior)throw Error('local-recovery-unavailable');const restored=restoreEntry(prior);if(restored.localRecoveryToken)throw Error('local-recovery-unavailable');entry.slots=slots(restored);entry.session=restored.session;entry.configuration=restored.configuration;entry.localRecoveryToken=null;}catch(e){if(!body.fallback)return reply(409,{error:e.message==='local-session-in-use'?'local-session-in-use':'local-recovery-unavailable'});entry.unavailableLocalRecoveryToken=entry.localRecoveryToken;entry.localRecoveryToken=null;entry.mode='main-menu';return reply(200,{available:false,localRecoveryFallback:true});}}
    if(body.mode==='story'&&slots(entry).story?.storyOwnerId&&getRegistry().storyState(slots(entry).story.storyOwnerId).runId!==(slots(entry).story.storyRunId||'legacy'))return reply(200,{available:false});
    if(body.mode==='story'&&slots(entry).story?.storyOwnerId!==undefined&&(slots(entry).story?.storyOwnerId||null)!==(onlineIdentity()?.playerId||null))return reply(200,{available:false});
    const target=slots(entry)[body.mode];if(!target||!resumable(target,await target.session.client.read()))return reply(200,{available:false});
    if(!select(entry,body.mode))return reply(200,{available:false});
    return reply(200,{available:true,configuration:entry.configuration,storyContext:slots(entry)[body.mode]?.storyContext,update:await entry.session.client.read()});
   }
   if(url.pathname==='/api/pvp/leave'){if(lan&&seatToken){try{const out=await pvp.route(seatToken,token,'leave');detachFormerPlayers();if(out.reclaimable){entry.mode='multiplayer';log('game-left-reclaimable');return reply(200,out);}if(out.mainMenu){entry.mode='main-menu';entry.seatToken=null;res.setHeader('Set-Cookie','st12seat='+cookieFlags+'; Max-Age=0');return reply(200,out);}}catch{}}if(entry){entry.mode='multiplayer-menu';entry.seatToken=null;}res.setHeader('Set-Cookie','st12seat='+cookieFlags+'; Max-Age=0');log('game-left');return reply(200,{left:true});}
   if(url.pathname.startsWith('/api/pvp/')||(seatToken&&(!entry?.mode||entry.mode==='multiplayer')&&['/api/open','/api/read','/api/command','/api/configure'].includes(url.pathname))){
    if(!lan)return reply(403,{error:'lan-disabled'});
    try{const action=url.pathname.split('/').at(-1);if(['make','join'].includes(action)){if(!entry)return reply(404,{error:'unknown-session'});const identity=onlineIdentity();const result=await pvp.lobby(action,{...body,name:identity.displayName,identity},token);res.setHeader('Set-Cookie',`st12seat=${result.token}${cookieFlags}; Max-Age=86400`);entry.seatToken=result.token;entry.recoveryNotice=null;delete result.token;entry.mode='multiplayer';log(action==='make'?'game-created':'seat-joined');return reply(200,result);}if(action==='configure'&&pvp.rooms.get(body.code)?.seats.length===2)return reply(403,{error:'lan-configuration-locked'});const result=await pvp.route(seatToken,token,action==='open'&&url.pathname==='/api/open'&&pvp.requiresExplicitReturn(seatToken)?'return':action,body);if(result.token&&entry){entry.seatToken=result.token;entry.recoveryNotice=null;entry.mode='multiplayer';res.setHeader('Set-Cookie',`st12seat=${result.token}${cookieFlags}; Max-Age=86400`);delete result.token;result.movedToRematch=true;}if(['surrender','give-up'].includes(action)&&entry){detachFormerPlayers();entry.seatToken=null;entry.recoveryNotice=null;entry.mode='main-menu';res.setHeader('Set-Cookie','st12seat='+cookieFlags+'; Max-Age=0');}if(action==='open'&&entry){result.modes=Object.keys(slots(entry));result.localRecoveryPending=!!entry.localRecoveryToken;}return reply(200,result);}catch(e){return reply(400,{error:['stale','rejoin-required','kick-unavailable','seat-handed-to-ai','unknown-seat','bad-game-code','game-full','invalid-name','already-seated','not-complete','invalid-configuration','unknown-session'].includes(e.message)?e.message:'invalid-request'});}
   }
   if(url.pathname==='/api/open'&&entry?.mode==='multiplayer'&&!seatToken)return reply(409,{error:'missing-seat-credential'});
   if(url.pathname==='/api/open'){
    if(Object.keys(body).some(k=>!['fresh','menuOnly'].includes(k))||body.fresh!==undefined&&body.fresh!==true||body.menuOnly!==undefined&&body.menuOnly!==true||body.fresh&&body.menuOnly)return reply(400,{error:'malformed-request'});
    if(body.menuOnly&&seatToken)return reply(409,{error:'missing-seat-credential'});
    if(token&&!entry&&!body.fresh&&!body.menuOnly)return reply(404,{error:'unknown-session'});
    const deferred=body.menuOnly&&!entry&&/^[a-f0-9]{64}$/.test(token||'')?token:null;
    const reconnected=!!entry&&!body.fresh;if(!reconnected){const made=make();entry=made.entry;if(deferred){entry.localRecoveryToken=deferred;entry.mode='main-menu';}res.setHeader('Set-Cookie',`st11sid=${made.token}${cookieFlags}; Max-Age=86400`);}
    return await ordered(entry,async()=>reply(200,{configuration:entry.configuration,reconnected,development,localRecoveryPending:!!entry.localRecoveryToken,mainMenu:entry.mode==='main-menu',multiplayerMenu:entry.mode==='multiplayer-menu',modes:Object.keys(slots(entry)),localResume:await localResumeModes(entry,onlineIdentity()),update:await entry.session.client.read()}));
   }
   if(!entry)return reply(404,{error:'unknown-session'});
   return await ordered(entry,async()=>{
    if(entry.localRecoveryToken&&['/api/command','/api/configure'].includes(url.pathname))return reply(409,{error:'local-recovery-unavailable'});
    if(url.pathname==='/api/read'){if(Object.keys(body).some(k=>k!=='after'))return reply(400,{error:'malformed-request'});try{return reply(200,await entry.session.client.read(body.after??0));}catch{return reply(400,{error:'invalid-cursor'});}}
    if(url.pathname==='/api/command'){
     const slot=slots(entry)[modeOf(entry.configuration)];if(!slot.matchStatistics?.startedAt)slot.statIdentity=onlineIdentity();
     const bindStory=update=>{if(slot.configuration.story&&update.accepted&&body.intent?.kind==='start'){if(slot.storyOwnerId===undefined)slot.storyOwnerId=onlineIdentity()?.playerId||null;if(slot.storyRunId===undefined)slot.storyRunId=slot.storyOwnerId?getRegistry().storyState(slot.storyOwnerId).runId:null;}return update;};
     if(req.headers.accept!=='application/x-ndjson')return reply(200,bindStory(await entry.session.client.dispatch(body)));
     const send=value=>{if(res.destroyed)return;if(!res.headersSent){res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.flushHeaders();}res.write(JSON.stringify(value)+'\n');};
     const update=bindStory(await entry.session.dispatchWithProgress(body,async frame=>{send({type:'preview',frame});await new Promise(resolve=>setImmediate(resolve));}));
     try{if(!fatal)await save();}catch{fatal=true;log('checkpoint-write-failed');send({type:'error',error:'server-recovery-unavailable'});res.end();return;}
     send({type:'result',update});res.end();return;
    }
    if(url.pathname==='/api/configure'){
     if(Object.keys(body).filter(k=>k!=='storyContext').sort().join(',')!=='battle,configuration,revision')return reply(400,{error:'malformed-request'});
     const current=await entry.session.client.read();if(body.battle!==current.snapshot.battle||body.revision!==current.snapshot.revision)return reply(409,{error:'stale'});
     let config,context;try{config=configuration(body.configuration,0);context=storyContext(body.storyContext);if(context&&!body.configuration.story)throw Error();}catch{return reply(400,{error:'invalid-configuration'});}
     try{const mode=modeOf(body.configuration),all=slots(entry);let target=all[mode],update;if(target){if(!!target.session.participants!==(body.configuration.singlePlayer?.npcNames.length>1)){target.session=localSession(body.configuration,undefined,onlineIdentity());delete target.matchStatistics;update=await target.session.client.read();}else update=await target.session.configure(config);target.configuration=structuredClone(body.configuration);}else{target={session:createLocalSession(configuration(body.configuration,seed??randomInt(0,0x100000000)),undefined,development),configuration:structuredClone(body.configuration)};const saved=JSON.parse(await target.session.serializePrivate());saved.epoch=randomInt(1,2**48);target.session=createLocalSession(config,JSON.stringify(saved),development);update=await target.session.client.read();all[mode]=target;}target.storyContext=context;target.storyOwnerId=body.configuration.story?(onlineIdentity()?.playerId||null):null;target.storyRunId=target.storyOwnerId?getRegistry().storyState(target.storyOwnerId).runId:null;delete target.storyCapturedEpoch;select(entry,mode);return reply(200,{configuration:entry.configuration,update});}catch{return reply(400,{error:'invalid-configuration'});}
    }
    if(url.pathname.startsWith('/api/dev/')){if(!development)return reply(403,{error:'development-denied'});if(url.pathname==='/api/dev/inspect')return reply(200,await entry.session.dev.inspect());if(url.pathname==='/api/dev/takeover'&&typeof body.enabled==='boolean')return reply(200,await entry.session.dev.takeover(body.enabled));if(url.pathname==='/api/dev/shoot')return reply(200,await entry.session.dev.shoot(body.cell));}
    return reply(404,{error:'not-found'});
   });
  }catch{log('request-failed');return reply(400,{error:'malformed-request'});}
 };
 const server=http.createServer(async(req,res)=>{req.betaArrival=performance.now();try{if(req.method==='POST'){let bytes=0;const chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>65536){res.writeHead(413,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'request-too-large'}));return;}chunks.push(chunk);}req.intake=Buffer.concat(chunks);}if(req.url.startsWith('/api/registry/')){req.groupLight=true;await handle(req,res);return;}const st=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('st12seat='))?.slice(9);if((req.url==='/api/pvp/heartbeat'&&pvp.requiresExplicitReturn(st))||(req.url==='/api/read'&&pvp.isGroup(st)&&pvp.isBusy(st))){req.groupLight=true;await handle(req,res);return;}/* Read-only allowlisted assets must not wait behind an active combat transaction. */if(req.method==='GET'&&!req.url.startsWith('/api/')){await handle(req,res);return;}requestQueue=requestQueue.then(()=>handle(req,res)).catch(()=>{log('unexpected-server-error');if(!res.headersSent)res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'server-error'}));});}catch{if(!res.destroyed)res.destroy();}});
 server.requestTimeout=15000;server.headersTimeout=10000;server.keepAliveTimeout=5000;server.setTimeout(20000,socket=>socket.destroy());
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,address,resolve);}).catch(e=>{store?.release();throw e;});origin='http://127.0.0.1:'+server.address().port;
 const policyTimer=setInterval(()=>{requestQueue=requestQueue.then(async()=>{if(stopping||fatal)return;if(await pvp.tick())await save();detachFormerPlayers();}).catch(()=>{fatal=true;log('disconnect-policy-failed');});},500);policyTimer.unref();
 log('startup',{checkpoint:checkpointId,build,mode:development?'development':'production',address,port:server.address().port,lan,persistence:!!store,recovery});
 return {origin,lan,address,pvp,close:async()=>{stopping=true;clearInterval(policyTimer);const closed=new Promise(resolve=>server.close(resolve));await requestQueue;await pvp.close();try{if(!fatal)await save();}finally{await closed;store?.release();registry?.close();log('shutdown');}},
  // Process-local test/restart capabilities. Never routed over production HTTP.
  checkpoint:token=>sessions.get(token)?.session.serializePrivate(),
  install:(c,checkpoint)=>make(c,checkpoint).token,
  sessions};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 try{const mode=process.env.ST_MODE||'production';if(!['production','development'].includes(mode))throw Error('Invalid ST_MODE');const app=await startServer({port:Number(process.env.PORT||3211),development:mode==='development'||process.argv.includes('--development'),lan:process.argv.includes('--lan'),bind:process.env.ST_BIND||process.env.LAN_BIND,stateDir:process.env.ST_STATE_DIR,publicOrigin:process.env.ST_PUBLIC_ORIGIN,secureCookies:process.env.ST_SECURE_COOKIES==='1'});console.log(app.origin);let closing=false;for(const signal of ['SIGINT','SIGTERM'])process.on(signal,async()=>{if(closing)return;closing=true;await app.close();process.exit(0);});}catch{console.error('Stone Throw startup failed: check configuration, state lock and checkpoint compatibility.');process.exitCode=1;}
}
