// Temporary private LAN diagnostics. No client payloads, gameplay entropy or recovery journal.
import fs from 'node:fs';
import {metricsContext} from './beta-metrics.mjs';
import path from 'node:path';
import {threadId} from 'node:worker_threads';
const identitiesByRoom=new Map();
const pending=new WeakMap(),LOG_LIMIT=2*1024*1024,STATE_LIMIT=32*1024*1024,ROW_LIMIT=4096;
const dir=()=>process.env.ST_PLAGUE_CAPTURE_DIR;
const key=c=>`${c.x},${c.y}`;
function adjacent(k,size){const [x,y]=k.split(',').map(Number),rows=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(dx||dy){const a=x+dx,b=y+dy;rows.push({cell:`${a},${b}`,reason:a<0||b<0||a>=size||b>=size?'outside-board':null});}return rows;}
function safe(fn){try{return fn();}catch(e){console.error('Private Plague capture failed: '+e.message);}}
function append(directory,row){const file=path.join(directory,'plague-trace.jsonl'),old=path.join(directory,'plague-trace.previous.jsonl'),text=JSON.stringify(row)+'\n';if(Buffer.byteLength(text)>LOG_LIMIT)return;if(fs.existsSync(file)&&fs.statSync(file).size+Buffer.byteLength(text)>LOG_LIMIT){fs.rmSync(old,{force:true});fs.renameSync(file,old);}fs.appendFileSync(file,text);}
function snapshot(directory,name,value){const text=JSON.stringify(value);if(Buffer.byteLength(text)>STATE_LIMIT){append(directory,{kind:'snapshot-size-limit',name,bytes:Buffer.byteLength(text),limit:STATE_LIMIT,use:'normal checkpoint.json retains full recovery state'});fs.rmSync(path.join(directory,name),{force:true});return false;}const file=path.join(directory,name),tmp=file+'.'+process.pid+'-'+threadId+'.tmp';fs.writeFileSync(tmp,text);fs.renameSync(tmp,file);return true;}
function outbreakId(room,h,p){if(!p)return null;if(p.outbreaks[0]?.statisticsId)return room.code+'/'+room.epoch+'/'+p.outbreaks[0].statisticsId;const k=room.code+'/'+room.epoch+'/'+p.ownerId+'/'+p.targetBoardId;const scheduled=h.pendingRoot?.events.filter(e=>e.kind==='plague-scheduled').at(-1);if(!identitiesByRoom.has(k)||p.outbreaks.every(o=>o.round===0)&&scheduled)identitiesByRoom.set(k,scheduled?k+'/'+scheduled.rootId+'/'+scheduled.sequence:k+'/observed-'+h.rootSerial);while(identitiesByRoom.size>64)identitiesByRoom.delete(identitiesByRoom.keys().next().value);return identitiesByRoom.get(k);}
export function beginPlagueCapture(room,command){if(!dir()||!metricsContext.getStore())return;pending.set(room,{before:room.host,command,rows:[],seen:new Set(),dropped:0});}
export function observePlagueCapture(room,h){const capture=pending.get(room);if(!capture)return;safe(()=>{const c=h.pendingRoot;if(!c)return;const f=c.frames.at(-1),op=f?.current[f.cursor]?.operation;if(!op||!['plague-step','plague-progress'].includes(op.kind))return;const token=c.id+'/'+f.id+'/'+f.cursor;if(capture.seen.has(token))return;capture.seen.add(token);if(capture.rows.length>=ROW_LIMIT){capture.dropped++;return;}const p=f.detachedPlague||c.state.plagues.find(p=>p.targetBoardId===op.targetBoardId&&(!op.plagueId||p.outbreaks.some(o=>o.statisticsId===op.plagueId))),o=p?.outbreaks[op.outbreakIndex??0],shots=new Set(c.state.seats.find(s=>s.boardId===op.targetBoardId)?.shots||[]),reserved=new Set(op.reserved||[]),classify=rows=>rows.map(r=>({...r,reason:r.reason||(shots.has(r.cell)?'already-shot':reserved.has(r.cell)?'reserved-in-step':null)})),local=o?(op.stage==='child'&&op.oldFrontier[op.parentIndex]?adjacent(op.oldFrontier[op.parentIndex],h.config.size):o.origin?adjacent(key(o.origin),h.config.size):[]):[],edge=o?[...new Set(o.infected.flatMap(k=>adjacent(k,h.config.size).filter(r=>!r.reason).map(r=>r.cell)))].map(cell=>({cell,reason:null})):[];
capture.rows.push({root:c.id,work:f.current[f.cursor].id,kind:op.kind,stage:op.stage??null,stopReason:op.kind==='plague-progress'&&!o&&p&&!p.outbreaks.some(o=>o.round>0&&o.round<5&&o.frontier.length)?(p.outbreaks.every(o=>o.round>=5)?'five-step-limit':p.outbreaks.every(o=>o.round===0)?'no-legal-seed':'frontier-exhausted'):null,outbreak:{id:outbreakId(room,h,p),owner:p?.ownerId,target:p?.targetPlayerId,board:p?.targetBoardId,trigger:p?.triggerPlayerId,moveOn:p?.moveOnPlayerId,index:op.outbreakIndex??0,origin:o?.origin},step:o?o.round+1:null,infected:o?[...o.infected]:[],frontier:o?[...o.frontier]:[],local:classify(local),wholeEdge:classify(edge),branchWanted:op.wanted??null,child:op.childIndex??null,rngCursor:h.rng.cursor});});}
export function finishPlagueCapture(room){const cap=pending.get(room);pending.delete(room);if(!cap||!dir())return;safe(()=>{const h=room.host,b=cap.before,events=h.events.slice(b.events.length).map(r=>r.event),changed=JSON.stringify(b.state.plagues)!==JSON.stringify(h.state.plagues),relevant=cap.rows.length||changed||events.some(e=>e.kind.startsWith('plague-')||e.meta?.source==='plague');if(!relevant)return;const directory=path.resolve(dir());fs.mkdirSync(directory,{recursive:true});const context={room:room.code,epoch:room.epoch,command:cap.command,hostCommand:h.history.at(-1)?.sequence,at:new Date().toISOString(),round:h.round,turn:h.turnIndex,active:h.activePlayerId,status:h.status,rngBefore:b.rng.cursor,rngAfter:h.rng.cursor};
const identities=p=>({id:outbreakId(room,h,p),owner:p.ownerId,target:p.targetPlayerId,trigger:p.triggerPlayerId,moveOn:p.moveOnPlayerId,board:p.targetBoardId,outbreaks:p.outbreaks});append(directory,{...context,kind:'command-before',plagues:b.state.plagues.map(identities)});for(const row of cap.rows)append(directory,{room:room.code,epoch:room.epoch,command:context.hostCommand,...row});for(const e of events)if(e.kind.startsWith('plague-')||e.meta?.source==='plague'||['hero-killed','outcome','compatibility-truncation'].includes(e.kind))append(directory,{room:room.code,epoch:room.epoch,command:context.hostCommand,kind:'rule-event',event:e});
const stopped=b.state.plagues.filter(p=>!h.state.plagues.some(q=>outbreakId(room,h,q)===outbreakId(room,h,p)));for(const p of stopped){const rows=cap.rows.filter(r=>r.outbreak.id===outbreakId(room,h,p)),last=rows.at(-1),reason=h.state.ring?.eliminated.includes(p.targetPlayerId)?'target-eliminated':h.state.match.outcome.kind!=='ongoing'?'match-ended':last?.stopReason?last.stopReason:events.some(e=>e.kind==='plague-contained')?'contained-inspect-frontier-rows':'UNEXPLAINED-removal';append(directory,{...context,kind:'outbreak-removed',owner:p.ownerId,target:p.targetPlayerId,reason,lastProgress:last});}
append(directory,{...context,kind:'command-after',plagues:h.state.plagues.map(identities),droppedRows:cap.dropped});snapshot(directory,'plague-state-before.json',{...context,host:b});snapshot(directory,'plague-state-after.json',{...context,host:h});});}
export const plagueCaptureLimits={logBytes:LOG_LIMIT,logFiles:2,stateBytes:STATE_LIMIT,stateFiles:2,rowsPerCommand:ROW_LIMIT};
