import {beginPlagueCapture,observePlagueCapture,finishPlagueCapture} from './plague-capture.mjs';
import {archiveEncoder,archiveDecoder} from './archive-wire.mjs';
import {cloneHost,isArchive} from '../canonical/compiled/archives.js';
import {captureGroupCredits,groupStatistics} from './group-statistics.mjs';
import {DISCONNECT_GRACE_MS,HEARTBEAT_TIMEOUT_MS,presence} from './disconnect-policy.mjs';
import {metricsContext,metric,measuredAsync} from './beta-metrics.mjs';
import {Worker} from 'node:worker_threads';
import {isDeepStrictEqual} from 'node:util';
import {groupPresentation} from './group-presentation.mjs';
import {exportRooms,restoreRooms} from './room-recovery.mjs';
import {randomBytes,randomInt} from 'node:crypto';
import {createHost} from '../canonical/compiled/host/initialization.js';
import {acceptCommand,pumpHost} from '../canonical/compiled/host/lifecycle.js';
import {normalTarget} from '../canonical/compiled/host/ring.js';
import {refreshHost} from '../canonical/compiled/host/refresh.js';
import {serializeHost} from '../canonical/compiled/host/serialization.js';
import {legacyRandomPlacement} from '../canonical/compiled/policy/placement-legacy.js';
import {heroRelocation,heroLocalEscape} from '../canonical/compiled/policy/special-decisions.js';
import {parseKey,cellKey} from '../canonical/compiled/combat/access.js';
import {random} from '../canonical/compiled/combat/rng.js';
import {normalPolicy,emptyNormalMemory} from '../canonical/compiled/local-host/normal-policy.js';
import {refreshNormalMemory} from '../canonical/compiled/local-host/normal-step.js';
import {normalCatapultChoice} from '../canonical/compiled/local-host/normal-catapult.js';
import {emptyStatistics,captureStatistics} from '../canonical/compiled/local-host/public-statistics.js';
import {projectSeat} from './projection.mjs';
import {neighbors8} from '../canonical/compiled/rules/coordinates.js';

export function createRingService(roster,{seed,onFailure,now=Date.now,workers=true,onFrame}={}){
 const rooms=new Map(),tokens=new Map();const presentation=groupPresentation((r,i,after)=>readBase(r,i,after),target,onFrame);const workerPool=new Map(),workerIdle=new WeakMap();const running=new Map(),cached=new Map(),readCache=new WeakMap();
 const execution=r=>{const base=presentation.execution(r);return {...base,observePresentationStep:h=>{captureGroupCredits(r,h);base.observePresentationStep(h);observePlagueCapture(r,h);}};};
 const configuration={size:15,story:false,battle:0,player:{size:15,...roster},enemy:{size:15,...roster}};
 const label=v=>{if(typeof v!=='string'||!v.trim()||v.trim().length>24)throw Error('invalid-name');return v.trim();};
 const cmd=(r,c)=>{const command={id:'ring-'+(++r.serial),...c};beginPlagueCapture(r,command);try{r.host=acceptCommand(r.host,command,execution(r));if(['start','advance-turn'].includes(c.kind))sample(r);}finally{finishPlagueCapture(r);}};
 const order=r=>r.host.state.ring.order;
 const active=(r,i)=>order(r).includes(r.host.config.players[i].id);
 const mapHandle=(map,id,prefix)=>{if(!map.has(id))map.set(id,prefix+(map.size+1));return map.get(id);};
 function view(r,i,j){const h=r.host,ids=[h.config.players[i].id,h.config.players[j].id];
  const seats=ids.map(id=>h.state.seats.find(p=>p.playerId===id));
  const own={...seats[0]};{const k=h.state.ring.knowledge[ids[0]+':'+ids[1]];own.scouted=k?.scouted||[];own.monkCandidates=k?.monkCandidates||[];}
  return {...h,config:{...h.config,players:ids.map(id=>h.config.players.find(p=>p.id===id))},state:{...h.state,seats:[own,seats[1]]}};
 }
 function target(r,i){const h=r.host,p=h.config.players[i],d=h.pendingRoot?.decisions.find(d=>d.status==='pending'&&d.actorId===p.id);
  if(d&&d.boardId!==p.boardId)return h.config.players.findIndex(p=>p.boardId===d.boardId);
  if(active(r,i)&&order(r).length>1)return h.config.players.findIndex(q=>q.id===normalTarget(h.state,p.id).playerId);
  return h.config.players.findIndex((q,j)=>j!==i&&order(r).includes(q.id));
 }
 function sample(r){readCache.delete(r);captureGroupCredits(r,r.host);for(let i=0;i<r.seats.length;i++)for(let j=0;j<r.seats.length;j++)if(i!==j&&(active(r,j)||!r.statistics[i][j].ended)){captureStatistics(view(r,i,j),r.statistics[i][j]);if(!active(r,j))r.statistics[i][j].ended=true;}for(let i=0;i<r.seats.length;i++){const own=r.statistics[i][i];if(!own.ended){captureStatistics(view(r,i,(i+1)%r.seats.length),own);if(!active(r,i))own.ended=true;}}}
 function place(r,i,intent){const p=r.host.config.players[i];const apply=(unitId,type,cells)=>cmd(r,{kind:'place',placement:{unitId,ownerId:p.id,boardId:p.boardId,type,cells}});
  function rebuild(keep){const rng=structuredClone(r.host.rng),c=r.host.config;r.host=createHost(c);for(const placement of keep)cmd(r,{kind:'place',placement});r.host.rng=rng;refreshHost(r.host);}
  if(intent.kind==='place')apply('ring-unit-'+(++r.serial),intent.unit,intent.cells);
  else if(intent.kind==='clear-placement')rebuild(r.host.placements.filter(u=>u.ownerId!==p.id));
  else if(intent.kind==='random-placement'){rebuild(r.host.placements.filter(u=>u.ownerId!==p.id));for(const u of legacyRandomPlacement(i?'second-seat':'first-seat',15,roster,r.host.rng,false))apply('ring-unit-'+(++r.serial),u.type,u.cells.map(parseKey));}
  else{const uid=[...r.handles[i]].find(([,v])=>v===intent.unit)?.[0],u=r.host.placements.find(u=>u.unitId===uid&&u.ownerId===p.id);if(!u)throw Error('wrong-seat');rebuild(r.host.placements.filter(p=>p.unitId!==uid));if(intent.kind==='move')apply(u.unitId,u.type,intent.cells);}
 }
 function reset(r,seedOverride){for(const s of r.seats){s.absence=null;s.disconnects=0;}r.creditState=null;r.news=[];r.noticeSerial=0;r.quick={status:'available',accepted:[]};r.rematchOrder=[];r.hostSeat??=0;const n=r.seats.length;r.host=createHost({matchId:'ring-private',rulesVersion:'stone-throw-v1.427',size:15,story:false,seed:seedOverride??seed??randomInt(0,0x100000000),players:r.seats.map((s,i)=>({id:'seat-'+i,boardId:'board-'+i,roster,decisionMode:'interactive'}))});r.epoch++;r.revision=0;r.serial=0;r.ready=Array(n).fill(false);r.rematch=r.seats.map(s=>s.controller==='ai');r.memory=emptyNormalMemory();r.aiMemory={};r.statistics=Array.from({length:n},()=>Array.from({length:n},emptyStatistics));r.handles=Array.from({length:n},()=>new Map());r.choices=Array.from({length:n},()=>new Map());
  for(let i=0;i<n;i++)if(r.seats[i].controller==='ai'){place(r,i,{kind:'random-placement'});r.ready[i]=true;}
 }
 function aiStep(r,i){const h=r.host,owner=h.config.players[i],d=h.pendingRoot?.decisions.find(d=>d.status==='pending'),j=d&&d.boardId!==owner.boardId?h.config.players.findIndex(p=>p.boardId===d.boardId):h.config.players.findIndex(p=>p.id===normalTarget(h.state,owner.id).playerId);
  // The accepted normal AI expects target first and AI owner second. Only its read context changes.
  const v={...h,config:{...h.config,players:[h.config.players[j],owner]},state:{...h.state,seats:[h.state.seats[j],h.state.seats[i]]}};
  const memory=r.aiMemory[i+':'+j]??=emptyNormalMemory();
  const aiSeat={...v.state.seats[1]},targetId=h.config.players[j].id;
  {const known=h.state.ring.knowledge[owner.id+':'+targetId];aiSeat.scouted=known?.scouted||[];aiSeat.monkCandidates=known?.monkCandidates||[];}v.state={...v.state,seats:[v.state.seats[0],aiSeat]};
  let hunt=[...memory.heroHunt];for(const {event:e}of h.events.slice(memory.eventCursor)){if(e.kind==='impact'&&e.meta?.targetPlayerId===targetId&&e.unitId&&e.cells[0]){const hero=h.state.match.units.find(u=>u.id===e.unitId);if(hero?.hero?.hitsTaken===2)hunt=neighbors8({size:h.config.size},e.cells[0].x,e.cells[0].y).filter(k=>!h.state.seats[j].shots.includes(k));}}
  v.brains=h.brains.map(b=>b.playerId===owner.id?{...b,heroHunt:hunt}:b);refreshNormalMemory(v,memory);const policy=normalPolicy(v,memory);
  if(!d){const plagueAware=h.state.plagues.some(p=>p.targetPlayerId===h.config.players[j].id),k=policy.target(plagueAware);if(plagueAware&&metricsContext.getStore()){const rows=r.betaAiPlagueDiagnostics??=[];rows.push({round:h.round,actor:owner.id,target:h.config.players[j].id,...policy.plagueDiagnostic(k)});if(rows.length>64)rows.shift();}if(k)cmd(r,{kind:'shoot',actorId:owner.id,boardId:h.config.players[j].boardId,cell:parseKey(k)});else{h.turnStep='plague';h.status='running';pumpHost(h,100000,execution(r));}return;}
  let cell=null,unitId=null;
  if(d.kind==='resurrection')unitId=d.legalUnitIds[Math.floor(random(h.rng,'resurrection')*d.legalUnitIds.length)];
  else if(d.kind==='hero-relocation'){const local=h.state.match.units.find(u=>u.id===d.unitId)?.hero?.hitsTaken===2,k=local?heroLocalEscape(h,owner.id,d.legalCells.map(cellKey)):heroRelocation(h,owner.id);cell=k?parseKey(k):null;}
  else if(d.kind==='scout'){if(!memory.scoutQueue.length)memory.scoutQueue=policy.scout(d.remaining);const k=memory.scoutQueue.shift();cell=k?parseKey(k):null;}
  else if(d.kind==='catapult-target'){const k=normalCatapultChoice(v,memory);cell=k?parseKey(k):null;}
  else if(d.kind==='catapult-roll'){const k=policy.roll(d.legalCells.map(cellKey),true);cell=k?parseKey(k):null;}
  else throw Error('Unsupported AI decision '+d.kind);
  cmd(r,{kind:'answer',answer:{actorId:owner.id,decisionId:d.id,cell,unitId}});
 }
 function drain(r){if(!r.seats.some(s=>s.controller==='human'&&s.token&&!s.left&&!s.absence&&now()-s.seen<HEARTBEAT_TIMEOUT_MS)){r.pausedAi=true;return;}r.pausedAi=false;for(let step=0;step<10000;step++){const h=r.host;if(h.status==='awaiting-turn'){cmd(r,{kind:'advance-turn'});continue;}const d=h.pendingRoot?.decisions.find(d=>d.status==='pending'),actor=d?.actorId||h.activePlayerId,i=h.config.players.findIndex(p=>p.id===actor);
   if(['awaiting-command','awaiting-decision'].includes(h.status)&&i>=0&&r.seats[i].controller==='ai'){aiStep(r,i);continue;}if(h.status==='running')throw Error('Unresolved host');sample(r);return;
  }throw Error('AI progress bound exceeded');
 }
 // Cache only observer-safe projection data for this exact committed host/revision.
 // Presence is refreshed independently; no authority or validation boundary is skipped.
 function read(r,i,after=0){let cache=readCache.get(r);if(r.host.status==='placement'||!cache||cache.host!==r.host||cache.revision!==r.revision){cache={host:r.host,revision:r.revision,updates:[]};readCache.set(r,cache);}const base=cache.updates[i]??=readBase(r,i,r.host.state.match.knowledge[r.host.config.players[i].id].events.length),update={...base,events:publicEvents(r,i,after),lan:{...base.lan,presence:presence(r,now()),connected:presence(r,now()).map(s=>s.connected),joined:r.seats.map(s=>!!s.token&&!s.left),controllers:r.seats.map(s=>s.controller),news:r.news||[],quickStart:r.quick,ready:[...r.ready],rematch:[...r.rematch],rematchCommitted:r.rematchOrder||[],closed:r.closed}};return presentation.decorate(r,i,update,after);}
 function publicEvents(r,i,after){const h=r.host,p=h.config.players[i],j=target(r,i),visibleSelf=active(r,i)||h.status==='complete',visibleTarget=h.status==='complete'||visibleSelf&&j>=0&&active(r,j),focus=j>=0?j:(i+1)%r.seats.length,boards=new Set([...(visibleSelf?[p.boardId]:[]),...(visibleTarget?[h.config.players[focus].boardId]:[])]);return h.state.match.knowledge[p.id].events.slice(after).filter(e=>boards.has(e.boardId)).map(e=>({position:e.sequence,kind:e.kind,side:e.boardId===p.boardId?'self':'opponent',cell:e.cell?{...e.cell}:null,unitKind:e.unitType}));}
 function readBase(r,i,after=0){const h=r.host,p=h.config.players[i],j=target(r,i),visibleSelf=active(r,i)||h.status==='complete',visibleTarget=h.status==='complete'||visibleSelf&&j>=0&&active(r,j);const focus=j>=0?j:(i+1)%r.seats.length,v=view(r,i,focus),boards=new Set([...(visibleSelf?[p.boardId]:[]),...(visibleTarget?[h.config.players[focus].boardId]:[])]);
  for(const u of h.state.match.units.filter(u=>u.ownerId===p.id))mapHandle(r.handles[i],u.id,`own-${r.epoch}-${i}-`);
  for(const d of h.pendingRoot?.decisions.filter(d=>d.actorId===p.id)||[])mapHandle(r.choices[i],d.id,`choice-${r.epoch}-${i}-`);
  const ownKnowledge=h.state.match.knowledge[p.id],visibleEvents=ownKnowledge.events.slice(after).filter(e=>boards.has(e.boardId)),events=visibleEvents.map((e,k)=>({...e,sequence:k+1}));
  v.state={...v.state,match:{...h.state.match,history:[],knowledge:Object.fromEntries(Object.entries(h.state.match.knowledge).map(([id,k])=>[id,{...k,events:id===p.id?events:[]}]))}};v.events=h.events.filter(e=>!e.event.meta||boards.has(e.event.meta.targetBoardId));
  const memory={...r.memory,resultMessage:null,demonRunes:(r.memory.demonRunes||[]).filter(b=>boards.has(b.boardId))};
  const update=projectSeat(v,memory,r.statistics[i][focus],r.epoch,r.revision,r.handles[i],r.choices[i],0,true);update.snapshot.eventPosition=ownKnowledge.events.length;update.events=update.events.map(e=>({...e,position:visibleEvents[e.position-1].sequence})).filter(e=>e.position>after);update.snapshot.groupRoom='room-'+r.epoch;
  const s=update.snapshot;s.scoutFootprints=[];
  // Publish only the coordinates of completed Scout observations on visible boards.
  for(const [side,index,visible]of [['self',i,visibleSelf],['opponent',focus,visibleTarget]])if(visible){const targetId=h.config.players[index].id,cells=new Set();for(const actor of h.config.players)for(const k of h.state.ring.knowledge[actor.id+':'+targetId]?.scouted||[])cells.add(k);for(const k of cells)s.scoutFootprints.push({side,cell:parseKey(k)});}
  s.stats.group=groupStatistics(r,i,view,active);for(const [side,seatIndex]of [['player',i],['enemy',focus]]){s.stats[side+'UnitsDestroyed']=s.stats.group.players[seatIndex].units;s.stats[side+'CoreDestroyed']=s.stats.group.players[seatIndex].core;}s.groupLog=ownKnowledge.events.slice(-120).map(e=>({sequence:e.sequence,text:(r.seats[h.config.players.findIndex(p=>p.boardId===e.boardId)]?.name||'Battle')+': '+e.kind+(e.unitType?' '+e.unitType:'')}));s.lossReveal=[];s.battle+=`-focus-${focus}`;if(h.status==='placement')for(const row of Object.values(s.strips.opponent))Object.assign(row,{placed:0,destroyed:0,heroHits:0});
  if(!visibleSelf){s.heroPresentation=null;s.plagueCells=[];s.storyPlagueTargets=[];s.demonRunes=[];s.owned=[];s.ownImpacts=[];s.choice=null;s.shotsLeft=0;s.rosters.self={};s.strips.self={};s.phase='finished';s.outcome=h.state.match.outcome.kind==='draw'?'draw':'loss';}
  if(!visibleTarget){s.opponent=[];s.rosters.opponent={};s.strips.opponent={};s.monkClues=[];s.aimAssistCells=[];s.enemyResurrection={active:false,cells:[]};}
  update.lan={group:true,rematchSource:r.rematchSource||null,joined:r.seats.map(s=>!!s.token&&!s.left),hostSeat:r.hostSeat,quickStart:r.quick,recoveryBattle:'room-'+r.epoch,presence:presence(r,now()),news:r.news||[],graceMs:DISCONNECT_GRACE_MS,current:h.activePlayerId?h.config.players.findIndex(p=>p.id===h.activePlayerId):null,rematchCommitted:r.rematchOrder||[],code:r.code,self:i,names:r.seats.map(s=>s.name),ready:[...r.ready],rematch:[...r.rematch],connected:presence(r,now()).map(s=>s.connected),closed:r.closed,waiting:!!h.pendingRoot?.decisions.some(d=>d.status==='pending'&&d.actorId!==p.id),controllers:r.seats.map(s=>s.controller),ring:h.status==='placement'?[]:order(r).map(id=>h.config.players.findIndex(p=>p.id===id)),eliminated:h.state.ring.eliminated.map(id=>h.config.players.findIndex(p=>p.id===id)),target:h.status!=='placement'&&visibleTarget?focus:null,complete:h.status==='complete',ownBoardVisible:visibleSelf,targetBoardVisible:visibleTarget};return update;
 }
 async function dispatch(r,i,request){return measuredAsync('authoritative-transaction-including-projection',()=>dispatchInner(r,i,request));}
 async function dispatchInner(r,i,request){const current=await read(r,i,r.host.state.match.knowledge[r.host.config.players[i].id].events.length),deny=error=>({...current,accepted:false,error,events:[],presentation:[]});if(!request||Object.keys(request).sort().join(',')!=='battle,contract,intent,revision')return deny('unsupported');if(request.contract!==current.snapshot.contract||request.battle!==current.snapshot.battle||request.revision!==r.revision)return deny('stale');
  const intent=request.intent,fields={place:['unit','cells'],move:['unit','cells'],remove:['unit'],'random-placement':[],start:[],shoot:['cell'],answer:['choice','cell','unit']};if(!intent||!fields[intent.kind]||Object.keys(intent).sort().join(',')!==['kind',...fields[intent.kind]].sort().join(','))return deny('unsupported');if(r.closed||!active(r,i)||r.seats[i].controller!=='human')return deny('illegal');
  const before={creditState:structuredClone(r.creditState),presentation:structuredClone(r.presentation),host:cloneHost(r.host),memory:structuredClone(r.memory),statistics:structuredClone(r.statistics),aiMemory:structuredClone(r.aiMemory),serial:r.serial,revision:r.revision,ready:[...r.ready]};presentation.begin(r);
  try{const p=r.host.config.players[i];if(['place','move','remove','random-placement'].includes(intent.kind)){if(r.host.status!=='placement'||r.ready[i])throw Error('placement-locked');place(r,i,intent);}
   else if(intent.kind==='start'){if(r.quick.status==='pending')throw Error('quick-pending');ready(r,i);}
   else if(intent.kind==='shoot'){if(r.host.activePlayerId!==p.id)throw Error('wrong-turn');cmd(r,{kind:'shoot',actorId:p.id,boardId:normalTarget(r.host.state,p.id).boardId,cell:intent.cell});drain(r);}
   else{const d=r.host.pendingRoot?.decisions.find(d=>d.status==='pending'&&d.actorId===p.id&&r.choices[i].get(d.id)===intent.choice);if(!d)throw Error('wrong-choice');const uid=intent.unit===null?null:[...r.handles[i]].find(([,v])=>v===intent.unit)?.[0];if(uid===undefined)throw Error('wrong-unit');cmd(r,{kind:'answer',answer:{actorId:p.id,decisionId:d.id,cell:intent.cell,unitId:uid}});drain(r);}
   sample(r);r.revision++;presentation.finish(r);return read(r,i,current.snapshot.eventPosition);
  }catch(e){Object.assign(r,before);onFailure?.(e);return deny('illegal');}
 }

 function identity(token,binding){const e=tokens.get(token);if(!e||e.r.seats[e.i].token!==token||e.r.seats[e.i].binding!==binding||e.r.seats[e.i].left)throw Error('unknown-seat');if(e.r.seats[e.i].controller!=='human')throw Error('seat-handed-to-ai');if(e.r.seats[e.i].absence)throw Error('rejoin-required');return e;}
 function heartbeat(token,binding){const {r,i}=identity(token,binding);r.seats[i].seen=now();const u=running.get(r)?.updates[i]||cached.get(r)?.[i]||read(r,i);return {lan:{...u.lan,presence:presence(r,now()),processing:running.has(r)}};}
 function liveRead(token,binding,after=0){const {r,i}=identity(token,binding),run=running.get(r);if(!run)return null;if(!Number.isSafeInteger(after)||after<0)throw Error('invalid-cursor');r.seats[i].seen=now();const u=run.updates[i];return {...u,lan:{...u.lan,processing:true,presence:presence(r,now())},events:[],presentation:run.frames[i].filter(f=>f.snapshot.eventPosition>after)};}
 async function background(r,token,binding,action,body,notify){const initial=r.seats.map((s,i)=>s.controller==='human'?read(r,i,r.host.state.match.knowledge[r.host.config.players[i].id].events.length):null),run={updates:initial,frames:r.seats.map(()=>[])};running.set(r,run);const betaStart=performance.now(),metricScope=metricsContext.getStore();let worker=workerPool.get(r);if(!worker){worker=new Worker(new URL('./group-worker.mjs',import.meta.url));worker.encodeArchive=archiveEncoder();worker.decodeArchive=archiveDecoder();workerPool.set(r,worker);}clearTimeout(workerIdle.get(worker));worker.ref();const seatKey=JSON.stringify(r.seats.map(s=>[s.token,s.binding])),reuse=worker.committedHost===r.host&&r.host.status!=='placement'&&worker.seatKey===seatKey?worker.lastJob:null;const job={job:(worker.serial=(worker.serial||0)+1),reuse,betaMetrics:!!metricsContext.getStore(),room:exportRooms(new Map([[r.code,r]]),true)[0],roster,seed,at:now(),token,binding,action,body};if(reuse!==null)job.room.host=null;try{return await new Promise((resolve,reject)=>{worker.on('message',m=>metricsContext.run(metricScope,()=>{try{if(m.archiveWire)m=worker.decodeArchive(m);if(m.type==='progress'){const i=m.seat,u={...m.update,lan:{...initial[i].lan,processing:true}};run.frames[i].push(...u.presentation);run.updates[i]=u;notify?.(i,u);}else if(m.type==='done'){if(m.job!==job.job)throw Error('Worker commit mismatch');metric('worker-resolution',performance.now()-betaStart);for(const [k,v]of Object.entries(m.betaMetrics||{}))metric(k,v.ms,v.count);const seen=r.seats.map(s=>s.seen),restored=new Map(),dummy=new Map();restoreRooms([m.room],restored,dummy,true);const next=restored.get(r.code);Object.assign(next,{epoch:m.room.epoch,revision:m.room.revision,handles:m.room.handles,choices:m.room.choices});delete next.queue;if(isArchive(r.host.initial)&&isDeepStrictEqual(r.host,m.room.host))next.host=r.host;Object.assign(r,next);worker.committedHost=r.host;worker.lastJob=m.job;worker.seatKey=JSON.stringify(r.seats.map(s=>[s.token,s.binding]));r.seats.forEach((s,i)=>s.seen=Math.max(s.seen,seen[i]));cached.set(r,m.updates);readCache.set(r,{host:r.host,revision:r.revision,updates:m.updates.map(u=>{if(!u)return null;const {presentation,...base}=u;return base;})});resolve(m.result);}else reject(Error(m.message));}catch(error){reject(error);}}));worker.on('error',reject);worker.on('exit',()=>reject(Error('Group worker stopped')));worker.postMessage(worker.encodeArchive(job));});}catch(error){workerPool.delete(r);await worker.terminate();throw error;}finally{running.delete(r);for(const event of ['message','error','exit'])worker.removeAllListeners(event);const forget=()=>{if(workerPool.get(r)===worker)workerPool.delete(r);};worker.on('error',forget);worker.on('exit',forget);worker.unref();const idle=setTimeout(()=>{forget();void worker.terminate();},60000);idle.unref();workerIdle.set(worker,idle);}}
 const recoveryBattle=r=>'room-'+r.epoch;
 const replacements=['their dad','their mom','their sister','their brother','their grandma','their grandpa','their cousin','their jester','their cat','their dog','their favorite chicken','their goldfish','their weird uncle','their neighbour','their accountant','their blacksmith','their tavern keeper','some drunk they met at the tavern','their imaginary friend','their pet rock'];
 const recoverable=r=>!r.closed&&r.host.status!=='complete';
 function announce(r,i,kind,extra={}){const e={id:++r.noticeSerial,seat:i,name:r.seats[i].name,kind,...extra};(r.news??=[]).push(e);if(r.news.length>40)r.news.shift();return e;}
 function ready(r,i){const p=r.host.config.players[i];if(r.host.status!=='placement'||r.ready[i])throw Error('placement-locked');for(const[k,n]of Object.entries(roster))if(r.host.placements.filter(u=>u.ownerId===p.id&&u.type===k).length!==n)throw Error('incomplete');r.ready[i]=true;startReady(r);}
 function startReady(r){if(r.host.status==='placement'&&r.ready.every(Boolean)&&r.seats.every(s=>s.controller==='ai'||s.token&&!s.left)){cmd(r,{kind:'start'});drain(r);}}
 function completeQuick(r){presentation.begin(r);r.ready.fill(false);for(let i=0;i<r.seats.length;i++){place(r,i,{kind:'random-placement'});r.ready[i]=true;}r.quick.status='accepted';startReady(r);r.revision++;}
 function quick(r,i,b){if(r.host.status!=='placement'||r.closed||b.battle!==recoveryBattle(r)||r.seats.some(s=>s.controller==='human'&&(!s.token||s.absence||s.left)))throw Error('quick-unavailable');if(b.action==='propose'){if(i!==r.hostSeat||r.quick.status!=='available'||r.ready.some((v,j)=>v&&r.seats[j].controller==='human'))throw Error('quick-unavailable');r.quick={status:'pending',proposer:i,accepted:r.seats.flatMap((s,j)=>s.controller==='ai'||j===i?[j]:[])};}else{if(r.quick.status!=='pending'||r.quick.accepted.includes(i))throw Error('quick-unavailable');if(b.action==='decline')r.quick.status='declined';else if(b.action==='accept')r.quick.accepted.push(i);else throw Error('quick-unavailable');}if(r.quick.status==='pending'&&r.quick.accepted.length===r.seats.length)completeQuick(r);else r.revision++;return read(r,i);}
 function takeover(r,i,reason){const saved={...r,creditState:structuredClone(r.creditState),seats:structuredClone(r.seats),host:cloneHost(r.host),ready:[...r.ready],quick:structuredClone(r.quick),news:structuredClone(r.news),memory:structuredClone(r.memory),statistics:structuredClone(r.statistics),aiMemory:structuredClone(r.aiMemory),presentation:structuredClone(r.presentation)};try{const s=r.seats[i];s.controller='ai';s.absence=null;s.kicked=true;s.takeover=announce(r,i,'takeover',{reason,replacement:replacements[randomInt(replacements.length)]});presentation.begin(r);if(r.host.status==='placement'){r.ready[i]=false;place(r,i,{kind:'random-placement'});r.ready[i]=true;if(r.quick.status==='pending'&&!r.quick.accepted.includes(i))r.quick.accepted.push(i);if(r.quick.status==='pending'&&r.quick.accepted.length===r.seats.length)completeQuick(r);else startReady(r);}else drain(r);r.revision++;}catch(e){Object.assign(r,saved);throw e;}}
 function absent(r,i,at){const s=r.seats[i];if(s.absence||s.controller==='ai'||!active(r,i))return;if((s.disconnects=(s.disconnects||0)+1)>=3){takeover(r,i,'connection');return;}s.absence={id:randomBytes(12).toString('hex'),startedAt:at,policy:'choice'};announce(r,i,'disconnected');}
 const takeoverDue=r=>r.seats.some(s=>s.controller==='human'&&s.token&&!s.left&&(s.absence?.policy==='auto'&&now()>=s.absence.startedAt+DISCONNECT_GRACE_MS||!s.absence&&(s.disconnects||0)>=2&&now()-s.seen>=HEARTBEAT_TIMEOUT_MS));
 function reconcile(r){if(!recoverable(r)||r.host.status==='running')return;for(let i=0;i<r.seats.length;i++){const s=r.seats[i];if(!s.token||s.left||s.controller==='ai'||!active(r,i))continue;if(!s.absence&&now()-s.seen>=HEARTBEAT_TIMEOUT_MS)absent(r,i,s.seen+HEARTBEAT_TIMEOUT_MS);if(s.absence?.policy==='auto'&&now()>=s.absence.startedAt+DISCONNECT_GRACE_MS)takeover(r,i,'auto');}}
 function returnInfo(r,i){const s=r.seats[i];return {returning:true,rejoin:s.controller==='ai'?{available:false,noticeId:s.takeover?.id,replacement:s.takeover?.replacement}:{available:true,battle:recoveryBattle(r),episode:s.absence?.id||null,remainingMs:s.absence?s.absence.startedAt+DISCONNECT_GRACE_MS-now():null,policy:s.absence?.policy||'choice'}};}

 const queue=(r,fn)=>{const t=r.queue.then(fn);r.queue=t.catch(()=>{});return t;};
 function seatToken(r,i,binding,name,identity){const token=randomBytes(32).toString('hex');Object.assign(r.seats[i],{token,binding,name:label(name),identity:identity?structuredClone(identity):null,seen:now(),left:false});tokens.set(token,{r,i});return token;}
 return {rooms,close:async()=>{await Promise.all([...rooms.values()].map(r=>r.queue));await Promise.all([...workerPool.values()].map(w=>{clearTimeout(workerIdle.get(w));return w.terminate();}));workerPool.clear();},finishProgress:code=>presentation.finish(rooms.get(code)),heartbeat,liveRead,isBusy:token=>{const e=tokens.get(token);return !!e&&running.has(e.r)&&e.r.host.status!=='placement';},
  reserveRematch:code=>{const r=rooms.get(code);return queue(r,()=>{if(r.host.status!=='placement'||!r.rematchSource)throw Error('game-full');if(r.seats.some(s=>s.controller==='human'&&!s.token))return;const i=r.seats.findIndex(s=>s.controller==='ai'&&!s.token);if(i<0)throw Error('game-full');place(r,i,{kind:'clear-placement'});r.seats[i].controller='human';r.seats[i].name=null;r.ready[i]=false;r.revision++;});},
  tick:async()=>{let changed=false;for(const r of rooms.values())await queue(r,async()=>{const n=r.noticeSerial,heavy=workers&&takeoverDue(r);if(heavy)await background(r,null,null,'tick',{});else reconcile(r);changed ||= n!==r.noticeSerial;});return changed;},
  list:binding=>[...rooms.values()].filter(r=>!r.closed&&r.host.status==='placement'&&r.seats[r.hostSeat]?.binding!==binding&&now()-r.seats[r.hostSeat]?.seen<HEARTBEAT_TIMEOUT_MS).map(r=>({code:r.code,creator:r.seats[r.hostSeat].name,type:'Group '+r.seats.length+'P',freeSlots:r.seats.filter(s=>s.controller==='human'&&!s.token).length})).filter(r=>r.freeSlots),
  exportState:(transfer=false)=>exportRooms(rooms,transfer,true),restoreState:(saved,transfer=false)=>restoreRooms(saved,rooms,tokens,transfer),
  async lobby(action,body,binding){if(!binding)throw Error('unknown-session');if(action==='make'||action==='rematch-make'){const n=body.seats;if(![3,4].includes(n)||!Array.isArray(body.controllers)||body.controllers.length!==n||body.controllers[0]!=='human'||body.controllers.some(v=>!['human','ai'].includes(v)))throw Error('invalid-configuration');const name=label(body.name),code=randomBytes(4).toString('hex').slice(0,6).toUpperCase(),r={code,seats:body.controllers.map((controller,i)=>({controller,name:controller==='ai'?'AI '+(i+1):null,token:null,binding:null,seen:0,left:false})),queue:Promise.resolve(),epoch:0,closed:false};reset(r,action==='rematch-make'?randomInt(0,0x100000000):undefined);const token=seatToken(r,0,binding,name,body.identity);rooms.set(code,r);return {token,configuration,update:await read(r,0)};}
   const r=rooms.get(String(body.code||'').trim().toUpperCase());if(!r||r.closed||r.host.status!=='placement')throw Error('bad-game-code');return queue(r,async()=>{if(r.seats.some(s=>s.binding===binding))throw Error('already-seated');const i=r.seats.findIndex(s=>s.controller==='human'&&!s.token);if(i<0)throw Error('game-full');const token=seatToken(r,i,binding,body.name,body.identity);r.revision++;return {token,configuration,update:await read(r,i)};});
  },
  async route(token,binding,action,body={},notify){const e=tokens.get(token);if(!e||e.r.seats[e.i].token!==token||e.r.seats[e.i].binding!==binding||e.r.seats[e.i].left)throw Error('unknown-seat');const {r,i}=e;if(workers&&['command','quick','give-up','surrender','rejoin','disconnect-policy','leave','return'].includes(action))return queue(r,()=>background(r,token,binding,action,body,notify));return queue(r,async()=>{if(workers&&takeoverDue(r))return background(r,token,binding,action,body,notify);const s=r.seats[i];reconcile(r);if(['return','return-status'].includes(action)){if(action==='return'){if(recoverable(r)&&active(r,i)&&(r.host.status!=='placement'||s.opened))absent(r,i,now());s.opened=true;}if(s.controller==='ai'||s.absence)return returnInfo(r,i);s.seen=now();return {configuration,reconnected:true,development:false,update:read(r,i)};}if(s.controller==='ai')throw Error('seat-handed-to-ai');
 if(['rejoin','surrender'].includes(action)){if(body.battle!==recoveryBattle(r)||!s.absence||body.episode!==s.absence.id)throw Error('stale');if(action==='surrender'){takeover(r,i,'surrender');return {released:true,takeover:s.takeover};}s.absence=null;s.seen=now();announce(r,i,'rejoined');if(r.pausedAi){presentation.begin(r);drain(r);r.revision++;}return {configuration,reconnected:true,development:false,update:read(r,i)};}
 if(action==='leave'){if(r.host.status==='placement'&&r.rematchSource){place(r,i,{kind:'clear-placement'});s.left=true;s.token=null;s.binding=null;r.ready[i]=false;r.revision++;if(i===r.hostSeat)r.hostSeat=r.seats.findIndex(s=>s.token&&!s.left&&s.controller==='human');if(r.hostSeat<0)r.closed=true;return {left:true,mainMenu:true};}if(active(r,i)&&recoverable(r)&&r.seats.some((s,j)=>j!==i&&s.controller==='human'&&s.token&&!s.left&&active(r,j))){absent(r,i,now());return s.controller==='ai'?{left:true,mainMenu:true}:{left:true,reclaimable:true};}s.left=true;if(r.seats.every(s=>s.left||s.controller==='ai'||!s.token))r.closed=true;return {left:true,mainMenu:true};}
 if(s.absence)throw Error('rejoin-required');s.seen=now();if(action==='heartbeat')return {lan:read(r,i).lan};if(action==='open')return{configuration,reconnected:true,development:false,update:read(r,i)};if(action==='read'){if(Object.keys(body).some(k=>k!=='after')||!Number.isSafeInteger(body.after??0)||(body.after??0)<0)throw Error('invalid-cursor');return read(r,i,body.after??0);}if(action==='disconnect-policy'){const j=body.seat,a=r.seats[j]?.absence;if(!active(r,i)||!Number.isInteger(j)||j===i||!a||body.episode!==a.id||body.battle!==recoveryBattle(r))throw Error('stale');if(body.action==='kick'){if(a.policy!=='wait')throw Error('kick-unavailable');takeover(r,j,'kick');}else{if(!['wait','auto'].includes(body.action)||a.policy!=='choice')throw Error('kick-unavailable');a.policy=body.action;reconcile(r);}return read(r,i);}
 if(action==='give-up'){if(!recoverable(r))throw Error('not-complete');takeover(r,i,'surrender');return {released:true};}
 if(action==='configure'){if(r.host.status!=='placement'||i!==r.hostSeat||!r.rematchSource)throw Error('invalid-configuration');const n=body.seats,controllers=body.controllers;if(![3,4].includes(n)||!Array.isArray(controllers)||controllers.length!==n||controllers.some(v=>!['human','ai'].includes(v)))throw Error('invalid-configuration');for(let j=0;j<r.seats.length;j++)if(r.seats[j].token&&!r.seats[j].left&&(j>=n||controllers[j]!=='human'))throw Error('invalid-configuration');const placements=r.host.placements.filter(u=>{const j=r.host.config.players.findIndex(p=>p.id===u.ownerId);return r.seats[j].token&&!r.seats[j].left;}),previousReady=[...r.ready];r.seats=Array.from({length:n},(_,j)=>r.seats[j]?.token&&!r.seats[j].left?r.seats[j]:{controller:controllers[j],name:controllers[j]==='ai'?'AI '+(j+1):null,token:null,binding:null,seen:0,left:false});reset(r);for(const placement of placements)cmd(r,{kind:'place',placement:{...placement,unitId:'ring-unit-'+(++r.serial)}});for(let j=0;j<n;j++)if(r.seats[j].controller==='human')r.ready[j]=!!previousReady[j];startReady(r);return read(r,i);}
 if(action==='quick')return quick(r,i,body);if(action==='command')return dispatch(r,i,body);if(action==='rematch'){if(active(r,i)&&r.host.status!=='complete')throw Error('not-complete');if(!r.rematch[i]){r.rematch[i]=true;(r.rematchOrder??=[]).push(i);announce(r,i,'rematch');r.revision++;}return read(r,i);}throw Error('unsupported');});},
  checkpoint:token=>{const e=tokens.get(token);if(!e)return null;const r=e.r;return JSON.stringify({host:serializeHost(r.host),memory:r.memory,aiMemory:r.aiMemory,statistics:r.statistics,ready:r.ready,epoch:r.epoch,revision:r.revision,serial:r.serial});}
 };
}
