import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {launch} from '../../../../stage10/development-harness/browser-harness.mjs';
import {startServer} from '../../server/main.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),read=n=>fs.readFileSync(path.join(root,n),'utf8'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const manifest=JSON.parse(read('assets/story/audio/narration-manifest.json')),chapters=Object.values(manifest),approved=fs.readFileSync('C:/Users/Notandi/Downloads/STONE_THROW_STORY_NARRATION_AUDIO_CODEX_HANDOFF.md','utf8').replaceAll('\r\n','\n');
assert.equal(chapters.length,19);assert.equal(new Set(chapters.map(c=>c.wav)).size,19);
for(const c of chapters){const b=fs.readFileSync(path.join(root,c.wav));assert.equal(sha(b),c.sha256);assert.equal(b.length,c.bytes);assert.equal(b.toString('ascii',0,4),'RIFF');const m=[...approved.matchAll(/^### (\d+)\. (.+)\n\n([\s\S]*?)(?=\n### |\n## INTEGRATION)/gm)].find(m=>+m[1]===c.chapter);assert.equal(c.title,m[2]);assert.deepEqual(c.paragraphs,m[3].trim().split('\n\n'));}
const source=read('source/legacy/story.js'),before=read('tools/story-narration/story-production-before.txt');
for(const mode of ['production','development'])assert.ok(read(`StoneThrow-v1.427-stage13-${mode}.html`).includes(source));
const b=await launch(),app=await startServer({port:0,seed:1427,logger:()=>{}}),results=[];
const invoke=(p,code)=>p.evaluate(code=>window.__storyTest(code),code);
async function page(old=false,fakeAudio=true){const c=await b.newContext();if(fakeAudio)await c.addInitScript(()=>{window.audioAttempts=[];window.Audio=class{constructor(){this.paused=true;}play(){this.paused=false;audioAttempts.push(this);return Promise.resolve();}pause(){this.paused=true;}removeAttribute(){this.src='';}load(){}};});const p=await c.newPage();await p.route(app.origin+'/',async r=>{let html=read('StoneThrow-v1.427-stage13-production.html');const text=old?before:source;const end=text.lastIndexOf('})();');const instrumented=text.slice(0,end)+'window.__storyTest=code=>eval(code);\n'+text.slice(end);html=html.replace(source,instrumented);await r.fulfill({body:html,contentType:'text/html'});});await p.goto(app.origin);await p.waitForFunction(()=>window.__storyTest&&window.__stoneThrowViewState);return {p,c};}
const baseline=await page(true),trial=await page();
async function reset(p,hasCastle=false){await invoke(p,`localStorage.clear();closeDialog();closeStoryTransition();storyPhase4OpeningBattle=null;storyPhase4MonkBattle=null;storyPhase4ClericInterruptionBattle=null;storyPhase4PendingMonkPlayerWon=null;storyPhase5OpeningBattle=null;storyPhase6OpeningBattle=null;storyPhase6HeroBattle=null;storyFinalBattle=null;storyPhase3NecroOwner=null;window.calls=[];window.plague=[];window.unlocked={player:false,enemy:false};window.__stoneThrowStoryPlagueTargets=()=>plague;window.__stoneThrowStoryPlayerHasCastle=()=>${hasCastle};window.__stoneThrowStoryClericUnlocked=s=>unlocked[s];window.__stoneThrowUnlockStoryClerics=s=>{calls.push(['unlock',s]);s.forEach(x=>unlocked[x]=true);};window.__stoneThrowSyncStoryClerics=()=>{calls.push(['sync']);unlocked.player=unlocked.enemy=true;};for(const name of ['Battle1','Battle2','Battle3','Phase2Battle','Phase3Battle','Phase4Battle','Phase5Battle','Phase6Battle'])window['__stoneThrowStartStory'+name]=(...args)=>calls.push([name,...args]);window.__stoneThrowPresentationReady=()=>Promise.resolve();`);}
async function assertChapter(p,key){const state=await invoke(p,`({title:storyPhaseOverlay.classList.contains('open')?storyAftermathTitle.textContent:dialogTitle.textContent,body:storyPhaseOverlay.classList.contains('open')?storyAftermathBody.textContent:dialogBody.textContent,src:audioAttempts.at(-1)?.src})`);assert.equal(state.title,manifest[key].title);assert.equal(state.src,manifest[key].wav);for(const para of manifest[key].paragraphs)assert.ok(state.body.includes(para),key);}
const pairs=[['showStoryBattle2Transition','castle'],['showStoryBattle3Transition','catapult'],['showDwarfTransition','phase2_dwarf'],['showElfTransition','phase2_elf'],['showGoblinTransition','phase2_goblin'],['showNecromancerTransition','phase3_necro'],['showMonkTransition','phase4_monk'],['showDragonTransition','phase5_dragon'],['showDemonTransition','phase5_demon'],['showWizardTransition','phase5_wizard'],['showHeroTransition','hero_intro']];
try{
 for(const won of [false,true])for(let battle=1;battle<=8;battle++){await reset(trial.p,won);await invoke(trial.p,`window.__stoneThrowContinueStory({battle:${battle},playerWon:${won}})`);await assertChapter(trial.p,Object.keys(manifest)[battle]);results.push(`result route ${battle}:${won}`);}
 for(const [fn,key]of pairs)for(const won of [false,true]){for(const p of [baseline.p,trial.p]){await reset(p,won);await invoke(p,`${fn}(${won});`);}await assertChapter(trial.p,key);assert.deepEqual(await invoke(trial.p,'({note:storyReinforcementNote.innerHTML,owner:storyNewUnitLabel.textContent})'),await invoke(baseline.p,'({note:storyReinforcementNote.innerHTML,owner:storyNewUnitLabel.textContent})'));for(const p of [baseline.p,trial.p])await invoke(p,'storyAftermathNext.__storyNextAction()');assert.deepEqual(await baseline.p.evaluate(()=>calls),await trial.p.evaluate(()=>calls));assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));results.push(fn+':'+won);}
 for(const [fn,key]of [['showStoryPrologue','border'],['showPhase2Opening','phase2_equal'],['showPhase2Sync','phase2_sync'],['showPhase4Complete','phase4_complete'],['showPhase5Complete','phase5_complete'],['showFinalBattleTransition','phase6_final'],['showStoryComplete','story_complete']]){await reset(trial.p);await invoke(trial.p,`${fn}()`);await assertChapter(trial.p,key);results.push(key);}
 for(const side of ['player','enemy'])for(const battle of [9,10,11,12,13,14,15,16,17]){
  for(const p of [baseline.p,trial.p]){await reset(p);await invoke(p,`storyPhase4OpeningBattle=10;storyPhase4MonkBattle=11;storyPhase5OpeningBattle=12;storyPhase6OpeningBattle=16;storyPhase6HeroBattle=17;plague=['${side}'];window.__stoneThrowContinueStory({battle:${battle},playerWon:true});`);}
  await assertChapter(trial.p,'phase3_cleric');
  if(battle>=11)await trial.p.locator('#stMenuDialogActions button').click();
  // Same deferred callback and exact ownership notes as the pre-integration route.
  for(const p of [baseline.p,trial.p])await invoke(p,"storyPhaseOverlay.classList.contains('open')?storyAftermathNext.__storyNextAction():dialogActions.querySelector('button').click()");
  assert.deepEqual(await trial.p.evaluate(()=>calls),await baseline.p.evaluate(()=>calls));
  if(battle===10){for(const p of [baseline.p,trial.p])await invoke(p,'window.__stoneThrowContinueStory({battle:11,playerWon:false})');await assertChapter(trial.p,'phase4_monk');assert.deepEqual(await invoke(trial.p,'storyReinforcementNote.innerHTML'),await invoke(baseline.p,'storyReinforcementNote.innerHTML'));}
  results.push(`Cleric ${side} battle ${battle}`);
 }
 await reset(trial.p);const monkBefore=await trial.p.evaluate(()=>audioAttempts.filter(a=>a.src.includes('11_the_silent_order')).length);await invoke(trial.p,'showPhase3Complete(false,9)');assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));await invoke(trial.p,'window.__stoneThrowContinueStory({battle:10,playerWon:true})');await assertChapter(trial.p,'phase4_monk');assert.equal(await trial.p.evaluate(()=>audioAttempts.filter(a=>a.src.includes('11_the_silent_order')).length),1);assert.ok(monkBefore>=0);
 await reset(trial.p);for(const outcome of [false,null]){await invoke(trial.p,`storyFinalBattle=19;window.__stoneThrowContinueStory({battle:19,playerWon:${outcome}})`);assert.equal(await trial.p.evaluate(()=>localStorage.getItem('stoneThrow.storyFinished.v1')),null);}await invoke(trial.p,'window.__stoneThrowContinueStory({battle:19,playerWon:true})');await assertChapter(trial.p,'story_complete');assert.equal(await trial.p.evaluate(()=>localStorage.getItem('stoneThrow.storyFinished.v1')),'1');
 await reset(trial.p);await invoke(trial.p,'showStoryPrologue();closeDialog()');assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));await invoke(trial.p,"showNecromancerTransition(true);revealStoryBattle2Unlock()");assert.equal(await trial.p.evaluate(()=>audioAttempts.at(-1).paused),false);
 const real=await page(false,false),requests=[];real.p.on('request',r=>{if(r.url().endsWith('.wav'))requests.push(r.url());});await real.p.evaluate(()=>{const Native=Audio;window.realAudio=[];window.Audio=function(){const a=new Native();realAudio.push(a);return a;};});
 assert.equal(requests.length,0);await real.p.locator('#stMenuStory').click();await real.p.waitForFunction(()=>realAudio[0]?.currentTime>0);assert.equal(requests.length,1);assert.ok(requests[0].endsWith(chapters[0].wav));await real.p.locator('#stMenuDialogActions button').last().click();assert.ok(await real.p.evaluate(()=>realAudio[0].paused&&!realAudio[0].getAttribute('src')));
 for(const chapter of chapters){const response=await fetch(app.origin+'/'+chapter.wav);assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'audio/wav');assert.equal(sha(Buffer.from(await response.arrayBuffer())),chapter.sha256);}
 const warnings=[];real.p.on('console',m=>{if(m.type()==='warning')warnings.push(m.text());});await real.p.route('**/01_an_old_rivalry.wav',r=>r.fulfill({status:404,body:''}));await real.p.locator('#stMenuStory').click();await real.p.waitForFunction(()=>realAudio.at(-1)?.error);await real.p.locator('#stMenuDialogActions button').first().click();assert.ok(await real.p.locator('#stPlacementBriefing').evaluate(e=>e.classList.contains('open')));assert.ok(warnings.some(w=>w.includes('Story narration')));
 await real.p.locator('#stPlacementContinue').click();await real.p.waitForFunction(()=>window.__stoneThrowViewState()?.storyMode&&document.getElementById('playerGrid').children.length===25);
 // Decode metadata for each exact supplied WAV using the browser's native decoder.
 const durations=await real.p.evaluate(async chapters=>{const out=[];for(const ch of chapters){const a=new Audio();a.preload='metadata';const duration=await new Promise((resolve,reject)=>{a.onloadedmetadata=()=>resolve(a.duration);a.onerror=()=>reject(Error(ch.wav));a.src=ch.wav;a.load();});out.push({chapter:ch.chapter,duration});a.removeAttribute('src');a.load();}return out;},chapters.slice(1));assert.ok(durations.every(x=>Number.isFinite(x.duration)&&x.duration>0));
 // Longest transition and ending remain readable/clickable at phone width.
 await trial.p.setViewportSize({width:390,height:844});await reset(trial.p);await invoke(trial.p,"showClericTransition('player')");await trial.p.locator('#stStoryAftermathNext').click();await trial.p.locator('#stStoryUnitRevealClose').click();await trial.p.locator('#stStoryAftermathNext').click();await reset(trial.p);await invoke(trial.p,'showStoryComplete()');await trial.p.locator('#stMenuDialogActions button').click();
 await trial.p.evaluate(()=>{document.getElementById('soundBtn').textContent='Hljóð: OFF';});await invoke(trial.p,'showStoryPrologue()');assert.ok(await trial.p.evaluate(()=>audioAttempts.at(-1).muted));await trial.p.evaluate(()=>{document.getElementById('soundBtn').textContent='Hljóð: ON';});assert.equal(await trial.p.evaluate(()=>audioAttempts.at(-1).muted),false);

 // One persistent preference, both Story surfaces and gear; ON never restarts a chapter.
 await trial.p.setViewportSize({width:1600,height:1100});await reset(trial.p);await invoke(trial.p,'showNecromancerTransition(true)');
 await trial.p.locator('#stStoryAftermathNext').click();assert.equal(await trial.p.evaluate(()=>audioAttempts.at(-1).paused),false);
 await trial.p.locator('#stStoryUnitRevealClose').click();await trial.p.locator('#stTransitionNarration').click();assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));assert.equal(await trial.p.locator('#stNarrationSetting').getAttribute('aria-pressed'),'false');
 const count=await trial.p.evaluate(()=>audioAttempts.length);await invoke(trial.p,'closeStoryTransition();showStoryPrologue()');assert.equal(await trial.p.evaluate(()=>audioAttempts.length),count);assert.equal(await trial.p.locator('#stDialogNarration').innerText(),'Narration: OFF');
 await trial.p.reload();await trial.p.waitForFunction(()=>window.__storyTest);assert.equal(await trial.p.locator('#stNarrationSetting').getAttribute('aria-pressed'),'false');await invoke(trial.p,'showStoryPrologue()');assert.equal(await trial.p.evaluate(()=>audioAttempts.length),0);
 await trial.p.locator('#stDialogNarration').click();assert.equal(await trial.p.locator('#stNarrationSetting').getAttribute('aria-pressed'),'true');assert.equal(await trial.p.evaluate(()=>audioAttempts.length),0);
 await invoke(trial.p,'showStoryPrologue()');assert.equal(await trial.p.evaluate(()=>audioAttempts.filter(a=>!a.paused).length),1);
 await trial.p.evaluate(()=>document.getElementById('stNarrationSetting').click());assert.equal(await trial.p.locator('#stDialogNarration').innerText(),'Narration: OFF');assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));await trial.p.evaluate(()=>document.getElementById('stNarrationSetting').click());assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));
 await reset(trial.p);await invoke(trial.p,'showNecromancerTransition(true);revealStoryBattle2Unlock()');assert.equal(await trial.p.evaluate(()=>audioAttempts.at(-1).paused),false);await invoke(trial.p,'revealStoryBattle2Unlock()');assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));
 await invoke(trial.p,'showStoryPrologue();menuMode(true)');assert.ok(await trial.p.evaluate(()=>audioAttempts.every(a=>a.paused)));
 await invoke(trial.p,'showStoryPrologue();showNecromancerTransition(true)');assert.equal(await trial.p.evaluate(()=>audioAttempts.filter(a=>!a.paused).length),1);await invoke(trial.p,'closeStoryTransition()');
 await invoke(real.p,'showNecromancerTransition(true)');await real.p.waitForFunction(()=>realAudio.at(-1)?.currentTime>0);await real.p.locator('#stStoryAftermathNext').click();const playingTime=await real.p.evaluate(()=>realAudio.at(-1).currentTime);await real.p.waitForFunction(t=>realAudio.at(-1).currentTime>t+.1,playingTime);await real.p.locator('#stStoryUnitRevealClose').click();await real.p.locator('#stTransitionNarration').click();assert.ok(await real.p.evaluate(()=>realAudio.at(-1).paused&&!realAudio.at(-1).getAttribute('src')));
 await real.c.close();
 fs.writeFileSync(path.join(root,'tools/story-narration/results.json'),JSON.stringify({passed:true,routes:results,approvedTextExact:19,wavBytesAndHttpMappings:19,realBrowserPlayback:true,browserDecoded:19,remainingDurations:durations,demandLoaded:true,stopOnCloseAndAdvance:true,revealKeepsPlaying:true,sharedPersistentNarrationPreference:true,reenableDoesNotRestart:true,noOverlappingNarration:true,missingAudioFallback:true,realBattle1Deployment:true,phoneControlsReachable:true,existingSoundSwitchRespected:true,monkSetupUnnarrated:true,finalLossAndDrawNotFinished:true,ownershipAndContinuationParity:true},null,2));console.log('PASS Story narration',results.length,'route checks; 19 WAV/text hashes; actual browser playback, stop and missing-file fallback, mobile controls, real Battle 1');
}finally{await baseline.c.close();await trial.c.close();await b.close();await app.close();}
