import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
import {launch} from '../../../../stage10/development-harness/browser-harness.mjs';import {startPlaytest} from '../playtest.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const stateDir=fs.mkdtempSync(path.resolve(root,'../story-deployment-state-'));const app=await startPlaytest({stateDir,open:()=>{}}),browser=await launch();
try{const context=await browser.newContext(),page=await context.newPage();const failures=[];
page.on('response',async r=>{if(r.url().includes('/api/')&&r.status()>=400){const f={url:r.url(),status:r.status(),body:await r.text(),request:r.request().postData()};failures.push(f);console.log(JSON.stringify(f));}});page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
await page.goto(app.origin);await page.waitForFunction(()=>window.__stoneThrowPresentationReady);await page.locator('#stMenuStory').click();await page.locator('#stMenuDialogActions button').first().click();await page.locator('#stPlacementContinue').click();await page.waitForTimeout(500);await page.evaluate(()=>window.__stoneThrowOpenMainMenu());await page.locator('#stMenuStoryStartOver').click();await page.locator('#stMenuDialogActions button').first().click();await page.locator('#stMenuDialogActions button').first().click();await page.locator('#stPlacementContinue').click();await page.waitForFunction(()=>window.__stoneThrowQuickStart&&document.getElementById('playerGrid').children.length===25);const stream=await page.evaluate(async()=>{const {snapshot:s}=await (await fetch('/api/read',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).json();const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/x-ndjson'},body:JSON.stringify({contract:s.contract,battle:s.battle,revision:s.revision,intent:{kind:'random-placement'}})});return {status:r.status,body:await r.text(),type:r.headers.get('content-type')};});assert.equal(stream.status,200);assert.equal(stream.type,'application/x-ndjson');assert.ok(JSON.parse(stream.body.trim().split('\n').at(-1)).update.accepted);await page.waitForTimeout(1200);console.log('VIEW',await page.evaluate(()=>({view:window.__stoneThrowViewState?.(),cells:document.getElementById('playerGrid').children.length,banner:document.getElementById('stTransportError')?.textContent})));assert.deepEqual(failures,[]);assert.equal(await page.locator('#stTransportError').count(),0);assert.equal(await page.locator('#playerGrid > *').count(),25);
await page.reload();await page.waitForFunction(()=>window.__stoneThrowViewState?.().storyMode&&document.getElementById('playerGrid').children.length===25);assert.equal(await page.locator('#stTransportError').count(),0);
const invalid=await page.evaluate(async()=>{const r=await fetch('/api/read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unexpected:true})});return {status:r.status,body:await r.json()};});assert.deepEqual(invalid,{status:400,body:{error:'malformed-request'}});
const single=await browser.newContext(),sp=await single.newPage();await sp.goto(app.origin);await sp.waitForFunction(()=>window.__stoneThrowViewState);const before=await sp.evaluate(async()=>await(await fetch('/api/read',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).json());
await sp.route('**/api/read',r=>r.abort('connectionrefused'));await sp.reload();await sp.locator('#stTransportError').waitFor();assert.match(await sp.locator('#stTransportError').innerText(),/server-unavailable/);await sp.unroute('**/api/read');await sp.locator('#stTransportError button').click();await sp.waitForFunction(()=>window.__stoneThrowViewState);assert.equal(await sp.locator('#stTransportError').count(),0);const after=await sp.evaluate(async()=>await(await fetch('/api/read',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).json());assert.deepEqual(after.snapshot,before.snapshot);await single.close();
console.log('PASS deployment, streamed placement, reload, malformed-request rejection, non-Story error banner and REJOIN with exact snapshot');
}finally{await browser.close();await app.close();}
