import type {PlayerId,BoardId,UnitId,UnitType,Cell,MatchId,MatchConfiguration} from '../model.js';
import type {CombatState,ResolutionContext,ExplicitRng,DecisionCommand,InternalRuleEvent} from '../combat/contracts.js';
export interface HostConfiguration {matchId:MatchId;rulesVersion:'stone-throw-v1.427';size:number;players:{id:PlayerId;boardId:BoardId;roster:Partial<Record<UnitType,number>>;decisionMode:'interactive'|'policy'}[];story:boolean;seed:number}
export interface Placement {unitId:UnitId;ownerId:PlayerId;boardId:BoardId;type:UnitType;cells:Cell[]}
export interface PolicyMemory {playerId:PlayerId;knownHits:string[];scoutKnowledge:{cell:string;classification:'empty'|'core'|'special'}[];heroHunt:string[]}
export interface MatchCounters {playerId:PlayerId;shots:number;directHits:number;cellsAffected:number;biggestAttack:number;longestChain:number}
export type HostCommand={id:string;kind:'place';placement:Placement}|{id:string;kind:'start'}|{id:string;kind:'advance-turn'}|{id:string;kind:'shoot';actorId:PlayerId;boardId:BoardId;cell:Cell}|{id:string;kind:'answer';answer:DecisionCommand};
export interface HostRecord {sequence:number;command:HostCommand;rngBefore:number;rngAfter:number;eventStart:number;eventEnd:number}
export interface HostState {contract:'stone-throw-host-v1';config:HostConfiguration;initial:CombatState;state:CombatState;rng:ExplicitRng;initialRng:ExplicitRng;placements:Placement[];status:'placement'|'running'|'awaiting-turn'|'awaiting-command'|'awaiting-decision'|'complete'|'guarded';activePlayerId:PlayerId|null;starterId:PlayerId|null;round:number;turnIndex:number;turnStep:'initial'|'enter'|'resurrection'|'scout'|'catapult'|'budget'|'actions'|'plague'|'finish';pendingRoot:ResolutionContext|null;rootSerial:number;rootEventCursor:number;history:HostRecord[];events:{turnIndex:number;event:InternalRuleEvent}[];brains:PolicyMemory[];counters:MatchCounters[];guards:{turnActions:number;outerIterations:number;pendingPrimaryLimit:boolean;reason:string|null};pendingPolicyCells:Cell[];statisticsFrames:{frameId:string;actorId:PlayerId;count:number;startCells:number;biggest:boolean}[];rootPurpose:'shot'|'entry'|'exit'|null;lastProbeSkippedPlague:boolean;plagueAwareAtTurnStart:boolean}
export type PrivateReplay=import('./replay.js').HostReplay;
